### ISSUE TITLE
SDL_HITTEST_RESIZE_* doesn't work on Windows

### ISSUE THREAD

**Issue by zturtleman** [libsdl-org/SDL#8586] opened 2023-11-21 01:55 UTC
testhittesting doesn't have working resizing on Windows.

SDL3 (main branch) doesn't have cursors or resizing.
SDL2 branch displays resize cursors but doesn't resize.

Only tested using a Windows 10 VM (other windows are resizable).

**Comment by icculus** [comment] 2023-11-27 15:09
Going to try to poke this for the 2.30.0 release, but it might slip.

**Comment by gabrielmedici** [comment] 2024-01-01 19:44
Hey, i've been debugging this issue and i've found a """solution""":
While debugging i found this function:
https://github.com/libsdl-org/SDL/blob/dd2d809407f152c00adc6e96e3a063eb530b7219/src/video/windows/SDL_windowswindow.c#L99-L138
And by calling `SDL_SetHint("SDL_BORDERLESS_WINDOWED_STYLE", "0");` before creating the window and thus setting the style to `STYLE_BORDERLESS`, windows now actually responds to SDL_HITTEST_RESIZE_.
My very obvious assumption is that one of the flags defined on those two styles are making windows ignore SDL_HITTEST_RESIZE_
https://github.com/libsdl-org/SDL/blob/dd2d809407f152c00adc6e96e3a063eb530b7219/src/video/windows/SDL_windowswindow.c#L93-L94
Sadly, i don't know much about windows so i don't think i will be able to help much with the code while maintaining the intended behavious for those two style options:
https://github.com/libsdl-org/SDL/blob/dd2d809407f152c00adc6e96e3a063eb530b7219/src/video/windows/SDL_windowswindow.c#L109-L111
anyways, i hope this finding helps solve the problem. happy new year!

**Comment by gabrielmedici** [comment] 2024-01-02 22:15
Hello again! Turns out `STYLE_BORDERLESS` doesn't have native shadows and snapping, so i got on searching and i found a repository by a really kind gentleman that implemented ***resizable*** borderless windows with all the nice stuff that aero gives us such as snapping. And he also explained in code comments the whys of the flags that he used:
[Perma link to the code in question since github doesnt link nicely code snippets from another repository](https://github.com/melak47/BorderlessWindow/blob/3b6978d88c0eef47f79c0ac125ec154bf701375c/BorderlessWindow/src/BorderlessWindow.cpp#L13-L22)

by plopping `WS_POPUP | WS_THICKFRAME | WS_CAPTION | WS_SYSMENU | WS_MAXIMIZEBOX | WS_MINIMIZEBOX` into `STYLE_BORDERLESS_WINDOWED` we get nice, resizable, beaultiful aero borderless windows with all the fancy stuff.

I'll get around to making a pull request so we can close this :)

**Comment by gabrielmedici** [comment] 2024-01-02 23:37
My tunnel vision wouldn't let me see 10ish lines below so i didn't realise i could just set the hint `SDL_BORDERLESS_RESIZABLE_STYLE` to true and it would do the same thing that i did above :)

**Closed** 2024-01-19 13:29 UTC
