### ISSUE TITLE
cmake warning

### ISSUE THREAD

**Issue by AMRezaee** [libsdl-org/SDL#5942] opened 2022-07-21 10:26 UTC
CMake Warning (dev) at SDL2/CMakeLists.txt:553 (if):Policy CMP0054 is not set: Only interpret if() arguments as variables or
keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
details.  Use the cmake_policy command to set the policy and suppress this
warning.

CMake Warning (dev) at SDL2/CMakeLists.txt:549 (if):Policy CMP0054 is not set: Only interpret if() arguments as variables or
keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
details.  Use the cmake_policy command to set the policy and suppress this
warning.

i think these warnings prevent me from compiling SDL
i get compile errors: 
SDL2\src\events\SDL_quit.c(148): error C2065: 'OFF': undeclared identifier
SDL2\src\events\SDL_quit.c(63): error C2065: 'OFF': undeclared identifier
SDL2\src\events\SDL_quit.c(69): error C2065: 'OFF': undeclared identifier
and a few more same error
i use cmake -> ninja -> msvc

**Comment by madebr** [comment] 2022-07-21 11:22
Looks like a new warning in CMake 3.24.
Does applying the following patch fix your issue?
```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 12d6eced9..daa4ec381 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -28,6 +28,12 @@ if(MSVC)
   target_compile_options(sdl-build-options INTERFACE "/MP")
 endif(MSVC)
 
+# CMake 3.0 expands the if in "set(OFF 1);set(A OFF);if(A)" to "if(1)"
+unset(OFF)
+unset(ON)
+if(POLICY CMP0054)
+  cmake_policy(SET CMP0054 NEW)
+endif()
 
 # !!! FIXME: this should probably do "MACOSX_RPATH ON" as a target property
 # !!! FIXME:  for the SDL2 shared library (so you get an
```

**Comment by AMRezaee** [comment] 2022-07-21 11:28
i changed lines 549 to 559 of root CMakeLists.txt to bottom code.
it works and fixes the warning and compile error

if(${SDL_BACKGROUNDING_SIGNAL} STREQUAL OFF)
  target_compile_definitions(sdl-build-options INTERFACE "-DSDL_BACKGROUNDING_SIGNAL=0")
else()
  target_compile_definitions(sdl-build-options INTERFACE "-DSDL_BACKGROUNDING_SIGNAL=1")
endif()

if(${SDL_FOREGROUNDING_SIGNAL} STREQUAL OFF)
  target_compile_definitions(sdl-build-options INTERFACE "-DSDL_FOREGROUNDING_SIGNAL=0")
else()
  target_compile_definitions(sdl-build-options INTERFACE "-DSDL_FOREGROUNDING_SIGNAL=1")
endif()

**Comment by madebr** [comment] 2022-07-21 11:47
That's not a solution because `SDL_BACKGROUNDING_SIGNAL` and `SDL_FOREGROUNDING_SIGNAL` are supposed to be configurable by the user: they can have more values then 0 or 1.
Also using `if(${XXX} ...)` is old-style syntax.

I cannot reproduce this warning with CMake 3.24.0-rc4 on Linux

**Comment by AMRezaee** [comment] 2022-07-21 11:59
sorry i thought it has boolean value.
i checked your patch it fixed the problem. thank you.

**Comment by madebr** [comment] 2022-07-21 12:09
Thanks for checking!
Fixed in https://github.com/libsdl-org/SDL/commit/8f33de84621319a5504f2197854a2e5c03ae5dea

**Closed by madebr** 2022-07-21 12:09 UTC
