### ISSUE TITLE
Screenshot button on Switch Pro Controller not detected

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3147] opened 2021-02-11 01:23 UTC
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Mac OS X (All), x86_64

# Comments on the original bug report:

On 2019-01-30 12:54:15 +0000,  wrote:

> I am trying to get Switch Pro Controller to work on my mac. After I called SDL_JoystickNumButtons(), it returned 15, which in fact should be 16. I've figured out that the missing button is the Screenshot button on the left side of the joystick (the one at the left of the home button and below the minus button). I've tried buttons from 0~14 and none of them represented the screenshot button.
> 
> I'm using the SDL2# binding by flibitijibibo but it shouldn't change anything since it's calling the same functions. And my OS X version is 10.14 Mojave.
> 
> I came here because the mighty internets does not seem to know about this problem.

**Comment by icculus** [comment] 2021-11-30 06:02
Duplicate of #3146.

**Closed by icculus** 2021-11-30 06:02 UTC
Labels: bug
