### ISSUE TITLE
[Wayland] Cursor keys and return key with phosh+squeekboard (on-screen keyboard) not working

### ISSUE THREAD

**Issue by ell1e** [libsdl-org/SDL#5911] opened 2022-07-12 12:11 UTC
Cursor keys and the return key under `SDL_VIDEODRIVER=wayland` with phosh+squeekboard (on-screen keyboard) are sadly not working when pressed on the squerkboard keyboard. With `SDL_VIDEODRIVER=x11` they work, letters and backspace also work just fine.

**Versions:**

- Phosh: 0.17.0
- squeekboard: 1.17.1
- SDL2: 2.0.22

**Comment by flibitijibibo** [comment] 2022-07-12 14:51
No idea what most of these things are, but I would imagine it falls in line with text_input_v3, which lives in these two areas:

https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandkeyboard.c

https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandevents.c#L1634-L1641

**Comment by ell1e** [comment] 2022-07-16 13:25
Phosh is one of the two most common mobile desktops in use on Linux phones etc. right now. Squeekboard is just the on-screen keyboard it's usually packaged with. This bug renders all applications unusable on Phosh linux phones that may require cursor key input but otherwise happen to be usable on a phone screen (also #5899 may break SDL_Renderer output) - unless you use SDL2's X11 backend, but then touch might be broken beyond use for you, see #5924 .

Right now, using SDL2 for linux phones is rather frustrating due to the amount of regressions and bugs like this, even though it seems one of the most natural choices to target this kind of platform, especially for simple and fun 2d games since most linux phones sold right now are comparatively lower spec.

**Comment by flibitijibibo** [comment] 2022-07-16 13:41
I don't think we have any maintainers with that environment at all - it's either desktop Linux or iOS/Android with nothing in between, so that's probably what's up. If someone came in to regularly review and patch for that environment it would prevent a lot of this! I filed a request for a PinePhone to do SDL testing with and they said no, so that's about as close as I've ever gotten to having the relevant hardware.

I don't know who builds and ships these devices with these systems installed, but if they have any engineers I would let them know that there's a big gap in a really popular library that they could fill in!

**Comment by ell1e** [comment] 2022-07-16 14:09
The PinePhone is community-maintained as far as the OS side goes, there isn't even an official distro and some just happen to target it. You could ask postmarketOS devs to help out with testing (which is the distro I use), but I imagine they are quite busy

However, Fedora packages Phosh for x64. If you can get it to run in undocked mode (not sure how easy that is, could be as simple as toggling in the notification area) to its phone mobile UI rather than the laptop/desktop convergence one and your laptop has a working touch screen you can probably most or all the issues I am filing. This environment also has one huge advantage to an actual PinePhone: you won't wait an hour for an SDL2 build, which is why I only test the distro versions usually.

(I actually have such a laptop but the kernel seems to have completely broken the touch drivers for it turning the touch screen effectively dead with nobody really minding, so that essential part sadly is missing for me. Also I'm away from home right now without the laptop, I am writing these tickets on my phone)

**Comment by flibitijibibo** [comment] 2022-07-16 14:20
It's definitely worth looking into - the Wayland landscape is currently in a state where if the author does not have the compositor literally in front of their face at least once, there's about a 50% chance it'll work. So, the lab here has basically every desktop on it at the same time: A mutter environment (GNOME), kwin environment (Plasma) and at least one wlroots environment (sway). That at least covers desktop, but even with the same compositing frameworks, the mobile UIs and input devices are different enough to make it fall in that "maybe it works, maybe it doesn't" category.

The hardware is the main blocker for my lab at least; I can run simulators and nested compositors, but it won't have the real input that we seem to hit and miss on so much (and I have no touch devices at this point, the Deck will be the closest one and that's not coming until the end of the year). The others might have something, but up to this point we basically never see reviews for changes on mobile until looong after the desktop people have verified it for their tests.

**Comment by ell1e** [comment] 2022-07-16 14:24
Afaik Phosh uses Phoc which uses wlroots. So if your sway environment has touch then #5924 at least might reproduce there if sway also happens to support xwayland. (Or not, who knows, I wouldn't know how much XWayland support is in wlroots itself and what's on top.)

**Comment by slouken** [comment] 2022-07-16 14:51
I'm optimistically adding this to the 2.24.0 milestone, hoping that someone will get hardware that we can test this on.

**Comment by ell1e** [comment] 2022-07-17 17:39
I just discovered the return key also doesn't work which is a way bigger problem. I used the xwayland/x11 sdl video driver up to now instead as a workaround but #5924 broke that very thoroughly. So now I can choose either no way to enter multi-line text (this bug) or all scrollbars and scroll views are unusable ( #5924 ). Needless to say neither are really workable 😭 so I'm a bit stuck. Glad for any workaround suggestions

**Comment by dos1** [comment] 2022-07-18 17:03
> but I would imagine it falls in line with text_input_v3

Not when it comes to things like cursor and return keys. Those are send to the compositor via virtual-keyboard and then sent to clients as regular wl-seat events.

However, since Squeekboard works with arbitrary layouts, it uses automatically generated keymaps that don't match any actual physical keyboard layouts. Some applications have troubles with that, and judging from the description this may be the case with SDL here.

There's no need for any special hardware for testing, Phosh consists of regular GNU/Linux applications that you can run on any desktop. Just launch [phoc](https://gitlab.gnome.org/World/Phosh/phoc) nested, run [Squeekboard](https://gitlab.gnome.org/World/Phosh/squeekboard) in it (`SQUEEKBOARD_DEBUG=force-show` env var may be handy) and then launch SDL app.

Also, this doesn't actually sound related to phosh/phoc at all - I'm pretty sure it will be reproducible on sway just as well.

**Comment by flibitijibibo** [comment] 2022-07-18 19:33
That all makes sense to me - that said, someone else will need to look into this:

As of today I've signed onto a job that will take me _very_ far away from Wayland development beyond review and running things through the lab when explicitly requested; I will not be writing _any_ Wayland patches for the rest of 2022. To try and keep things organized I've added a Wayland label to everything that had Wayland on it and/or was assigned to me; all of those items are now unassigned.

(Separately: Still working on audio and PipeWire-by-default, as well as general Linux-y things, only this is on hold.)

**Comment by icculus** [comment] 2022-08-04 14:46
I just ordered a PinePhone; I have no idea when it'll arrive, but it's definitely not going to land in this milestone.

**Comment by dos1** [comment] 2022-08-04 16:32
> I'm pretty sure it will be reproducible on sway just as well.

For the record, I've verified that now and, indeed, it's also happening under sway (and likely any other compositor + OSK combo that happens to use custom keymaps as well). Unfortunately, I personally don't know much about how SDL handles keymaps, so I'm hoping that someone with that knowledge jumps into it before I go into this rabbit hole myself...

**Comment by flibitijibibo** [comment] 2022-08-04 16:35
Here's our keyboard listener: https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandevents.c#L1127

Both the keymap and modifiers callbacks will be where all the related activity is.

**Comment by dos1** [comment] 2022-08-04 16:49
The most interesting part seems to be https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandevents.c#L1009, which appears... hardcoded?

**Comment by flibitijibibo** [comment] 2022-08-04 21:09
That array refers to the scancode value AFAIK. From what I remember, the key is a scancode that we're expected to translate, so we make the translation table in keymap/modifiers and then use it when passing to SDL_SendKeyboardKey. Note that this is key presses rather than text, which is handled with keyboard_input_get_text within that function. SDL_IME usually handles text but keyboard_input_get_text does have an xkb fallback that _supposedly_ translates as well, but this is where things started getting done with trial-and-error to get it working on both GNOME and Plasma.

**Comment by dos1** [comment] 2022-08-05 01:09
I believe `keyboard_input_get_text` works fine, it's `SDL_SendKeyboardKey` where things go wrong, and I don't see how can it even be supposed to work. Unless I'm missing something, it doesn't seem to consult the keymap at all and just uses a hardcoded array, which obviously fails since Squeekboard uses autogenerated keymaps with arbitrary scancodes.

**Comment by ell1e** [comment] 2022-08-30 19:07
For what it's worth, if my memory isn't tricking me I think the X11/XWayland code path of SDL2 had the exact same problem with squeekboard's dynamic keyboards, and I think someone similarly discovered SDL2 used some wrongly hardcoded assumptions about the keymap. So maybe there is some insight in SDL2's X11/XWayland code path and how it was fixed there? (I might be wrong though, I have almost no clue how lowlevel X11 or Wayland code works like.)

**Comment by Kontrabant** [comment] 2022-10-17 22:43
https://github.com/Kontrabant/SDL/tree/wayland_scancodes_by_name

Can someone with the right setup try this experimental branch? Instead of using the hardcoded table, it looks up the SDL scancodes for the keys via their canonical xkb names, so a virtual keyboard using arbitrary scancodes shouldn't be an issue.

**Comment by Kontrabant** [comment] 2022-10-20 21:23
I finally got a librem5 VM configured with SDL building (note that the current version of SDL doesn't build the Wayland backend without modification due to librem shipping wayland-client 1.16 and SDL requiring 1.18), and squeekboard uses both arbitrary scancodes _and_ keycode names, so the previous approach won't work.

I have a new idea to address this, keeping a table of control key (esc, return, arrows, etc...) mappings between xkb keysyms and SDL scancodes, which is used to dynamically map these keys, and treating everything else as a text generating key only, so they will generate text events, but not key up/down events.  You won't be able to use things like WASD controls with squeekboard, but that's not really what it's meant for anyways.

**Comment by ell1e** [comment] 2022-10-20 21:34
Key up/down are IMHO quite important, they might be used for navigating menus that may not be fully ported to touch, keyboard shortcuts people may want to use, and some simpler games also use them for text input (even though they maybe shouldn't). Also, for X1 there was the same problem with no up/down being generated by squeekboard and other such keyboards and it was also added in as faked events somehow for compatibility, so not doing so for Wayland would be inconsistent. However, I'm not sure if any virtual keyboard can be expected to generate them or how exactly to make sure you don't end up with duplicates, it might again be worth checking the X11 code path where that was added for that.

**Comment by Kontrabant** [comment] 2022-10-20 23:10
https://github.com/Kontrabant/SDL/tree/wayland_dynamic_keyboard

**Closed** 2022-11-15 19:00 UTC
Labels: waiting
