### ISSUE TITLE
MINOR ISSUE: Using SDL_WINDOWPOS_CENTERED should center to a single display and not the sum of all displays

### ISSUE THREAD

**Issue by willrabbermann** [libsdl-org/SDL#7009] opened 2023-01-06 20:25 UTC
For context:
```
Monitors: 2
0: +DP-4 2560/697x1440/392+1920+0  DP-4
1: +HDMI-0 1920/477x1080/268+0+0  HDMI-0
```
Gentoo Linux, X11, DWM

a 1080p monitor to my (left)
A 1440p monitor to my (right)

When creating a centered window, 
```
window = SDL_CreateWindow( caption,
		SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
		SCREEN_WIDTH, SCREEN_HEIGHT, SDL_WINDOW_OPENGL );

SDL_SetWindowPosition(window, SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED);
// SetWindowPosition makes it slightly more centered on the right monitor but not perfectly.
```
The centered position is found by finding the bounds of the display(s), 
then finding the middle point:
```
if (SDL_WINDOWPOS_ISUNDEFINED(x) || SDL_WINDOWPOS_ISUNDEFINED(y) ||
        SDL_WINDOWPOS_ISCENTERED(x) || SDL_WINDOWPOS_ISCENTERED(y)) {
        SDL_VideoDisplay *display = SDL_GetDisplayForWindow(window);
        int displayIndex;
        SDL_Rect bounds;

        displayIndex = SDL_GetIndexOfDisplay(display);
        SDL_GetDisplayBounds(displayIndex, &bounds);
        if (SDL_WINDOWPOS_ISUNDEFINED(x) || SDL_WINDOWPOS_ISCENTERED(x)) {
            window->x = bounds.x + (bounds.w - w) / 2;
        }
        if (SDL_WINDOWPOS_ISUNDEFINED(y) || SDL_WINDOWPOS_ISCENTERED(y)) {
            window->y = bounds.y + (bounds.h - h) / 2;
        }
}
```

At first I thought this was a bug with my WM (dwm & x11) 
but after running the same application on my second monitor (to my left), it is perfectly centered.

When opening my application on my right monitor, it is slightly upper left bound. As if it is finding the midpoint of the 1080p + 1440p monitors together. 

This is a super minor issue.
I set my left monitor in my .xinitrc with xrandr as such:
```xrandr --output HDMI-0 --auto --left-of DP-4```

**Comment by willrabbermann** [comment] 2023-01-06 21:08
Checking ```SDL/SDL_video.c```
```
int SDL_GetDisplayBounds(int displayIndex, SDL_Rect *rect)
```
...
```
 if (displayIndex == 0) {
        rect->x = 0;
        rect->y = 0;
    } else {
        SDL_GetDisplayBounds(displayIndex - 1, rect);
        rect->x += rect->w;
    }
```
Recursively calls itself with displayIndex - 1. Thats why my left monitor is perfectly center. It is index 0. Index 1 is my right monitor and it will add the sum of both display bounds.

**Comment by willrabbermann** [comment] 2023-01-07 01:09
![2023-01-06-190739_2560x1440_scrot](https://user-images.githubusercontent.com/105755092/211124226-acf4d83f-0f98-491f-a124-86b22affcc45.png)

**Comment by willrabbermann** [comment] 2023-01-19 19:29
I'm switching to Wayland but keeping my X config. This should fix the noticeable screen tearing when using graphical applications. Ill see if the issue is still present inside Wayland, don't know why I went with a legacy windowing system/server.

**Comment by 1bsyl** [comment] 2023-01-23 09:06
I give a try and couldn't reproduce it.

it that that case (x11 / wayland also) this is *not* recursive:
_this->GetDisplayBounds is implemented and always returns 0;

**Comment by 1bsyl** [comment] 2023-01-23 09:25
@slouken :
small parenthesis: 
- it's possible to center the window on a different display using SDL_WINDOWPOS_CENTERED_DISPLAY()
maybe we should have a:
`void SDLCALL SDL_SetWindowPositionOnDisplay(SDL_Window * window, int x, int y, int displayIndex); `

Also a typedef, not sure, this is index vs id:
`typedef int SDL_DisplayID;`

**Comment by 1bsyl** [comment] 2023-01-23 10:36
this can be reproduced by forcing the use of X11_InitModes_StdXlib()
./test/testdisplayinfo  would only report 1 big display for instance (including two), instead of two display.
so the window is center in the middle of both

**Comment by willrabbermann** [comment] 2023-01-23 22:25
I rebuilt libsdl with +xinerama; my window still shows up in the same position as before.

**Comment by 1bsyl** [comment] 2023-01-24 10:18
@willrabbermann, if you re-try, please add traces into: 
X11_InitModes_StdXlib() and X11_InitModes_XRandR()

**Comment by willrabbermann** [comment] 2023-01-24 14:45
implicit declaration of X11_InitModes_StdXlib() and X11_InitModes_XRandR()
what include am I missing?

```
```

**Comment by willrabbermann** [comment] 2023-02-26 13:25
on wayland the sdl app is perfectly centered, this issue only applies to xorg applications on multiple monitors.

**Comment by slouken** [comment] 2023-05-20 17:45
This is expected if XRandR isn't available. I'm going to go ahead and re-close this.

Thanks!

**Closed by slouken** 2023-05-20 17:45 UTC
