### ISSUE TITLE
Add flush to SDL_rwops

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3581] opened 2021-02-11 01:51 UTC
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Linux, All

# Comments on the original bug report:

On 2020-03-11 15:32:58 +0000, Rainer Deyke wrote:

> I am using SDL_RWops for a log file.  This works fine for most cases, but if my program crashes with the log file open, the resulting log file is truncated because the file hasn't been flushed to the disk.  Would it be possible to add a flush function to SDL_RWops so that I can manually flush my log file to disk?

**Comment by icculus** [comment] 2022-06-14 04:38
Duplicate of #3121.

**Closed by icculus** 2022-06-14 04:38 UTC
