### ISSUE TITLE
Mouse down event. Triggered when window active event ocure by clicking on window title.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1707] opened 2021-02-10 23:51 UTC
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.3
**Reported for operating system, platform:** Windows 7, x86

# Comments on the original bug report:

On 2014-12-05 19:48:34 +0000, Alex wrote:

> Step to reproduce:
> 1. Run SDL2 windowed application with mouse down capture event.
> 2. Click on something else on your desctop to lose app focus.
> 3. Click back on SDL2 app window title bar to activate it.
> Mouse down event should not trigger when you click on window title bar.
> 
> Problem may relay to file: SDL_windowsevents.c
> Code:
>     case WM_ACTIVATE:
>         {
>             BOOL minimized;
> 
>             minimized = HIWORD(wParam);
>             if (!minimized && (LOWORD(wParam) != WA_INACTIVE)) {
>                 SDL_SendWindowEvent(data->window, SDL_WINDOWEVENT_SHOWN, 0, 0);
>                 if (SDL_GetKeyboardFocus() != data->window) {
>                     SDL_SetKeyboardFocus(data->window);
>                 }
>                 WIN_UpdateClipCursor(data->window);
>                 WIN_CheckAsyncMouseRelease(data);//PROBLEM HERE!!!!!!
> .............
> 
> Call of "WIN_CheckAsyncMouseRelease(data);" lead to this mouse down event
> Quick solution is to simply comment this line: WIN_CheckAsyncMouseRelease(data);//PROBLEM HERE!!!!!!
> But can brake something else, not sure what purpose of this code for window activation ... 
> 
> Can be the same bug described here: 
> https://bugzilla.libsdl.org/show_bug.cgi?id=2195

**Comment by icculus** [comment] 2021-08-11 13:44
Duplicate of #1178.

**Closed** 2021-08-11 13:45 UTC
Labels: bug
