### ISSUE TITLE
A border-less window, when maximised will consume the whole screen

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2163] opened 2021-02-11 00:20 UTC
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.4
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2016-05-11 02:03:39 +0000, Paul wrote:

> A border-less window, when maximised will consume the whole screen instead of the system's actual working area. The result is identical to SDL_WINDOW_FULLSCREEN_DESKTOP bar event differences.
> 
> Maximising a border-less window should behave identically to a bordered window, just like other border-less applications.

**Comment by slouken** [comment] 2023-11-04 19:51
I'll check to see if we're doing something special here, but we should let Windows do whatever is appropriate for maximized windows.

**Comment by icculus** [comment] 2024-10-06 17:46
Duplicate of #7975, we'll handle this over there.

**Closed** 2024-10-06 17:46 UTC
