### ISSUE TITLE
Wait for vsync stops working when window is hidden and using an external monitor

### ISSUE THREAD

**Issue by ellipticaldoor** [libsdl-org/SDL#4521] opened 2021-07-22 16:06 UTC
It looks like when the window gets completely covered by another window and an external screen is conected then vsync will not wait and the fps will render above 60fps to 3000fps throttling the application and draining the laptop battery.

I tried this using both OpenGL and Vulkan window and I get the same behaviour.

As soon as I disconnect the external monitor, then the window vsync wait works as expected when getting covered.

**Comment by ellipticaldoor** [comment] 2021-07-23 11:05
I forgot to mention that this happens on latest macos big sur 11.4

**Comment by icculus** [comment] 2021-11-07 20:05
This is apparently intended behavior for Metal (which is to say, Vulkan via MoltenVK probably has the same issue)...windows that are completely obscured either just abandon submitted command buffers or at least ignore presentDrawable commands.

I would not be surprised if OpenGL has this issue in modern macOS, too.

Also someone has noted vsync in OpenGL has broken in Monterey as well (see issue #4918).

I don't think this is an SDL bug, so I'm closing it; if this is in error, please say so.

The best workaround is likely to be checking if an SDL_GL_SwapBuffer call returned way too quickly and calling SDL_Delay() for a few milliseconds if so. This isn't a good way to regulate the framerate, but if battery life or the CPU fans blasting is the bigger concern, it's probably good enough.

**Closed by icculus** 2021-11-07 20:05 UTC
