### ISSUE TITLE
[Feature request] always on top window wayland

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [libsdl-org/SDL#5779] opened 2022-06-10 02:09 UTC
I am pretty sure always on top windows are supported on wayland through wlr-layer-shell, so I think it would be nice if it got supported in sdl2.
I can only think of one compositor (mutter) that doesn't support this feature, so it's probably worth implementing

**Comment by flibitijibibo** [comment] 2022-06-10 13:13
I'm actually not 100% sure we can use this as an application library - the closest protocol I was able to find was wlr-layer-shell, and wlroots protocols are usually for the compositor. It does look like it has layers for topmost windows, but again I'm not sure we're supposed to be using this, unlike the protocols you can find in the [core protocols](https://gitlab.freedesktop.org/wayland/wayland-protocols/) repository.

**Comment by Etaash-mathamsetty** [comment] 2022-06-10 19:07
I am pretty sure gtk-layer-shell uses it, and basically all compositors except mutter support wlr-layer-shell

**Comment by Etaash-mathamsetty** [comment] 2022-06-21 23:45
![image](https://user-images.githubusercontent.com/45927311/174914442-16b0ff05-8da1-44cc-a0e6-afad25b5ce74.png)
I was right, kde along with wlroots (ofc) support it

**Comment by Etaash-mathamsetty** [comment] 2022-07-06 10:53
> Using layer-shell to implement always-on-top would be a huge abuse of the protocol and would be insanely broken when it comes to window positioning, resizing, placement on task bar and likely a lot of other things that don't instantly come to my mind. Please don't even consider this ;)

could I ask why?
according to the wlroots documentation, "This interface should be suitable for the implementation of many desktop shell components, and a broad number of other applications that interact with the desktop."

**Comment by flibitijibibo** [comment] 2022-07-06 12:55
The key phrase is "desktop shell components," which is what I was saying earlier - this is likely for things like picture-in-picture rather than just app windows. It vaguely leaves the door open, but if this is something you want at the app level I would bring it up with the wayland-protocols repo.

**Comment by Etaash-mathamsetty** [comment] 2022-07-11 18:21
> The key phrase is "desktop shell components," which is what I was saying earlier - this is likely for things like picture-in-picture or taskbar elements rather than just app windows. It vaguely leaves the door open, but if this is something you want at the app level I would bring it up with the wayland-protocols repo.



> The key phrase is "desktop shell components," which is what I was saying earlier - this is likely for things like picture-in-picture or taskbar elements rather than just app windows. It vaguely leaves the door open, but if this is something you want at the app level I would bring it up with the wayland-protocols repo.

there's an issue about picture in picture in that repo, so once someone makes a valid wayland protocol for it we could probably add it into SDL

**Comment by diagonalisability** [comment] 2022-10-21 17:01
It looks like there was already a request for an always-on-top window Wayland protocol (https://gitlab.freedesktop.org/wayland/wayland/-/issues/305), but it was marked as a duplicate of the "Support for Picture-in-Picture windows" issue (https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/44). The linked MR is specific to Picture-In-Picture windows, like what Firefox has for playing videos. On the MR page though (https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/132), there's a long discussion about what Wayland clients should be allowed to do with PiP windows, and it sounds pretty restrictive. It looks like these PiP windows would be used for videos and ongoing phone calls, but it's kind of hard to think of any other real reasons to keep a window above every other window, instead of just temporarily bringing it to the front to get the user's attention (which is handled by the XDG activition protocol: https://wayland.app/protocols/xdg-activation-v1). It doesn't sound like they'd be open to having a generic always-on-top protocol, given that they seem to want any use-cases for always-on-top windows to be handled by more specific protocols.

**Comment by flibitijibibo** [comment] 2022-10-21 17:23
I'd have to agree with the protocols group on this one - I'm not aware of any applications using this and my guess is the case we eventually find will be specific enough to be able to expose a very specific feature that uses an appropriate protocol, rather than the current API that's kind of a sledgehammer.

This might be something to think about for 3.0: Changing "always-on-top" to be more specific about what you're actually supposed to do with it; I imagine this would be applicable to mobile platforms in particular which now have features like PiP available. (CC @slouken)

For this: Going to close as `WONTFIX` since it probably won't make it into any 2.x release, and ideally 3.0 will change this to be something Wayland can safely support.

**Closed by flibitijibibo** 2022-10-21 17:23 UTC
Labels: enhancement, wayland

**Comment by davidedmundson** [comment] 2023-01-23 21:33
What was your original use case for "always on top"? I want to push forward on something upstream and want to make sure it covers all existing applications.

**Comment by Etaash-mathamsetty** [comment] 2023-01-23 21:33
> What was your original use case for "always on top"? I want to push forward on something upstream and want to make sure it covers all existing applications.

picture in picture
