### ISSUE TITLE
SDL 2.28.5, Retroflag USB SNES controller not working on Mac OS, but works on Windows, Linux 

### ISSUE THREAD

**Issue by cidus** [libsdl-org/SDL#8566] opened 2023-11-16 20:02 UTC
I have some Retroflag USB controllers, which are detected correctly by MacOS Ventura and work on some apps like Steam and OpenEmu, but they do not work on EmulationStation - Desktop Edition (SDL 2.28.5). I have reported this with them, and they redirected me here.

The controller is detected and configured on Steam with the following bind string:

03000000830500006020000000010000,iBuffalo SNES Controller,a:b0,b:b1,back:b6,dpdown:+a1,dpleft:-a0,dpright:+a0,dpup:-a1,leftshoulder:b4,rightshoulder:b5,start:b7,x:b2,y:b3,hint:SDL_GAMECONTROLLER_USE_BUTTON_LABELS:=1,platform:macOS,

Steam version 1698777785

On EmulationStation for Windows, Linux, the controller works correctly.

I'm using a Macbook Pro 2021, M1 Pro, MacOS Ventura 13.5.2

**Comment by slouken** [comment] 2023-11-17 04:21
This is a known issue with the latest version of macOS.

**Comment by slouken** [comment] 2023-11-22 18:00
This is a duplicate of https://github.com/libsdl-org/SDL/issues/8341, which is now fixed.

**Closed by slouken** 2023-11-22 18:00 UTC
