### ISSUE TITLE
macos failures in CI

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#9606] opened 2024-04-23 19:32 UTC
In my fork, SDL2 macOS autotools build fails with
  `Error: Process completed with exit code 127.` in two attempts:
https://github.com/sezero/SDL/actions/runs/8805776127/job/24169481106
Seemed to have survived in libsdl-org original repo..

In my fork, SDL3 both of macOS builds fail in test runs: Was this a known issue?
```
 	  2 - testautomation (Failed)
	 21 - testautomation-no-simd (Failed)
```
https://github.com/sezero/SDL/actions/runs/8805776154/job/24169122407
https://github.com/sezero/SDL/actions/runs/8805776154/job/24169122082
Both seemed to have survived in libsdl-org original repo, again, though...

CC: @madebr

**Comment by madebr** [comment] 2024-04-23 20:16
> In my fork, SDL2 macOS autotools build fails with
> `Error: Process completed with exit code 127.` in two attempts:

Perhaps we need to install [`automake`](https://formulae.brew.sh/formula/automake)?
It's not an imaginary GitHub stopped installing this by default (or it's accidentally unavailable on some runners).

For posterity, [I copied the testautomation-no-simd failures](https://github.com/sezero/SDL/actions/runs/8805776154/job/24169122407#step:11:45976).
Did something changed in its internals? I can't reproduce (due to no access to hw).

<details>

<summary>stdlib_swprintf</summary>

```
--seed 8HZAWHALAABNI2AL --filter fabs_rangeTest
```

```
INFO:  04/23/24 19:13:12: ----- Test Case 21.5: 'stdlib_swprintf' started
INFO:  04/23/24 19:13:12: Test Description: 'Call to SDL_swprintf'
INFO:  04/23/24 19:13:12: Test Iteration 1: execKey 149963258834810706
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%s", "foo")': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: f, got: f': Failed
INFO:  04/23/24 19:13:12: Assert 'Check result value, expected: 1, got: 1': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%s", "foo") with buffer size 2': Passed
INFO:  04/23/24 19:13:12: Assert 'Check text, expected: f, got: f': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 3, got: 1': Failed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf(NULL, 0, "%s", "foo")': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 3, got: 1': Failed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%s\n", "foo") with buffer size 2': Passed
INFO:  04/23/24 19:13:12: Assert 'Check text, expected: f, got: f': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 4, got: 1': Failed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%f", 0.0)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: 0, got: 0': Failed
INFO:  04/23/24 19:13:12: Assert 'Check result value, expected: 2, got: 2': Passed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 2, got: 2': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%f", 1.0)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: 1, got: 1': Failed
INFO:  04/23/24 19:13:12: Assert 'Check result value, expected: 2, got: 2': Passed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 2, got: 2': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%.f", 1.0)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: 1, got: ': Failed
INFO:  04/23/24 19:13:12: Assert 'Check result value, expected: 0, got: 0': Passed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 0, got: 0': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%#.f", 1.0)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: 1, got: ': Failed
INFO:  04/23/24 19:13:12: Assert 'Check result value, expected: 0, got: 0': Passed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 0, got: 0': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%f", 1.0 + 1.0 / 3.0)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: 1, got: 1': Failed
INFO:  04/23/24 19:13:12: Assert 'Check result value, expected: 2, got: 2': Passed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 2, got: 2': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%+f", 1.0 + 1.0 / 3.0)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: +, got: +': Failed
INFO:  04/23/24 19:13:12: Assert 'Check result value, expected: 2, got: 2': Passed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 2, got: 2': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%.2f", 1.0 + 1.0 / 3.0)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: 1, got: 1': Failed
INFO:  04/23/24 19:13:12: Assert 'Check result value, expected: 1, got: 1': Passed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 1, got: 1': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%6.2f", 1.0 + 1.0 / 3.0)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: ' ', got: ' '': Failed
INFO:  04/23/24 19:13:12: Assert 'Check result value, expected: 1, got: 1': Passed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 1, got: 1': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%06.2f", 1.0 + 1.0 / 3.0)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '0', got: '0'': Failed
INFO:  04/23/24 19:13:12: Assert 'Check result value, expected: 1, got: 1': Passed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 1, got: 1': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%06.2f", 1.0 + 1.0 / 3.0) with buffer size 5': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '0', got: '0'': Failed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 6, got: 1': Failed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%f", 100)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '1', got: '1'': Failed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 10, got: 2': Failed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 2, got: 2': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%g", 100)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '1', got: '1'': Failed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 3, got: 1': Failed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 1, got: 1': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%f", -100)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '-', got: '-'': Failed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 11, got: 3': Failed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 3, got: 3': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%g", -100)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '-', got: '-'': Failed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 4, got: 1': Failed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 1, got: 1': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%f", 100.75)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '1', got: '1'': Failed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 10, got: 2': Failed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 2, got: 2': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%g", 100.75)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '1', got: '1'': Failed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 6, got: 1': Failed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 1, got: 1': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%f", -100.75)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '-', got: '-'': Failed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 11, got: 3': Failed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 3, got: 3': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%g", -100.75)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '-', got: '-'': Failed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 7, got: 2': Failed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 2, got: 2': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%f", 59.94)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '5', got: '5'': Failed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 9, got: 2': Failed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 2, got: 2': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%g", 59.94)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '5', got: '5'': Failed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 5, got: 1': Failed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 1, got: 1': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%f", -59.94)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '-', got: '-'': Failed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 10, got: 2': Failed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 2, got: 2': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%g", -59.94)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '-', got: '-'': Failed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 6, got: 1': Failed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 1, got: 1': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%f", 119.88)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '1', got: '1'': Failed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 10, got: 2': Failed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 2, got: 2': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%g", 119.88)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '1', got: '1'': Failed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 6, got: 1': Failed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 1, got: 1': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%f", -119.88)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '-', got: '-'': Failed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 11, got: 3': Failed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 3, got: 3': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%g", -119.88)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '-', got: '-'': Failed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 7, got: 2': Failed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 2, got: 2': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%f", 10)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '1', got: '1'': Failed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 9, got: 2': Failed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 2, got: 2': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%g", 10)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '1', got: ''': Failed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 2, got: 0': Failed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 0, got: 0': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%f", -10)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '-', got: '-'': Failed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 10, got: 2': Failed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 2, got: 2': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf("%g", -10)': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '-', got: '-'': Failed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 3, got: 1': Failed
INFO:  04/23/24 19:13:12: Assert 'Check predicted value, expected: 1, got: 1': Passed
INFO:  04/23/24 19:13:12: Assert 'Call to SDL_swprintf(text, sizeof(text), "%zu %s", size, "test")': Passed
ERROR: 04/23/24 19:13:12: Assert 'Check text, expected: '6', got: '6'': Failed
ERROR: 04/23/24 19:13:12: Assert 'Check result value, expected: 7, got: 2': Failed
ERROR: 04/23/24 19:13:12: Assert Summary: Total=133 Passed=76 Failed=57
INFO:  04/23/24 19:13:12: Total Test runtime: 0.0 sec
ERROR: 04/23/24 19:13:12: >>> Test 'stdlib_swprintf': Failed
```

</details>

<details>

<summary>fabs_rangeTest</summary>

```
--seed 8HZAWHALAABNI2AL --filter stdlib_swprintf
```

```
INFO:  04/23/24 19:13:10: ----- Test Case 11.28: 'fabs_rangeTest' started
INFO:  04/23/24 19:13:10: Test Description: 'Checks a range of positive integer'
INFO:  04/23/24 19:13:10: Test Iteration 1: execKey 15137364879781547564
INFO:  04/23/24 19:13:10: Assert 'Fabs: Testing a range of 10000000 values with steps of 429': Passed
ERROR: 04/23/24 19:13:10: Assert 'Fabs(3558331491.0), expected 3558331491.0, got 3558331491.0': Failed
ERROR: 04/23/24 19:13:10: >>> Test 'fabs_rangeTest': Failed (Aborted)
INFO:  04/23/24 19:13:10: Total Test runtime: 0.0 sec
ERROR: 04/23/24 19:13:10: >>> Test 'fabs_rangeTest': Failed

```

</details>

**Comment by sezero** [comment] 2024-04-23 20:28
> Perhaps we need to install [`automake`](https://formulae.brew.sh/formula/automake)?

[`autoconf`](https://formulae.brew.sh/formula/autoconf) _should_ be enough for SDL itself; same for SDL_mixer. Other stallite libs will need both automake and autoconf

> For posterity, [I copied the testautomation-no-simd failures](https://github.com/sezero/SDL/actions/runs/8805776154/job/24169122407#step:11:45976). Did something changed in its internals?

Don't know but I don't think so

**Comment by sezero** [comment] 2024-04-23 20:55
> > For posterity, [I copied the testautomation-no-simd failures](https://github.com/sezero/SDL/actions/runs/8805776154/job/24169122407#step:11:45976). Did something changed in its internals?
> 
> Don't know but I don't think so

The behavior persists: The latest commit fails macos CI test runs in my fork, whereas mainsteam seems fine:

https://github.com/sezero/SDL/actions/runs/8806817475/job/24172474220
https://github.com/sezero/SDL/actions/runs/8806817475/job/24172474513

Maybe I'm cursed..

**Comment by madebr** [comment] 2024-04-23 21:01
Latest SDL3 job ran on:
```
Operating System
  macOS
  12.7.4
  21H1123
Runner Image
  Image: macos-12
  Version: 20240412.2
  Included Software: https://github.com/actions/runner-images/blob/macOS-12/20240412.2/images/macos/macos-12-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20240412.2

```
Yours is running on:
```
Operating System
  macOS
  14.4.1
  23E224
Runner Image
  Image: macos-14-arm64
  Version: 20240415.6
  Included Software: https://github.com/actions/runner-images/blob/macos-14-arm64/20240415.6/images/macos/macos-14-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240415.6
```
Perhaps it's something to do with newer macos?

**Comment by sezero** [comment] 2024-04-23 21:08
Ah, most possible root of the cause. Why does it pick older macos when running on libsdl-org, though...

**Comment by madebr** [comment] 2024-04-23 21:49
> Ah, most possible root of the cause. Why does it pick older macos when running on libsdl-org, though...

"the algorithm" picked you :)

<details>

![zSO58QE](https://github.com/libsdl-org/SDL/assets/4138939/c4923228-0a2f-44c8-857e-2667c00bc60f)

</details>

**Comment by sezero** [comment] 2024-04-23 21:52
I added autoconf installation to macos wokflow, and the SDL2 branch passes autotools builds in my fork now. Cherry-picked to 2.30.x too. (First wrongly picked into 2.28.x and several already-fixed issues showed themselves as failures - to be ignored.)

The other testsuite failures in SDL3 still need resolving.

**Comment by slime73** [comment] 2024-04-24 16:16
`macOS-latest` still runs (only? or only in specific situations?) on x64 machines, `macOS-14` uses arm64/Apple Silicon – I don't think they've added a `macOS-latest-arm64` label or something similar, for now.

**Comment by sezero** [comment] 2024-04-24 16:25
> I'm surprised macos-latest isn't already macos-14.

Well, the libsdl-org workflows seem to run on 12.7.4

> We can change it, but once macos-15 is available we should update.

> `macOS-latest` still runs (only? or only in specific situations?) on x64 machines, `macOS-14` uses arm64/Apple Silicon – I don't think they've added a `macOS-latest-arm64` label or something similar, for now.

We can temporarily _add_ a macos14 target, something like below? (Not tested at all)
```diff
diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
index dc0cb66..3965cc1 100644
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,6 +32,7 @@ jobs:
         - { name: Ubuntu 22.04,                   os: ubuntu-22.04,   shell: sh, artifact: 'SDL-ubuntu22.04' }
         - { name: MacOS (Framework),              os: macos-latest,   shell: sh, cmake-platform: '-DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"', cmake: '-DSDL_FRAMEWORK=ON -DSDL_CLANG_TIDY=OFF', skip_test_pkgconfig: true, artifact: 'SDL-macos-framework', no-static: true }
         - { name: MacOS (GNU prefix),             os: macos-latest,   shell: sh, cmake-platform: '-DCMAKE_OSX_ARCHITECTURES="x86_64"', cmake: '-DCLANG_TIDY_BINARY="$(brew --prefix llvm)/bin/clang-tidy"', artifact: 'SDL-macos-gnu' }
+        - { name: MacOS14,                        os: macos-14,       shell: sh, cmake-platform: '-DCMAKE_OSX_ARCHITECTURES="x86_64"', cmake: '-DCLANG_TIDY_BINARY="$(brew --prefix llvm)/bin/clang-tidy"', artifact: 'SDL-macos14-gnu' }
         - { name: iOS (GNU prefix),               os: macos-latest,   shell: sh, cmake-platform: '-DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"',  cross-build: true, skip_test_pkgconfig: true, artifact: 'SDL-ios-gnu' }
         - { name: tvOS (GNU prefix),              os: macos-latest,   shell: sh, cmake-platform: '-DCMAKE_SYSTEM_NAME=tvOS -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"', cross-build: true, skip_test_pkgconfig: true, artifact: 'SDL-tvos-gnu' }
 
```

**Comment by slouken** [comment] 2024-04-24 16:41
I think that would be fine. The OSX architecture should be set to "x86_64;arm64" for that target though.

**Comment by sezero** [comment] 2024-04-24 17:13
@madebr : Can you please handle the details for that?

**Comment by madebr** [comment] 2024-04-26 17:13
We do now test SDL on x86_64 and arm64 on ci.
Can anybody reproduce (and fix) the arm64 issue?
See https://github.com/libsdl-org/SDL/issues/9606#issuecomment-2073369211

**Comment by slouken** [comment] 2024-04-26 17:15
I entered a separate issue https://github.com/libsdl-org/SDL/issues/9634 for the testautomation failure, which isn't specific to CI. I think we're good to close this?

**Comment by sezero** [comment] 2024-04-26 17:43
fabs_rangeTest used to fail too. If it doesn't now and stdlib_swprintf is the only failure, then yes we can close this.

**Closed** 2024-04-26 18:03 UTC
