### ISSUE TITLE
Windows: SDL_hid_device_info breaks support with MSVC.

### ISSUE THREAD

**Issue by carlo-bramini** [libsdl-org/SDL#5454] opened 2022-03-26 13:12 UTC
It seems that the `SDL_hid_device_info` structure, which has been recently made available according to the logs, breaks the support with Microsoft Visual Studio, at least starting from VS2019 on ARM64.
If your project includes SDL_hidapi.h, then you can get this message on the console:

```
SDL_hidapi.h(97,33): error C2220: the following warning is treated as an error
SDL_hidapi.h(97,33): warning C4121: 'SDL_hid_device_info': alignment of a member was sensitive to packing
```

This issue happens because the `SDL_hid_device_info` structure has been poorly written.
At the time of writing, that structure is:

```
typedef struct SDL_hid_device_info
{
    /** Platform-specific device path */
    char *path;
    /** Device Vendor ID */
    unsigned short vendor_id;
    /** Device Product ID */
    unsigned short product_id;
    /** Serial Number */
    wchar_t *serial_number;
    /** Device Release Number in binary-coded decimal,
        also known as Device Version Number */
    unsigned short release_number;
    /** Manufacturer String */
    wchar_t *manufacturer_string;
    /** Product string */
    wchar_t *product_string;
    /** Usage Page for this Device/Interface
        (Windows/Mac only). */
    unsigned short usage_page;
    /** Usage for this Device/Interface
        (Windows/Mac only).*/
    unsigned short usage;
    /** The USB interface which this logical device
        represents.

        * Valid on both Linux implementations in all cases.
        * Valid on the Windows implementation only if the device
          contains more than one interface. */
    int interface_number;

    /** Additional information about the USB interface.
        Valid on libusb and Android implementations. */
    int interface_class;
    int interface_subclass;
    int interface_protocol;

    /** Pointer to the next device */
    struct SDL_hid_device_info *next;
} SDL_hid_device_info;
```

As you can see, there are several small size items mixed with larger size items, which can cause troubles if the user changes the default alignment or the packing of the structure and it seems that MSVC does not like it.

A better written code would be a structure with items sorted by size, for example like this;

```
typedef struct SDL_hid_device_info
{
    /** Platform-specific device path */
    char *path;
    /** Serial Number */
    wchar_t *serial_number;
    /** Manufacturer String */
    wchar_t *manufacturer_string;
    /** Product string */
    wchar_t *product_string;

    /** Pointer to the next device */
    struct SDL_hid_device_info *next;

    /** The USB interface which this logical device
        represents.

        * Valid on both Linux implementations in all cases.
        * Valid on the Windows implementation only if the device
          contains more than one interface. */
    int interface_number;

    /** Additional information about the USB interface.
        Valid on libusb and Android implementations. */
    int interface_class;
    int interface_subclass;
    int interface_protocol;

    /** Device Vendor ID */
    unsigned short vendor_id;
    /** Device Product ID */
    unsigned short product_id;
    /** Device Release Number in binary-coded decimal,
        also known as Device Version Number */
    unsigned short release_number;
    /** Usage Page for this Device/Interface
        (Windows/Mac only). */
    unsigned short usage_page;
    /** Usage for this Device/Interface
        (Windows/Mac only).*/
    unsigned short usage;

} SDL_hid_device_info;
```

to avoid useless waste of space.
However, since this code has been already made available, an alternative solution can be applied by including also `_M_ARM64` inside `begin_code.h`, since we are talking about a 64bit platform:

https://github.com/libsdl-org/SDL/blob/94ed6b0a54d127cd8caf0f1841c694093e4c0628/include/begin_code.h#L110

But I don't know how much this can break compatibility for existing versions of `SDL2.DLL`.

**Comment by cgutman** [comment] 2022-03-26 14:42
> However, since this code has been already made available, an alternative solution can be applied by including also `_M_ARM64` inside `begin_code.h`, since we are talking about a 64bit platform:
> 
> https://github.com/libsdl-org/SDL/blob/94ed6b0a54d127cd8caf0f1841c694093e4c0628/include/begin_code.h#L110
> 
> But I don't know how much this can break compatibility for existing versions of `SDL2.DLL`.

If we’re going to modify that, we should change it to `#ifdef _WIN64` to catch all 64-bit architectures.

**Comment by cgutman** [comment] 2022-03-26 17:49
Okay, I took a deeper look at this and now kind of wish I didn't 😆 

So it turns out alignment on MSVC ARM64 is screwed and the only way to fix it requires breaking the ABI. That `pack` in begin_code.h was a landmine for ARM64 (and IA-64, not that anyone cares).

In a SDL2.dll compiled for ARM64 with VS2022, `SDL_hid_device_info` is laid out in memory like this:
```
0:000> dt SDL2!SDL_hid_device_info
SDL2!SDL_hid_device_info
   +0x000 path             : Ptr64 Char
   +0x008 vendor_id        : Uint2B
   +0x00a product_id       : Uint2B
   +0x00c serial_number    : Ptr64 Wchar
   +0x014 release_number   : Uint2B
   +0x018 manufacturer_string : Ptr64 Wchar
   +0x020 product_string   : Ptr64 Wchar
   +0x028 usage_page       : Uint2B
   +0x02a usage            : Uint2B
   +0x02c interface_number : Int4B
   +0x030 interface_class  : Int4B
   +0x034 interface_subclass : Int4B
   +0x038 interface_protocol : Int4B
   +0x03c next             : Ptr64 SDL_hid_device_info
```

Note that `serial_number` and `next` are both 64-bit pointer types aligned at 4-byte boundaries.

While this HID struct is probably not commonly used yet, this also goes for core structures like `SDL_Surface`:
```
0:000> dt SDL2!SDL_Surface
   +0x000 flags            : Uint4B
   +0x004 format           : Ptr64 SDL_PixelFormat
   +0x00c w                : Int4B
   +0x010 h                : Int4B
   +0x014 pitch            : Int4B
   +0x018 pixels           : Ptr64 Void
   +0x020 userdata         : Ptr64 Void
   +0x028 locked           : Int4B
   +0x02c list_blitmap     : Ptr64 Void     <------- Oops
   +0x034 clip_rect        : SDL_Rect
   +0x044 map              : Ptr64 SDL_BlitMap <------ :(
   +0x04c refcount         : Int4B
```

Code generation is affected by this suboptimal alignment.

Here is `SDL_InvalidateAllBlitMap()` reading and clearing `SDL_Surface->list_blitmap` with current main:
```
00000001`800b898c f842c014 ldur        x20,[x0,#0x2C]
00000001`800b8990 f802c01f stur        xzr,[x0,#0x2C]
```

and after changing default packing to 8 bytes:
```
00000001`800b883c f9401c14 ldr         x20,[x0,#0x38]
00000001`800b8840 f9001c1f str         xzr,[x0,#0x38]
```

I don't know enough about the performance characteristics of those instructions to if `ldur/stur` is worse than `ldr/str`, but there will definitely be a runtime penalty for the unaligned access regardless of the instruction used. 

This alignment problem also poses an issue for [ARM64EC](https://blogs.windows.com/windowsdeveloper/2021/06/28/announcing-arm64ec-building-native-and-interoperable-apps-for-windows-11-on-arm/) applications using SDL, since it will result in crashes or memory corruption when passing SDL structures between ARM64 and x64 code in the same process due to incompatible structure packing. It also causes incompatibilities between code compiled with Clang/GCC and MSVC for ARM64.

I think I'm in favor of just biting the bullet and doing an ARM64 ABI break for 2.0.22 to fix it. ARM64 application support in the ecosystem is still relatively early and it will only get harder to fix as more applications are ported to ARM64.

@slouken thoughts?

**Comment by slouken** [comment] 2022-03-27 16:42
Yes, let's do it for the hidapi structures, scoped to ARM64 only. Can you propose a tested change?

**Comment by cgutman** [comment] 2022-03-27 17:23
I'm not sure why the warning only fired for `SDL_hid_device_info` because the default packing is wrong for _all_ SDL structures. `SDL_Surface` is also affected, and I'm sure a bunch of other structures are too.

IMHO, if we're going to do an ABI break at all (as we would be changing `SDL_hid_device_info`), we might as well go all the way and fix everything at once.

**Comment by slouken** [comment] 2022-03-27 19:07
We can't do an ABI break. If we need to do that, we need to re-think this and move it to SDL 3.

**Comment by cgutman** [comment] 2022-03-27 19:34
It's particularly messy, because doing nothing is also leaving ABI incompatibilities around (sort of like the situation in #3373)

Right now, the ABI is incompatible between Clang/GCC ARM64 builds and MSVC ARM64 builds. It's also incompatible between MSVC ARM64 and GCC/Clang/MSVC x64 (which matters for ARM64EC applications).

So changing to use `#pragma pack(push,8)` on MSVC ARM64 would:
- Fix ABI compatibility between MSVC ARM64 and Clang/GCC ARM64 builds
- Fix ABI compatibility between MSVC ARM64 and x64 builds
- Slightly improve performance by avoiding unaligned access
- Break ABI compatibility between older and newer MSVC ARM64 builds

I think our 2 options are:
- Suppress that C4121 warning (leaving the status quo, but fixing the build warning)
- Adjust that `#ifdef _M_X64` in begin_code.h to `#ifdef _WIN64` (with the effects mentioned above)

Ultimately it's a judgement call of what ABI compatibilities we care about more.

**Comment by slouken** [comment] 2022-03-27 19:58
Well, like I said, if it just affects ARM64, I’m fine with an ABI break here. I think that won’t affect too many people or games.

If it affects any other architecture, then we should wait for SDL 3.

**Comment by slouken** [comment] 2022-03-27 20:00
(I think I’m saying we should go with option 2 for this release, I just don’t want to misunderstand anything here)

**Comment by cgutman** [comment] 2022-03-28 00:10
OK, I made the `_M_X64` -> `_WIN64` change in a60986caa8206e50b1ea5f8cb4821e40e18c572b which will fix alignment on Windows ARM64 platforms.

However, I wasn't able to reproduce the warnings locally (even with `/Wall`) before or after the change. @carlo-bramini can you confirm that those are fixed now?

**Comment by sezero** [comment] 2022-03-28 12:12
Should we make sdl12-compat require SDL2 >= 2.0.22 for WIN64 which isn't x64?
(Real SDL-1.2 doesn't have this change though - maybe we should, maybe not...)

**Comment by slouken** [comment] 2022-03-28 15:35
No, ARM64 didn't exist when SDL 1.2 was the new thing, I think we're fine here.

**Comment by carlo-bramini** [comment] 2022-03-30 08:16
> However, I wasn't able to reproduce the warnings locally (even with `/Wall`) before or after the change. @carlo-bramini can you confirm that those are fixed now?

Using `_WIN64` instead of `_M_X64` has the same behaviour of adding `_M_ARM64`, so it's fine too on my side.
I have discovered this issue when compiling a native ARM64 executable of R.E.L.I.V.E. engine:

https://aliveteam.github.io/

In reality, I have not recompiled SDL2, I just did an hack into `begin_code.h` and I verified that the build process of the application completed successfully. Since I'm using VCPKG for providing SDL2 to CMake, unfortunately I had no other choices, at least until a new version of SDL2 will be released with this fix included and the port into VCPKG will be also updated.

**Comment by carlo-bramini** [comment] 2022-03-30 08:24
> Well, like I said, if it just affects ARM64, I’m fine with an ABI break here. I think that won’t affect too many people or games.
> 
> If it affects any other architecture, then we should wait for SDL 3.

if I can give a suggestion...  I didn't know that there was an SDL3 in progress and I don't know if it has been already done, but perhaps an issue should be opened to remind that it would be worth to re-order the items of the structures of the library, from larger to smaller, in a manner that they will be efficiently addressed on all types of architectures.

**Closed** 2022-05-24 15:26 UTC
