### ISSUE TITLE
Exiting fullscreen on X11 breaks rendering

### ISSUE THREAD

**Issue by spindlebink** [libsdl-org/SDL#6205] opened 2022-09-09 18:23 UTC
I'm on Manjaro with NVIDIA nonfree drivers and X11. `inxi -Fz` shows me:

```
Device-2: NVIDIA TU116 [GeForce GTX 1660 SUPER] driver: nvidia
  v: 515.65.01
Display: x11 server: X.org v: 1.21.1.4 with: Xwayland v: 22.1.3 driver:
  X: loaded: modesetting,nvidia unloaded: nouveau gpu: i915,nvidia
  resolution: 1: 1920x1080~60Hz 2: 1440x900~60Hz 3: 2560x1440~60Hz
OpenGL: renderer: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 v: 4.6.0 NVIDIA
  515.65.01
```

Switching an SDL window to fullscreen and back (either desktop windowless fullscreen or real fullscreen) causes the rendering context to apparently lose connection with the window. The window can be moved or closed as usual, but the renderer stops working in a way that's a little difficult to explain--it looks like when you create a window and don't clear or present it but still move and resize it.

![window](https://user-images.githubusercontent.com/63519521/189417068-5cd1bacf-8c6a-48cb-9ac6-57ba7c148f7e.gif)

This occurs with either a built-in `SDL_Renderer` or with a minimal OpenGL context, although I've only demonstrated the `SDL_Renderer` version below because of the boilerplate length of a GL version. I've also verified that this issue occurs with equivalent code in LÖVE, which uses SDL and OpenGL as well. I have not tested Vulkan.

I wasn't able to find another reported issue with these precise symptoms, although I see there are a couple of other issues regarding multi-monitor setups and fullscreen on Linux.

Minimal reproduction:
```c
#include <SDL2/SDL.h>

void main() {
  SDL_Init(SDL_INIT_VIDEO);
  
  int should_exit = 0;
  int fullscreen = 0;
  
  SDL_Window *window;
  SDL_Renderer *renderer;

  SDL_CreateWindowAndRenderer(800, 600, SDL_WINDOW_OPENGL, &window, &renderer);
  
  while (!should_exit) {
    SDL_Event event;
    while (SDL_PollEvent(&event)) {
      if (event.type == SDL_QUIT) {
        should_exit = 1;
      } else if (event.type == SDL_KEYDOWN) {
        if (event.key.keysym.scancode == SDL_SCANCODE_F) {
          fullscreen = !fullscreen;
          SDL_SetWindowFullscreen(
            window,
            fullscreen ? SDL_WINDOW_FULLSCREEN_DESKTOP : 0
          );
        }
      }
    }
    
    SDL_SetRenderDrawColor(renderer, 0, 0, 0, 0);
    SDL_RenderClear(renderer);
    SDL_RenderPresent(renderer);
  }
  
  SDL_DestroyRenderer(renderer);
  SDL_DestroyWindow(window);
  SDL_Quit();
}
```

**Comment by chickenSandwich** [comment] 2022-09-10 19:36
This has been happening to me for quite some time, and I've been pulling my hair out trying to figure it out.  I can confirm this issue with OpenGL, Vulkan, and SDL_Renderer.  I had to code a work around to do a "fake" full screen on the desktop by removing the border and maximizing the window.

```
             /////////////                 
         /////////////////////            ------------- 
      ///////*767////////////////         OS: Pop!_OS 22.04 LTS x86_64 
    //////7676767676*//////////////       Host: Thelio Major thelio-major-b2 
   /////76767//7676767//////////////      Kernel: 5.19.0-76051900-generic 
  /////767676///*76767///////////////     Uptime: 4 days, 8 hours, 56 mins 
 ///////767676///76767.///7676*///////    Packages: 3203 (dpkg), 36 (flatpak), 9 (snap) 
/////////767676//76767///767676////////   Shell: bash 5.1.16 
//////////76767676767////76767/////////   Resolution: 3840x2160, 3840x2160 
///////////76767676//////7676//////////   DE: GNOME 42.3.1 
////////////,7676,///////767///////////   WM: Mutter 
/////////////*7676///////76////////////   WM Theme: Pop 
///////////////7676////////////////////   Theme: Pop-dark [GTK2/3] 
 ///////////////7676///767////////////    Icons: Pop [GTK2/3] 
  //////////////////////'////////////     Terminal: gnome-terminal 
   //////.7676767676767676767,//////      CPU: Intel i9-10900X (20) @ 4.500GHz 
    /////767676767676767676767/////       GPU: NVIDIA GeForce RTX 3070 Ti 
      ///////////////////////////         Memory: 9637MiB / 31802MiB 
         /////////////////////
             /////////////                                        
```
```
SDL v2.25.0 | Rev: https://github.com/libsdl-org/SDL.git@6dfd7a17e1d9ea94015bb0fda4c570f8b20781bd
```

**Comment by icculus** [comment] 2022-09-11 05:45
Confirmed here on Ubuntu 22.04, gnome on x11. I'll bisect in the morning.

**Comment by icculus** [comment] 2022-09-12 17:17
Everything back to `release-2.0.0` is doing it, too. Did this break in Gnome at some point? It might be a window manager issue and not an SDL issue. Gonna try KDE real fast.

**Comment by icculus** [comment] 2022-09-12 19:00
Latest in git works on Ubuntu 16.10 Gnome in vmware, which doesn't mean much, but I had it laying around. Trying some other things still, but leaning towards this being a Gnome bug.

**Comment by icculus** [comment] 2022-09-12 22:48
Doesn't happen on icewm (which is a very simple X11 window manager). Doesn't have this problem in Xwayland on Ubuntu 22.04, even if I just log out of the same Gnome install and log back in, switching the desktop from X11 to Wayland. This is really starting to feel like a Gnome/x11 window manager bug. Still haven't tried KDE, installing that real fast now.

**Comment by icculus** [comment] 2022-09-13 03:26
Doesn't happen on KDE, Ubuntu 22.04. I'm now pretty confident that this is a Gnome compositor bug.

It does happen on Gnome/x11 in Ubuntu 21.10, too, so it's not a new bug for this release. I'm not going to keep installing old Ubuntu releases until I find where this originally broke, but I'm going to guess it's been doing this since they moved to from Unity to Gnome 3 in 18.04.  (My prior comment about testing "Ubuntu 16.10 Gnome" was actually Unity, not Gnome.)

I would have to debug gnome-shell or Metacity to go further on this, so I think now we should point to the Gnome bug tracker and close this as not an SDL issue.

**Comment by icculus** [comment] 2022-09-13 03:29
I should say also that, out of laziness, my test case was `./testsprite2 --fullscreen-desktop` and pressing alt-enter to go back to windowed mode, and dragging that window around for the same effect as the animated gif posted above, but the test program posted is probably also good...but testsprite2 was available wherever I cloned SDL through a bunch of OS installations.

**Comment by chickenSandwich** [comment] 2022-09-13 05:39
@icculus Thank-you.  I'm just confused about one thing:  If this were not an SDL issue, wouldn't I be able to observe it with other applications?

**Comment by cgutman** [comment] 2022-09-13 06:51
Any chance this has to do with `_NET_WM_BYPASS_COMPOSITOR`?

Does it change if you set `SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR=0`?

**Comment by icculus** [comment] 2022-09-13 11:02
> @icculus Thank-you.  I'm just confused about one thing:  If this were not an SDL issue, wouldn't I be able to observe it with other applications?

What else uses fullscreen that I could test?

**Comment by icculus** [comment] 2022-09-13 11:05
> Does it change if you set SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR=0?

Good call! Setting that to zero mitigates the bug.

**Comment by icculus** [comment] 2022-09-13 11:09
Maybe we should try toggling `_NET_WM_BYPASS_COMPOSITOR` off and back on when changing fullscreen modes, to see if it coerces Gnome to reset some crucial state. I'll mess with it later today.

**Comment by chickenSandwich** [comment] 2022-09-13 12:12
@icculus @cgutman :+1:  Thank-you.  That seems to work.

I used: `xprop _NET_WM_BYPASS_COMPOSITOR` to check my window
My window reported: `_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 1`
I tested: `SDL_WINDOW_FULLSCREEN_DESKTOP` and observed the bug
Then I set the hint: `SDL_SetHintWithPriority(SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR, "0", SDL_HINT_OVERRIDE)`
My window reported: `_NET_WM_BYPASS_COMPOSITOR:  not found.`
Re-tested: `SDL_WINDOW_FULLSCREEN_DESKTOP` and did not observe the bug.
Then I repeated...ad nauseam with success.

I was not aware of that hint because it is not documented on: https://wiki.libsdl.org/CategoryHints

Thanks again!

**Comment by icculus** [comment] 2022-09-13 23:37
So I can turn off _NET_WM_BYPASS_COMPOSITOR after returning from fullscreen, and it seems to fix the issue, but I can't reenable it again once in window mode or it blows up in the same way.

This really needs to go to a Gnome developer now, it really feels like a gnome-shell bug and the trivial workaround I was hoping for didn't fix it.

**Comment by icculus** [comment] 2022-09-15 15:01
Wait, I spoke too soon, if I start it in fullscreen, this program reproduces the bug.

**Comment by chickenSandwich** [comment] 2022-09-15 15:05
@icculus I'm so glad that you are going to file a bug in gnome!  Could you provide a link to the bug when it gets submitted please.  Thanks!

**Comment by icculus** [comment] 2022-09-15 15:14
Updated test case that reproduces. It seems reliable if you wait a second or two after going fullscreen before pressing a key.

Gonna write up a bug report for Gnome later today, then close this bug.

```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/Xatom.h>

#define WINX 100
#define WINY 100
#define WINW 640
#define WINH 480

#define _NET_WM_STATE_REMOVE    0l
#define _NET_WM_STATE_ADD       1l

static Bool isAnyEvent(Display *display, XEvent *ev, XPointer arg) { return True; }
static Bool isMapNotify(Display *display, XEvent *ev, XPointer arg) { return (ev->type == MapNotify) ? True : False; }

static void set_fullscreen(Display *display, const int screen, Window w, const int fs)
{
    Atom _NET_WM_STATE = XInternAtom(display, "_NET_WM_STATE", False);
    Atom _NET_WM_STATE_FULLSCREEN = XInternAtom(display, "_NET_WM_STATE_FULLSCREEN", False);
    XEvent xevent;

    XSizeHints *sizehints = XAllocSizeHints();
    long flags = 0;
    XGetWMNormalHints(display, w, sizehints, &flags);

    if (fs) {
        /* we are going fullscreen so turn the flags off */
        sizehints->flags &= ~(PMinSize | PMaxSize);
    } else {
        /* Reset the min/max width height to make the window non-resizable again */
        sizehints->flags |= PMinSize | PMaxSize;
        sizehints->min_width = sizehints->max_width = WINW;
        sizehints->min_height = sizehints->max_height = WINH;
    }
    XSetWMNormalHints(display, w, sizehints);
    XFree(sizehints);

    memset(&xevent, 0, sizeof (xevent));
    xevent.xany.type = ClientMessage;
    xevent.xclient.message_type = _NET_WM_STATE;
    xevent.xclient.format = 32;
    xevent.xclient.window = w;
    xevent.xclient.data.l[0] = fs ? _NET_WM_STATE_ADD : _NET_WM_STATE_REMOVE;
    xevent.xclient.data.l[1] = _NET_WM_STATE_FULLSCREEN;
    xevent.xclient.data.l[3] = 0l;
    XSendEvent(display, RootWindow(display, screen), 0, SubstructureNotifyMask | SubstructureRedirectMask, &xevent);
    XFlush(display);
}

int main(int argc, char **argv)
{
    XInitThreads();
    Display *display = XOpenDisplay(NULL);
    const int screen = DefaultScreen(display);
    XSetWindowAttributes xattr;
    XSizeHints *sizehints;
    XWMHints *wmhints;
    XClassHint *classhints;
    Window w;

    memset(&xattr, '\0', sizeof (xattr));
    xattr.event_mask = ExposureMask |
                       ButtonPressMask | ButtonReleaseMask | KeyPressMask | KeyReleaseMask |
                       StructureNotifyMask | FocusChangeMask | PointerMotionMask;

    w = XCreateWindow(display, RootWindow(display, screen),
                       WINX, WINY, WINW, WINH,
                       0, CopyFromParent, InputOutput, CopyFromParent,
                       CWEventMask, &xattr );

    sizehints = XAllocSizeHints();
    sizehints->flags = 0;
    sizehints->min_width = sizehints->max_width = WINW;
    sizehints->min_height = sizehints->max_height = WINH;
    sizehints->flags |= (PMaxSize | PMinSize);

    sizehints->x = WINX;
    sizehints->y = WINY;
    sizehints->flags |= USPosition;

    /* Setup the input hints so we get keyboard input */
    wmhints = XAllocWMHints();
    wmhints->input = True;
    wmhints->window_group = (XID) getpid();
    wmhints->flags = InputHint | WindowGroupHint;

    /* Setup the class hints so we can get an icon (AfterStep) */
    classhints = XAllocClassHint();
    classhints->res_name = "SDL_App";
    classhints->res_class = "SDL_App";

    /* Set the size, input and class hints, and define WM_CLIENT_MACHINE and WM_LOCALE_NAME */
    XSetWMProperties(display, w, NULL, NULL, NULL, 0, sizehints, wmhints, classhints);

    XFree(sizehints);
    XFree(wmhints);
    XFree(classhints);

    long pid = (long) getpid();
    Atom _NET_WM_PID = XInternAtom(display, "_NET_WM_PID", False);
    XChangeProperty(display, w, _NET_WM_PID, XA_CARDINAL, 32, PropModeReplace, (unsigned char *) &pid, 1);

    Atom _NET_WM_WINDOW_TYPE = XInternAtom(display, "_NET_WM_WINDOW_TYPE", False);
    Atom _NET_WM_WINDOW_TYPE_NORMAL = XInternAtom(display, "_NET_WM_WINDOW_TYPE_NORMAL", False);
    XChangeProperty(display, w, _NET_WM_WINDOW_TYPE, XA_ATOM, 32, PropModeReplace, (unsigned char *)&_NET_WM_WINDOW_TYPE_NORMAL, 1);

    long compositor = 1;
    Atom _NET_WM_BYPASS_COMPOSITOR = XInternAtom(display, "_NET_WM_BYPASS_COMPOSITOR", False);
    XChangeProperty(display, w, _NET_WM_BYPASS_COMPOSITOR, XA_CARDINAL, 32, PropModeReplace, (unsigned char *)&compositor, 1);

    XMapRaised(display, w);

    XFlush(display);

    /* make sure we're mapped and then go fullscreen. */
    XEvent xevent;
    XCheckIfEvent(display, &xevent, isMapNotify, NULL);
    set_fullscreen(display, screen, w, 1);

    XGCValues ctx_vals;
    const unsigned long gcflags = GCForeground | GCBackground;
    memset(&ctx_vals, 0, sizeof (ctx_vals));
    GC gc = XCreateGC(display, w, gcflags, &ctx_vals);

    int presses = 0;
    while (presses < 6) {
        while (XCheckIfEvent(display, &xevent, isAnyEvent, NULL)) {
            switch (xevent.type) {
                case KeyPress:
                    printf("KEYPRESS\n");
                    presses++;
                    set_fullscreen(display, screen, w, (presses & 1) == 0);
                    break;
            }
        }

        XFillRectangle(display, w, gc, 0, 0, 999999, 999999);
        XFlush(display);
        usleep(10000);
    }

    XFreeGC(display, gc);
    XDestroyWindow(display, w);
    XCloseDisplay(display);

    return 0;
}
```

**Closed** 2022-09-15 18:44 UTC

**Comment by chickenSandwich** [comment] 2022-09-15 18:46
@icculus You are amazing!

**Comment by icculus** [comment] 2022-11-16 04:36
Quick followup: this was fixed in Gnome's revision control a few weeks ago, so expect distros to eventually ship this fix.

https://gitlab.gnome.org/GNOME/mutter/-/commit/46fc94b67f3c1255f5c6be1a33ff8f80d90a0958
