### ISSUE TITLE
Bug: cursor changes internal position during relative mode

### ISSUE THREAD

**Issue by expikr** [libsdl-org/SDL#7250] opened 2023-02-05 21:18 UTC
https://user-images.githubusercontent.com/77922942/216846146-bbfb44b4-a051-4b6f-8e72-7567a045dcbe.mp4

### Code used for testing

```lua
function makeUser32()
    local ffi = require("ffi")
    ffi.cdef[[
        typedef struct { long x, y; } POINT;
        bool GetCursorPos(POINT *lpPoint);
    ]]
    return ffi.C
end

function love.load()
    local ffi = require("ffi")
    USER32 = makeUser32()
    CURPOS=ffi.new("POINT")
    love.graphics.setLineStyle( 'rough' )
    love.cacheX = 0
    love.cacheY = 0
end

function love.draw()
    USER32.GetCursorPos(CURPOS)
    local x, y, displayindex = love.window.getPosition( )
    local w, h = love.graphics.getDimensions( )
    local mx, my = love.mouse.getPosition( )
    love.graphics.setColor(0,0,1,1)
    love.graphics.line(1,1+my,w,1+my)
    love.graphics.line(1+mx,1,1+mx,h)
    love.graphics.setColor(1,0,0,1)
    love.graphics.line(1,1+love.cacheY,w,1+love.cacheY)
    love.graphics.line(1+love.cacheX,1,1+love.cacheX,h)
    love.graphics.setColor(0,1,0,1)
    love.graphics.print(CURPOS.x .. ',' .. CURPOS.y)
    love.graphics.line(0,1+CURPOS.y-y,w,1+CURPOS.y-y)
    love.graphics.line(1+CURPOS.x-x,0,1+CURPOS.x-x,h)
end

function love.mousemoved( x, y, dx, dy, istouch )
    if love.mouse.getRelativeMode() then return end
    love.cacheX = x
    love.cacheY = y
end

function love.mousepressed( x, y, button, istouch, presses )
    if button==3 then
       love.mouse.setRelativeMode(true)
    end
end

function love.mousereleased( x, y, button, istouch, presses )
    if button==3 then
       love.mouse.setRelativeMode(false)
    end
end

```

### Tested on
Love2D 11.4 with SDL.dll replaced with the 2.26.2 release, on Win10

### Expected Behavior
1. Upon exiting relative mode, the visible cursor should snap to the red xhair (last cursor position upon entering relative mode)
2. Blue xhair should be stationary (and therefore stays underneath red xhair) when relative mode is active and mouse is moved

### Actual Behavior
1. Upon exiting relative mode, the visible cursor incorrectly snaps to the blue xhair instead of correctly snapping to the red xhair
2. Blue xhair is not stationary (and therefore not occluded by the red xhair) when relative mode is active and mouse is moved

### Proposed Solution
1. Upon activating relative mode, the cursor coordinate at activation should be saved 
2. While relative mode is active, the internal cursor coordinate should not be updated. 
3. Upon exiting relative mode, the cursor should be warped to the saved coordinate-at-activation

**Comment by slime73** [comment] 2023-02-05 21:22
I think relative mouse mode is not meant to guarantee anything about the cursor's reported or actual position while in relative mode, for what it's worth. It just guarantees that relative movement events will be generated and the cursor won't click outside of the window.

**Comment by slime73** [comment] 2023-02-05 21:24
My comment was mostly about list item 2 in the expected behaviour / actual behaviour / proposed solution lists. I don't know enough to say much about the rest. :)

**Comment by Susko3** [comment] 2023-07-10 15:42
> Yes, but the problem isn't about its position during relative mode, but rather the warp behavior _after_ exiting relative mode. It should restore to the position at time of entering relative mode.

If this is the premise of this issue, then it's a duplicate of #7840 and should be closed as such.

**Closed** 2024-06-16 13:21 UTC
