### ISSUE TITLE
2.0.22rc1 regression in Tomb Raider (2013): black screen/unresponsive when loading game, "Error sending request: Resource temporarily unavailable"

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL#5529] opened 2022-04-13 11:00 UTC
Debian 10, GNOME/Wayland, AMD GPU, Mesa 18.3.6 (I've been testing SDL 2.0.22rc1 on the oldest still-supported Wayland-by-default environment I could find, hence the old versions).

To reproduce:

* Have a saved game (in case it matters, mine is in the first level shortly after being able to walk around for the first time, while doing puzzles with a burning torch and waterfalls)
* Use the *Steam Linux Runtime* compatibility tool, which runs in a Debian-10-based container with an up-to-date version of SDL
* Launch the game with `SDL_VIDEODRIVER=wayland`
* Continue from the saved game

Expected result:

* Main menu disappears
* Mostly-black loading screen with gameplay tips
* Game loads

Actual result:

* Main menu disappears, leaving a black screen
* The loading screen is not rendered
* The game becomes unresponsive
* `Error sending request: Resource temporarily unavailable` is logged to the game's stderr

This appears to be genuinely a regression in 2.0.22rc1: doing the same with the 2.0.20 from  Steam Linux Runtime "soldier" version 0.20220329.49, forcing Wayland via `SDL_VIDEODRIVER=wayland`, works fine.

2.0.22rc1 with `SDL_VIDEODRIVER=x11` also works fine, so this is specific to using Wayland *and* 2.0.22rc1.

**Comment by flibitijibibo** [comment] 2022-04-13 14:34
This sounds like #4769, where it hangs without presenting and causes a timeout. There's an issue filed for libwayland to try and buffer some things to prevent this from happening.

**Comment by sulix** [comment] 2022-04-14 08:58
I can't reproduce this exactly, also under nVidia (GTX 1060, 510.60.02)/Wayland, with openSUSE Tumbleweed (20220412) and KDE/KWin (5.24.4). My savegame's also later in the game (just before the end), but I doubt that matters.

But, note that:
- 32-bit nVidia/Wayland is broken _completely_ on openSUSE, as the [32-bit libnvidia-egl-wayland library was unpackaged](https://build.opensuse.org/request/show/970059). Once an appropriate library was installed, the game mostly worked in windowed mode, but:
- This is affected by https://github.com/NVIDIA/egl-wayland/issues/52 — which prevented the game from starting in fullscreen for me, and there were some issues with the loading screen getting 'stuck' (which either Alt+Tab a few times or just waiting long enough seemed to fix), though ``Error sending request: Resource temporarily unavailable`` never appeared.

That being said, with https://github.com/NVIDIA/egl-wayland/pull/53 Tomb Raider 2013 is working perfectly under wayland with SDL's current git HEAD (55a4e1d336db).

(Also, note that the game's launcher window uses X11 regardless of SDL_VIDEODRIVER.)

My suspicion is that this is likely an nVidia/Wayland issue, though what change in SDL triggered it, I'm not sure.

**Comment by flibitijibibo** [comment] 2022-04-17 20:03
In addition to the above it may also be related to #5536, where libdecor seems to compound the event queue problem in such a way that it breaks harder on GNOME than it does elsewhere. Not sure if libdecor's status changed recently in the runtime, that might be what caused this? 2.0.22's changes have mostly been fixes for different window types and scales, with the event system not changing all that much (if at all; I know output events got changed but that's more a startup thing).

**Comment by smcv** [comment] 2022-04-18 13:32
Sorry, yes, this might be a SDL2-with-libdecor regression rather than genuinely a 2.0.22 regression. The production runtime has SDL 2.0.20 compiled *without* libdecor support, and my test runtime had several changes compared with the production runtime: libdecor added, libwayland upgraded from 1.16 to 1.18 (as a dependency for libdecor and the new SDL), and SDL upgraded to 2.0.22rc1 and compiled *with* libdecor.

Your theory sounds plausible, and at some point I'll try some other combinations to confirm whether the regression was in the SDL code, or in the enabled/disabled status of its libdecor code path. I didn't get as far as trying this particular game on NVIDIA.

**Comment by sulix** [comment] 2022-04-18 14:03
FWIW, I was able to reproduce the black screen on loading _once_, with libdecor CSD force-enabled, in a window. It worked when I re-ran it, though, and it hasn't happened since, so I wasn't able to debug it much further.

**Comment by slouken** [comment] 2022-04-18 16:26
Wayland is no longer the default as of https://github.com/libsdl-org/SDL/commit/254fcc90eb22bb159ab365ad956222a9c5632841. I'm going to close this for 2.0.22, but I'll label it "wayland regression" so we can re-examine this later as needed.

**Closed by slouken** 2022-04-18 16:26 UTC

**Comment by smcv** [comment] 2022-04-19 17:17
For what it's worth, moving from 2.0.22rc1 to 02225aa73 seems to have avoided this failure mode in some (admittedly rather brief) testing, even with Wayland forced via `SDL_VIDEODRIVER=wayland` (and I can tell it's working, because I get a black libdecor window decoration, rather than the light grey GNOME Shell window decoration I see on X11 apps).
