### ISSUE TITLE
On Wayland, SDL2 seems to default to xwayland

### ISSUE THREAD

**Issue by DanielGibson** [libsdl-org/SDL#4988] opened 2021-11-21 18:19 UTC
According to https://github.com/dhewm/dhewm3/issues/425 SDL2 (@Yamagi confirms that it also happens with latest SDL git), SDL2 defaults to using X11 via xwayland instead of native wayland - `SDL_GetCurrentVideoDriver()` returns "x11" instead of "wayland".

@obedlink, the original dhewm3 bug reporter, uses "KDE-Neon, Radeon driver, Mesa 21.3", @Yamagi uses Gnome 41.1 (also with a current Radeon Mesa driver).

I think SDL2 should default to native wayland if available - it probably will give better performance and apparently when it goes via xwayland 8x MSAA isn't supported (while it works when enforcing the wayland backend with `SDL_VIDEODRIVER=wayland`).

Tagging @flibitijibibo as he has done lots of SDL wayland work recently and @icculus because if you agree that it should default to native wayland on wayland, it would probably nice to fix this before 2.0.18

**Comment by flibitijibibo** [comment] 2021-11-21 18:45
Duplicate of #2710, see #4306. Just need surface suspension first!

**Comment by DanielGibson** [comment] 2021-11-21 18:55
Damn, sorry I didn't find the existing bug (and look at the existing PRs) first!
(I thought I searched for issues at least a few days ago, but maybe I included "videodriver" in the search)

**Closed** 2022-01-26 17:32 UTC

**Comment by Mailaender** [comment] 2023-06-11 18:37
On SDL 2.0.22 I still require `SDL_VIDEODRIVER=wayland` otherwise I get an X11 window.

**Comment by slouken** [comment] 2023-06-11 19:54
Yes, that's correct. X11 is the default in SDL 2.
