### ISSUE TITLE
USB controller is connected but has no inputs

### ISSUE THREAD

**Issue by genericptr** [libsdl-org/SDL#6686] opened 2022-11-28 13:14 UTC
Following my discussion at https://discourse.libsdl.org/t/sdl-joysticknumbuttons-always-returns-0/40357/10 I have wired NES USB controller which upon receiving a `SDL_JOYDEVICEADDED` event is returning:

```YAML
SDL_JoystickName: USB Gamepad
SDL_JoystickGetAttached: TRUE
SDL_JoystickNumButtons: 0
SDL_JoystickNumHats: 0
SDL_JoystickNumAxes: 0
SDL_IsGameController: FALSE
```

I'm running macOS 13 on an M1 Pro and SDL 2.24.1. The  controller works using emulators and `gamepad-tool` shows it correct and gets button presses.

![](https://discourse.libsdl.org/uploads/default/original/2X/6/6c1bd7fa554d6db4c5550f1ba8f05e4c170ea60b.jpeg)

**Comment by slouken** [comment] 2022-11-28 16:35
Are you able to debug SDL and see what's going on? If not, are you willing to send me your controller so I can debug it? :)

**Comment by kjliew** [comment] 2022-11-28 17:13
I have the same problem with 8BitDo Bluetooth game controllers in D-Input mode since macOS Ventura update. I just found out that Mac mode is also broken. Only X-Input mode and Switch mode are working on macOS Ventura.

Online gamepad testers are able to detect proper functions of both Mac mode and D-Input mode. Perhaps SDL2 is indeed broken. D-Input mode works fine for Linux and both D-Input and X-Input modes work fine for Windows. Both D-Input and Mac modes used to work on macOS Monterey.

The exact models are M30 and SN30 Pro. The OP wired NES USB controller is likely to be in D-Input mode.

**Comment by slouken** [comment] 2022-11-28 17:16
I can test the 8BitDo controllers here. Thanks for the additional info!

**Comment by slouken** [comment] 2022-11-28 19:09
I wasn't able to reproduce this with an 8BitDo Pro 2. I'll see if I can get the M30 and SN30 Pro to try them out.

**Comment by slouken** [comment] 2022-11-28 20:50
Yes, I tried DirectInput mode.

**Comment by funbuffet** [comment] 2022-11-28 21:51
I'm experiencing the same issue with both an 8BitDo Pro 2 and a PS4 Controller connected to my M1 Mac. The gamepad pointer is constructed fine and throws no errors. SDL will log the specific controller connected when queried ("PS4 Controller"). But no gamepad inputs are registered, either in the event loop or by querying the gamepad state manually.

**Comment by slouken** [comment] 2022-11-28 23:07
Hmm, I just connected the 8BitDo over Bluetooth in DInput mode and didn't have any issues. Are there input monitoring permissions problems or something?

**Comment by slouken** [comment] 2022-11-28 23:14
And I just tried a Bluetooth PS4 controller and it worked fine... ?

**Comment by genericptr** [comment] 2022-11-29 00:34
> Are you able to debug SDL and see what's going on? If not, are you willing to send me your controller so I can debug it? :)

Debug in the SDL Xcode project? I have some experience using IOKit on Mac so maybe I could help. What's the best way to get started?

Yeah I would but I'm in Thailand until next July. Here's where I bought them: https://www.amazon.com/Controller-suily-Joystick-RetroPie-Emulators/dp/B07M7SYX11/ref=sr_1_1?crid=NGH1AOGF4CW9&keywords=suily+usb+nes+controller&qid=1669681823&sprefix=sui+usb+nes+controller%2Caps%2C390&sr=8-1 $13/USD for a pair if you're in the US.

A similar wired SNES controller failed also but strangely the _wireless_ SNES controllers work.

**Comment by slouken** [comment] 2022-11-29 00:36
Given a bunch of people are having trouble with controllers that are working for me, I think it makes sense for you guys to see if you can debug it on your end.

**Comment by genericptr** [comment] 2022-11-29 00:45
> Given a bunch of people are having trouble with controllers that are working for me, I think it makes sense for you guys to see if you can debug it on your end.

are you testing wired controllers because my wireless ones worked. Also macOS 13 is probably the other important part if you haven't upgraded yet.

**Comment by genericptr** [comment] 2022-11-29 01:11
@slouken What's the best way to debug SDL? Can I make a debug build framework so I can at least set breakpoints? I use SDL with Pascal and VSCode/LLDB as my debugger but maybe there's a test app or something I could use from within Xcode?

**Comment by slouken** [comment] 2022-11-29 01:52
> are you testing wired controllers because my wireless ones worked. Also macOS 13 is probably the other important part if you haven't upgraded yet.

Yep, I just upgraded to macOS Ventura, and have tried those controllers wired and wireless.

**Comment by kjliew** [comment] 2022-11-29 04:50
@slouken Just a dumb question, is your Mac also an M1 and not Intel? I am sorry that I don't have an Intel Mac to check and I can't go back to macOS Monterey.

D-Input mode - `testjoystick.c`
Same problem as OP.
```
2022-11-28 20:21:59.272 joytest[58640:806780] INFO: Joystick device 0 added.
2022-11-28 20:21:59.272 joytest[58640:806780] INFO: Joystick
2022-11-28 20:21:59.272 joytest[58640:806780] INFO:           name: 8BitDo M30 gamepad
2022-11-28 20:21:59.272 joytest[58640:806780] INFO:           type: Game Controller
2022-11-28 20:21:59.272 joytest[58640:806780] INFO:            LED: no
2022-11-28 20:21:59.272 joytest[58640:806780] INFO:         rumble: no
2022-11-28 20:21:59.272 joytest[58640:806780] INFO: trigger rumble: no
2022-11-28 20:21:59.272 joytest[58640:806780] INFO:           axes: 0
2022-11-28 20:21:59.272 joytest[58640:806780] INFO:          balls: 0
2022-11-28 20:21:59.272 joytest[58640:806780] INFO:           hats: 0
2022-11-28 20:21:59.272 joytest[58640:806780] INFO:        buttons: 0
2022-11-28 20:21:59.272 joytest[58640:806780] INFO:    instance id: 0
2022-11-28 20:21:59.272 joytest[58640:806780] INFO:           guid: <removed>
2022-11-28 20:21:59.273 joytest[58640:806780] INFO:        VID/PID: 0x0000/0x0000
```
Mac mode - `testjoystick.c`
Joystick found, but no input events coming in.
```
2022-11-28 20:34:50.431 joytest[58742:810649] INFO: Joystick device 0 added.
2022-11-28 20:34:50.431 joytest[58742:810649] INFO: Joystick
2022-11-28 20:34:50.431 joytest[58742:810649] INFO:           name: PS4 Controller
2022-11-28 20:34:50.431 joytest[58742:810649] INFO:           type: Game Controller
2022-11-28 20:34:50.431 joytest[58742:810649] INFO:            LED: no
2022-11-28 20:34:50.431 joytest[58742:810649] INFO:         rumble: no
2022-11-28 20:34:50.431 joytest[58742:810649] INFO: trigger rumble: no
2022-11-28 20:34:50.431 joytest[58742:810649] INFO:           axes: 6
2022-11-28 20:34:50.431 joytest[58742:810649] INFO:          balls: 0
2022-11-28 20:34:50.431 joytest[58742:810649] INFO:           hats: 0
2022-11-28 20:34:50.431 joytest[58742:810649] INFO:        buttons: 16
2022-11-28 20:34:50.431 joytest[58742:810649] INFO:    instance id: 0
2022-11-28 20:34:50.431 joytest[58742:810649] INFO:           guid: <removed>
2022-11-28 20:34:50.431 joytest[58742:810649] INFO:        VID/PID: 0x054c/0x05c4
```
`testgamecontroller.c` failed with 0 attached gamecontroller(s) in D-Input mode. In Mac mode, it found the same `PS4 Controller` but no input events ever showed up.

**Comment by slouken** [comment] 2022-11-29 05:14
Yes, I'm testing on an M1 mac. Can you provide the GUID? There is no system identifiable information in there, but it will tell us what SDL driver is being used.

**Comment by kjliew** [comment] 2022-11-29 05:24
D-input mode `guid: 05009b4238426974446f204d00002000`
Mac mode `guid: 03008fe54c050000c405000000016800`

**Comment by kjliew** [comment] 2022-11-29 05:40
The 2 following modes all from the same 8BitDo M30 work fine on macOS Ventura.

Switch mode
```
2022-11-28 21:35:11.955 joytest[59241:830291] INFO: Joystick device 0 added.
2022-11-28 21:35:12.138 joytest[59241:830291] INFO: Joystick
2022-11-28 21:35:12.138 joytest[59241:830291] INFO:           name: Nintendo Switch Pro Controller
2022-11-28 21:35:12.138 joytest[59241:830291] INFO:           type: Game Controller
2022-11-28 21:35:12.138 joytest[59241:830291] INFO:            LED: no
2022-11-28 21:35:12.138 joytest[59241:830291] INFO:         rumble: yes
2022-11-28 21:35:12.138 joytest[59241:830291] INFO: trigger rumble: no
2022-11-28 21:35:12.138 joytest[59241:830291] INFO:           axes: 6
2022-11-28 21:35:12.138 joytest[59241:830291] INFO:          balls: 0
2022-11-28 21:35:12.138 joytest[59241:830291] INFO:           hats: 0
2022-11-28 21:35:12.138 joytest[59241:830291] INFO:        buttons: 20
2022-11-28 21:35:12.138 joytest[59241:830291] INFO:    instance id: 0
2022-11-28 21:35:12.138 joytest[59241:830291] INFO:           guid: 030056fb7e0500000920000001006803
2022-11-28 21:35:12.138 joytest[59241:830291] INFO:        VID/PID: 0x057e/0x2009
```
X-Input mode
```
2022-11-28 21:36:55.908 joytest[59273:831315] INFO: Joystick device 0 added.
2022-11-28 21:36:55.908 joytest[59273:831315] INFO: Joystick
2022-11-28 21:36:55.908 joytest[59273:831315] INFO:           name: Xbox One S Controller
2022-11-28 21:36:55.908 joytest[59273:831315] INFO:           type: Game Controller
2022-11-28 21:36:55.908 joytest[59273:831315] INFO:            LED: no
2022-11-28 21:36:55.908 joytest[59273:831315] INFO:         rumble: yes
2022-11-28 21:36:55.908 joytest[59273:831315] INFO: trigger rumble: yes
2022-11-28 21:36:55.908 joytest[59273:831315] INFO:           axes: 6
2022-11-28 21:36:55.908 joytest[59273:831315] INFO:          balls: 0
2022-11-28 21:36:55.908 joytest[59273:831315] INFO:           hats: 0
2022-11-28 21:36:55.908 joytest[59273:831315] INFO:        buttons: 15
2022-11-28 21:36:55.908 joytest[59273:831315] INFO:    instance id: 0
2022-11-28 21:36:55.908 joytest[59273:831315] INFO:           guid: 030082795e040000e002000003096800
2022-11-28 21:36:55.908 joytest[59273:831315] INFO:        VID/PID: 0x045e/0x02e0
```

**Comment by genericptr** [comment] 2022-11-30 02:11
> > @slouken What's the best way to debug SDL? Can I make a debug build framework so I can at least set breakpoints? I use SDL with Pascal and VSCode/LLDB as my debugger but maybe there's a test app or something I could use from within Xcode?
> 
> Try opening Xcode/SDLTest/SDLTest.xcodeproj and running the testgamecontroller target?

Ok I built the SDL 3 framework from the main project and it built to` ~/Library/Developer/Xcode/DerivedData/SDL-goctvbcoxkiommfamjlgzlztoqef/Build/Products/Debug`. Now when I run the SDLTest project it says it can't find the SDL3 framework. I suspect it built to the wrong location. Any ideas?

**Comment by slouken** [comment] 2023-03-07 00:28
I believe this is fixed by https://github.com/libsdl-org/SDL/commit/5925cd4ef377a2211fd057ef6fa9f41141999cb7, can you confirm?

**Comment by genericptr** [comment] 2023-03-08 14:10
I've never used SDL 3 but I built the framework (I'm on macOS) and now I'm getting some linker errors. Are these functions removed or did I need to configure something differently so these functions are included. I built from the Xcode project included in the package.

```
Undefined symbols for architecture arm64:
  "_SDL_GetWindowDisplayIndex", referenced from:
      _GLCANVAS_$$_GETDISPLAYSIZE$$TGVEC2$1$CRC713F463B_CRC217401AD in GLCanvas.o
  "_SDL_IsGameController", referenced from:
      _GLCANVAS_$$_POLLSYSTEMINPUT$PSDL_EVENT in GLCanvas.o
  "_SDL_JoystickClose", referenced from:
      _GLCANVAS_$$_POLLSYSTEMINPUT$PSDL_EVENT in GLCanvas.o
  "_SDL_JoystickGetAttached", referenced from:
      _GLCANVAS$_$TGAMECONTROLLER_$__$$_ISCONNECTED$$BOOLEAN in GLCanvas.o
      _GLCANVAS_$$_POLLSYSTEMINPUT$PSDL_EVENT in GLCanvas.o
  "_SDL_JoystickGetGUID", referenced from:
      _GLCANVAS$_$TGAMECONTROLLER_$__$$_GUIDSTRING$$SHORTSTRING in GLCanvas.o
      _GLCANVAS_$$_POLLSYSTEMINPUT$PSDL_EVENT in GLCanvas.o
  "_SDL_JoystickGetGUIDString", referenced from:
      _GLCANVAS$_$TGAMECONTROLLER_$__$$_GUIDSTRING$$SHORTSTRING in GLCanvas.o
  "_SDL_JoystickInstanceID", referenced from:
      _GLCANVAS_$$_POLLSYSTEMINPUT$PSDL_EVENT in GLCanvas.o
  "_SDL_JoystickName", referenced from:
      _GLCANVAS$_$TGAMECONTROLLER_$__$$_NAME$$SHORTSTRING in GLCanvas.o
      _GLCANVAS_$$_POLLSYSTEMINPUT$PSDL_EVENT in GLCanvas.o
  "_SDL_JoystickNumAxes", referenced from:
      _GLCANVAS_$$_POLLSYSTEMINPUT$PSDL_EVENT in GLCanvas.o
  "_SDL_JoystickNumButtons", referenced from:
      _GLCANVAS_$$_POLLSYSTEMINPUT$PSDL_EVENT in GLCanvas.o
  "_SDL_JoystickNumHats", referenced from:
      _GLCANVAS_$$_POLLSYSTEMINPUT$PSDL_EVENT in GLCanvas.o
  "_SDL_JoystickOpen", referenced from:
      _GLCANVAS_$$_POLLSYSTEMINPUT$PSDL_EVENT in GLCanvas.o
```

**Comment by slime73** [comment] 2023-03-08 14:41
Yes, those functions are renamed/removed - see https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md

The commit was backported to SDL2 as well though: https://github.com/libsdl-org/SDL/commit/2c6995778e941524a4857b55d4e35745313c924a

**Comment by kjliew** [comment] 2023-03-08 17:36
> The commit was backported to SDL2 as well though: [2c69957](https://github.com/libsdl-org/SDL/commit/2c6995778e941524a4857b55d4e35745313c924a)

Somehow, it was missed out in the just release SDL2 2.26.4.

**Comment by kjliew** [comment] 2023-03-08 21:29
Cherry-picked https://github.com/libsdl-org/SDL/commit/1723e93a0cce6f6248844391bff1e7cb42cf3ea0 into 2.26.4. 8BitDo M30 D-Input and Mac mode (PS4 Controller) now work fine on macOS Venture 13.2.1. But D-Input mode seemed to enumerate twice, as Gamecontroller and Joystick. Mac mode has no such issue.
```
gamepad: #0 PS4 Controller                                
gamepad: #0 Removed                                
gamepad: #0 8BitDo M30 Gamepad                                
gamepad: #1 8BitDo M30 gamepad [ 0 buttons 0 axes 0 hats ]
```

**Comment by slouken** [comment] 2023-03-10 00:16
I fixed the duplicate controller issue as well, so I think we can close this. Thanks!

**Comment by genericptr** [comment] 2023-03-10 01:38
Sorry I used SDL from Pascal so I'm gonna have to update my headers and that will take some time. I'll test this later though and reopen if it's not fixed.

**Comment by kjliew** [comment] 2023-03-11 17:59
> I fixed the duplicate controller issue as well, so I think we can close this. Thanks!

With this change cherry-picked into 2.26.4, D-Input mode only showed up as Joystick and no input events ever come in. 
```
gamepad: #0 8BitDo M30 gamepad [ 0 buttons 0 axes 0 hats ]
gamepad: #0 Removed                                
gamepad: #0 8BitDo M30 gamepad [ 0 buttons 0 axes 0 hats ]
gamepad: #0 Removed
```
Whereas before that, while it showed up twice as GameController and Joystick, it actually worked as GameController and input events came in as well since the other Joystick instance registered 0 buttons 0 axes and 0 hats. Is this the expected behavior?

**Comment by slouken** [comment] 2023-03-11 21:05
What exactly did you cherry pick? The fix was to wait a bit to make sure GCController picked up the new controller and then use that, which should solve the problem you're seeing. If that isn't fixing it for you, can you see what's happening on your system?

**Comment by kjliew** [comment] 2023-03-11 22:07
I cherry-picked https://github.com/libsdl-org/SDL/commit/45167b9d13738c6a9025237284b9857c5946152d. Well, "solve the problem" if you meant duplicated device, but it didn't make D-Input mode work. Is D-Input mode supposed to work on macOS?

**Comment by slouken** [comment] 2023-03-11 22:58
No, but GCController is supposed to pick it up. If you change MAX_ATTEMPTS in that patch, can you see how high you have to make it before it returns SDL_TRUE?

**Comment by kjliew** [comment] 2023-03-12 00:16
Well, I don't think https://github.com/libsdl-org/SDL/commit/45167b9d13738c6a9025237284b9857c5946152d actually fixed anything. The M30 itself is quite flaky in D-Input mode. The other SN30 Pro works fine in D-Input mode without this commit. IIRC, the M30 D-Input mode wasn't recognized as GameController in Windows 11 or Linux and may require gamecontrollerdb.txt overrides. Perhaps my last M30 firmware update could have broken D-Input mode as well. I will just avoid D-Input.

**Comment by Balderick** [comment] 2023-03-22 00:28
Using 8BitDo Pro 2 with latest firmware v3.00 in D input and A macos modes are completely broken in steam sdl.    Using ds4windows to emulate ds4 controller is how i got a working controller in steam which also fixed BT to give same behaviour after steam detected ds4 controller.  in both ds4windows and steam.

but the vigem driver used together with the BT emulated device seem to have broken BT on my pc.   Even after uninstalling vigem driver 8BitDo controller will never connect to BT now, regradless of which mode used.

Steam seems to be using wrong steamxbox.sys driver for expected hid device, which is likely contributiong to steamui loading configs for wrong controller type so steamui is broken and game configs are broken because of bad controller layout being applied by steam sdl.    nintendo buttons seem to applied too sometimes when they are not set in controller settings.  Using define layout or nbpms set input device layout ui never get applied after fixing the bad hardcoded config for controller layout.

Switching bt off on pc is needed to disconnect controller but makes steam client lock up and has to be killed by task manager as it never recovers

![Screenshot 2023-03-10 061125](https://user-images.githubusercontent.com/6255884/226771257-12054c1c-0eac-4325-b9d6-2f8a8451b657.png)

Using ds4windows to emulate ds4 controller also gets analog triggers working in D and A modes in steam games - even when steam tries to map button as trigerr in controller layout (not game config or steamui config) if steamui config and game config are set to use config for ps4 type controller - which is great reminder of how configurable steam input used to be.   i.e. change steam ui button prompts and in gam button prompts by selecting or configuring controller settings to set any of the supported controller types regardless of controller type is detected by steam

There are scores of related issues.

How did steam sdl get so bad?

**Comment by slajerek** [comment] 2023-05-18 20:35
Confirmed, DS4 gamepad does not work on macOS Ventura. It is registered, opened but no input events.

**Closed** 2023-05-20 18:18 UTC

**Comment by slouken** [comment] 2023-05-20 18:19
@Balderick, this bug report was regarding SDL on macOS. If you have an issue that can be reproduced with testgamecontroller on a Windows system, feel free to report a separate issue with complete steps.
