### ISSUE TITLE
SDL_snprintf %f truncates instead of rounding

### ISSUE THREAD

**Issue by Markvy** [libsdl-org/SDL#4805] opened 2021-10-03 16:30 UTC
(Alternative "clickbait"-y bug title: 50% of possible inputs to printf produce wrong output)
Not sure if this is worth fixing but I think it is, because sometimes the output can be VERY wrong.
(speaking of wrong output: the below code block has inconsistent syntax highlighting and I have no idea why.)
```c
printf("%.0f", 1.9); // integer case: expected 2, got 1
printf("%.1f", .19); // fractional case: expected 0.2 but got 0.1
printf("%.1f", -9.99); // annoying case: expected -10.0 but got -9.9 
```
Not sure if I should have filed two separate issues or just one; from a user point of view, the symptom is similar, but there are two separate places in the code that cause this.  Decided to file one since it's easy to split one issue but hard to combine two.

**Comment by Markvy** [comment] 2021-10-08 03:20
Thanks!  Quoting fixed, first line now looks more like the others, so still not identical.
Also, does anyone have anything to say about the bug?  Will be fixed in next release?
Some future release?  Unknown?  Depends?

**Comment by InfoTeddy** [comment] 2021-10-08 06:12
> [but] still not identical.

This is probably because you are omitting the semicolons, too.

> Also, does anyone have anything to say about the bug? Will be fixed in next release?
Some future release? Unknown? Depends?

The next release will be 2.0.18, sometime in November. You can view [its milestone here](https://github.com/libsdl-org/SDL/milestone/2). As you can see, there are a lot of other higher-priority bugs than this one. So even though this will probably be fixed, it's just not that high of a priority.

**Comment by slouken** [comment] 2021-10-08 10:38
Feel free to submit a patch or pull request, and we'll evaluate it for the next release.

Cheers!

**Comment by Markvy** [comment] 2021-10-09 00:57
I actually do have an idea about how to fix this, but avoided saying what it was because you might think of a better one, and I didn't want to accidentally "contaminate" your thought process.  If you're sure you don't mind, I can share my current idea for how to fix it.  Should i?  Or better wait?

**Comment by Markvy** [comment] 2021-10-10 16:34
Okay, it turns out my original idea doesn't work if the buffer size is too small to contain the full answer without truncation.
I think I have a way to patch this, but first let me describe the original idea, which is (slightly) simpler.
The hard part is the fractional case, so let's focus on that; the integer case is similar but simpler.
I find it helps to have an example in mind when reading through an algorithm description; the example I plan to keep in mind here (and occasionally refer to) is this:
```c
print("%.1f". 0.950001); // expect 1.0, and not 0.9
```
The idea is to add some fixup logic after this `while` loop:
https://github.com/libsdl-org/SDL/blob/main/src/stdlib/SDL_string.c#L1667
(in-lining loop here for convenience and in case line numbers change on the main branch)
```c
while (info->precision-- > 0) {
	value = (unsigned long) (arg * mult);
	length += SDL_PrintUnsignedLong(TEXT_AND_LEN_ARGS, NULL, value);
	arg -= (double) value / mult;
	mult *= 10;
}
```
The key insight is this: by the time the loop completes, we should round up if (and only if) `arg * mult` exceeds 5.  (Actually, if we want to be really proper, we might need to round up if arg * mult is exactly 5, using "round to even" rules, but let's not worry about that for now; this is not going to be an perfectionist printf.)

So, we can simply increment the last digit that we printed, unless it was a 9.  If it was a nine, we implement the algorithm we learned in school: we carry the 1.  Eventually we either reach a digit that was not a nine, which we can increment, or else we reach the decimal point.  If we reach the decimal point, then we know that this should actually be printed as an integer.  The easiest way to do that is simply to make a recursive call to SDL_PrintFloat.  (Or `goto` the beginning.)

The catch is that we've destroyed the original value of `arg` (including its sign) and also the precision.   So we should be careful and save them somewhere, or maybe don't touch them and instead work on copies.  The other catch is that I've been assuming that we have access to all the digits we computed, but if the buffer size is too small, we might not.  At first I thought that this is fine: if the last digit is going to be cut off anyway, it makes no difference whether we round it up or down.  But of course, as my example shows, this is wrong, because by the time we carry the 1, it might affect digits we actually can see.

The fix turns out to be simple.  Inside the while loop, we keep track of how many consecutive nines we produce.  If we know this number, we don't need access to the digits in order to carry the 1.  And if the number of nines equals the requested precision, we don't bother carrying and simply make a recursive call to print `ceil(original_arg)`.  (Not quite, because I think `ceil()` doesn't do what we want for negative numbers, but you know what I mean.)

So...
- Does this make sense?
- Should I explain it better?
- Do you prefer to see actual C code?
- Do you prefer that I go away and don't come back until I think of something simpler?
- Some combination of the above?  None of the above?

**Comment by Markvy** [comment] 2021-10-17 00:20
(note: I had a typo in my original bug report: I wrote `"%.2f"` when I meant `"%.1f"`.  fixed now.)

Implementation coming soon as I manage to debug it

**Comment by vladh** [comment] 2023-08-13 19:27
I can't reproduce this on the `SDL2` branch. Perhaps this could be closed.

**Comment by slouken** [comment] 2023-11-07 03:18
Yes, this has been fixed for the next release, I'll go ahead and close it.

**Closed by slouken** 2023-11-07 03:18 UTC
