### ISSUE TITLE
Hang in ISensorManager_Release()

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#4276] opened 2021-04-03 18:50 UTC
Someone reported a hang on SDL_Quit, which appears to be in ISensorManager_Release() under SDL_WINDOWS_SensorQuit().

![120977ac986da134a7d382d5b9d66458cabb0047_2_690x332](https://user-images.githubusercontent.com/673562/113488379-b603cf00-948b-11eb-9068-79dfec0d4dfd.png)

Discussion was here:

https://discourse.libsdl.org/t/sdl-quit-freezes-at-program-shutdown/31117/3

Tossing this into the 2.0.16 milestone in case it's an obvious fix, but we can push back if necessary.

**Comment by slouken** [comment] 2021-07-24 07:28
From the original bug report, it looks like this only started happening once the code was moved into a DLL.

**Comment by slouken** [comment] 2021-07-24 07:55
I created a DLL project with this code:
```
// t.h

extern "C"
{
	int __declspec( dllexport ) init();
	int __declspec( dllexport ) loop();
	int __declspec( dllexport ) quit();
}
```
```
// t.cpp

#include "pch.h"
#include "SDL.h"
#include <iostream>
#include "t.h"

static SDL_Window *m_pWindow;
static SDL_GLContext m_context;

int init()
{
	if ( SDL_Init( SDL_INIT_EVERYTHING ) == 0 )
	{
		std::cout << "SDL initialized." << std::endl;
	}
	else
	{
		return false;
	}

	int flags = 0;
	flags = SDL_WINDOW_SHOWN;
	flags |= SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE;

	SDL_GL_SetAttribute( SDL_GL_CONTEXT_MAJOR_VERSION, 4 );
	SDL_GL_SetAttribute( SDL_GL_CONTEXT_MINOR_VERSION, 1 );
	SDL_GL_SetAttribute( SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE );
	SDL_GL_SetAttribute( SDL_GL_DOUBLEBUFFER, 1 );

	SDL_GL_SetAttribute( SDL_GL_MULTISAMPLEBUFFERS, 1 );
	SDL_GL_SetAttribute( SDL_GL_MULTISAMPLESAMPLES, 4 );
	SDL_GL_SetAttribute( SDL_GL_DEPTH_SIZE, 24 );

	m_pWindow = SDL_CreateWindow( "Game", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 1920, 1080, flags );

	if ( m_pWindow == nullptr )
		return false;

	m_context = SDL_GL_CreateContext( m_pWindow );
	if ( m_context == nullptr )
		return false;

	// 	glewExperimental = GL_TRUE;
	// 	auto init_res = glewInit();
	// 	if ( init_res != GLEW_OK )
	// 	{
	// 		std::cout << glewGetErrorString( glewInit() ) << std::endl;
	// 	}

	if ( SDL_GL_SetSwapInterval( 1 ) < 0 )   // <-- vsync disabled
	{
		printf( "Warning: Unable to set VSync! SDL Error: %s\n", SDL_GetError() );
	}
	return true;
}

int loop()
{
	bool done = false;
	while ( !done )
	{
		SDL_Event event;
		if ( SDL_PollEvent( &event ) == 1 )
		{
			if ( event.type == SDL_QUIT )
			{
				done = true;
			}
		}
	}
	return true;
}

int quit()
{
	SDL_GL_DeleteContext( m_context );
	SDL_DestroyWindow( m_pWindow );
	SDL_Quit(); // <-- hangs
	return true;
}
```

and a Win32 application with this code:
```
#include <windows.h>

extern "C"
{
	int init();
	int loop();
	int quit();
}

int WINAPI
WinMain( HINSTANCE hInst, HINSTANCE hPrev, LPSTR szCmdLine, int sw )
{
	init();
	loop();
	quit();
	return 0;
}
```
I wasn't able to reproduce the issue with this setup.
I did this from a desktop system with no sensors, so maybe that's a factor here?

**Comment by mmmaisel** [comment] 2022-06-14 16:00
For your information: In the program AntimicroX, this issue was triggered by the flag SDL_INIT_SENSOR regardless of whether a controller is connected or not.
Removing this flag during initialization fixed the issue while the sensors kept working.

**Comment by slouken** [comment] 2023-11-07 02:28
I believe this is fixed in the latest SDL release. Please feel free to reopen this if that's not the case.

**Closed by slouken** 2023-11-07 02:28 UTC
