### ISSUE TITLE
Tiling an SDL Window on macOS crashes the SDL Window

### ISSUE THREAD

**Issue by philippemnoel** [libsdl-org/SDL#4883] opened 2021-10-26 07:24 UTC
Basically, there appears to be an SDL bug which causes issues with tiling. When tiling an SDL window on macOS (so that you an have two full-screen applications in split screen mode), the SDL Window crashes. We've tested this both with our application and with a simple SDL program (see below).

```C++
#include <SDL.h>
#include <iostream>

const int SCREEN_WIDTH = 800;
const int SCREEN_HEIGHT = 600;

int main(int arc, char ** argv) {

    if (SDL_Init( SDL_INIT_VIDEO ) < 0) {
        std::cout << "SDL could not initialize! SDL_Error: " << SDL_GetError() << std::endl;
    } else {
        
        SDL_Window* w = SDL_CreateWindow(
            "SDL2 Demo",
            SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
            SCREEN_WIDTH, SCREEN_HEIGHT,
            SDL_WINDOW_ALLOW_HIGHDPI | SDL_WINDOW_OPENGL|SDL_WINDOW_RESIZABLE
        );
        
        SDL_Event event;
        while (true) {
            SDL_Delay(50);
            if (SDL_PollEvent(&event)) {
                switch (event.type) {
                    case SDL_QUIT:
                        return 0;
                    default:
                        break;
                }
            }
        }
    }
    
    return 0;
}
```

**Comment by slime73** [comment] 2021-10-30 00:03
I haven't been able to reproduce this so far (on macOS 11.6 using the latest SDL code compiled from source) – the given code works for me without crashes.

However if I drag the tile border to adjust sizes after entering tiling mode, it kicks me out of tiling mode (without crashing), and prints some logs:
```
[Window] Window 0x1b3 failed to resize to fit its tiled full screen space. Constraints were not violated; subclassing or a delegate may have prevented resize.

[Window] Window 0x1b3 is being ejected from tiled full screen after failing to resize to fit.
```

**Comment by slime73** [comment] 2021-10-30 02:57
This SetWindowStyle call is what's preventing resizing from within tiled Spaces from working, which makes sense I suppose: https://github.com/libsdl-org/SDL/blob/main/src/video/cocoa/SDL_cocoawindow.m#L786-L801

Nothing has immediately come to mind that would solve both the tiling-resize issue and the issue described in the linked comment.

(Either way, I still haven't been able to reproduce the crash.)

**Comment by icculus** [comment] 2021-10-30 16:37
I couldn't reproduce a crash here either, and it's a pretty basic example, so I'm surprised it's crashing.

Is it possible to get the actual build of the library/framework uploaded so I can run the exact problem build in a debugger?

**Comment by rpadaki** [comment] 2021-11-02 20:04
Hey I'm the one who initially came across this

Apologies that my issue description here wasn't clear and led to wasted time! As far as I can tell, any crash here is my fault, and was maybe caused by some other things I was trying with SDL.

I'll confirm again soon though -- it's possible that there's different behavior between the primary tiled window and secondary tiled window cases (are you dragging another application window to join a fullscreen sdl window, or are you dragging a windowed sdl window to join another fullscreen application?)

I'll do a bit more experimenting and confirm whether or not the bug was entirely on me

**Comment by rpadaki** [comment] 2021-11-04 19:25
I stand corrected! The window can totally permanently disappear here, though the program doesn't crash; the window simply ceases to exist.

1. Start in windowed mode
2. Click and hold on the green traffic light button and select "tile to left of screen", and choose another application to be the right of screen partner
3. Resize, booting SDL window out of the tiled screen
4. Fullscreen SDL window by clicking the green button
5. Three-finger swipe up to see all your windows, and drag a non-SDL window onto the fullscreen SDL window to trigger a tile to the right

For me, pretty consistently, the window will entirely disappear at this point, though the program continues to run!

**Comment by icculus** [comment] 2021-11-04 21:25
I'm putting this in 2.0.18's milestone, but I'm about to kick a bunch of stuff to 2.0.20 and this might be part of that batch, depending on what I find when I look at this.

**Comment by icculus** [comment] 2022-08-07 06:19
Revisiting this and can't reproduce the window _vanishing_ ... running `testsprite2 --resizable` and following the steps, it reliably gets booted out of the fullscreen space instead of tiling on step 5, but ends up in focus on the primary space, windowed.

It's possible the not-vanishing is due to a fix in recent Monterey releases, but even if that's true, it's compensating for a possible bug in SDL, since it refuses to tile the app.

`testsprite2 --resizable --fullscreen-desktop` (go right to a fullscreen space without all the other steps) and then dragging a window in, to tile with it, will cause SDL to kick out too, and then attempt to migrate to its own fullscreen space...it got stuck for awhile, but eventually started rendering again, but it definitely struggled and this obviously isn't what it should have done at all.

So this clearly has some issues that need to get ironed out.

My guess is that our fullscreen code, which predates the idea that you can tile fullscreen windows in the same space, probably needs to be updated to manage that. My guess is that it isn't expecting to get a resize event and assumes this means it was supposed to be in windowed mode and takes steps to drop out of fullscreen mode.

I'll dig in on this shortly.

**Comment by icculus** [comment] 2022-08-09 00:33
Okay, so we made the resizable fix that @slime73 mentioned for what is now #2497, but this fix is silly; it only happens if you click all the way at the border _and never move the mouse a single pixel_ while holding it down. Once you do, the system realizes you can't resize or drag this window and unblocks.

It's worth noting that _the same thing happens_, still, in windowed mode, with resizable windows.

This is probably a real SDL bug (watching YouTube on Safari doesn't freeze the video in this scenario), but not being able to tile windows in fullscreen seems like a much more serious issue, so I'm taking that change out and closing this bug (as it appears to totally fix this issue).

**Closed** 2022-08-09 00:35 UTC
