### ISSUE TITLE
%1 is not a valid Win32 application

### ISSUE THREAD

**Issue by readsack** [libsdl-org/SDL#6220] opened 2022-09-13 11:00 UTC
Whenever compiling with sdl2 I am getting the error mentioned in the title. I have tested it is due to sdl2 as when I remove the include statement, it compiles fine. I was just testing if sdl2 is working correctly or not.

```c
#include "iostream"
#include "SDL2/SDL.h"

int main(int argc, char *argv[]){
std::cout << "SDL Works" << std::endl;
return 0;
}
```

**Comment by icculus** [comment] 2022-09-13 11:30
You get error message during compilation, or running the newly-compiled binary?

(And are you compiling with mingw, by any chance?)

**Comment by Keshav-Agarwala** [comment] 2022-09-13 14:16
> You get that error message during compilation, or running the newly-compiled binary?
> 
> (And are you compiling with mingw, by any chance?)

I am indeed using mingw and I dont get any errors during compilation. Just when running the exe file which was created

**Comment by icculus** [comment] 2022-09-13 14:37
Duplicate of #6139.

**Closed as not planned by icculus** 2022-09-13 14:37 UTC
