### ISSUE TITLE
Remove SDL_SoftStretch?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#8667] opened 2023-12-06 16:43 UTC
From the SDL_SoftStretch docs in SDL_surface.h:

```
 * Perform a fast, low quality, stretch blit between two surfaces of the same
 * format.
 *
 * **WARNING**: Please use SDL_BlitSurfaceScaled() instead.
```

Should we take this out of the public API (or SDL entirely) for SDL3?

**Comment by Starbuck5** [comment] 2023-12-07 02:06
We use it in pygame-ce as our generic surface scaling function.

It does a different thing than BlitScaled iirc, since blitscaled can blend with the destination. SoftStretch just replaces the destination always, which is exactly what we want.

**Comment by 1bsyl** [comment] 2023-12-07 09:28
I quickly looked at the code, and seems we could remove them (both SoftStrech and SoftStrechLinear). there are somehow duplicate of BlitScaled which are higher level.

If you don't use complex flags, 
SDL_COPY_MODULATE_COLOR | SDL_COPY_MODULATE_ALPHA |
SDL_COPY_BLEND | SDL_COPY_ADD | SDL_COPY_MOD | SDL_COPY_MUL |
SDL_COPY_COLORKEY

it finally does the SDL_SoftStretch

**Comment by 1bsyl** [comment] 2023-12-07 10:56
@Starbuck5  maybe you can try the replacement for softstretch here: https://github.com/libsdl-org/sdl2-compat/pull/115

**Comment by slouken** [comment] 2023-12-07 14:50
> Remove SDL_SoftStretch() and SDL_SoftStretchLinear() but, we now also need to add SDL_BlitSurfaceScaledLinear() and SDL_BlitSurfaceUncheckedScaledLinear() for consistency

Hmm, I'm not sure that's a good idea. @icculus?

**Comment by icculus** [comment] 2023-12-07 14:52
I don't want to _add_ complexity, I was just noting the documentation says "don't use this function."

**Comment by 1bsyl** [comment] 2023-12-07 15:44
if remove SDL_SoftStretch(), it makes sense to remove also SDL_SoftStretchLinear().
and if we remove bilinear scaling, it needs to be available somehow because it's useful.

adding SDL_BlitSurfaceScaledLinear() 
similarly to SDL_BlitSurfaceScaled() which is nearest.
(but maybe we would need some  SDL_SetSurfaceScaleMode (similar to SDL_SetTextureScaleMode )


Also, we remove SDL_SoftStrech() in favor of SDL_BlitScaled()
because, if i'm correct,  SDL_SoftStrech just does scaling ignoring any blending.
which is the default if you haven't set any modulation/blend.

**Comment by Starbuck5** [comment] 2023-12-07 17:47
I think the comment in the docs is mistaken and softstretch has its own justified place.

It’s nice to be able to take in any surface and scale it without needing to clear the set attributes, which is what the proposed SDL2compat shim has to do.

**Comment by slouken** [comment] 2023-12-07 18:25
Maybe we just fix the documentation. :)

**Comment by 1bsyl** [comment] 2023-12-08 10:38
indeed, that's easier to fix the document. Looking at the log, the comment was imported from the wiki.

but:
in SDL2compat, the implementation is a little long because it make sure to clear all the flags. but in real case, eg for most of the case, you only have set blendmode_none, if you use rgba or nothing for a rgb surface.


Btw, the PR also add BlitSurfaceScaledLinear, functionnalty wasn't exposed before. 
(unless you create a SW render, and use Texture with SDL_SCALEMODE_LINEAR)

Maybe the API name is not a good choice, and it would be better to have SDL_SetSurfaceScaleMode() similarly to 
SDL_SetTextureScaleMode()

**Comment by 1bsyl** [comment] 2023-12-18 08:42
(update the PR since SDL_SetSurfaceScale was added)

**Closed** 2023-12-19 00:40 UTC
