### ISSUE TITLE
Assertion failure at SDL_SetKeyboardFocus

### ISSUE THREAD

**Issue by Dlinuigh** [libsdl-org/SDL#9747] opened 2024-05-10 07:49 UTC
This WARN show every time when trying to quit SDL;
And the SDL_keyboard.c file does not exist on my computer.
Although this WARN can ignore, but I still feel uncomfortable.
``` cpp
SDL_QuitSubSystem(SDL_INIT_EVENTS);
SDL_QuitSubSystem(SDL_INIT_VIDEO);
for(auto f : font_lut){
  TTF_CloseFont(f.second);
}
TTF_Quit();
SDL_DestroyRenderer(render);
SDL_DestroyWindow(window);
SDL_Quit();
```
I think the problem may exist between this code. Because the `break` button tells me.
I'm not sure if this is an SDL concern, but I think I might seek help here.
![Screenshot from 2024-05-10 15-37-39](https://github.com/libsdl-org/SDL/assets/46435838/9eb19dea-ff52-46c0-b041-0382b5a5afd4)

**Comment by Sackzement** [comment] 2024-05-10 09:41
Does reordering the functions help?
```
for(auto f : font_lut){
  TTF_CloseFont(f.second);
}
TTF_Quit();
SDL_DestroyRenderer(render);
SDL_DestroyWindow(window);
SDL_QuitSubSystem(SDL_INIT_EVENTS); // <---
SDL_QuitSubSystem(SDL_INIT_VIDEO);  // <---
SDL_Quit();
```

**Comment by slouken** [comment] 2024-05-10 15:46
Do you have a simple example we can run here to reproduce the problem?

**Comment by Dlinuigh** [comment] 2024-05-11 05:09
I am trying to write a short code example, sorry for the late reply.

**Comment by Dlinuigh** [comment] 2024-05-11 05:11
> Does reordering the functions help?
> 
> ```c++
> for(auto f : font_lut){
>   TTF_CloseFont(f.second);
> }
> TTF_Quit();
> SDL_DestroyRenderer(render);
> SDL_DestroyWindow(window);
> SDL_QuitSubSystem(SDL_INIT_EVENTS); // <---
> SDL_QuitSubSystem(SDL_INIT_VIDEO);  // <---
> SDL_Quit();
> ```

It seems no difference, but I found the break point is still around `SDL_DestroyWindow` line.

**Comment by Dlinuigh** [comment] 2024-05-11 05:31
ok, I complete the example

**Comment by Dlinuigh** [comment] 2024-05-11 05:33
[test_sdl.zip](https://github.com/libsdl-org/SDL/files/15281727/test_sdl.zip)
well, this example is complied with meson, and as a subproject.

**Comment by Dlinuigh** [comment] 2024-05-11 05:40
Press the white button in the top left corner. I have tested this in a clean environment, though not a literal one. And
``` c
C++ compiler for the host machine: ccache c++ (gcc 14.1.1 "c++ (GCC) 14.1.1 20240507")
C++ linker for the host machine: c++ ld.bfd 2.42.0
```

**Comment by Dlinuigh** [comment] 2024-05-11 05:42
And this is the meson.build file content for the latter test.
``` meson
project('SDL_Test_SetKeyBoardFocus', 'cpp',
  version : '0.1',
  default_options : ['warning_level=3', 'cpp_std=c++14'])

deps = [
  dependency('sdl3'),
  dependency('sdl3-ttf')
]

executable('SDL_Test_SetKeyBoardFocus',
           'test_sdl.cpp',dependencies:deps,
           install : true)
```

**Comment by Dlinuigh** [comment] 2024-05-11 05:43
So if you need any other information related, just leave a message.

**Comment by Dlinuigh** [comment] 2024-05-11 09:23
I found that this is actually a Wayland only problem, Gnome with xorg will not show this WARN.

**Comment by Dlinuigh** [comment] 2024-05-11 09:27
Lately, I've encountered numerous issues with Wayland compatibility, which has left me feeling quite tense.

**Comment by Kontrabant** [comment] 2024-05-11 14:18
The sample code has many problems:
- SDL_PollEvent() needs to be called until all events have been processed
- The backbuffer needs to be redrawn every frame
- It seems to be using an older version of SDL3, as it uses the removedsoftware renderer flag. The assertion you are seeing was likely fixed by commit https://github.com/libsdl-org/SDL/commit/b41699e9c41847d817f8e3536cca9d966449c7ef

```
#include <SDL3/SDL.h>
#include <sys/types.h>

class Test
{
    SDL_Window *window;
    SDL_Renderer *render;
    SDL_Event event;

  public:
    Test()
    {
        SDL_Init(SDL_INIT_EVENTS);
        SDL_Init(SDL_INIT_VIDEO);
        window = SDL_CreateWindow("Test", 800, 600, SDL_WINDOW_BORDERLESS);
        render = SDL_CreateRenderer(window, NULL, 0);
    }
    bool in_btn()
    {
        float mouse_x, mouse_y;
        SDL_GetMouseState(&mouse_x, &mouse_y);
        return 0 < mouse_x && 0 + 64 > mouse_x && 0 < mouse_y &&
               32 > mouse_y;
    }
    bool handle()
    {
        while (SDL_PollEvent(&event)) {
            switch (event.type) {
            case SDL_EVENT_MOUSE_BUTTON_DOWN:
                if (event.button.button == SDL_BUTTON_LEFT && in_btn()) {
                    return false;
                }
                break;
            case SDL_EVENT_KEY_DOWN:
                if (event.key.keysym.sym == SDLK_q) {
                    return false;
                }
                break;
            }
        }

        return true;
    }
    void clean()
    {
        SDL_DestroyRenderer(render);
        SDL_DestroyWindow(window);
        SDL_QuitSubSystem(SDL_INIT_EVENTS); // <---
        SDL_QuitSubSystem(SDL_INIT_VIDEO);  // <---
        SDL_Quit();
    }
    void present()
    {
        SDL_SetRenderTarget(render, NULL);
        SDL_SetRenderDrawColor(render, 255, 255, 255, 255);
        SDL_FRect btn = { 0, 0, (float)64, (float)32 };
        SDL_RenderFillRect(render, &btn);
        SDL_RenderPresent(render);
    }
};

int main()
{
    Test test;
    while (test.handle()) {
        test.present();
    }
    test.clean();
    return 0;
}
```

With this on the current version of SDL3, it runs correctly.

**Comment by Dlinuigh** [comment] 2024-05-11 15:56
I compiled and run the code above, it still has the problem on Wayland. So do you run the code in a xorg environment?

**Comment by Dlinuigh** [comment] 2024-05-11 15:58
And I agree that this is the problem of mouse event for this won't happen when I quit with keyboard down event.

**Comment by Dlinuigh** [comment] 2024-05-11 15:59
Anyway I will compile the latest version of SDL3 to test, thank you.

**Comment by Dlinuigh** [comment] 2024-05-11 16:03
Ok, the problem has been solved. Thank you again.

**Closed** 2024-05-11 16:03 UTC
