### ISSUE TITLE
[Design flaw] Resize appears to block main thread on windows - that's fatal for multiplayer games

### ISSUE THREAD

**Issue by ell1e** [libsdl-org/SDL#4614] opened 2021-08-09 13:37 UTC
From my tests, any window resize on MS Windows appears to just fully block SDL2 on the main thread, I assume in some event queue related function (I haven't tracked down yet which, I would guess you probably already know). If true, I think this is unacceptable and should be fixed. The remaining ticket illustrates why the impact of this is IMHO quite substantial.

1. Multiplayer games are the worst one hit: how am I apparently required to either 1. off-load all game logic to a separate thread and do complicated and possibly quite error prone synchronization with the main thread just to have unproblematic window resize, or 2. hilariously not allow any window resizing in 2021 since in SDL2 apparently that doesn't safely allow not-heavily-threaded multiplayer games, or 3. accept all players in an action heavy game that may need a shorter connection timeout will semi or permanently drop out if they dare resize the window for a second too long? It's just such an odd limitation.

2. I imagine many games with an integrated updater, or maybe some simple mod manager that can download files, might opt to poll their TCP download connection on the main thread for simplicity. Now if I resize the window for long enough on Windows the entire download will pause, or even time out? Oof.

3. What if my game has a midi-like music engine that is timed and triggers notes from the main thread? Even if the audio callback continues due to being on another thread, the music will drop out when I dare *gasp* resize the window. Not really as problematic as the others, but still feels like it just shouldn't happen with a sane multimedia lib.
 
4. Games that have a cutscene that is expected to sync up to a prebaked audio track may have things heavily desync just from any window resize during such a cutscene. (The impact would depend on how much catch-up their game loop allows. But I think most sane game loops will reset game time after falling more than 500-100ms+ behind in case it was either a machine suspend, or the game is possibly running so slowly that it might freeze permanently if attempting to catch up.) Obviously such cutscene audio desyncs are also at risk of happening on just lower specs machines or with any other more substantial system timing hiccup, but then likely gradual and less extreme in impact.

Summed up, I think this main thread block should therefore be removed. The main problem I'm seeing is that threads are a dangerous investment even today, so it's good advise to just keep it simple if they're not really needed. But limitations like this one mess with this. It pushes people to threads that would otherwise have better kept a simple design.

Please note I couldn't care less if the window *redraws* during resize. I think the contents being just black is indeed quite minor, and who even cares. I wouldn't complain however if that was also addressed as a side effect of fixing this.

**Comment by slouken** [comment] 2021-08-09 15:37
This is a duplicate of https://github.com/libsdl-org/SDL/issues/1059, which has a patch you can use to fix this. It was deemed too risky for mainline SDL, for reasons outlined in that bug, so we haven't applied it and don't currently plan to.

However, please let us know how it works for you!

**Comment by slouken** [comment] 2021-08-09 15:38
Duplicate of #https://github.com/libsdl-org/SDL/issues/1059

**Comment by slouken** [comment] 2021-08-09 15:39
Duplicate of #1059

**Closed by slouken** 2021-08-09 15:38 UTC

**Comment by ell1e** [comment] 2021-08-09 17:15
> However, please let us know how it works for you!

It doesn't seem to me like a useful approach, also [see my comment here](https://github.com/libsdl-org/SDL/issues/1059#issuecomment-895373155)
