### ISSUE TITLE
SDL_SetWindowFullscreen don't create SDL_WINDOWEVENT_SIZE_CHANGED event

### ISSUE THREAD

**Issue by CarlosBarrazaE** [libsdl-org/SDL#6025] opened 2022-08-09 00:12 UTC
The SDL_SetWindowFullscreen function does not raise the SDL_WINDOWEVENT_SIZE_CHANGED event, but when exiting fullscreen with SDL_SetWindowFullscreen(window, 0) the event is raised, possibly due to the mesa update to version 22.1.5

In libsdl2-2.0.22

**Comment by icculus** [comment] 2022-08-09 13:35
I can't reproduce this here on X11. Is this a Wayland thing, maybe?

**Comment by CarlosBarrazaE** [comment] 2022-08-09 15:27
No, it's from X11 on gentoo.
xorg-server-21.1.4
nvidia-drivers-390.151
I don't know what additional information you may need.

**Comment by omgitsaheadcrab** [comment] 2022-08-10 09:14
If I start the my application with `SDL_WINDOW_FULLSCREEN_DESKTOP` it works as intended, if I toggle it using `SDL_SetWindowFullscreen` then the image is not re-scaled but the window is indeed fullscreen. Could this be related?

**Comment by CarlosBarrazaE** [comment] 2022-08-10 12:56
@omgitsaheadcrab  It's the same problem, if I start my application with SDL_WINDOW_FULLSCREEN_DESKTOP it works fine the problem only happens from window to full screen.

**Comment by icculus** [comment] 2022-08-10 14:03
Moving to 2.24 in case I can reproduce this quickly with this new info, but it's bumping back to 2.26 if not (we're almost out of time for 2.24).

**Comment by icculus** [comment] 2022-08-11 18:38
Running `SDL_EVENT_LOGGING=1 ./testvulkan --resizable` here and pressing alt-enter to go fullscreen_desktop and back is working correctly on Gnome/x11; I get a SIZE_CHANGED for both going and coming from fullscreen_desktop mode.

It's possible it only triggers on kwin...?

**Comment by CarlosBarrazaE** [comment] 2022-08-11 19:11
Remove kwin and put twm, it worked correctly, I have no gnome to test.

**Comment by icculus** [comment] 2022-08-11 19:15
Wait, this _does_ reproduce for me with Gnome, if I use the actual 2.0.22 release. The latest in revision control works correctly...it's possible this was fixed by cf63af8ae265c99e80ffc93e9930336c939524bc in some way I don't understand yet. I'll bisect and see if it was something else instead.

Has anyone tried this on kwin with the latest SDL, or has this all been tested with 2.0.22?

**Comment by icculus** [comment] 2022-08-11 19:34
The actual fix was 9edd411a8315540b86fceec590dd5aa6be41f5f0, which was made after 2.0.22 shipped (this explicitly generates a RESIZED event in response to a fullscreen change, which will cause SDL to generate a SIZED_CHANGED event under the hood as well).

I'm assuming this is fixed for 2.24.0 already, but if you find this is still busted on kwin with the latest in revision control, please let me know and I'll reopen the issue. Thanks!

**Closed by icculus** 2022-08-11 19:34 UTC
