### ISSUE TITLE
SDL3 crashes after changing SDL_LOGICAL_PRESENTATION_DISABLED to SDL_LOGICAL_PRESENTATION_LETTERBOX

### ISSUE THREAD

**Issue by andreasgrabher** [libsdl-org/SDL#9698] opened 2024-05-05 10:13 UTC
Short description:

I am creating a renderer like this:

```
int nWindowWidth, nWindowHeight;
float dpiFactor;
SDL_Window* sdlWindow = NULL;
SDL_Renderer* sdlRenderer = NULL;
int width = 1120;
int height = 832;
sdlWindow = SDL_CreateWindow(PROG_NAME, width, height, SDL_WINDOW_RESIZABLE | SDL_WINDOW_HIGH_PIXEL_DENSITY);
sdlRenderer = SDL_CreateRenderer(sdlWindow, NULL, SDL_RENDERER_PRESENTVSYNC);
SDL_GetWindowSizeInPixels(sdlWindow, &nWindowWidth, &nWindowHeight);
dpiFactor = (float)nWindowWidth / width;
SDL_SetRenderLogicalPresentation(sdlRenderer, width, height, SDL_LOGICAL_PRESENTATION_DISABLED, SDL_SCALEMODE_LINEAR);
SDL_SetRenderScale(sdlRenderer, dpiFactor, dpiFactor);
```

After changing the presentation mode from disabled to letterbox:

```
SDL_SetRenderLogicalPresentation(sdlRenderer, width, height, SDL_LOGICAL_PRESENTATION_LETTERBOX, SDL_SCALEMODE_LINEAR);
```
I get a crash when resizing my window. The crash seems to occur within SDL_RenderPresent() and the message is "hit program assert".

System: Mac mini M1 with Studio Display running macOS Sonoma v14.4.1.

**Comment by slouken** [comment] 2024-05-06 16:10
What is the assert that you're hitting? Can you get a call stack in the debugger?

**Comment by andreasgrabher** [comment] 2024-05-06 18:00
I hope the appended file helps. The problem might be related to calling routines from a secondary thread. Same thing works just fine with SDL2 though.

[call_stack.txt](https://github.com/libsdl-org/SDL/files/15224595/call_stack.txt)

**Comment by slouken** [comment] 2024-05-06 18:07
Can you build with debug symbols and include all the threads in the stack trace?

Thanks!

**Comment by andreasgrabher** [comment] 2024-05-09 16:29
Can anyone provide instructions on how to build with debug symbols or provide a binary of SDL3.cxframework that supports it?

**Comment by slouken** [comment] 2024-05-09 17:17
You can just build the SDL framework using the included Xcode project.

**Comment by andreasgrabher** [comment] 2024-05-09 17:40
OK, I was able to build a debugging framework. Unfortunately I can't make it crash with that framework. Instead of crashes I get very long delays, but it recovers. Only from inside Xcode I can get the "hit program assert". Screenshot is appended. I hope this is useful.
<img width="1728" alt="Bildschirmfoto 2024-05-09 um 19 38 07" src="https://github.com/libsdl-org/SDL/assets/112762147/1fa9da02-c8a8-44f4-ada7-24686172aa95">

**Comment by slouken** [comment] 2024-05-09 17:48
That assertion definitely shows a problem. Is there any chance you can provide a link to your code and test steps so we can reproduce it?

**Comment by andreasgrabher** [comment] 2024-05-09 17:57
Of course:
The code is here: [https://sourceforge.net/p/previous/code/HEAD/tree/branches/branch_filesharing/](url)

The code uses a workaround/new resizing method at the moment to avoid the crash. So you have to undo it with the appended patch (patch -p1 -i debug.diff):
[debug.txt](https://github.com/libsdl-org/SDL/files/15265914/debug.txt)

You can then build on macOS using these commands
```
./configure
make
```
or if you want a debugging version
```
./configure --enable-debug
make
```

It will automatically create an application bundle which is located in the src directory. You can also create an Xcode project using this command:
`cmake -G Xcode .`

**Comment by andreasgrabher** [comment] 2024-06-01 16:02
I caught this error message during one of these crashes. Maybe it is useful:
`Set Vertex Buffer Offset Validation
offset(256) must be < [buffer length](256).`

**Comment by andreasgrabher** [comment] 2024-10-05 11:35
This crash seems to be gone when using metal renderer. When using gpu renderer I get main thread warnings.
<img width="1683" alt="Bildschirmfoto 2024-10-05 um 13 31 55" src="https://github.com/user-attachments/assets/00659649-e468-42eb-86a0-16e50fb39b81">

**Comment by thatcosmonaut** [comment] 2024-10-05 17:45
This issue is clearly because the client is using the render API on a thread. As far as I can tell the documentation already states that the Render API should only be used on the main thread. If Apple really doesn't let you call window functions outside of the main thread we might have to stipulate that the GPU API only allows you to call window functions on the main thread.

**Comment by slouken** [comment] 2024-10-05 19:08
Apple really doesn't let you call window functions outside of the main thread. The problem here is that the renderer is implicitly calling window functions on your behalf. Does that imply that the GPU API can only be used on the main thread?

**Comment by thatcosmonaut** [comment] 2024-10-05 19:39
We might be able to work around this by caching the window pixel size when the event triggers.

**Comment by thatcosmonaut** [comment] 2024-10-09 18:52
I've been investigating this issue and I'm confused because as far as I can tell, SDL_gpu_metal.m doesn't call any window functions. Is MoltenVK being used here? 

We might need to come up with a ClaimWindow workaround for Vulkan on MacOS to use vkCreateMetalSurfaceEXT instead of going through SDL_Vulkan_CreateSurface, that way we could just query the layer's drawableSize instead of needing to go through Cocoa_GetWindowSizeInPixels. On non-Mac platforms just querying the window extents on a thread isn't an issue.

**Comment by andreasgrabher** [comment] 2024-10-09 20:02
Not sure I understand this message. My application does not actively use Vulkan.

**Comment by thatcosmonaut** [comment] 2024-10-09 22:44
@slouken Considering that the docs state the Render API can't be used from a non-main thread, I think we should mark this as wontfix. If you want to relax that requirement we'll have to come up with a workaround. I can make sure that the GPU API avoids calling window query functions separately.

**Comment by andreasgrabher** [comment] 2024-10-10 11:54
If the gpu renderer can't be used with threaded applications I think we should make metal the default renderer on macOS. There are no more multithreading issues when using the metal renderer in my application.

I know that the default renderer can be specified, but I think these things should work out of the box. 

We are in 2024 and almost every computer has lots of CPU cores. Multithreading should just work.

**Comment by slouken** [comment] 2024-10-10 14:49
> We are in 2024 and almost every computer has lots of CPU cores. Multithreading should just work.

Except it doesn't. It looks like we can fix this for the metal renderer, but what you are doing does not work across all platforms and renderers, and is _more_ likely to work with the GPU renderer.

**Comment by andreasgrabher** [comment] 2024-10-10 15:00
On other platform all rendering is done on the main thread. Due to this bug I can‘t do that on macOS: https://github.com/libsdl-org/SDL/issues/10475

**Comment by thatcosmonaut** [comment] 2024-10-10 15:40
To be clear all that needs to be done to make the Render GPU backend work in this case is making sure GetWindowSizeInPixels is called on the main thread.

**Comment by andreasgrabher** [comment] 2024-10-10 15:48
`SDL_GetWindowSizeInPixels()` is called on the main thread. Functions called on the secondary thread are:

```
SDL_RenderClear(sdlRenderer);
SDL_RenderTexture(sdlRenderer, fbTexture, NULL, &screenRect);
SDL_RenderTexture(sdlRenderer, uiTexture, NULL, &screenRect);
/* Sleeps until next VSYNC */
SDL_RenderPresent(sdlRenderer);
```

**Comment by thatcosmonaut** [comment] 2024-10-10 15:49
I'm not talking about your client code, I'm talking about SDL_render_gpu.c

**Comment by andreasgrabher** [comment] 2024-10-10 15:50
Sorry, my misunderstanding.

**Comment by slouken** [comment] 2024-12-04 17:46
The GPU renderer is no longer the default, so this should be fixed, thanks!

**Closed by slouken** 2024-12-04 17:46 UTC
