### ISSUE TITLE
Audio initialization hits assertion in HoloLens

### ISSUE THREAD

**Issue by hanseuljun** [libsdl-org/SDL#4239] opened 2021-03-27 01:01 UTC
HoloLens is an AR headset which runs UWP applications on its version of Windows. When checked through SDL, the only audio driver available is WASAPI (disk and dummy were also found as device names but I guess they are not actual drivers).

The issue is with HoloLens running with 24-bit audio. In the below function WaveFormatToSDLFormat, it falls into the case 
1. waveformat->wFormatTag == WAVE_FORMAT_EXTENSIBLE
2. ext->SubFormat matches SDL_KSDATAFORMAT_SUBTYPE_PCM
3. waveformat->wBitsPerSample == 24

Due to 1., code enters the 4th case of the first layer of conditions. Inside there there is no condition matching 2 and 3, especially 3 since 16 and 32 are covered but not 24.

https://github.com/libsdl-org/SDL/blob/6d9c4f6c6c71af6ae32cc316a6bd0cc0af102591/src/audio/wasapi/SDL_wasapi.c#L85

As seemingly, SDL audio does not provide native support for 24-bit audio systems, which I guessed based on AUDIO_S24SYS not existing.

Now the solution part: Would it be okay to merely return 0 here before hitting SDL_assert in this case? Is 0 some kind of a valid return value as a last resort or is it just invalid?

**Comment by flibitijibibo** [comment] 2021-03-27 04:23
Duplicate of #4223

**Closed** 2021-03-29 15:55 UTC
