### ISSUE TITLE
[Linux] The share button on Xbox Series X|S controller produces "double events"

### ISSUE THREAD

**Issue by Igetin** [libsdl-org/SDL#6296] opened 2022-09-28 17:35 UTC
# Description

When pressing [the share button](https://i.imgur.com/Wo5m5oX.png) on the Xbox Series X|S controller, it seems to be produce "double events". When running the testjoypad program provided with the SDL source, a button press outputs the following:

```
INFO: Joystick 0 button 15 down
The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL forums/mailing list <https://discourse.libsdl.org/> X11 KeyCode 175 (167), X11 KeySym 0x1008FF1C (XF86AudioRecord).
INFO: Joystick 0 button 15 up
```

I originally posted about this erroneously on [a different SDL issue](https://github.com/libsdl-org/SDL/issues/4222#issuecomment-1013738984). My use case is that I want to map the share button in [AntiMicroX](https://github.com/AntiMicroX/antimicrox), which uses SDL behind the scenes. However, the button press is not [recognized by the program](https://github.com/AntiMicroX/antimicrox/issues/307), and its developer deemed that the issue might be caused by SDL.

Note that I do not know if this is _actually_ a bug in SDL, or even if it is a bug at all! I was just redirected here by another developer.

I can try to provide more information if needed.

# Environment

- Operating system: Fedora 35
- Display server: Xorg 1.20.14
- Kernel: Linux 5.18.18

**Comment by slouken** [comment] 2022-09-28 17:56
There are several issues here. The first is AntiMicroX not recognizing the share button. I haven't looked at the source code, but AntiMicroX may not be looking for the button `SDL_CONTROLLER_BUTTON_MISC1`. The bug report there didn't have enough information because of the second issue - the Xbox kernel driver being used to generate the log output doesn't support the share button at all, so it never showed up.

The final issue, is the kernel driver on your system is translating the share button into a keypress that is being interpreted by X11 as an audio record action.

I can fix the error message, but you might want to debug AntiMicroX and see if it's handling the misc1 button. If you find that it isn't, the author is more likely to see what's happening if you file a working patch or a pull request that fixes the issue for you.

**Comment by Igetin** [comment] 2022-09-28 18:22
>AntiMicroX may not be looking for the button `SDL_CONTROLLER_BUTTON_MISC1`

I just checked, seems like you are right about this. I'll message the author about it. Thanks!

>The final issue, is the kernel driver on your system is translating the share button into a keypress that is being interpreted by X11 as an audio record action.

Ah, that might be a nuisance at some point… in that case I will have to research if I can somehow easily disable that behavior.

**Comment by pktiuk** [comment] 2022-10-16 12:53
Hello @slouken  

The main source of the problem is not the lack of direct handling of `SDL_CONTROLLER_BUTTON_MISC1` but the different behaviour of Share button in comparison to other buttons of gamepad.   


While other buttons when pressed launch two events (for example `SDL_CONTROLLERBUTTONDOWN` and `SDL_JOYBUTTONDOWN`) the Share button launches only one event (`SDL_JOYBUTTONDOWN`).

Is it intended behaviour? (for devices that are marked as `SDL_IsGameController()` only events `SDL_GAMECONTROLLER...` are handled)


<details>
  <summary>Example logs</summary>
  
```
[15:12:59.492] 🐞DEBUG	Processing event: SDL_CONTROLLERBUTTONDOWN From joystick with instance id: 0 Got button with id: 0 is one of the GameControllers: true is one of the joysticks:false (file unner/work/antimicrox/antimicrox/src/inputdaemon.cpp:751)
[15:12:59.492] 🐞DEBUG	Processing event: SDL_JOYBUTTONDOWN From joystick with instance id: 0 Got button with id: 0 is one of the GameControllers: true is one of the joysticks:false (file unner/work/antimicrox/antimicrox/src/inputdaemon.cpp:751)
[15:12:59.492] 🐞DEBUG	Processing JoyButton::joyEvent for: A: [NO KEY] SDL index: 0 className: JoyButton (file unner/work/antimicrox/antimicrox/src/joybutton.cpp:179)
[15:12:59.623] 🐞DEBUG	Processing event: SDL_CONTROLLERBUTTONUP From joystick with instance id: 0 Got button with id: 0 is one of the GameControllers: true is one of the joysticks:false (file unner/work/antimicrox/antimicrox/src/inputdaemon.cpp:751)
[15:12:59.623] 🐞DEBUG	Processing event: SDL_JOYBUTTONUP From joystick with instance id: 0 Got button with id: 0 is one of the GameControllers: true is one of the joysticks:false (file unner/work/antimicrox/antimicrox/src/inputdaemon.cpp:751)
[15:12:59.623] 🐞DEBUG	Processing JoyButton::joyEvent for: A: [NO KEY] SDL index: 0 className: JoyButton (file unner/work/antimicrox/antimicrox/src/joybutton.cpp:179)
[15:13:02.394] 🐞DEBUG	Processing event: SDL_JOYBUTTONDOWN From joystick with instance id: 0 Got button with id: 15 is one of the GameControllers: true is one of the joysticks:false (file unner/work/antimicrox/antimicrox/src/inputdaemon.cpp:751)
[15:13:02.544] 🐞DEBUG	Processing event: SDL_JOYBUTTONUP From joystick with instance id: 0 Got button with id: 15 is one of the GameControllers: true is one of the joysticks:false (file unner/work/antimicrox/antimicrox/src/inputdaemon.cpp:751)
```
</details>

**Comment by slouken** [comment] 2022-10-16 15:39
Ah, this means it's just not in the mapping. You can use controllermap (that comes in the SDL test directory) to generate a binding and include it here for the next SDL release.

**Comment by Igetin** [comment] 2022-10-16 15:48
I actually [added the mapping](https://github.com/gabomdq/SDL_GameControllerDB/pull/618) for that controller in the SDL_GameControllerDB repository a few days ago, but I wasn't really familiar with the exact relationship of that project and the main SDL repo. It seems like SDL also has its own set of mappings included with the library? In any case, you can find the mapping from the link.

**Comment by slouken** [comment] 2022-10-16 16:06
The projects are independent. The ones that are included in SDL directly are validated a little more rigorously and so aren't automatically added from SDL_GameControllerDB.

I added your mapping, thanks!

**Closed** 2022-10-16 16:06 UTC
