### ISSUE TITLE
SDL_Vulkan_GetDrawableSize returns outdated value on macos after updating to 2.24.1

### ISSUE THREAD

**Issue by ellipticaldoor** [libsdl-org/SDL#6464] opened 2022-10-30 15:32 UTC
When using vulkan on macos with latest `2.24.1` and calling `SDL_Vulkan_GetDrawableSize` it will return a wrong value when resizing a window manually.

For example in SDL `2.22.0`, when using an hdpi monitor in mac, I call `SDL_Vulkan_GetDrawableSize` and I get twice the pixels that SDL_GetWindowSize reports.
```
SDL_GetWindowSize -> 1698, 938
SDL_Vulkan_GetDrawableSize -> 3396, 1876
```

But when using `2.24.1` I get this
```
SDL_GetWindowSize ->  1698, 938
SDL_Vulkan_GetDrawableSize -> 3442, 1892
```

This issue only happens when resizing the window, and also I noticed that the resolution that `SDL_Vulkan_GetDrawableSize` reports is just the previous one, so it seems like `SDL_GetWindowSize` is out of sync with `SDL_Vulkan_GetDrawableSize`

This issue is not present in windows and `SDL_GL_GetDrawableSize` works fine too.

I tested 2.24.0 and this version also has this issue.

**Comment by ellipticaldoor** [comment] 2022-11-07 20:17
Ah yes, sorry I forgot to share an example to reproduce the issue:

```c++
bool get_screen_info(SDL_Window *window) {
    int _window_width = 0, _window_height = 0;
    SDL_GetWindowSize(window, &_window_width, &_window_height);

    int _screen_width = 0, _screen_height = 0;
    SDL_Vulkan_GetDrawableSize(window, &_screen_width, &_screen_height);

    if ((float)_window_width / (float)_screen_width !=
        (float)_window_height / (float)_screen_height) {
        // this means SDL_Vulkan_GetDrawableSize is out of sync
        return false;
    }
    return true;
}

int app_event_watcher(void *data, SDL_Event *event) {
    if (event->type != SDL_WINDOWEVENT) return 0;
    SDL_Window *_window = SDL_GetWindowFromID(event->window.windowID);
    if (_window != (SDL_Window *)data) return 0;

    switch (event->window.event) {
        case SDL_WINDOWEVENT_SIZE_CHANGED:
        case SDL_WINDOWEVENT_RESIZED:
            get_screen_info(_window);
            break;
    }

    return 0;
}

int main() {
    // sdl init code for a vulkan window...
    
    SDL_AddEventWatch(app_event_watcher, window);
    
    // sdl event loop code...
}

```

**Comment by icculus** [comment] 2022-11-09 20:05
This reproduces for me on 2.0.22 and 2.0.20 (and maybe further back), so it isn't new in 2.24.0.

My updated testvulkan patch:

```diff
diff --git a/test/testvulkan.c b/test/testvulkan.c
index 4b65179c1..0aa9b27fd 100644
--- a/test/testvulkan.c
+++ b/test/testvulkan.c
@@ -987,6 +987,38 @@ static void shutdownVulkan(SDL_bool doDestroySwapchain)
     SDL_Vulkan_UnloadLibrary();
 }

+
+static int get_screen_info(SDL_Window *window) {
+    int _window_width = 0, _window_height = 0;
+    SDL_GetWindowSize(window, &_window_width, &_window_height);
+
+    int _screen_width = 0, _screen_height = 0;
+    SDL_Vulkan_GetDrawableSize(window, &_screen_width, &_screen_height);
+
+    if ((float)_window_width / (float)_screen_width !=
+        (float)_window_height / (float)_screen_height) {
+        // this means SDL_Vulkan_GetDrawableSize is out of sync
+printf("OUT OF SYNC: window %dx%d vs vulkan %dx%d\n", _window_width, _window_height, _screen_width, _screen_height);
+        return 0;
+    }
+    return 1;
+}
+
+static int app_event_watcher(void *data, SDL_Event *event) {
+    if (event->type != SDL_WINDOWEVENT) return 0;
+    SDL_Window *_window = SDL_GetWindowFromID(event->window.windowID);
+    if (_window != (SDL_Window *)data) return 0;
+
+    switch (event->window.event) {
+        case SDL_WINDOWEVENT_SIZE_CHANGED:
+        case SDL_WINDOWEVENT_RESIZED:
+            get_screen_info(_window);
+            break;
+    }
+
+    return 0;
+}
+
 static SDL_bool render(void)
 {
     uint32_t frameIndex;
@@ -1100,6 +1132,8 @@ int main(int argc, char **argv)
         return 1;
     }

+    SDL_AddEventWatch(app_event_watcher, state->windows[0]);
+
     SDL_GetCurrentDisplayMode(0, &mode);
     SDL_Log("Screen BPP    : %" SDL_PRIu32 "\n", SDL_BITSPERPIXEL(mode.format));
     SDL_GetWindowSize(state->windows[0], &dw, &dh);
```

**Comment by icculus** [comment] 2022-11-09 20:28
I'm inclined to say that testing the drawable size inside an event watcher is not a good idea, even if we don't have explicit documentation saying that it isn't.

**Comment by icculus** [comment] 2022-11-12 01:02
SDL_PollEvent, run in a loop until it returns zero, once per frame, is the more common way to do this.

You'll need to even if you don't do anything with the events at this point, because the event queue will keep filling if you only use an event watcher.

By the time the event queue is being polled in that loop, system-managed things like the size of drawables will have settled down.

**Comment by icculus** [comment] 2022-11-15 18:13
I'm closing this, as this works correctly outside of an event watcher.

**Closed by icculus** 2022-11-15 18:13 UTC
