### ISSUE TITLE
OpenBSD X11 window titles

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#4979] opened 2021-11-18 23:48 UTC
According to https://twitter.com/morgant/status/1461402997351759874 we broke window titles on OpenBSD when we patched #4290.

**Comment by sezero** [comment] 2021-11-18 23:55
Also see https://github.com/libsdl-org/SDL/issues/4924#issuecomment-973147103

**Comment by sezero** [comment] 2021-11-26 18:32
What happened to this one?

**Comment by icculus** [comment] 2021-11-28 04:16
I don't think the patch arrived.

**Comment by morgant** [comment] 2021-11-28 21:41
This _should_ be resolved by PR #5029, but I have run out of time to test today.

**Comment by ctrlcctrlv** [comment] 2021-11-28 21:56
yeah i just went ahead and patched it since i broke it…and since i realized i have the most experience with arcane text encodings of anyone available at a moment's notice, so knew to watch out for foreign locales, ISO 2022 issues with COMPOUND_TEXT, etc. there's a reason my original patch tried hard to avoid setting `WM_NAME`—doing it right is hard, and SDL was never doing it right (actual X11 COMPOUND_TEXT implementation via XStdICCTextStyle)

i'd encourage anyone interested to read this interesting code comment in Xlib, file `src/xlibi18n/lcUTF8.c`:

```c
/*
 * This file contains:
 *
 * I. Conversion routines CompoundText/CharSet <--> Unicode/UTF-8.
 *
 *    Used for three purposes:
 *      1. The UTF-8 locales, see below.
 *      2. Unicode aware applications for which the use of 8-bit character
 *         sets is an anachronism.
 *      3. For conversion from keysym to locale encoding.
 *
 * II. Conversion files for an UTF-8 locale loader.
 *     Supports: all locales with codeset UTF-8.
 *     How: Provides converters for UTF-8.
 *     Platforms: all systems.
 *
 * The loader itself is located in lcUTF8.c.
 */

/*
 * The conversion from UTF-8 to CompoundText is realized in a very
 * conservative way. Recall that CompoundText data is used for inter-client
 * communication purposes. We distinguish three classes of clients:
 * - Clients which accept only those pieces of CompoundText which belong to
 *   the character set understood by the current locale.
 *   (Example: clients which are linked to an older X11 library.)
 * - Clients which accept CompoundText with multiple character sets and parse
 *   it themselves.
 *   (Example: emacs, xemacs.)
 * - Clients which rely entirely on the X{mb,wc}TextPropertyToTextList
 *   functions for the conversion of CompoundText to their current locale's
 *   multi-byte/wide-character format.
 * For best interoperation, the UTF-8 to CompoundText conversion proceeds as
 * follows. For every character, it first tests whether the character is
 * representable in the current locale's original (non-UTF-8) character set.
 * If not, it goes through the list of predefined character sets for
 * CompoundText and tests if the character is representable in that character
 * set. If so, it encodes the character using its code within that character
 * set. If not, it uses an UTF-8-in-CompoundText encapsulation. Since
 * clients of the first and second kind ignore such encapsulated text,
 * this encapsulation is kept to a minimum and terminated as early as possible.
 *
 * In a distant future, when clients of the first and second kind will have
 * disappeared, we will be able to stuff UTF-8 data directly in CompoundText
 * without first going through the list of predefined character sets.
 */
```

this stuff is very complicated, and it's something of a tragedy that it's 2021 and we're still talking about CompoundText as an encoding that's a going concern, but who knows, maybe next decade it'll finally die :crossed_fingers:

**Comment by ctrlcctrlv** [comment] 2021-11-28 21:57
by the way the words “UTF-8-in-CompoundText encapsulation” are indeed what nightmares are made of

**Comment by slouken** [comment] 2021-11-28 22:15
Is anyone able to test @ctrlcctrlv's PR against OpenBSD fvwm?

**Comment by slouken** [comment] 2021-11-29 05:01
This should be fixed in the latest code, can you confirm?

**Comment by slouken** [comment] 2021-11-29 05:30
I confirmed that this works with KDE, using testsprite --title "foo" and testmessage.

**Comment by slouken** [comment] 2021-11-29 17:18
I confirmed this works when X_HAVE_UTF8_STRING is disabled. I'm going to go ahead and close this bug, please let us know if there's still a case that doesn't work!

**Closed by slouken** 2021-11-29 17:18 UTC
