### ISSUE TITLE
Add paddle mappings for Xbox One Elite 2 Controller

### ISSUE THREAD

**Issue by jre21** [libsdl-org/SDL#7211] opened 2023-02-01 05:41 UTC
Linux >= 6.1 detects Xbox One Elite controllers' paddles when the controller's firmware isn't mapping them to other button events, and I would like for these to be supported in the gamepad db.  I collected the following mapping on Arch Linux using the controllermap.c script from SDL 2.26.2 with Linux kernel 6.1.7-zen1:

`030000005e040000000b00000f050000,Xbox One Elite 2 Controller,platform:Linux,crc:085d,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b8,start:b7,leftstick:b9,rightstick:b10,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,paddle1:b13,paddle2:b11,paddle3:b14,paddle4:b12,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,`

**Comment by slouken** [comment] 2023-11-08 02:19
This is fixed in the latest SDL release.

**Closed by slouken** 2023-11-08 02:19 UTC

**Comment by pvtri96** [comment] 2023-12-07 15:26
Hi, the issue isn't fixed with SDL 2.28.5 as the integration via an AntimicroX build [here](https://github.com/AntiMicroX/antimicrox/issues/685). Do I need to file another issue or reopen this one?

**Comment by slouken** [comment] 2023-12-07 15:47
Please enter a new issue and include your OS information and what GUID is used in addition to the mapping string.

Thanks!
