### ISSUE TITLE
Playstation 5 Controller not listed as haptic enabled device.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3936] opened 2021-02-11 02:13 UTC
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.14
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2020-12-22 04:05:32 +0000,  wrote:

> The PS5 Controller is not found as a haptic supported device when using the "testrumble" SDL test application.
> 
> Additionally, when using the haptic subsystem to open a haptic device with the PS5 controller, the Haptic device created appears to be NULL, however controller haptic works using the Gamepad API "SDL_GameControllerRumble" function. This impacts haptic support for older applications that use the haptic api for controller haptics, where replacing the DLL doesn't bring the functionality (unlike previous versions).

On 2021-01-15 13:14:51 +0000, Dimitriy Ryazantcev wrote:

> You can use https://wiki.libsdl.org/CategoryGameController API and its SDL_GameControllerRumble() for PS4/PS5 controllers

**Comment by undersquire** [comment] 2021-08-29 19:35
Is there any news on a fix or workaround for this?

**Comment by meyraud705** [comment] 2021-08-30 18:28
> Is there any news on a fix or workaround for this?

Use SDL_GameControllerRumble, see this comment: https://github.com/libsdl-org/SDL/issues/4435#issuecomment-896432954

**Comment by slouken** [comment] 2021-08-30 18:46
Duplicate of #4435

**Closed by slouken** 2021-08-30 18:46 UTC
Labels: bug

**Comment by undersquire** [comment] 2021-08-30 22:00
So is SDL_gamecontroller ultimately replacing SDL_joystick? I see that SDL_gamecontroller supports a lot of similar features to SDL_joystick, so I am wondering when to use one over the other.

**Comment by slouken** [comment] 2021-08-31 17:07
No, SDL_gamecontroller is basically a gamepad oriented layer on top of SDL_joystick. If you want gamepad control in your game, you should use that. If you want to support arbitrary joysticks, flightsticks, wheels, etc, then you should use SDL_joystick.

**Comment by undersquire** [comment] 2021-08-31 23:21
Also is there any documentation for SDL_GameControllerRumble? I cannot find any on the official libsdl website.

**Comment by slouken** [comment] 2021-09-01 03:39
Here you go:
https://wiki.libsdl.org/SDL_GameControllerRumble
