### ISSUE TITLE
SDL_CopyPath file system API

### ISSUE THREAD

**Issue by luppichristian** [libsdl-org/SDL#10054] opened 2024-06-18 23:51 UTC
In the file system API having this functionality would be useful:
extern SDL_DECLSPEC int SDLCALL SDL_CopyPath(const char *srcpath, const char *dstpath);

**Comment by icculus** [comment] 2024-06-19 02:19
Duplicate of #9553.

**Closed** 2024-06-19 02:19 UTC
