### ISSUE TITLE
android SDL_RenderSetClipRect BUG

### ISSUE THREAD

**Issue by baidwwy** [libsdl-org/SDL#5188] opened 2022-01-06 20:26 UTC
```cpp

#include "SDL.h"


int main(int argc, char** argv)
{
    if (SDL_Init(SDL_INIT_VIDEO) == -1) {
        fprintf(stderr, "SDL_Init failed: %s\n", SDL_GetError());
        return 1;
    }

    const int winw = 1280;
    const int winh = 720;
    SDL_Window* window = SDL_CreateWindow("Hello SDL", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, winw, winh, 0);
    if (!window) {
        fprintf(stderr, "SDL_CreateWindow failed: %s\n", SDL_GetError());
        SDL_Quit();
        return 1;
    }
    //SDL_SetHint("SDL_RENDER_DRIVER", "opengles2"); //If define this, the BUG disappears
    //BUG only exists in opengles2
    SDL_Renderer* renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_PRESENTVSYNC);
    if (!renderer) {
        renderer = SDL_CreateRenderer(window, -1, 0);
    }
    SDL_RenderSetLogicalSize(renderer,640,480) //it is necessary

    while (keep_going) {
        SDL_Event e;
        while (SDL_PollEvent(&e)) {

        }

        
        SDL_SetRenderDrawColor(renderer, 0x70, 0x70, 0x70, 255);
        SDL_RenderClear(renderer);
        SDL_SetRenderDrawColor(renderer, 255, 0, 0, 255);
        SDL_Rect  rect = {10,10,50,50};
        SDL_RenderFillRect(renderer,rect);
        SDL_Rect  crect = {100, 100, 200, 200};
        SDL_RenderSetClipRect(renderer,crect);//it is necessary
            SDL_SetRenderDrawColor(renderer, 255, 0, 0, 255);
            SDL_Rect  drawrect = {100, 100, 50, 50};
            SDL_RenderDrawRect(renderer,drawrect);//it is necessary
            SDL_Rect  fillrect = {100, 100, 0, 0};//it is necessary  w,h = 0
            SDL_RenderFillRect(renderer,fillrect);//it is necessary
        SDL_RenderSetClipRect(renderer)
        SDL_RenderPresent(renderer);
    }

    SDL_Quit();
    return 0;
}
```
expect
![QQ拼音截图未命名](https://user-images.githubusercontent.com/6239458/148446887-258947ae-ec3e-4247-957c-6f6b6b29f0d0.png)

BUG empty
![2](https://user-images.githubusercontent.com/6239458/148446962-4c07a5af-24cf-4890-afa3-b26e1a9e1ee8.png)

**Comment by slouken** [comment] 2022-01-06 20:31
@icculus, can you look at this? I don't imagine it's specific to Android.

**Comment by icculus** [comment] 2022-01-06 22:44
I haven't looked at this yet, but some recent change broke line drawing for GLES2. I'll look at that tonight.

**Comment by 1bsyl** [comment] 2022-01-07 08:52
The test case isn't compiling so I've updated.
I've run it on the android emulator, and this seems fine to me.
Also run it on linux and it's ok.

@baidwwy can you give more precision and double-check ? 

```
#include "SDL.h"


int main(int argc, char** argv)
{
    if (SDL_Init(SDL_INIT_VIDEO) == -1) {
        fprintf(stderr, "SDL_Init failed: %s\n", SDL_GetError());
        return 1;
    }

    const int winw = 1280;
    const int winh = 720;
    SDL_Window* window = SDL_CreateWindow("Hello SDL", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, winw, winh, 0);
    if (!window) {
        fprintf(stderr, "SDL_CreateWindow failed: %s\n", SDL_GetError());
        SDL_Quit();
        return 1;
    }
   
 //   SDL_SetHint(SDL_HINT_RENDER_BATCHING, "1");
 //   SDL_SetHint("SDL_RENDER_DRIVER", "opengles2"); //If define this, the BUG disappears
//    SDL_SetHint("SDL_RENDER_DRIVER", "software"); //If define this, the BUG disappears
    //BUG only exists in opengles2
    SDL_Renderer* renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_PRESENTVSYNC);
    if (!renderer) {
        renderer = SDL_CreateRenderer(window, -1, 0);
    }
    SDL_RenderSetLogicalSize(renderer,640,480); //it is necessary

    int quit = 1;
    while (quit) {
        SDL_Event evt;
        while (SDL_PollEvent(&evt)) {
            switch (evt.type)
            {
                case SDL_KEYDOWN:
                    {
                        const int sym = evt.key.keysym.sym;
                        if (sym == SDLK_SPACE) {
                            SDL_Log("Key : Space!");
                        }
                        if (sym == SDLK_ESCAPE || sym == SDLK_AC_BACK) {
                            quit = 0;
                            SDL_Log("Key : Escape!");
                        }
                    }
                    break;
                case SDL_QUIT:
                    {
                        quit = 0;
                        SDL_Log("Ctlr+C : Quit!");
                    }
                    break;

            }
 
        }

        
        SDL_SetRenderDrawColor(renderer, 0x70, 0x70, 0x70, 255);
        SDL_RenderClear(renderer);
        SDL_SetRenderDrawColor(renderer, 255, 0, 0, 255);
        SDL_Rect  rect = {10,10,50,50};
        SDL_RenderFillRect(renderer, &rect);
        SDL_Rect  crect = {100, 100, 200, 200};
        SDL_RenderSetClipRect(renderer, &crect);//it is necessary
            SDL_SetRenderDrawColor(renderer, 255, 0, 0, 255);
            SDL_Rect  drawrect = {100, 100, 50, 50};
            SDL_RenderDrawRect(renderer, &drawrect);//it is necessary
            SDL_Rect  fillrect = {100, 100, 0, 0};//it is necessary  w,h = 0
            SDL_RenderFillRect(renderer, &fillrect);//it is necessary
        SDL_RenderSetClipRect(renderer, NULL);
        SDL_RenderPresent(renderer);
    }

    SDL_Quit();
    return 0;
}
```

**Comment by baidwwy** [comment] 2022-01-07 12:30
@1bsyl 
Replenish
emulator size Must be >LogicalSize

And my SDL version is 2.0.18
I sync to git, try again

**Comment by 1bsyl** [comment] 2022-01-07 14:20
If you manually resize the emulator, you can indeed make one or two line disappear. but that a limitation of the emulator.
But you cannot make the filled area disappear.

**Comment by icculus** [comment] 2022-01-07 19:39
> I haven't looked at this yet, but some recent change broke line drawing for GLES2.

This was actually a bug in drawing points, disregard my comment for this issue.

If @1bsyl says this is not a bug, we can close this.

**Comment by baidwwy** [comment] 2022-01-08 01:13
i missed SDL_WINDOW_FULLSCREEN
or test this
https://github.com/baidwwy/SDL2TEST

**Comment by baidwwy** [comment] 2022-01-08 01:18
@1bsyl 
version https://github.com/libsdl-org/SDL/commit/4b38d4c96b03b6e1e845ee2a0338d78aca652f5a

**Comment by icculus** [comment] 2022-01-08 01:42
Updated test program that compiles:

```c
#include "SDL.h"

int main(int argc, char** argv)
{
    int keep_going = 1;
    if (SDL_Init(SDL_INIT_VIDEO) == -1) {
        fprintf(stderr, "SDL_Init failed: %s\n", SDL_GetError());
        return 1;
    }

    const int winw = 1280;
    const int winh = 720;
    SDL_Window* window = SDL_CreateWindow("Hello SDL", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, winw, winh, SDL_WINDOW_RESIZABLE);
    if (!window) {
        fprintf(stderr, "SDL_CreateWindow failed: %s\n", SDL_GetError());
        SDL_Quit();
        return 1;
    }
    //SDL_SetHint("SDL_RENDER_DRIVER", "opengles2"); //If define this, the BUG disappears
    //BUG only exists in opengles2
    SDL_Renderer* renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_PRESENTVSYNC);
    if (!renderer) {
        renderer = SDL_CreateRenderer(window, -1, 0);
    }
    SDL_RenderSetLogicalSize(renderer,640,480);  //it is necessary

    while (keep_going) {
        SDL_Event e;
        while (SDL_PollEvent(&e)) {
            if (e.type == SDL_QUIT) {
                keep_going = 0;
            }
        }

        SDL_SetRenderDrawColor(renderer, 0x70, 0x70, 0x70, 255);
        SDL_RenderClear(renderer);
        SDL_SetRenderDrawColor(renderer, 255, 0, 0, 255);
        SDL_Rect  rect = {10,10,50,50};
        SDL_RenderFillRect(renderer,&rect);
        SDL_Rect  crect = {100, 100, 200, 200};
        SDL_RenderSetClipRect(renderer,&crect);//it is necessary
            SDL_SetRenderDrawColor(renderer, 255, 0, 0, 255);
            SDL_Rect  drawrect = {100, 100, 50, 50};
            SDL_RenderDrawRect(renderer, &drawrect);//it is necessary
            SDL_Rect  fillrect = {100, 100, 0, 0};//it is necessary  w,h = 0
            SDL_RenderFillRect(renderer,&fillrect);//it is necessary
        SDL_RenderSetClipRect(renderer, NULL);
        SDL_RenderPresent(renderer);
    }

    SDL_Quit();
    return 0;
}
```

**Comment by icculus** [comment] 2022-01-08 01:49
So this works for me on Linux, with the opengles2 renderer, but it's worth noting that you _can_ make the lines disappear on any renderer by resizing the window in some unfortunate way:

![2022-01-07_20-40](https://user-images.githubusercontent.com/673562/148626644-be8afaec-544b-4605-9a0a-76c1bf47aeeb.png)

Because sometimes logical scaling eats an entire row or column of pixels, and it can eat an entire rectangle this way, too.

I'm definitely not seeing the missing filled rectangle in any case, so it's not a GLES2 renderer issue. Could be an Android-specific issue or the emulator.

**Comment by baidwwy** [comment] 2022-01-08 02:02
I tested it on my phone, the problem doesn't exist, my fault，sorry

**Comment by slouken** [comment] 2022-01-08 02:12
Okay, thanks for letting us know!

**Closed by slouken** 2022-01-08 02:12 UTC
Labels: invalid
