### ISSUE TITLE
Xbox series X controller share button not working

### ISSUE THREAD

**Issue by RT2Code** [libsdl-org/SDL#7098] opened 2023-01-16 16:26 UTC
I own a Xbox series X controller and when I press the share button, I get no SDL_CONTROLLERBUTTON events. I get the SDL_JOYBUTTON events though, so I added an entry to the gamecontrollerdb.txt with my controller GUID and the share button mapped to misc1, and it fixed the problem.

I made a PR to submit this change to the game controller database repository, but it was closed because my controller is an XInput device, and apparently it should be handled by the SDL's driver directly and should require no manual mapping : https://github.com/gabomdq/SDL_GameControllerDB/pull/655

My controller is standard Xbox series X controller, its GUID is 0300509d5e040000120b000000007200, and when I press the share button the code I get from the SDL_JOYBUTTON event is 11.

**Comment by slouken** [comment] 2023-11-08 01:36
Duplicate of https://github.com/libsdl-org/SDL/issues/4222

**Closed by slouken** 2023-11-08 01:36 UTC
