### ISSUE TITLE
Why got the Github Wiki removed?

### ISSUE THREAD

**Issue by Axilot** [libsdl-org/SDL#4153] opened 2021-03-06 11:56 UTC
I am just wondering why the SDL wiki got removed out of this Github repository. Have i missed something?

**Comment by icculus** [comment] 2021-03-06 14:55
We're working on improving it. I wrote something to make it work more like we wanted ( http://GitHub.com/icculus/ghwikipp ) and have the wiki up and running (and in need of editing!) at https://testwiki.libsdl.org/

This will move to a more permanent URL when things stabilize.

**Comment by Axilot** [comment] 2021-03-06 20:28
Oh nice, thanks.

**Comment by peppy** [comment] 2021-03-10 02:37
As a heads up, now that the old wiki has been removed a lot of links lead to nowhere ([example](https://github.com/libsdl-org/SDL/blob/main/INSTALL.txt)).

**Comment by madscientist42** [comment] 2021-03-15 17:10
Heh...  It makes it all but impossible to use the "documentation" right now...

**Comment by icculus** [comment] 2021-03-15 18:51
> now that the old wiki has been removed a lot of links lead to nowhere

We'll revert the change that pointed all these to the now-gone GitHub wiki soon. https://wiki.libsdl.org/ still exists as it always did, so I'm sure we can all work from something other than the README files for a little longer while we finish building out the new fancy wiki tech, which is taking a few days longer than I had hoped.

**Comment by madscientist42** [comment] 2021-03-16 18:44
Heh.  I'm back dealing with SDL2 after years of not doing any gamedev/porting.  (Work's using it for media playback)- so I'm trying to figure out how to drive the EGL stuff, Ryan.  Are we expecting the info/intel on that part of things with the new Wiki soon?

**Comment by icculus** [comment] 2021-03-16 19:48
> how to drive the EGL stuff

We'll take this [discussion elsewhere](https://discourse.libsdl.org/) if necessary, but in case this just knocks out your question right now, here you go:

If you specifically want OpenGL ES, you just ask for a GLES context:

```c
SDL_Init(SDL_INIT_VIDEO);  // check things for errors in real life, though.  :)
SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);  // GLES2, if you want GLES3, use 3.
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);
SDL_Window *window = SDL_CreateWindow("Hello world", 100, 100, 100, 100, SDL_WINDOW_OPENGL);
SDL_GLContext *glctx = SDL_GL_CreateContext(window);  // this makes the context current, too.

// Optionally, use SDL_GL_GetProcAddress() to lookup entry points.

while (still_running) {
    // Draw stuff using OpenGL ES here, etc.
    SDL_GL_SwapWindow(window);  // done with the frame, put it on the screen.
    // etc.
}
```

Behind the scenes, SDL might use EGL if that's the appropriate way to get this going (on an embedded device or whatnot), but it might use glX, for example, if we're talking to an X server and it reports it can provide a GLES context.

There _is_ an EGL mention in the list of things that SDL_GL_SetAttribute will take, but that's a legacy thing from before we had more-proper GLES support.

**Comment by madscientist42** [comment] 2021-03-19 01:01
Well, Ryan, it doesn't help- the problem is that I had a junior engineer go and use your stuff and then I pulled a trick out of the hat to solve a problem and SDL's doing nasty, nasty things to us.  I need to support EGL in that manner, but with a provided WID as we're "sharing" a window and GLX contexts for a specific problem I'm side-stepping.

We probably ought to move this to another ticket or a discussion list.  :D

**Comment by icculus** [comment] 2021-03-19 14:34
@madscientist42 Drop me an email and we'll try to figure out what to do.

**Comment by icculus** [comment] 2021-03-20 02:07
Oh, I see you moved over here, even better: https://discourse.libsdl.org/t/revisiting-the-opengl-override-for-foreign-windows-discussion/30946

The "the wiki is a mess" bug is over at https://github.com/libsdl-org/SDL/issues/4064, so I'm going to close this one.

**Closed by icculus** 2021-03-20 02:07 UTC
