### ISSUE TITLE
Support consuming SDL via C++20 modules.

### ISSUE THREAD

**Issue by Zopolis4** [libsdl-org/SDL#5957] opened 2022-07-25 04:06 UTC
I'm working on a project written using C++20 modules, but I have to use global module fragments in order to `#include "SDL.h"`. Being able to simply use `import SDL;` would be more convenient and would allow me to benefit from the increased compilation speed and smaller file size from using modules.

**Comment by madebr** [comment] 2022-07-25 11:35
This is a duplicate of #5499.
Please re-open if you think it's not.

**Comment by Zopolis4** [comment] 2022-07-25 11:37
#5499 is about clang's personal implementation of modules for C, whereas this is relating to the C++20 modules standard.

**Comment by Zopolis4** [comment] 2022-07-25 11:37
I don't have the permissions to reopen.

**Comment by madebr** [comment] 2022-07-25 16:50
Using c++ modules is implementation dependent: clang, gcc and MSVC have a different implementation.
This requires support by the build tools, [which CMake does not have yet](https://gitlab.kitware.com/cmake/cmake/-/issues/18355).
Also, there is [currently no standard way to distribute c++ modules](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2473r1.pdf).

Nonetheless, this should not stop anyone from consuming SDL as a c++20 module today already.
You just need to create the interface yourself.
e.g. the following works with gcc 12.1 on Linux
```
#/bin/sh

set -e

cat >mygame.cpp <<EOF
import "SDL.h";

int main(int argc, char* args[]) {
    SDL_version compiled;
    SDL_version linked;

    SDL_VERSION(&compiled);
    SDL_GetVersion(&linked);
    SDL_Log("Compiled against SDL %u.%u.%u.\n",
            compiled.major, compiled.minor, compiled.patch);
    SDL_Log("  Linked against SDL %u.%u.%u.\n",
            linked.major, linked.minor, linked.patch);

    if (SDL_Init(SDL_INIT_VIDEO) < 0) {
        SDL_Log("could not initialize sdl2: %s\n", SDL_GetError());
        return 1;
    }
    SDL_Quit();
    return 0;
}
EOF

# Exclude SDL_cpuinfo.h from the CMI because gcc has issues with mmintrin.h, xmmintrin.h, emmintrin.h and pmmintrin.h

g++ -std=c++20 -fmodules-ts -x c++-header -fdirectives-only /usr/include/SDL2/SDL.h -DSDL_cpuinfo_h_

g++ -std=c++20 -fmodules-ts mygame.cpp -I/usr/include/SDL2 -lSDL2 -o mygame
```

**Comment by GhostCore07** [comment] 2022-10-04 18:23
Attempting to import SDL.h is probably not the best idea in a lot of cases. Clearly it can be done in a roundabout way with GCC but I could not find a similar compiler flag for MSVC. The added complexity of "importing" macros (the whole thing modules are designed to prevent you from doing) when you need them does not make import/modules look good here. Luckily the committee gave us the global fragment for this very purpose, as inconvenient as it may be.

**Comment by Zopolis4** [comment] 2022-10-07 03:07
Precompiled header units aren't really the focus of modules. [Here's](https://learn.microsoft.com/en-us/cpp/build/walkthrough-header-units) how you do them with MSVC, anyways.

Also--
```
An important difference between a header unit and a header file is that a header unit isn't affected by macro definitions outside of the header unit. 
```

**Comment by GhostCore07** [comment] 2022-10-07 14:28
> Precompiled header units aren't really the focus of modules. [Here's](https://learn.microsoft.com/en-us/cpp/build/walkthrough-header-units) how you do them with MSVC, anyways.
> 
> Also--
> 
> ```
> An important difference between a header unit and a header file is that a header unit isn't affected by macro definitions outside of the header unit. 
> ```

Agreed it goes both ways though, only declarations and definitions can be imported/exported, for example `SDL_INIT_VIDEO`  is a macro that cannot be imported/exported:
`#define SDL_INIT_VIDEO          0x00000020u`
If, instead, it was enum then the enum could be exported, as an example:
`typedef enum
{
    SDL_FALSE = 0,
    SDL_TRUE = 1
} SDL_bool;`
certianly the reliance of macros within SDL is much deeper than that, only the devs would know how hard it would be to switch macros to enums, if it's possible or even worth it to do so.
Thus in my humble opinion SDL.h is not _fully_ compatible with modules. If you need `SDL_INIT_VIDEO,` you have to take "extra steps" after import SDL.h and even then it's platform dependent. In my case that means #include is the obvious choice and not some workaround that lets me use import. This is just my situation though, others might have different needs.

**Closed** 2024-03-03 20:40 UTC
