### ISSUE TITLE
SDL_SetClipboardText takes exactly 5 seconds the second time you use it.

### ISSUE THREAD

**Issue by menne386** [libsdl-org/SDL#7203] opened 2023-01-31 08:30 UTC
Hi!

Working on windows platform (VisualC) with SDL2-devel-2.26.2-VC.zip

When using SDL_SetClipboardText the 1st time, it takes 0.00 seconds to complete.
The second time i use the function it takes exactly 5.00 seconds to complete.
From that point onward, it will always take exactly 5.00 seconds to complete.

Code for reproducing:
````
//Time the calls using your favorite tooling:
   SDL_SetClipboardText("FUBAR1"); //Should take 0.00 
  SDL_SetClipboardText("FUBAR2"); //Takes 5.00????
```

**Comment by JJCUBER** [comment] 2023-01-31 11:20
Are either of the function calls returning a non-zero value?

**Comment by menne386** [comment] 2023-02-05 21:12
Just checked: return value is 0 in both cases and the text is present at the clipboard.

So works, but 5 seconds is a performance issue.

**Comment by slouken** [comment] 2023-02-05 21:42
I'm not reproducing that here, both calls take 0 seconds. Can you post a full minimal example that shows the problem?

**Comment by icculus** [comment] 2023-02-06 17:38
I'm going to reopen this, because this sounds like it's worth exploring a bit more. If it's trivial to fix to work on threads, we should do so (and if not, oh well, we'll close this again).

**Comment by slouken** [comment] 2023-02-06 17:40
I think this is because interacting with the clipboard involves the message pump, and isn't supported off the main thread on any platform.

**Closed by slouken** 2023-02-06 17:40 UTC

**Comment by menne386** [comment] 2023-02-06 21:33
You guys are awesome, thx for the fast replies! Keep up the good work!
