### ISSUE TITLE
AudioQueueObject C++ Exception on Mix_CloseAudio()

### ISSUE THREAD

**Issue by grimaldini** [libsdl-org/SDL#6229] opened 2022-09-06 03:58 UTC
The following minimal example, causes a C++ exception on `audioqueue_thread` when attempting to dispose the audio queue.

```
#include <SDL.h>
#include <SDL_mixer.h>

int main() {
    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_AUDIO) < 0) {
        printf("SDL could not initialize! SDL Error: %s\n", SDL_GetError());
        return EXIT_FAILURE;
    }
    if (Mix_OpenAudio(44100, MIX_DEFAULT_FORMAT, 2, 2048) < 0) {
        printf("SDL_mixer could not initialize! SDL_mixer Error: %s\n", Mix_GetError());
        return EXIT_FAILURE;
    }
    
    Mix_CloseAudio(); // fails here
    Mix_Quit();
    SDL_Quit();
    return EXIT_SUCCESS;
}
```

Output up to breakpoint: 
```
2022-09-05 20:54:28.881146-0700 test[67987:13892064] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x6000024e4ee0> F8BB1C28-BAE8-11D6-9C31-00039315CD46
2022-09-05 20:54:28.886536-0700 test[67987:13892064]  HALC_ProxyObjectMap::_CopyObjectByObjectID: failed to create the local object
2022-09-05 20:54:28.886568-0700 test[67987:13892064]  HALC_ShellDevice::RebuildControlList: couldn't find the control object
2022-09-05 20:54:28.940405-0700 test[67987:13892359] [aqme]        MEMixerChannel.cpp:1636  client <AudioQueueObject@0x14580e800; [0]; play> got error 2003332927 while sending format information
2022-09-05 20:54:29.073056-0700 test[67987:13892064] [aqme]        MEMixerChannel.cpp:1636  client <AudioQueueObject@0x14580e800; [0]; play> got error 2003332927 while sending format information
```

Make sure to enable "break on C++ exceptions". I'm able to repro this running it via VS code and/or Xcode.

**Comment by grimaldini** [comment] 2022-09-16 04:58
Here's the callstack
<img width="936" alt="Screen Shot 2022-09-15 at 9 56 16 PM" src="https://user-images.githubusercontent.com/653273/190559928-06e95c8b-da35-46ea-806e-2e6ab88e2884.png">

**Comment by icculus** [comment] 2022-09-16 13:23
I have to dig it up when I'm not on a phone, but I think we have a "core audio race condition during device close" bug open somewhere already.

**Comment by icculus** [comment] 2022-09-16 14:29
Yeah, this is a duplicate of #6159.

**Closed by icculus** 2022-09-16 14:29 UTC
