### ISSUE TITLE
Multi-display configuration lost after exiting fullscreen

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3989] opened 2021-02-11 02:17 UTC
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** don't know
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2021-01-16 12:04:51 +0000,  wrote:

> I am not sure about Component, guess it is Render.
> About version, I guess it repeats for range of versions, repeated on openMSX 0.12.0, which uses SDL 1.x, and also on SuperTux, which is found in SDL 2.x application list to check if the bug is version-specific.
> 
> The issue is when I go fullscreen and then back to windowed mode, my display configuration is lost. That's very annoying.
> 
> I have two display system, main is vertical, secondary is in horizontal position.
> After an application returns to windowed, display orientation is lost and system behaves as there is only one display, it mirrors the image to the both of them, and hence one of them is rotated, so the image also is.
> 
> This is annoying because leads always to repeat the configuration manually, and checking each application if it is SDL-based before switching is attention- and time-expensive too, so no way to effectively work around it.
> 
> 3 bugs I found with manual search and 7 bugs suggested in this form as Possible Duplicates sometimes sound similar, and may relate, but distinctly describe different things.

**Comment by slouken** [comment] 2023-11-07 02:33
Duplicate of https://github.com/libsdl-org/SDL/issues/4398

**Closed by slouken** 2023-11-07 02:33 UTC
