### ISSUE TITLE
Mouse jumps after warp if xinput matrix is set

### ISSUE THREAD

**Issue by Desour** [libsdl-org/SDL#6275] opened 2022-09-23 13:09 UTC
SDL version: 6812f1b5d7d1e75d26d52982d6e8a4865a5c14b3
I'm using X11 with xorg-server 21.1.4. Edit: And libxi 1.8.

(Can reproduce with two different pointing devices.)

### Summary

I'm using a mouse where I've set the xinput `Coordinate Transformation Matrix` property to something else than identity (or just translation) (i.e. scale or shear).
If I move this mouse, then use `SDL_SetRelativeMouseMode(SDL_FALSE)` or `SDL_WarpMouseGlobal(x,y)` (with `(x,y)!=(0,0)`) or `SDL_WarpMouseInWindow`, and then move this mouse again, the cursor jumps to some location on the screen (which seems to depend on the matrix, and on where the mouse was warped to).
(If I move a mouse with identity matrix directly before- or afterwards, I can't reproduce the issue.)

### Steps to reproduce

Find the name of your pointing device:
`$ xinput list`
And set the property `Coordinate Transformation Matrix`:
`$ xinput --set-prop '<insert name>' 'Coordinate Transformation Matrix' 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000`
(To reproduce, don't use identity.)

Example matrices:
* Scale by 1/3: `1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 3.000000`
* Scale by 0.3: `0.300000, 0.000000, 0.000000, 0.000000, 0.300000, 0.000000, 0.000000, 0.000000, 1.000000`
* Shear: `1.000000, 1.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000`
* Translate (no issue here): `1.000000, 0.000000, 1.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000`

Compile and execute this test program:
<details><summary>code</summary>

```c
#include <SDL2/SDL.h>
#include <unistd.h>
#include <stdio.h>

void print_error(const char *where)
{
	const char *errstr = SDL_GetError();
	if (errstr == NULL || errstr[0] == '\0')
		return;
	fprintf(stderr, "SDL Error after '%s': %s\n", where, errstr);
	SDL_ClearError();
}

int main()
{
	SDL_Init(SDL_INIT_VIDEO);
	print_error("SDL_INIT()");
	SDL_Window *window = SDL_CreateWindow("Mouse Warp Test", SDL_WINDOWPOS_UNDEFINED,
			SDL_WINDOWPOS_UNDEFINED, 400, 400, SDL_WINDOW_SHOWN);
	print_error("SDL_CreateWindow()");
	SDL_Renderer *renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED);
	print_error("SDL_CreateRenderer()");

	SDL_bool quit = SDL_FALSE;
	while (!quit) {
		SDL_Event event;
		while (SDL_PollEvent(&event)) {
			print_error("SDL_PollEvent()");
			switch (event.type) {
			case SDL_QUIT: {
				quit = SDL_TRUE;
				break;
			} case SDL_KEYDOWN: {
				switch (event.key.keysym.sym) {
				case SDLK_ESCAPE:
				case SDLK_q:
					quit = SDL_TRUE;
					break;
				case SDLK_f: {
					printf("f\n");
					SDL_WarpMouseInWindow(window, 0, 0);
					break;
				} case SDLK_v: {
					printf("v\n");
					SDL_WarpMouseInWindow(window, 100, 200);
					break;
				} case SDLK_g: {
					printf("g\n");
					SDL_WarpMouseGlobal(0, 0);
					break;
				} case SDLK_b: {
					printf("b\n");
					SDL_WarpMouseGlobal(100, 200);
					break;
				} case SDLK_r: {
					printf("r\n");
					SDL_SetRelativeMouseMode(!SDL_GetRelativeMouseMode());
					break;
				} case SDLK_c: {
					printf("c\n");
					static SDL_bool mouse_captured = SDL_FALSE;
					if (SDL_CaptureMouse(!mouse_captured) == 0)
						mouse_captured = !mouse_captured;
					else
						print_error("SDL_CaptureMouse");
					break;
				} default:
					break;
				}
				break;
			} case SDL_MOUSEMOTION: {
				int gx, gy;
				SDL_GetGlobalMouseState(&gx, &gy);
				printf("mousemotion: x=%d, y=%d, gx=%d, gy=%d, xrel=%d, yrel=%d\n",
						event.motion.x, event.motion.y, gx, gy, event.motion.xrel,
						event.motion.yrel);
				break;
			} default: {
				break;
			}}
		}
		SDL_RenderPresent(renderer);
		usleep(12000);
	}

	SDL_DestroyRenderer(renderer);
	SDL_DestroyWindow(window);
	SDL_Quit();
	print_error("quit");
	return 0;
}
```

</details>

Example:
Matrix is: `1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 3.000000`
Key input:

<details>

* c (in window; just to capture mouse)
* move mouse
* f
* move mouse
* v
* move mouse
* g
* move mouse
* b
* move mouse
* r
* move mouse
* r
* move mouse

</details>

Output:
<details>

```
mousemotion: x=52, y=73, gx=813, gy=436, xrel=0, yrel=0
c
mousemotion: x=52, y=74, gx=813, gy=437, xrel=0, yrel=1
mousemotion: x=52, y=75, gx=812, gy=440, xrel=0, yrel=1
mousemotion: x=51, y=76, gx=812, gy=440, xrel=-1, yrel=1
mousemotion: x=51, y=77, gx=812, gy=440, xrel=0, yrel=1
mousemotion: x=51, y=78, gx=812, gy=441, xrel=0, yrel=1
mousemotion: x=51, y=79, gx=812, gy=442, xrel=0, yrel=1
f
mousemotion: x=0, y=0, gx=761, gy=363, xrel=0, yrel=0
mousemotion: x=-509, y=-243, gx=252, gy=120, xrel=-509, yrel=-243
mousemotion: x=-510, y=-243, gx=251, gy=120, xrel=-1, yrel=0
mousemotion: x=-511, y=-243, gx=250, gy=120, xrel=-1, yrel=0
mousemotion: x=-512, y=-243, gx=248, gy=120, xrel=-1, yrel=0
mousemotion: x=-513, y=-243, gx=248, gy=120, xrel=-1, yrel=0
mousemotion: x=-514, y=-243, gx=247, gy=120, xrel=-1, yrel=0
v
mousemotion: x=100, y=200, gx=861, gy=563, xrel=0, yrel=0
mousemotion: x=-475, y=-176, gx=285, gy=187, xrel=-575, yrel=-376
mousemotion: x=-476, y=-176, gx=285, gy=187, xrel=-1, yrel=0
mousemotion: x=-476, y=-175, gx=285, gy=188, xrel=0, yrel=1
mousemotion: x=-476, y=-174, gx=285, gy=189, xrel=0, yrel=1
g
mousemotion: x=-761, y=-363, gx=0, gy=0, xrel=-285, yrel=-189
mousemotion: x=-761, y=-362, gx=0, gy=1, xrel=0, yrel=1
mousemotion: x=-761, y=-361, gx=0, gy=2, xrel=0, yrel=1
mousemotion: x=-761, y=-360, gx=0, gy=3, xrel=0, yrel=1
mousemotion: x=-761, y=-359, gx=0, gy=4, xrel=0, yrel=1
b
mousemotion: x=-661, y=-163, gx=100, gy=200, xrel=100, yrel=196
mousemotion: x=-729, y=-297, gx=36, gy=72, xrel=-68, yrel=-134
mousemotion: x=-728, y=-296, gx=36, gy=72, xrel=1, yrel=1
mousemotion: x=-728, y=-295, gx=36, gy=72, xrel=0, yrel=1
mousemotion: x=-727, y=-294, gx=36, gy=72, xrel=1, yrel=1
mousemotion: x=-726, y=-293, gx=36, gy=72, xrel=1, yrel=1
mousemotion: x=-725, y=-291, gx=40, gy=77, xrel=1, yrel=2
mousemotion: x=-725, y=-290, gx=40, gy=77, xrel=0, yrel=1
mousemotion: x=-723, y=-289, gx=40, gy=77, xrel=2, yrel=1
mousemotion: x=-723, y=-288, gx=40, gy=77, xrel=0, yrel=1
mousemotion: x=-722, y=-287, gx=40, gy=77, xrel=1, yrel=1
mousemotion: x=-722, y=-286, gx=40, gy=77, xrel=0, yrel=1
mousemotion: x=-721, y=-286, gx=40, gy=77, xrel=1, yrel=0
mousemotion: x=-721, y=-285, gx=42, gy=79, xrel=0, yrel=1
mousemotion: x=-720, y=-284, gx=42, gy=79, xrel=1, yrel=1
mousemotion: x=-719, y=-284, gx=42, gy=79, xrel=1, yrel=0
mousemotion: x=-719, y=-283, gx=44, gy=82, xrel=0, yrel=1
mousemotion: x=-719, y=-282, gx=44, gy=82, xrel=0, yrel=1
mousemotion: x=-718, y=-282, gx=44, gy=82, xrel=1, yrel=0
mousemotion: x=-718, y=-281, gx=44, gy=82, xrel=0, yrel=1
mousemotion: x=-717, y=-281, gx=44, gy=82, xrel=1, yrel=0
mousemotion: x=-717, y=-280, gx=44, gy=83, xrel=0, yrel=1
r
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=0
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=-1
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=-1
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=-1
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=-1
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=0
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=-1
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=0
mousemotion: x=0, y=0, gx=761, gy=363, xrel=0, yrel=-1
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=-1
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=-1
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=-1
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=-1
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=0
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=-1
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=0
mousemotion: x=0, y=0, gx=761, gy=363, xrel=0, yrel=-1
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=0
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=-1
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=0
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=-1
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=0
mousemotion: x=0, y=0, gx=761, gy=363, xrel=0, yrel=-1
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=0
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=0
mousemotion: x=0, y=0, gx=761, gy=363, xrel=0, yrel=-1
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=0
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=-1
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=0
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=-1
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=0
mousemotion: x=0, y=0, gx=761, gy=363, xrel=-1, yrel=-1
r
mousemotion: x=0, y=0, gx=761, gy=363, xrel=0, yrel=0
mousemotion: x=-509, y=-243, gx=252, gy=120, xrel=-509, yrel=-243
mousemotion: x=-510, y=-243, gx=251, gy=120, xrel=-1, yrel=0
mousemotion: x=-511, y=-243, gx=249, gy=119, xrel=-1, yrel=0
mousemotion: x=-511, y=-244, gx=249, gy=119, xrel=0, yrel=-1
mousemotion: x=-512, y=-244, gx=249, gy=119, xrel=-1, yrel=0
mousemotion: x=-513, y=-244, gx=248, gy=119, xrel=-1, yrel=0
mousemotion: x=-514, y=-244, gx=247, gy=119, xrel=-1, yrel=0
mousemotion: x=-515, y=-244, gx=246, gy=118, xrel=-1, yrel=0
mousemotion: x=-515, y=-245, gx=246, gy=118, xrel=0, yrel=-1
mousemotion: x=-516, y=-245, gx=245, gy=118, xrel=-1, yrel=0
```

</details>

The jumps can be seen in the 2nd mousemotion event after f, v, b or the 2nd r. (As you can see, the (absolute values of) xrel and yrel are very large.)

**Comment by ndren** [comment] 2022-10-11 19:21
If the issue is the same as the one fixed in Irrlicht (as described in https://github.com/minetest/irrlicht/pull/123), something similar to this should work:
```
diff --git a/src/video/x11/SDL_x11mouse.c b/src/video/x11/SDL_x11mouse.c
index 4fd8fa9..b71958c 100644
--- a/src/video/x11/SDL_x11mouse.c
+++ b/src/video/x11/SDL_x11mouse.c
@@ -315,7 +315,14 @@ WarpMouseInternal(Window xwindow, const int x, const int y)
 {
     SDL_VideoData *videodata = (SDL_VideoData *) SDL_GetVideoDevice()->driverdata;
     Display *display = videodata->display;
-    X11_XWarpPointer(display, None, xwindow, 0, 0, 0, 0, x, y);
+#if SDL_VIDEO_DRIVER_X11_XINPUT2
+    int deviceid = 0;
+    XIGetClientPointer(display, xwindow, &deviceid);
+    if (deviceid != 0)
+        X11_XIWarpPointer(display, deviceid, None, xwindow, 0, 0, 0, 0, x, y);
+    else
+#endif
+        X11_XWarpPointer(display, None, xwindow, 0, 0, 0, 0, x, y);
     X11_XSync(display, False);
     videodata->global_mouse_changed = SDL_TRUE;
 }
diff --git a/src/video/x11/SDL_x11sym.h b/src/video/x11/SDL_x11sym.h
index 1a1b102..d137b0f 100644
--- a/src/video/x11/SDL_x11sym.h
+++ b/src/video/x11/SDL_x11sym.h
@@ -270,6 +270,8 @@ SDL_X11_SYM(int,XIGrabTouchBegin,(Display *a,int b,Window c,int d,XIEventMask *e
 SDL_X11_SYM(int,XIUngrabTouchBegin, (Display *a,int b,Window c, int d,XIGrabModifiers *e),(a, b, c, d, e),return)
 SDL_X11_SYM(Status,XIQueryVersion,(Display *a,int *b,int *c),(a,b,c),return)
 SDL_X11_SYM(XIEventMask*,XIGetSelectedEvents,(Display *a,Window b,int *c),(a,b,c),return)
+SDL_X11_SYM(Bool,XIGetClientPointer,(Display *a,Window b,int *c),(a,b,c),return)
+SDL_X11_SYM(Bool,XIWarpPointer,(Display *a,int b,Window c,Window d,double e,double f,int g,int h,double i,double j),(a,b,c,d,e,f,g,h,i,j),return)
 #endif
 
 /* XRandR support */
```
Unfortunately I was not able to reproduce the issue, so @Desour could you try and see if WarpMouseInternal is where the issue stems from by trying out the patch above? Please note I have not tested the patch at all. (Maybe remove the #if and #endif I added to make sure it is compiling that section of code.)

**Comment by Desour** [comment] 2022-10-11 21:25
^ Works!
(I had to make some small changes to make it compile and make it not crash on global warp: <https://github.com/Desour/SDL/tree/fix_mouse_jump>)

((Btw. I'm not quite sure how different clients can have different pointer devices. The warp still works even if I've focused another window when the warp happens.))

**Comment by slouken** [comment] 2022-10-11 21:49
Great, can you make a PR with a single commit for merging?

**Comment by Desour** [comment] 2022-10-11 22:26
Done: #6382

@ndren I've added you as co-author. I hope this is fine with you.

**Closed** 2022-10-11 23:43 UTC

**Comment by ndren** [comment] 2022-10-12 16:38
@Desour Nice! I'm glad it worked out.
