### ISSUE TITLE
windows: tests leak display related memory

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#8189] opened 2023-09-01 22:40 UTC
Using https://github.com/libsdl-org/SDL/pull/8144, the tests leak a display related allocation.

```
> testviewport --trackmem
INFO: Current Viewport x=0 y=0 w=100 h=100
INFO: Current Viewport x=100 y=100 w=150 h=150
INFO: Current Viewport x=200 y=200 w=200 h=200
INFO: 0.97 frames per second
INFO: Memory allocations:
Allocation 0: 26 bytes
        0x7ff850a0a465: SDL_malloc_REAL+0x25
        0x7ff850b3aead: WIN_GetDisplayMode+0x5d
        0x7ff850b3b3c1: WIN_AddDisplay+0x91
        0x7ff850b3b8b3: WIN_AddDisplaysCallback+0xb3
        0x7ff8e2b589c8: SystemParametersInfoForDpi+0xc8
        0x7ff8e3890e94: KiUserCallbackDispatcher+0x24
        0x7ff8e1631984: NtUserEnumDisplayMonitors+0x14
        0x7ff850b3b909: WIN_AddDisplays+0x39
        0x7ff850b3a323: WIN_InitModes+0x13
        0x7ff850b40d4e: WIN_VideoInit+0x2e
        0x7ff850ad4bd7: SDL_VideoInit+0x357
        0x7ff8509073a7: SDL_InitSubSystem_REAL+0x157
        0x7ff85092fa72: SDL_InitSubSystem+0x12
        0x7ff6f6184b57: SDLTest_CommonInit+0x107
        0x7ff6f6181b93: SDL_main+0x103
        0x7ff850b242eb: SDL_RunApp_REAL+0x1bb
        0x7ff850938335: SDL_RunApp_DEFAULT+0x35
        0x7ff850931490: SDL_RunApp+0x30
        0x7ff6f6181e50: main+0x20
        0x7ff6f6190fa9: invoke_main+0x39
        0x7ff6f6190e4e: __scrt_common_main_seh+0x12e
        0x7ff6f6190d0e: __scrt_common_main+0xe
        0x7ff6f619103e: mainCRTStartup+0xe
        0x7ff8e33a7614: BaseThreadInitThunk+0x14
        0x7ff8e38426b1: RtlUserThreadStart+0x21
Total: 0.03 Kb in 1 allocations
```
(The stack frame is identical for other tests)

**Comment by slouken** [comment] 2023-11-08 08:49
I think this is a duplicate of https://github.com/libsdl-org/SDL/issues/7982, can you debug and see why WIN_AddDisplays() is getting called twice for the same monitor in your case?

**Comment by madebr** [comment] 2023-11-08 21:26
The first time, `WIN_AddDisplays` is called through `WIN_VideoInit` -> `WIN_InitModes`-> `WIN_AddDisplays` (see https://github.com/libsdl-org/SDL/issues/8189#issue-1878123151).
The second time, it is through `SDL_CreateWindowInternal` -> `WIN_RefreshDisplays` -> `WIN_AddDisplays`.


stack of the second call:
```
WIN_AddDisplays(SDL_VideoDevice *) SDL_windowsmodes.c:477
WIN_RefreshDisplays(SDL_VideoDevice *) SDL_windowsmodes.c:671
SDL_CreateWindowInternal(const char *, int, int, int, int, SDL_Window *, unsigned int) SDL_video.c:1847
SDL_CreateWindowWithPosition_REAL(const char *, int, int, int, int, unsigned int) SDL_video.c:2044
SDL_CreateWindowWithPosition(const char *, int, int, int, int, unsigned int) SDL_dynapi_procs.h:164
SDLTest_CommonInit(SDLTest_CommonState *) SDL_test_common.c:1372
SDL_main(int, char **) testviewport.c:188
SDL_RunApp_REAL(int, char **, int (*)(int, char **), void *) SDL_windows.c:425
SDL_RunApp_DEFAULT(int, char **, int (*)(int, char **), void *) SDL_dynapi_procs.h:614
SDL_RunApp(int, char **, int (*)(int, char **), void *) SDL_dynapi_procs.h:614
main(int, char **) SDL_main_impl.h:102
invoke_main() 0x00007ff6a30e11f9
__scrt_common_main_seh() 0x00007ff6a30e109e
__scrt_common_main() 0x00007ff6a30e0f5e
mainCRTStartup(void *) 0x00007ff6a30e128e
```

**Comment by slouken** [comment] 2023-11-08 22:18
Ah, that makes sense, thanks!

**Closed** 2023-11-08 22:28 UTC
