### ISSUE TITLE
SDL_AUDIODEVICEREMOVED should be triggered even if device is not in use.

### ISSUE THREAD

**Issue by HexmindGames** [libsdl-org/SDL#5199] opened 2022-01-08 02:24 UTC
From looking at the source code it is clear that the decision was made to send an SDL_AUDIODEVICEREMOVED event only if the device is actually in use.

However, I believe the event should be sent regardless whether or not the device is in use. It should not matter. A device has been removed and should therefore be reported.

Say a game builds a list of available audio devices for the player to select from. Then one of them is removed before the player makes a selection. The game has no way, other then constantly calling SDL_GetNumAudioDevice(), to tell one of the devices is no longer valid.

Furthermore, unplugging and plugging an unused audio device has the effect of adding an incremented number in parenthesis as if there was more than one of that device. Repeating that process will continuously increment that number.
 
I just think it would make more sense to send the event even if it's not in use, just as the event of a new audio device added is sent even if the device is not in use (even though that'd be hard to use a device that is yet to be added but you get the point).

Hope you agree,

Alain

**Comment by slouken** [comment] 2022-01-08 03:40
Yup, I agree.

**Comment by icculus** [comment] 2022-01-08 03:49
I'm not sure _why_ it was done like that. I'll look into why and fix this if there wasn't a good reason.

**Comment by icculus** [comment] 2022-01-10 18:55
> I'm not sure why it was done like that.

It was probably done like that because that's how we handle joystick hotplug, sort of: device adds tell you about new hardware coming in as a device index, disconnects tell you about a device _instance_.

The problem is audio devices don't have a device instance (device id) until they are opened, so this is complicated to fix without adding a new event.

**Comment by slouken** [comment] 2022-01-10 19:10
We might be able to assign a device ID at discovery, like we do for joysticks?

**Comment by icculus** [comment] 2022-01-10 19:48
mmm...maybe. There might be some complicated interactions with audio id 1 (which is reserved for the legacy SDL_OpenAudio() call) to think through. I'll pick through this and see what can be done for 2.0.22.

**Comment by icculus** [comment] 2022-07-22 03:04
As a workaround for SDL2: how about for unopened devices being removed, we just send the event with an AudioDeviceID of zero, which the app can use as a signal to refresh the device list...?

Since SDL_CloseAudio/SDL_CloseAudioDevice return void, it'd be harmless for apps that just respond to the event by closing the device (SDL will ignore a close of device 0).

**Comment by HexmindGames** [comment] 2022-07-22 23:53
Not sure if you're asking me or Sam. As far as I'm concerned though, that would solve the issue of not knowing when an unopened device is removed.

**Closed** 2022-07-26 16:44 UTC
Labels: early in milestone

**Comment by icculus** [comment] 2022-07-26 16:45
Okay, this change is in there; if you get an SDL_AUDIODEVICEREMOVED with a `which` field of zero, refresh the list of devices being shown to the user!

If it's not zero, it's a device you have opened, so you should close it, too. But it's safe to close a 0 device, too.

**Comment by HexmindGames** [comment] 2022-07-28 01:26
Thanks a lot Ryan!
