### ISSUE TITLE
iOS: real mouse device right click has a fingerId and a touchId

### ISSUE THREAD

**Issue by DominusExult** [libsdl-org/SDL#4482] opened 2021-06-30 19:39 UTC
A real mouse connected to an iPad via Bluetooth has a fingerId when you poll SDL_FINGERDOWN so it can't be (easily?) filtered out.

```
switch (event.type) {
case SDL_FINGERDOWN: {
	cout << "FINGER DOWN " << endl;
	cout << "MOUSE_TOUCHID " << SDL_TOUCH_MOUSEID << endl;
	cout << "TouchID: " << event.tfinger.touchId << endl;
	cout << "FingerID: " << event.tfinger.fingerId << endl;
	break;
}
....
}
```
finger touch:
```
FINGER DOWN 
MOUSE_TOUCHID 4294967295
TouchID: 1
FingerID: 5622091344
```

left click:
```
FINGER DOWN 
MOUSE_TOUCHID 4294967295
TouchID: -1
FingerID: 0
```

right click:
```
FINGER DOWN
MOUSE_TOUCHID 4294967295
TouchID: 1
FingerID: 5602579504
```

The fingerId of the finger touch always changes but the fingerId of the right click stays the same on every new click.

Also, curiously, when I left click it logs both the left and right click event. So it does look rather like this:
left click:
```
FINGER DOWN 
MOUSE_TOUCHID 4294967295
TouchID: -1
FingerID: 0
...app reports where you clicked...
FINGER DOWN
MOUSE_TOUCHID 4294967295
TouchID: 1
FingerID: 5602579504
```

**Comment by slime73** [comment] 2021-06-30 20:51
What's the reported touch device type (via `SDL_GetTouchDeviceType`) of the mouse? Maybe you can filter it out that way.

**Comment by DominusExult** [comment] 2021-06-30 21:07
I'm a bit at loss at what and how to pass SDL_TouchID to SDL_GetTouchDeviceType, I need to investigate...

But that the right click registers as touch is wrong, right?

**Comment by DominusExult** [comment] 2021-07-01 19:02
To grab SDL_GetTouchDeviceType I used the code from testgesture.c
```
int i;
for (i = 0; i < SDL_GetNumTouchDevices(); ++i) {
	const SDL_TouchID id = SDL_GetTouchDevice(i);
	SDL_Log("Fingers Down on device %" SDL_PRIs64": %d", id, SDL_GetNumTouchFingers(id));
}
```

But again I am getting the same result for the touch and right click:
```
INFO: Fingers Down on device -1: 0
INFO: Fingers Down on device 1: 1
```
The left click returns:
```
INFO: Fingers Down on device -1: 1
INFO: Fingers Down on device 1: 1
```
So something is not working correctly here.

**Comment by slime73** [comment] 2021-07-01 19:09
Just to confirm - what iOS version are you testing on, what Xcode / SDK version are you using, and are you using the latest SDL source? It looks like SDL's iOS backend got some mouse-related code in October 2020, and whether it's enabled depends on the Xcode and iOS versions being used.

**Comment by DominusExult** [comment] 2021-07-01 19:20
Al the latest and almost the latest git of SDL (ca383599b5c99). iOS 14.6, Xcode 12.51, not setting a specific SDK -> latest, BUT deployment target is iOS 10 (which is already further than SDL2's default of deployment target 8)

**Comment by DominusExult** [comment] 2021-07-25 11:39
In our code we workaround this by saving the last fingerId (unless it's value is 0) and then compare the last one with a new fingerId. If it's not the same we assume it's a real finger and not a mouse click. This is of course not ideal because it is wrong for the first mouse click but that's negligible for now.
Ideally when this is fixed by SDL I *think* that mouse clicks should always have fingerId with the value 0.

**Comment by slouken** [comment] 2021-11-10 04:56
This is fixed by setting the key UIApplicationSupportsIndirectInputEvents to true in your Info.plist and using the latest SDL code as of https://github.com/libsdl-org/SDL/commit/27ce91446327c796a3a2dc477d893880d58f4a99.

By the way, thanks for the great bug reports, they really helped me improve the iOS mouse code. :)

**Closed by slouken** 2021-11-10 04:56 UTC

**Comment by DominusExult** [comment] 2021-11-10 17:38
Something else is now borked of which 27ce914 is the culprit.
In Exult we use a custom mouse pointer. You move your Avatar by holding down the left mouse button and moving the mouse in various directions. The further away from the Avatar the faster you move (and the mouse pointer changes shape as well).
This worked with the previous release of SDL2. Now the mouse location gets "locked down" *while* you press a button (left or right) and you can't move the mouse until you release the button.
Tested with 19c129fab and that still works.

My pleasure to help in any way I can. Due to Exult being so old but still running great on iOS with SDL2 we seem to stumble over a couple of edge cases :)

**Comment by slouken** [comment] 2021-11-10 17:51
Do you enable relative mode while the mouse is down?

**Comment by DominusExult** [comment] 2021-11-10 17:59
Uhm no. How do I do this?

**Comment by slouken** [comment] 2021-11-10 18:00
Never mind, not that you should, I was just wondering if you did. :)
I think I know what the problem is here, I'll take a look. Thanks!

**Comment by slouken** [comment] 2021-11-10 18:29
So I was unable to reproduce this. Can you try with the touch demo in Xcode-iOS/Demos/Demos.xcodeproj in the latest snapshot?
http://www.libsdl.org/tmp/SDL-2.0.zip

**Comment by slouken** [comment] 2021-11-10 18:30
Also, can you open a separate bug for this issue, so we can track it on the 2.0.18 milestone?

Thanks!

**Comment by DominusExult** [comment] 2021-11-10 21:28
opened a new issue at 4941
