### ISSUE TITLE
After a fullscreen toggle and returning to windowed mode, exiting causes a fullscreen close

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1331] opened 2021-02-10 23:27 UTC
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Fullscreen Toggle Code (ToggleCode.txt, text/plain, 2014-01-28 21:58:35 +0000, 405 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1542)

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2014-01-28 21:58:35 +0000,  wrote:

> Created attachment 1542
> Fullscreen Toggle Code
> 
> I noticed this when I implemented a fullscreen toggle to my game engine using the SDL_SetWindowFullscreen() function.
> 
> If you run SDL in windowed mode and exit the application everything goes fine, but if you toggle SDL_WINDOW_FULLSCREEN mode and then return to windowed mode and exit the application, the entire screen turns black as though it's exiting from a fullscreen context rather than a window before returning to the desktop.
> 
> The same thing happens even if you initialize the window as fullscreen then toggling back to window mode and exiting.
> 
> Additionally, if you exit while in fullscreen it seems to work fine but may be causing the same black screen resulting in the application taking longer to close but it's hard to tell.
> 
> This doesn't happen with SDL_WINDOW_FULLSCREEN_DESKTOP mode toggling.
> 
> -----
> 
> My OS is Windows 7 64bit and I am using an OpenGL 3.3 Core context.
> 
> Occurs in both the latest SDL 2.0.1 (stable) and Mercurial builds with Visual Studio 2012 express.
> 
> This also happens on both my NVIDIA Geforce 295 GTX and Geforce 780 TI graphics cards.
> 
> I've attached the code I use to perform the window / fullscreen toggle.

On 2014-01-29 05:02:24 +0000, Alex Szpakowski wrote:

> This bug is specific to Windows I think - I can't reproduce it in OS X, but someone else in Windows is having the same problem: https://bitbucket.org/rude/love/issue/835/ (LÖVE uses SDL 2.)

**Comment by icculus** [comment] 2021-08-11 00:20
Let's check the state of this for 2.0.18 and decide what to do next.

**Comment by AntTheAlchemist** [comment] 2021-11-11 04:48
I remember something like this happening a long time ago, then it didn't happen at some version later.
I just tested this on Win10 and couldn't reproduce.
It would be good to know what size the window was when this happened to the bug reporter. I tried several different window sizes. My vote is to assume it's fixed.

**Comment by icculus** [comment] 2021-11-15 05:20
Yeah, it's not reproducing here, either. Closing.

**Closed by icculus** 2021-11-15 05:20 UTC
Labels: bug
