### ISSUE TITLE
rpi video backend doesn't work with OpenGL on Raspberry Pi 4

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3678] opened 2021-02-11 01:57 UTC
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Initial fix for Raspberry Pi 4 (SDL-rpi4-support-RYAN1.diff, text/plain, 2020-05-09 06:57:47 +0000, 1843 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4335)

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Linux, ARM

# Comments on the original bug report:

On 2020-05-08 23:51:40 +0000, Ryan C. Gordon wrote:

> SDL works fine on a virtual terminal on a Raspberry Pi 3 and earlier, using SDL's "rpi" video backend, but it doesn't work on Raspberry Pi 4.
> 
> Running testsprite2 in this configuration produces:
> 
>     INFO: Couldn't create window: Could not initialize EGL
> 
> My basic understanding from reading RetroPie developer discussions is that the dispmanx API doesn't work on the RPi4, and you have to use kmsdrm instead.
> 
> SDL has a kmsdrm backend, too, but it currently produces this for testsprite2:
> 
>     INFO: Couldn't create window: Could not initialize OpenGL / GLES library
> 
> To be clear: SDL+X11 still works fine on the RPi4--accelerated GLX and all--but this affects things that want to use a Pi as a game console or kiosk thing without X11.
> 
> --ryan.

On 2020-05-09 06:57:47 +0000, Ryan C. Gordon wrote:

> Created attachment 4335
> Initial fix for Raspberry Pi 4
> 
> 
> This patch gets it running again, but it's not ready for revision control.
> 
> The basic idea is the KMSDRM target works, but it tries to default to desktop OpenGL, which causes SDL_GLES_LoadLibrary to fail, etc.
> 
> Setting the default to GLES2 lets it slide through far enough that desktop GL _will_ work, fwiw, but generally most things want GLES2 on the Raspberry Pi in any case, so this default makes sense regardless.
> 
> But this patch needs a better way to decide that it's running on a Raspberry Pi than "the rpi video driver is also built into this copy of SDL." This is trivial, I assume, but I don't know a good preprocessor check at the moment.
> 
> Further work after that: the 2D render API needs to default to GLES2 on this platform; GLES1 and desktop OpenGL will all work but they are slower, and right now SDL picks desktop OpenGL.
> 
> --ryan.

On 2020-05-11 16:16:26 +0000, Cameron Gutman wrote:

> I found that --enable-video-kmsdrm --disable-video-rpi results in working video on the Raspberry Pi 4 using KMSDRM, so that's what I've been using.
> 
> It was several months ago that I debugged this, but if I remember correctly, SDL_egl.c picks different GL libraries if SDL_VIDEO_DRIVER_RPI is specified at build.

On 2020-10-09 23:59:18 +0000, Sam Lantinga wrote:

> Manuel, is this something that you can look at?

On 2020-10-10 14:13:54 +0000, Manuel Alfayate Corchete wrote:

> @Sam Lantiga: Yes, but I believe dispmanx is more or less deprecated now, so maybe removing the specific Raspberry Pi support would be the easiest way to avoid this problem. All Pis should be using KMSDRM by now, not dispmanx anymore.
> What do you think?

**Comment by icculus** [comment] 2021-02-14 05:36
I think we fixed this in 2.0.14? Marking this as a 2.0.16 milestone to verify before the next release.

**Comment by cgutman** [comment] 2021-04-05 01:31
fwiw, I agree with @vanfanel that we ought to to encourage migration from the legacy dispmanx backend to the standard KMSDRM interface.

I think a good start would be to disable the RPi backend by default, and enable the KMSDRM backend by default. Right now the reverse is true, so SDL built against the Raspberry Pi libraries is going to use the old RPi backend.

**Comment by icculus** [comment] 2021-04-05 03:09
There are still reasonable Pi units out there that need dispmanx afaik. But we should definitely be _defaulting_ to KMSDRM and falling back to dispmanx on those units (which, I confess, I thought we were already doing).

**Comment by icculus** [comment] 2021-05-07 18:27
(alternately, we should be trying dispmanx first on the assumption that it will fail on more-modern devices and kmsdrm will pick up from there, if that's more appropriate. But either way, KMSDRM is definitely the way forward.)

**Comment by icculus** [comment] 2021-05-10 16:54
Okay, so this actually _doesn't_ work on the RPi4 right now. Segfault. Researching further, in case it's something dumb that I did.

**Comment by icculus** [comment] 2021-05-11 18:15
Turns out the Pi didn't have GLES or EGL libraries installed. I just had to `apt-get install` them.

I fixed the segfault when it tries to gracefully clean up after that happens: https://github.com/libsdl-org/SDL/commit/e1db4b82ecf4b2420840b7b31a666563b2656481

But once those libraries are in place, this works fine on a Raspberry Pi 4 with KMSDRM, GLES1, GLES2 and Software renderers.

**Comment by cgutman** [comment] 2021-05-11 18:32
Do we have another issue tracking enabling KMSDRM by default and falling back to dispmanx (or vice versa)?

**Comment by icculus** [comment] 2021-05-12 16:19
Actually, that's a good question. Why _is_ kmsdrm disabled by default? Was it an experimental thing that is stable now, or do we still need to block this at configure time?

**Comment by slouken** [comment] 2021-05-12 16:25
It used to be experimental, but dispmanx is now deprecated and DRM is the recommended path forward.

**Comment by icculus** [comment] 2021-05-12 17:26
Okay, I'm going to flip it on by default in configure (for everyone, not just the Pi), and make sure that modern Pis cleanly fail from dispmanx to kmsdrm. Will test on older and newer Pis and Rasbian installs, then we'll consider this resolved.

**Comment by icculus** [comment] 2021-06-10 01:27
KMSDRM is enabled by default in the configure script as of 642fa0e3cf1b6a4b999a787d373e4a3a519bceca.

**Comment by icculus** [comment] 2021-06-12 00:53
All tests just install the default version of Raspberry Pi OS (previously named "Raspbian"), get all the updates, install all the dev packages in docs/README-linux.md, and then build SDL from git with the configure script. Then run testsprite2.

Raspberry Pi 3 on Rasberry Pi OS 9: builds with both rpi and kmsdrm drivers (good), tries kmsdrm, fails (correctly), tries rpi and succeeds (good).

Raspberry Pi 3 on Rasberry Pi OS 10: builds with both rpi and kmsdrm drivers (good), tries kmsdrm, fails (correctly), tries rpi and succeeds (good).

(Raspberry Pi 4 intentionally doesn't boot on RPiOS9, skipping)

Raspberry Pi 4 on Rasberry Pi OS 10: builds with both rpi and kmsdrm drivers (good), tries kmsdrm fails (bad!), tries rpi and fails (good).

The error is: `INFO: Couldn't create window: Can't load EGL/GL library on window creation.`

So one failing case.

A quick walk through this with gdb suggests that we're hitting this line in SDL_egl.c:

```c
if (_this->gl_config.profile_mask == SDL_GL_CONTEXT_PROFILE_ES) {
```

...and skip this condition, as we have not asked for an OpenGL ES profile.

This is further confirmed by testgles2.c working just fine with kmsdrm in this scenario.

I feel like we hit this problem before, I'll trace a little further.

**Comment by icculus** [comment] 2021-06-12 01:04
Ah, easy fix. Okay, this works now across all the configurations, favoring KMSDRM on the Raspberry Pi 4, which needs it, and using dispmanx on the Pi3 and earlier, which don't support KMSDRM.

**Comment by vanfanel** [comment] 2021-06-12 09:24
@icculus KMSDRM is supported (and works) on every Raspberry Pi model, not only on Raspberry Pi 4.

**Comment by icculus** [comment] 2021-06-12 11:43
I wonder if it failed because it needed the patch I made. I'll retest.

**Comment by cgutman** [comment] 2021-06-12 16:04
I think you have to explicitly opt-in for Fake KMS on Raspberry Pi 3 and earlier by setting `dtoverlay=vc4-fkms-v3d` in `/boot/config.txt`, otherwise dispmanx is all you can use.

**Comment by icculus** [comment] 2021-06-12 22:24
Thanks, I didn't know about vc4-fkms-v3d...if I add that, kmsdrm _does_ in fact work as expected on a Pi3.

But this confirms we work correctly on all Pi configs out of the box, whether they are kmsdrm ready or not. I'm satisfied, let's close this issue.

**Closed** 2021-06-12 22:24 UTC
Labels: bug

**Comment by vanfanel** [comment] 2021-06-12 22:36
@icculus @cgutman 

That is NOT true: `dtoverlay=vc4-fkms-v3d` emulates KMS on top of dispmanx.
When dispmanx is retired (I expect it to happen soon) that will stop working.

`dtoverlay=vc4-kms-v3d`, which is the option for full KMS, does work on Pi 3.
There's no need for `dtoverlay=vc4-fkms-v3d` on a Pi3 with current stable kernel.

**Comment by icculus** [comment] 2021-06-12 23:46
Am I incorrect that you have to edit /boot/config.txt to make it work on a pi3? If it works but not by default, then dispmanx remains important until that changes in a newer Raspberry Pi OS release.

We definitely favor kmsdrm, and if it doesn't work for whatever reason, we try dispmanx. Obviously kmsdrm is the way forward and we are ready for it.
