### ISSUE TITLE
SDL window shaping code allocates memory that isn't freed

### ISSUE THREAD

**Issue by slime73** [libsdl-org/SDL#6104] opened 2022-08-21 21:21 UTC
I only discovered this while looking at code for #6103, and haven't verified what I saw using memory debugging tools, so this might (hopefully) not be a valid issue.

`SDL_CreateShapedWindow`'s backend implementations allocate a `SDL_WindowShaper` structure on the heap, and also a backend-specific ShapeData object (usually on the heap) stored in a driverdata field in SDL_WindowShaper. SDL_Window has a field for the SDL_WindowShaper structure but I haven't found any place where its memory is freed when a window is destroyed. I also haven't seen any backend code which frees the ShapeData driverdata object when the window is destroyed.

So I believe there are at least two memory leaks in each `SDL_CreateShapedWindow` backend implementation, but I'm happy to be proven wrong. This might also demonstrate how few people use those APIs.

**Comment by slime73** [comment] 2022-08-22 15:15
Oops, this is a duplicate of #2128

**Comment by slouken** [comment] 2022-08-24 18:46
Closed as duplicate of https://github.com/libsdl-org/SDL/issues/2128

**Closed by slouken** 2022-08-24 18:46 UTC
