### ISSUE TITLE
Viewport and clip rect getters are broken

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2688] opened 2021-02-11 00:54 UTC
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.6
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2017-10-26 13:00:46 +0000, Daniel wrote:

> SDL_RenderGetClipRect() and SDL_RenderGetViewport() are broken due to the lossy math. They don't return original rectangles most of the time.
> 
> Consider x coordinate 5 and renderer scale 0.1. SDL_RenderSetClipRect() will truncate it ((int)floor(5 * 0.1)), resulting in renderer->clip_rect.x equal to 0.
> When SDL_RenderGetClipRect() will return as (int)(0 / 0.1), resulting in 0.
> 
> The same happen with scale > 1.0 - it will usually return 1 px smaller coordinate. When SDL_RenderSetClipRect() and SDL_RenderSetClipRect() calls are chained, the error will accumulate. This makes SDL_RenderGetClipRect() and SDL_RenderGetViewport() completely useless.

**Comment by icculus** [comment] 2021-11-30 03:27
Duplicate of #4643.

**Closed** 2021-11-30 03:28 UTC
