### ISSUE TITLE
SDL2, Win.dll problem

### ISSUE THREAD

**Issue by RexAssault** [libsdl-org/SDL#8405] opened 2023-10-17 02:55 UTC
left stick giving right stick input without movement with SDL2.dll, doing fine with Windows.Gaming.Input API (WinGamingInput.dll) cemu uses. also problem is gone when i start cemu first and open controller input and then yuzu if i start yuzu only problem persists

**Comment by slouken** [comment] 2023-11-08 20:05
Duplicate of https://github.com/libsdl-org/SDL/issues/8168

**Closed by slouken** 2023-11-08 20:05 UTC
