### ISSUE TITLE
[Feature Request] Add Handheld and Custom device capability and feature support

### ISSUE THREAD

**Issue by antheas** [libsdl-org/SDL#10564] opened 2024-08-18 11:18 UTC
Hi,

Prompted a bit by this [Verge article](https://www.theverge.com/2024/8/13/24219469/valve-steamos-asus-rog-ally-steady-progress-dual-boot), I think it is a good idea for me to stop procrastinating and open a discussion about adding capability recognition for handheld Windows devices and custom/virtual controllers in general to SDL. Therefore, I get to upstream some of the work I did last year, and you get to skip some of it for SteamOS and SDL.

If this is not the appropriate place for this discussion, we can move the thread to e.g., SteamForLinux or wherever the correct place is.

I think we've done a great job in Bazzite in adding support for a wide range of [Windows handhelds](https://github.com/hhd-dev/hhd#supported-devices) and done so in a [prompt manner](https://www.gamingonlinux.com/2024/07/bazzite-linux-36-out-now-bringing-full-asus-rog-ally-x-support/). This support is very reliable. To such an extent that users of these devices forget that their device was made to run Windows (which induces a lot of roadblocks for Linux support). Getting to this level of compatibility without being in the graces of either the manufacturers or Valve meant that certain compromises had to be made, which results in a few nuisances that would be good to fix, hopefully in part by this issue.

Notable examples of this are from the manufacturer side that e.g., the vendor buttons of the Ally do not support holding. For the side of Valve, it is that Steam needs to see a DualSense controller to enable the gyro profile of Steam Input which causes three quirks: undesirable glyphs (because Sony/or worse Nintendo), wrong default 3D to 2D conversion, and an inverted roll axis (both due to no concept of handheld). The other one is that Steam exposes a TDP slider (which we fixed) but high power devices such as the Ally expose tuned manufacturer profiles which are more user intuitive, and that the fixed GPU frequency slider is useless for those devices, with EPP and CPU boost being more important.

Let us ignore the TDP controls of Steam in this issue, as they are not applicable to SDL. They are a thing you should be aware of, however, as it means the current API of steamos-manager might be limiting.

I will separate this issue into three parts:
1) Background or "Why SDL cannot support current Windows handhelds by itself"
2) Given that, assuming that handheld support is handled outside SDL, a small proposal for a standard to convey to SDL the capabilities of handhelds, and then from SDL to Steam and to other userspace apps.
3) Expand on that standard, by enumerating the capabilities of devices that currently exist in the market.
   
And I should know a thing or two, since I have personally added or merged support (thanks to other great contributors) for the majority of Windows handhelds in the market, under the tool [Handheld Daemon](https://github.com/hhd-dev/hhd), which I started building last year.

## Background or "Why SDL cannot support current Windows handhelds by itself"
SDL and/or Steam with a proprietary LibUSB blob cannot support current Windows handhelds fully (i.e., replacing their vendor software while supporting all hardware features).

The answer to this question is very simple and is the result of the following:
 1) Marshalling the disjoint hardware devices requires **privileged** access, where SDL and Steam run on the user level.
 2) Reading certain devices requires having **exclusive** access to them, where multiple copies of SDL might be running at the same time.

So let us expand on these two points, as it might not be clear why.

First, some background. Users want access to advanced controller features: gyro, RGB, menu buttons, and paddle support. However, the Windows API has lagged behind, which has resulted in all current Windows devices using XInput (i.e., the Xbox 360 controller). To enable additional features, vendors use their own proprietary firmware with their proprietary application. There is only so much you can do with firmware due to XInput though, where users would prefer a unified controller (e.g., gyro implementations are subpar, paddles are not very customizable).

Therefore, the challenge becomes how to wrap the Windows designed firmware with its disjoint devices to create a unified controller that appears as if it was created to support Linux.

To do this we have to wrap 6 different types of Windows devices into one:
1) The XInput controller
2) The vendor buttons, which are either windows shortcuts in the AT Keyboard or vendor hid reports
    - Windows shortcuts need muting, lest you want the calculator to open while you are ingame
    - This means: **exclusive access**
3) The vendor interface, which provides access to RGB and configuration (e.g., resetting mappings, deadzones, switching to mouse mode on the Ally)
    - Either EC (through driver) or HID, requires **privileged** access and care, such as debouncing and input filterring.
4) Access to the display IIO IMU (gyro) (only the Legion Go has controller gyros)
    - The parameters of the IMU (e.g., frequency) need to be set and/or hrtimer needs to be set
    - This means: **privileged** access
    - For minimizing CPU use and proper timestamping, IIO needs to be setup using the buffered interface
      - Only one userspace application can access the buffer at a time
      - This means: **exclusive access**
    - Alternative (unprivileged): reading raw values (e.g., `in_accel_x_raw`)
      - Each read causes an I2C access (**very expensive; 6 reads per sample**)
      - Lower frequency
      - Fake timestamp causes jitters due to inconsistent wakeups
      - Very high CPU use
      - If multiple consumers, issues will occur as well
    - This is not true in Windows (SDL has support for the Ally Gyro after all)
      - Windows driver allows shared access to IMU measurements
      - But it is crappy 100hz gyro
5) The touchpad
   - if it does not feature a click, make it virtual with tap to click for gamescope
   - if the user wants it for XInput, pass it through the controller
     - Release when SDL is not running
   - In both cases, capture it and mute (**exclusive access**)
6) The shortcuts devices (if any; additional to point 2)
    - Exposed as Keyboards/Mice allowing the user to map to shortcuts such as Ctrl+Alt+Del
    - Found on both the Ally and the Legion Go, other devices use the AT Keyboard
    - For Legion Go, needs to be muted: **exclusive access**
    - For Ally, only needs to be read after mapping the paddles to F17/F18 (not muting maintains the mouse mode of the Ally which users expect).

Therefore, a root level daemon needs to process the input devices to clean them up in way most users would expect. Doing this in the kernel is not possible either, as the devices come from different subsystems and would be very hard to merge.

Of course, as the Steam Deck shows, this is only required for Windows-built handhelds and may be skipped for Linux-built handhelds or with manufacturer cooperation. This is provided there is a standard for adding support for them (there is not), which brings us to the next section.

I should note that most handhelds that have come out already either have hardware limitations (e.g., the controller daughter board cannot access all components) or it is likely their manufacturer will not release a firmware update for this support. So even if every manufacturer jumps on board, there will still be a need for a root level daemon for legacy device support, which is only activated when necessary (e.g., not for the Steam Deck).

> Even with manufacturer cooperation, not needing userspace marshalling is not guaranteed. For example, the current [Orange Pi Neo prototype](https://forum.manjaro.org/t/development-q-a-orangepi-neo-01/) needs this, as its touchpads are wired to the I2C bus of the device and not to the controller daughter board. The same is true for 2 of the vendor buttons, but in my opinion this could be fixed with some creative bios work.

## Capability Standard
Therefore, the question (after we handle the controller) becomes how do we convey the capabilities of a device to SDL and its users, and after that, which standard do we use for the controller.

In my opinion, this could be done by dedicating a few USB PID values, which are used to expose the capabilities of the device to SDL agnostic of hardware manufacturer. Then, SDL converts these VID/PID pairs into a struct of capabilities that can be consumed by applications and, if applicable for legacy purposes, by having it lie to some legacy checks (e.g., is_dualsense if the device has gyro). As devices start natively supporting the standard, manufacturers can dedicate VID/PID pairs for this purpose that can be manually added to SDL.

Following, since the DualSense controller is one of the most supported controllers in Linux applications (SDL, the Kernel, and emulators have handwritten drivers for it, including a lot of games) and has a superset of capabilities for all handhelds currently in the market, I propose using that as a base for the protocol.

It is also well mimicked by manufacturers, so repurposing existing firmware should not be particularly difficult for creating new handhelds. For future Windows/Linux cross-compatibility, manufacturers can make their controllers support both an XInput+Vendor variant for Windows and a DualSense like variant for Linux or Steam Input/SDL on Windows. This can be made configurable through their vendor software, BIOS, or a keybind (for example, the Legion Go has a DInput mode which can be activated with Legion L + RB, although it is inferior to XInput feature-wise).

## Handheld Capabilities
Now, the fun part begins, where I group and enumerate the capabilities of every Windows handheld in the market (I purposely omit the Jog dials of the Zotac Zone and the capacitive sticks, pressure sensors of the Steam Deck).

### Vendor Buttons
Handheld devices will always contain either an Xbox button (e.g., GPD) or at least a single vendor button. This button should open the main system overlay, regardless of what it is. Let us assume it is Steam. We will refer to this as the Guide button.

Following, most devices include a second vendor button, which is used to open a side menu feature. This button may not always be available. GPD devices do not have it by default, but the user may dedicate one of the two remappable buttons to it. In fact, we use the right remappable button by default for GPD. We will refer to this as the Share button.

> I currently remap double tapping of the share button to open [hhd-ui](https://github.com/hhd-dev/hhd-ui), and leave the single press for steam. This is less user intrusive than stealing a button, but adds latency to the Steam side menu.

The first two buttons might not chord correctly, as is the case on the Ally (although, given the verge article, perhaps Asus will be compelled to add some hid reports for the button press and release). This may not always be the case even for the same handheld: we give Ally owners to swap the start/select keys with the vendor buttons.

### Paddles
Certain devices do not have any other extra buttons (e.g., Ayn Loki; paddles are hardcoded to LS/RS).

Ayaneo have two extra buttons, either on the top or on the bottom of the face of the device (the front are awkward to remap). GPD has two remappable buttons on the front (GPD Mini, Max) or the back (GPD Win 3/4). The Ally has two paddles on the back.

The Legion Go has two paddles on the left controller that are vertical, two on the right that are horizontal, and a fifth button on the right controller that acts as a mouse click on FPS mode (very easy to misclick, disabled by default; because of this, assume it only has four buttons).

In addition, certain devices have buttons that are easy to press by mistake, prompting a lot of them to disable them. Or, we might choose to map them to keyboard/overlay shortcuts for their convenience. Therefore, the amount of remappable buttons each device has is subject to change depending on user choice.

### Gyro
If a device has a gyro feature, we can divide it into four categories.

First, we have devices that act as controllers (e.g., the Dualsense controller). In this case, the user either expects Player Space or Yaw to be used for their controller when aiming.

The second category is devices where the motion sensor is on the handheld display itself. In this case, the user expects Local Space to be used for gyro aiming, and the roll axis needs to be inverted.

The third category is when the user has enabled a single gyro on e.g., the Legion Go and has detached the controllers. In this case, it is the same situation as the dual joycons, where laser pointer aiming could be used.

Finally, we have the case where the user has detached the controllers from their handheld and enabled both controller gyros (e.g., Legion Go). In this case, I am unsure what behavior Steam should have (target use-case is emulators), but SDL should make both gyroscopes available (as is the case currently for JoyCon pair merging).

### Touchpad
For touchpads, if one exists, we can group them into three categories. First, remember that the user might just want to use the touchpad to navigate, so this capability might not always be available.

Here are the three categories:
  - **Single**: the touchpad is accessible by both fingers, and can be segmented into left/right/center (GPD Mini, Max, Dualsense).
  - **Sided**: the touchpad is on the dominant finger of the user, meant primarily for navigation (Legion Go).
  - **Dual**: each finger has its own touchpad (Orange Pi Neo, Zotac Zone, Ayaneo Kun).

All three categories can be accommodated by the DualSense SDL driver, by just mapping the touchpad to various sections of the DualSense touchpad. The DualSense touchpad supports two fingers, so in the case of e.g., the Orange Pi Neo both touchpads can be used at the same time.

I note here that the placement of the touchpads in all current Windows handhelds is not ideal for aiming. Nevertheless, it is a feature that is desirable to support, for e.g., keypad mappings or PlayStation streaming support.

### RGB
Let us not get complicated here. The users can either use their distribution/vendor software to set or disable RGB (e.g., Handheld Daemon) or they can feed it to the controller and use SDL to set RGB using a single zone RGB values. We think most users prefer the former, but certain games such as Death Stranding and Portal 2 look really impressive with RGB passthrough. Moreover, broad market support encourages game developers to add RGB support to their games.

The Ally has quad zone RGB. Certain Ayaneo devices have multizone that has a huge delay to set. Legion go briefly had dual zone RGB, but it was disabled with a firmware update due to what I assume are bugs with the stick LEDs unsyncing with each other. Other manufacturers have single zone RGB.

### Dynamic Capabilities
Mind the fact that the same device can **transition** its capabilities at any given point or have different capabilities depending on the distribution or point in time.

Here are some scenarios:
  - Detaching the controllers with gyro becoming handheld (e.g., Legion Go)
  - The user might disable RGB
  - The RGB driver might not be installed (e.g., Ayaneo with EC RGB)
  - The extra buttons of the device might be wired to shortcuts to help novice users
    - We suggest: left button for keyboard, right button for manufacturer overlay
  - Gyro may be disabled to minimize CPU utilization
    - Does not use CPU noticeably
      - From a user perspective that is, but it is [noticeable on htop](https://github.com/hhd-dev/hhd/issues/63#issuecomment-2091906482)
    - If a user does not need it, why waste the cycles?

Preferably we would prefer to maintain the same virtual device, as yanking it to change the VID/PID can interfere with games. Alas, it is only a problem when detaching handheld controllers (e.g., Legion go), where the gyro capability changes. In other scenarios, the change is user initiated and there is a certain expectation the game might not like it.

### Code Sample
Finally, let us see how this could look in SDL. Please indulge in including some pseudocode to encode the information above:

```python
class Capabilities(NamedTuple):
    # If vid and pid are manufacturer specific, we can add a name for it so that
    # e.g., Steam can use manufacturer specific glyphs (with manufacturer consent).
    # Bazzite community members maintain an unofficial glyph database that is
    # currently optionally installed as a Decky CSS theme.
    name: str | None

    # Controlelr gyro type
    # For normal controllers e.g., yaw should be used for the gyro
    # If the controller is a handheld and gyro aiming is used, Local space
    # should be used for the gyro and the roll axis needs to be inverted
    # If it is sticks (e.g., Legion Go, Joycons), it is very likely that
    # there are dual gyros and/or laser pointer aiming should be used
    # Sided means primary hand, not decided by SDL, and dual means both
    # (SDL application may decide which to use).
    gyro: Literal["none", "handheld", "controller", "sided", "dual"]
   
    # Controller touchpad type
    # Single: GPD devices, the Dualsense controller
    # Touchpad is accessible by both fingers, and can be segmented into
    # left/right/center Sided: the touchpad is on the dominant finger of the
    # user, meant primarily for navigation, example: Legion Go
    # Dual: each finger has its own touchpad,
    # example: Orange Pi Neo, Zotac Zone, Ayaneo Kun
    touchpad: Literal["none", "single", "sided", "dual"]

    # RGB Support
    # This can get very complex. The ally has quad zone RGB, and manufacturers
    # often create various RGB modes. Keep it as a simple on/off.
    rgb: bool

    # Additional buttons
    # Whether there is an additional auxiliary button for opening a side menu
    # Assume Xbox button always exists
    share: bool

    # Wether there are additional remappable buttons. They could be on the top
    # (as in Ayaneo's case) or the back (as in the Ally's and Legion Go's case).
    # Some devices do not have them (e.g., Ayn Loki)
    # In addition, certain devices such as the Legion Go and Steam Deck have
    # four back buttons (technically the Legion Go has 5 extra buttons, and
    # we support that but lets not go there)
    paddles: Literal["none", "dual", "quad"]
```

We can encode the above into a bit field, so that it is easy to add support for new devices through SDL without having to PR it and wait for Steam.

Given the above, we can calculate that `5*4*2*2*3 = 240` PID values are required to encode the capabilities of all current handhelds in the market. It would be relatively easy for Valve to donate these beginning in a specific range in their VID allocation, and then they can be hardcoded to SDL.

Therefore, to see if the device supports RGB, given an offset `X` on the VID 0x28DE allocation, we can do:
```python
def supports_rgb(pid: int) -> bool:
    return (pid - X) // (3*2) & 2 == 1
```

And repeat to fill in the capability map for a generic device.

Of course, the capability struct can be expanded as necessary, and unique VID/PID pairs, capabilities can be added for exotic devices. But for most boutique manufacturers (e.g., Ayaneo, Aokzoe) that already use a generic Xbox 360 VID/PID and release multiple models per year, selecting a VID/PID pair based on their device capabilities and sourcing a "DualSense like" controller daughter board should be sufficient.

## Conclusion
I hope that this issue sets a good foundation for the discussion of adding handheld capabilities to SDL.

As part of Handheld Daemon, I already have UInput and DualSense HID implementations that work flawlessly (well; could be better if https://github.com/libsdl-org/SDL/issues/9688 closes, but nobody has noticed the Legion Go is 125hz while gyro is active). Either implementation can be used as a reference for the new standard, by using one of the 25 handhelds Handheld Daemon supports (using the Ally or Legion Go would be preferable). Then, we can make modifications for the new standard as necessary. We have reached a point where controller emulation never breaks, under any device, and only adds just 0.17ms of latency on average. And with advanced features such as controller caching while the handheld controller and gyro reconnect after suspend, it goes a step above in ensuring that, e.g., games which do not support controller hot plugging do not break after suspend.

Of course, I do not mean to imply that Handheld Daemon is the only project in this space. Parallel works such as [ViGEmBus](https://vigembusdriver.com), [DSX](https://dualsensex.com), [inputtino](https://github.com/games-on-whales/inputtino) (part of [Sunshine](https://github.com/LizardByte/Sunshine) on Linux), and [Handheld Companion](https://github.com/Valkirie/HandheldCompanion) exist as well and would benefit from this standard greatly in both Windows and Linux. Imagine Sunshine being able to pass through the exact controller's capabilities when streaming, it would be great. On the same note, the standard I laid out above can be implemented the same by any project or manufacturer, in Windows or Linux, through firmware or software.

**Comment by ShadowApex** [comment] 2024-09-21 20:17
As one of the co-creators of [InputPlumber](https://github.com/ShadowBlip/InputPlumber/), which is being used to bring handheld gamepad support to many Linux distributions such as ChimeraOS, Manjaro, SteamFork, and others, I would like to offer some commentary on this proposal, as this is something that I have also been working on and discussing with others for some time.

I think that you have summarized the problem with these handhelds well and enumerated the different features that we'd like to support as first-class citizens in Linux. While I think that encoding the capabilities of input devices through a fake vendor id/product id is a novel idea, it feels like it's shoehorning in a solution to the problem rather than creating a robust standard that vendors could target. The VID/PID are meant to identify the hardware, not encode capability information. Ideally we should be able to support these hardware features without misappropriating these device properties.

Adopting your proposal as currently written would mean that two different devices or hardware revisions with the same capabilities would share the same product id, making it hard to distinguish from other devices and could affect other software that rely on the uniqueness of the VID/PID. It may also make management of these devices more difficult for hardware vendors themselves who try to adopt this standard, as different devices with completely different hardware could share the same product id.

It also doesn't address the other hardware features like the Steam Deck's capacitive joysticks or the Zotac Zone's ring dials, as you mentioned, and it would be good if we could support those features.

I have been [working on a solution](https://github.com/ShadowBlip/InputPlumber/issues/72) to this problem for the past few months which might better address the issues at hand. I didn't want to submit a proposal to the SDL project until I had finalized the specification, but due to this PID/VID request I think it would be good to post information about it now to offer an alternative solution to this problem. I may submit a separate feature request for this once the specification is finalized.

In short, I would propose that we instead define a standard HID interface that programs like InputPlumber and HHD could emulate with uhid that would provide a hardware agnostic interface for other software like SDL (or kernel driver) to consume. In the future this interface could also be used by hardware manufacturers to implement directly to provide native Linux support out of the box.

You can view the full interface specification I have been working on here:

https://github.com/ShadowBlip/UnifiedControllerInputSpec

To summarize how it would work, this interface would allow SDL to query for the capabilities of the device via HID Feature Report, notify SDL if any capabilities have changed, and provides versioning to allow for expanding the spec to easily include new hardware features.

I think this comes with some advantages over the VID/PID encoding approach:

- It does not require Valve to donate any part of their VID/PID space
- The number of capabilities we could define wouldn't be limited by a single 32-bit product id
- SDL can dynamically react to capabilities being added or removed from the device (e.g. the Legion Go detachable controllers being removed, devices switching from DInput to XInput modes, etc.)
- The HID device can pass through real vendor ids and product ids that software can use to uniquely identify the device
- We would be able to more easily support exotic hardware features like the Zotac dial or Steam Deck capacitive touch sticks

**Comment by pastaq** [comment] 2024-09-22 01:07
Greetings all. As an introduction for those who don't know me, I am the other co-developer of InputPlumber and I have been working towards a solution to this issue since April of 2022 through various approaches. For nearly two years I was the only person working in this space to solve the issue of input management for handhelds in Linux, and I have used that experience in creating InputPlumber and the Unified Controller Input Specification mentioned above. Sufficed to say I am quite invested in the outcome of this proposal. I want to first thank Antheas for starting this conversation, as it is an important issue that needs to be addressed. It is my hope that we will find an extensible long term solution that works for device manufacturers, software developers, and ultimately everyday gamers.

@ShadowApex fairly succinctly addressed most of my initial thoughts on the above proposal. As noted, he and I have been working on this for quite a while with a few other notable members of the community behind the scenes. I just want to expound on a couple of points that I believe need to be more thoroughly addressed.

Firstly, Antheas you briefly described the historical reason why Xinput both became the standard and then failed to fully support future advancements. However; you failed to properly attribute the root cause of that problem, in that there was no room for the expansion of the specification. This meant that any new input methods were not able to be supported natively (touchpad, back paddles, share button, gyro, etc.) which resulted in every manufacturer inventing new ways of doing it themselves. I believe that the use of PID to encode this data suffers from the same limitation. Your own examples of omitting capacitive touch and joystick dials bears that out in that they couldn't be included without ballooning the spec from 240 PID groups to 960, assuming they are simple boolean values. If an OEM were to add something else new in the future like pressure sensitive joysticks, additional Sega style C/Z buttons, an 8 way finger hat instead of back paddles, etc, the specification as described becomes unmanageable. The manufacturer is then left with two choices: respect the SDL specification, or innovate to gain market advantage. I think it is clear which avenue most for-profit companies would pursue.

Secondly, I think that starting with an SDL specification and working backwards from there won't solve the root cause of the issue we have been solving with our input management solutions: fragmentation. The specification does not inform OEM's or ODM's on how they could or should implement the specification into their devices, other than to limit the possibilities. This will continue the same sort of issues we see today where every device has a new proprietary interface that generates no reusable kernel/driver code and requires an additional pull request to every library or tool that uses gamepad input. Take for example the ROG Ally and the MSI Claw. Both devices are functionally identical in Windows and have the same buttons in roughly the same locations, but are so wildly different in their firmware that they require hundreds of hours of work to be properly implemented into the Linux kernel. You could honestly even use the ROG Ally and the ROG Ally X in that example, and none of them have native SDL support yet. In my view a proper solution to this problem will provide hints to the manufacturers on how to implement an open HID specification, and drivers and SDL will fully understand that specification by default. This *hopefully* will result in lower overhead in maintaining support and faster adoption. This problem is what the Unified Controller Input Specification aims to resolve.

**Comment by slouken** [comment] 2024-09-22 01:19
I think in the long run virtual devices that reflect functionality available on the system presented in a standardized way would be something that SDL would benefit from as well as enhance any application that wanted it, whether it used SDL or not. It would be important in this design to allow multiple applications to access the functionality at the same time. This seems like a good way forward.

I’ll close this for now, and we can open new issues for supporting standardized platform functionality in the future.

**Closed by slouken** 2024-09-22 01:19 UTC
