### ISSUE TITLE
Proposal: use enums as types where applicable

### ISSUE THREAD

**Issue by Susko3** [libsdl-org/SDL#9186] opened 2024-03-03 17:28 UTC
I've been looking into using [ClangSharp](https://github.com/dotnet/ClangSharp) to generate C# bindings for SDL3.

I've noticed that in a lot of places, `Uint32` is used instead of the specific enum type.
I propose to use the actual enum type in as much places as possible (those places where the size of the parameter/field is 32 bits).

For example, the mouse wheel event has `Uint32 type` and `Uint32 direction`, which could be replaced with `SDL_EventType` and `SDL_MouseWheelDirection` respectively.

https://github.com/libsdl-org/SDL/blob/22dbc0f32f9ea3a73c67c07cb7766dd1348f76dd/include/SDL3/SDL_events.h#L353-L368

Is there a specific reason for not using enums as types? Using the enum as the type conveys more information, and helps when generating bindings, as the type is known (using the bindings as-is requires explicit casting in C#).

I guess the main reason for using concrete types is that in C, [enums don't have well-defined underlying types (except in C23)](https://en.cppreference.com/w/c/language/enum). But [SDL checks that enums are the size of an `int`](https://github.com/libsdl-org/SDL/blob/1e8b006d43166a77d8311d89938e2082b9febe22/include/SDL3/SDL_stdinc.h#L365-L380). (`int`s also don't have a specific size, but it's probably 32 bits on most platforms.)

Enums are already used as types in some places. Namely the `SDL_Keysym` struct which uses the `SDL_Scancode` enum.

**Comment by slouken** [comment] 2024-03-03 17:36
Yes, for SDL3 we've decided to go with enums where it makes sense. Feel free to create a PR to correct these as you go.

**Comment by Susko3** [comment] 2024-03-03 17:39
Should I also change defines to enums where it makes sense? Example:

https://github.com/libsdl-org/SDL/blob/22dbc0f32f9ea3a73c67c07cb7766dd1348f76dd/include/SDL3/SDL_events.h#L50-L52

Maybe better to change in a separate PR in case there's disagreement about the naming of a new enum.

**Comment by slouken** [comment] 2024-03-03 17:52
> Should I also change defines to enums where it makes sense? Example:
> 
> https://github.com/libsdl-org/SDL/blob/22dbc0f32f9ea3a73c67c07cb7766dd1348f76dd/include/SDL3/SDL_events.h#L50-L52
> 
> Maybe better to change in a separate PR in case there's disagreement about the naming of a new enum.

No, we don't want to enforce applications changing their code to deal with enums where they don't currently need to. This is a particularly good example. An application might check `if ( state == TRUE ) ...`, etc.

**Comment by Dragon-Baroque** [comment] 2024-03-07 08:50
In the Exult project https://exult.info, we are trying to move to SDL 3.
Since commits 424616e0 and c70710cd, Exult gets the following error, although the same code exists as identical in `src/test/SDL_test_common.c`, possibly because Exult is written in C++ :
```
imagewin.cc:356:6: error: no matching function for call to 'SDL_GetMasksForPixelFormatEnum'
  356 |         if (SDL_GetMasksForPixelFormatEnum(
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/SDL3/SDL_pixels.h:750:34: note: candidate function not viable: no known conversion from 'const Uint32' (aka 'const unsigned int') to 'SDL_PixelFormatEnum' for 1st argument
imagewin.cc:357:43: error: invalid conversion from 'Uint32' {aka 'unsigned int'} to 'SDL_PixelFormatEnum' [-fpermissive]
  357 |                                 dispmode->format, &bpp, &Rmask, &Gmask, &Bmask, &Amask)
      |                                 ~~~~~~~~~~^~~~~~
      |                                           |
      |                                           Uint32 {aka unsigned int}
```
In the error, `dispmode` is a `SDL_DisplayMode`.

**Diagnostic :**
The field `format` in `SDL_PixelFormat` was migrated to `SDL_PixelFormatEnum` in `include/SDL3/SDL_pixels.h`, but the same field `format` in `SDL_DisplayMode` remained as a `Uint32` in `include/SDL3/SDL_video.h`.

If I apply to SDL3 main the following patch :
```
--- a/include/SDL3/SDL_video.h
+++ b/include/SDL3/SDL_video.h
@@ -82,7 +82,7 @@ typedef enum
 typedef struct
 {
     SDL_DisplayID displayID;    /**< the display this mode is associated with */
-    Uint32 format;              /**< pixel format */
+    SDL_PixelFormatEnum format; /**< pixel format */
     int w;                      /**< width */
     int h;                      /**< height */
     float pixel_density;        /**< scale converting size to pixels (e.g. a 1920x1080 mode with 2.0 scale would have 3840x2160 pixels) */
```
SDL 3 still compiles, the error in the Exult build disappears, and Exult still works over SDL 3.

**Comment by slouken** [comment] 2024-03-07 11:39
That is the correct fix, thanks!

**Comment by sezero** [comment] 2024-03-07 12:06
Great, now several others are failing which probably weren't updated. I _hate_ the SDL_PixelFormatEnum patch which [cause pain in sdl2-compat](https://github.com/libsdl-org/sdl2-compat/issues/144) too.

**Comment by Dragon-Baroque** [comment] 2024-03-07 15:47
With the main branch latest commits up to 790cd39, my migration of Exult to SDL 3 is now compiling and working again.
Thank you.

**Comment by slouken** [comment] 2024-03-07 16:05
Great, thanks for the feedback!

**Comment by radgeRayden** [comment] 2024-04-26 23:55
The recent change that moves SDL_KeyCode _away_ from an enum is causing me FFI headaches for similar reasons. We use libclang to compile the header and then consume the compilation nodes. This works great for enums and even simple defines, but the new keycode defines aren't very clean. For example quoted characters like `\r` don't get exported at all, and nested macros such as `SDL_SCANCODE_TO_KEYCODE(x)` are a big no no as well. The issue is that in C defines are very literal, and we can't consume anything but plain numerical values and sometimes (unparenthesized) arithmetic expressions.

This seemed like a decent place to add this feedback, but I can file a new issue if adequate.

**Comment by slouken** [comment] 2024-05-07 16:33
The problem is that the SDL keycode can potentially be any valid Unicode code point, and having an enumeration of some of them was causing confusion. In general flags will be an unsigned type and the appropriate values will be cast to the appropriate type. The pattern will be consistent, so if this is a problem you can run a pre-processing script to transform the values as needed.

At this point, the original bug has been resolved, so I'm going to close this. Feel free to open new issues for specific things that need to be addressed.

**Closed by slouken** 2024-05-07 16:33 UTC
