### ISSUE TITLE
Android app is not quite fullscreen

### ISSUE THREAD

**Issue by pistolparody** [libsdl-org/SDL#5876] opened 2022-07-03 12:13 UTC
Hello.

There is a thin bar at the top of the phone screen's that shows battery and clock and notifications.
When I try to run my app in fullscreen, this bar is purely black, meaning if I paint the whole window white with 
```SDL_RenderClear(renderer)``` the color of bar does not change. So it means it is not a part of the window right?

I found two similar threads in discourse.libsdl.org that are mentioning the exact same issue. 
I tried the methods that both of them mentioned but It had no effect for me.  
One thread was created by [**devvr** ](https://discourse.libsdl.org/t/android-full-screen-view-end-at-status-bar-bottom/25672) and the other by [**Starg**](https://discourse.libsdl.org/t/sdl2-code-change-to-make-android-really-fullscreen/26868).

I created my window with ```SDL_WINDOW_FULLSCREEN``` and ```SDL_WINDOW_BORDERLESS``` flags.
And after that I did this ```SDL_SetWindowFullscreen(window,SDL_TRUE);```

I tested the app only on Samsung Galaxy A22, but I'm not sure if it is a device related problem.

**__UPDATE__**

I tested the app on Samsung Galaxy J5, and the notification bar was totally hidden there.
I also tested the app on Samsung Galaxy A30 and I faced the same issue (notification bar is not a part of the window)

Another thing that I noticed  is that the window height that ```SDL_GetCurrentDisplayMode``` is giving me on A22 and A30 is actually a little bit bigger than the actual size (meaning the objects at the bottom of the window can't be seen in the screen).

So i think that ```SDL_GetCurrentDisplayMode``` is actually doing okay and is giving me the right width and height but because the notification bar is not considered a part of the window, I am facing this issue too.

**Comment by slouken** [comment] 2024-12-30 18:07
Duplicate of https://github.com/libsdl-org/SDL/issues/5894

**Closed by slouken** 2024-12-30 18:07 UTC
