### ISSUE TITLE
Crash on keypress when running iOS app on M1 mac

### ISSUE THREAD

**Issue by thenewandy** [libsdl-org/SDL#5367] opened 2022-02-25 04:45 UTC
Steps to reproduce:

1. Build Demo app "Happy" for "My Mac (Designed for iPad)" (I suspect any application works - my simplest SDL app also has the same problem) from SDLv2.0.20
2. Run it on an M1 Mac in xCode
3. While app has focus, press left arrow key
4. Observe crash.

This is what I see for the crash. It highlights line 67 of SDL_uikitevents.m:

        result = CFRunLoopRunInMode(kCFRunLoopDefaultMode, seconds, TRUE);

With the text:

        Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

The back trace looks like this:

```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001982d8334 libobjc.A.dylib`objc_msgSend + 52
    frame #1: 0x00000001bff69480 UIKitCore`_UIResponderWindowForTarget + 200
    frame #2: 0x00000001bff695b4 UIKitCore`_UIResponderTargetPassesHoppingTest + 124
    frame #3: 0x00000001bff68520 UIKitCore`_UIResponderTargetForActionWithTestBlock + 1204
    frame #4: 0x00000001bff6979c UIKitCore`_UIResponderTargetForAction + 92
    frame #5: 0x00000001c06cf588 UIKitCore`-[UIApplication _unswizzledTargetInChainForAction:sender:] + 460
    frame #6: 0x00000001c06f0c90 UIKitCore`__42-[UIResponder _keyCommandForEvent:target:]_block_invoke + 300
    frame #7: 0x00000001c06f198c UIKitCore`__66-[UIResponder _enumerateKeyCommandsInChainWithOptions:usingBlock:]_block_invoke.363 + 88
    frame #8: 0x00000001c06f141c UIKitCore`-[UIResponder _enumerateKeyCommandsInChainWithOptions:usingBlock:] + 1688
    frame #9: 0x00000001c06f0a7c UIKitCore`-[UIResponder _keyCommandForEvent:target:] + 344
    frame #10: 0x00000001c0b9fae8 UIKitCore`-[UIApplication(iOSMacSupport) _keyboardEventCorrespondsToKeyCommand:] + 184
    frame #11: 0x00000001c0ba0044 UIKitCore`-[UIApplication(iOSMacSupport) _isUIKeyCommandEvent:] + 64
    frame #12: 0x00000001ada369ac UIKitMacHelper`__61-[UINSApplicationDelegate installIsUIKeyCommandEventHandler:]_block_invoke + 252
    frame #13: 0x00000001ada3f230 UIKitMacHelper`-[UINSInputView keyDown:] + 284
    frame #14: 0x000000019b1dea78 AppKit`-[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 5920
    frame #15: 0x000000019b1dd0ec AppKit`-[NSWindow(NSEventRouting) sendEvent:] + 348
    frame #16: 0x000000019b1dc558 AppKit`-[NSApplication(NSEvent) sendEvent:] + 4064
    frame #17: 0x000000019b49459c AppKit`-[NSApplication _handleEvent:] + 76
    frame #18: 0x000000019b7d99e4 AppKit`-[NSApplication _handleEventsImmediatelyIfAllowed] + 328
    frame #19: 0x000000019b7da44c AppKit`___NSRunLoopObserverCreateWithHandler_block_invoke + 64
    frame #20: 0x0000000198517e4c CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36
    frame #21: 0x0000000198517c98 CoreFoundation`__CFRunLoopDoObservers + 572
    frame #22: 0x00000001985172f0 CoreFoundation`__CFRunLoopRun + 1052
    frame #23: 0x0000000198516734 CoreFoundation`CFRunLoopRunSpecific + 600
  * frame #24: 0x0000000100324b2c Happy`UIKit_PumpEvents(_this=0x000000011c86ca00) at SDL_uikitevents.m:69:18
    frame #25: 0x000000010036481c Happy`SDL_PumpEventsInternal(push_sentinel=SDL_TRUE) at SDL_events.c:821:9
    frame #26: 0x000000010036492c Happy`SDL_WaitEventTimeout(event=0x000000016fb38530, timeout=0) at SDL_events.c:993:9
    frame #27: 0x00000001003648c8 Happy`SDL_PollEvent(event=0x000000016fb38530) at SDL_events.c:860:12
    frame #28: 0x00000001002cb554 Happy`SDL_main(argc=3, argv=0x000060000031a6c0) at happy.c:163:16
    frame #29: 0x00000001003bca98 Happy`-[SDLUIKitDelegate postFinishLaunch](self=0x0000600000134240, _cmd="postFinishLaunch") at SDL_uikitappdelegate.m:349:19
    frame #30: 0x000000019940cf08 Foundation`__NSFireDelayedPerform + 460
    frame #31: 0x0000000198533468 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
    frame #32: 0x0000000198533064 CoreFoundation`__CFRunLoopDoTimer + 1076
    frame #33: 0x0000000198532af0 CoreFoundation`__CFRunLoopDoTimers + 392
    frame #34: 0x000000019851766c CoreFoundation`__CFRunLoopRun + 1944
    frame #35: 0x0000000198516734 CoreFoundation`CFRunLoopRunSpecific + 600
    frame #36: 0x00000001a10a8f68 HIToolbox`RunCurrentEventLoopInMode + 292
    frame #37: 0x00000001a10a8bf4 HIToolbox`ReceiveNextEventCommon + 320
    frame #38: 0x00000001a10a8a9c HIToolbox`_BlockUntilNextEventMatchingListInModeWithFilter + 72
    frame #39: 0x000000019b06cce0 AppKit`_DPSNextEvent + 844
    frame #40: 0x000000019b06b584 AppKit`-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1332
    frame #41: 0x000000019b05d5a4 AppKit`-[NSApplication run] + 596
    frame #42: 0x000000019b02ec78 AppKit`NSApplicationMain + 1064
    frame #43: 0x000000019b305084 AppKit`_NSApplicationMainWithInfoDictionary + 24
    frame #44: 0x00000001ada159ac UIKitMacHelper`UINSApplicationMain + 1280
    frame #45: 0x00000001bf9a2b28 UIKitCore`UIApplicationMain + 164
    frame #46: 0x00000001003bb754 Happy`SDL_UIKitRunApp(argc=3, argv=0x000000016fb3b218, mainFunction=(Happy`SDL_main at happy.c:131)) at SDL_uikitappdelegate.m:61:9
    frame #47: 0x0000000100373f70 Happy`main(argc=3, argv=0x000000016fb3b218) at SDL_uikit_main.c:17:12
    frame #48: 0x00000001005e10f4 dyld`start + 520
```

I don't know if this would happen on an iDevice when a bluetooth keyboard is plugged in.

**Comment by icculus** [comment] 2022-03-23 22:06
A new iOS app, built from the default template with Xcode 13.3 on an M1 Mac Mini running macOS 12.3 does not crash with keypresses when running in this configuration:

Just adding this to the AppDelegate implementation ...

```objc
- (void)pressesBegan:(NSSet<UIPress *> *)presses
           withEvent:(UIPressesEvent *)event {
    NSLog(@"WHOA\n");
}
```

...happily logs "WHOA" every time I key a physical key.

I'll spend some time to get SDL building in this configuration and see if I can reproduce, but I wanted to quickly rule out "iOS apps that use the keyboard are just broken on macOS" here.

**Comment by thenewandy** [comment] 2022-03-25 10:04
Please note that I can only reproduce this by pressing arrow keys, other keys don't seem to cause the crash

**Comment by icculus** [comment] 2022-03-25 13:33
I tried those keys.  :)

**Comment by slouken** [comment] 2022-08-02 02:05
It looks like this has been fixed by Apple. I just tested this with Xcode 13 and macOS 12.5, and I modified the Happy demo to print out a log message when a key has been pressed, and everything works fine here. I tested both with and without GCKeyboard support enabled.

The call stack here is a little different:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 3.1
    frame #0: 0x0000000100eff374 Happy`-[SDL_uikitview pressesBegan:withEvent:](self=0x000000015a11e860, _cmd="pressesBegan:withEvent:", presses=1 element, event=0x0000600003ec9770) at SDL_uikitview.m:419:10
  * frame #1: 0x00000001d907a7d4 UIKitCore`-[UIWindow _sendButtonsForEvent:] + 336
    frame #2: 0x00000001d859be70 UIKitCore`-[UIWindow sendEvent:] + 3432
    frame #3: 0x00000001d859a5e8 UIKitCore`-[UIApplication sendEvent:] + 848
    frame #4: 0x00000001d850cc28 UIKitCore`-[UIApplication _handleKeyUIEvent:] + 520
    frame #5: 0x00000001d850c98c UIKitCore`-[UIResponder _handleKeyUIEvent:] + 84
    frame #6: 0x00000001d850c98c UIKitCore`-[UIResponder _handleKeyUIEvent:] + 84
    frame #7: 0x00000001d850c98c UIKitCore`-[UIResponder _handleKeyUIEvent:] + 84
    frame #8: 0x00000001d850c98c UIKitCore`-[UIResponder _handleKeyUIEvent:] + 84
    frame #9: 0x00000001d850c98c UIKitCore`-[UIResponder _handleKeyUIEvent:] + 84
    frame #10: 0x00000001d850c98c UIKitCore`-[UIResponder _handleKeyUIEvent:] + 84
    frame #11: 0x00000001d850c888 UIKitCore`-[UIApplication handleKeyUIEvent:] + 84
    frame #12: 0x00000001d9526720 UIKitCore`-[UIApplication(iOSMacSupport) _sendKeyEvent:] + 68
    frame #13: 0x00000001c5baaab4 UIKitMacHelper`-[UINSInputView _sendKeyEvent:isDown:] + 452
    frame #14: 0x00000001c5bab344 UIKitMacHelper`-[UINSInputView keyDown:] + 408
    frame #15: 0x00000001b2f93e88 AppKit`-[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 5908
    frame #16: 0x00000001b2f9250c AppKit`-[NSWindow(NSEventRouting) sendEvent:] + 348
    frame #17: 0x00000001b2f914b4 AppKit`-[NSApplication(NSEvent) sendEvent:] + 2780
    frame #18: 0x00000001c5b94b6c UIKitMacHelper`-[NSApplication(UINSApplicationSwizzling) _uinsSwizzledSendEvent:] + 292
    frame #19: 0x00000001b324b0f4 AppKit`-[NSApplication _handleEvent:] + 76
    frame #20: 0x00000001b3592a70 AppKit`-[NSApplication _handleEventsImmediatelyIfAllowed] + 328
    frame #21: 0x00000001b35934d8 AppKit`___NSRunLoopObserverCreateWithHandler_block_invoke + 64
    frame #22: 0x00000001b02bc254 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36
    frame #23: 0x00000001b02bc0a4 CoreFoundation`__CFRunLoopDoObservers + 592
    frame #24: 0x00000001b02bb6f0 CoreFoundation`__CFRunLoopRun + 1052
    frame #25: 0x00000001b02bab34 CoreFoundation`CFRunLoopRunSpecific + 600
    frame #26: 0x0000000100f01e4c Happy`UIKit_PumpEvents(_this=0x0000000159830c00) at SDL_uikitevents.m:67:18
    frame #27: 0x0000000100f47a74 Happy`SDL_PumpEventsInternal(push_sentinel=SDL_TRUE) at SDL_events.c:858:9
    frame #28: 0x0000000100f47bac Happy`SDL_WaitEventTimeout(event=0x000000016ef60520, timeout=0) at SDL_events.c:1037:9
    frame #29: 0x0000000100f47b44 Happy`SDL_PollEvent(event=0x000000016ef60520) at SDL_events.c:897:12
    frame #30: 0x0000000100ea1858 Happy`SDL_main(argc=3, argv=0x00006000001cac00) at happy.c:163:16
    frame #31: 0x0000000100faabdc Happy`-[SDLUIKitDelegate postFinishLaunch](self=0x00006000003c4340, _cmd="postFinishLaunch") at SDL_uikitappdelegate.m:349:19
    frame #32: 0x00000001b11c1574 Foundation`__NSFireDelayedPerform + 460
    frame #33: 0x00000001b02d7964 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
    frame #34: 0x00000001b02d754c CoreFoundation`__CFRunLoopDoTimer + 1064
    frame #35: 0x00000001b02d6fd4 CoreFoundation`__CFRunLoopDoTimers + 392
    frame #36: 0x00000001b02bba64 CoreFoundation`__CFRunLoopRun + 1936
    frame #37: 0x00000001b02bab34 CoreFoundation`CFRunLoopRunSpecific + 600
    frame #38: 0x00000001b8efa338 HIToolbox`RunCurrentEventLoopInMode + 292
    frame #39: 0x00000001b8efa0b4 HIToolbox`ReceiveNextEventCommon + 564
    frame #40: 0x00000001b8ef9e68 HIToolbox`_BlockUntilNextEventMatchingListInModeWithFilter + 72
    frame #41: 0x00000001b2e2251c AppKit`_DPSNextEvent + 860
    frame #42: 0x00000001b2e20e14 AppKit`-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1328
    frame #43: 0x00000001b2e12fe0 AppKit`-[NSApplication run] + 596
    frame #44: 0x00000001b2de46fc AppKit`NSApplicationMain + 1132
    frame #45: 0x00000001b30ba640 AppKit`_NSApplicationMainWithInfoDictionary + 24
    frame #46: 0x00000001c5b7f3c0 UIKitMacHelper`UINSApplicationMain + 1276
    frame #47: 0x00000001d831cc2c UIKitCore`UIApplicationMain + 164
    frame #48: 0x0000000100fa96f0 Happy`SDL_UIKitRunApp(argc=3, argv=0x000000016ef63208, mainFunction=(Happy`SDL_main at happy.c:131)) at SDL_uikitappdelegate.m:61:9
    frame #49: 0x0000000100f59e94 Happy`main(argc=3, argv=0x000000016ef63208) at SDL_uikit_main.c:16:12
    frame #50: 0x000000010121908c dyld`start + 520
```

I'm going to go ahead and close this bug. Feel free to reopen if you're able to reproduce it on a newer version of macOS.

**Closed by slouken** 2022-08-02 02:05 UTC

**Comment by thenewandy** [comment] 2022-09-14 12:34
Sorry, took me a while to confirm. But yes, I haven't been able to reproduce it any more.
