### ISSUE TITLE
multiple mice and keyboards

### ISSUE THREAD

**Issue by netpipe** [libsdl-org/SDL#5663] opened 2022-05-15 10:20 UTC
https://github.com/netpipe/libInput/ here is the part for x11

**Comment by mgerhardy** [comment] 2022-05-16 14:45
Multiple mice input is supported afaik: `Uint32 which` in `SDL_MouseXXXEvent`

**Comment by roisterous** [comment] 2022-10-14 23:01
The which will report back different IDs, but everything else is missing. You don't have a way to iterate through the available devices, to find out which ID belongs to which mouse, what kind of mice are available (how many buttons each one has would be useful), all those related functions don't exist. 

e.g. to be able to use two mice to be able to control two unique players in side by side co-op with mice

**Comment by roisterous** [comment] 2022-10-14 23:04
It's also still listed in the Wishlist on the roadmap: https://wiki.libsdl.org/Roadmap

**Comment by Tovarichtch** [comment] 2022-10-15 04:10
I would absolutly love to be able to play coop game with two or more light guns. As an example, all emulators (except the ones using Retroarch) rely on this. Since it's unsupported by SDL, all mice control the first and only mouse input. Therefore, playing as two or more players with light guns is impossible.

**Comment by ivan-roksandic** [comment] 2023-01-26 18:52
Seems possible to get multiple keyboards in Windows as well using GetRawInputData
https://devblogs.microsoft.com/oldnewthing/20160627-00/?p=93755

**Comment by slouken** [comment] 2023-11-07 05:34
Duplicate of https://github.com/libsdl-org/SDL/issues/7498

**Closed by slouken** 2023-11-07 05:34 UTC
