### ISSUE TITLE
[Windows 7] "Not a valid Win32 application" errors after upgrading to 2.24.0.

### ISSUE THREAD

**Issue by Donopatay** [libsdl-org/SDL#6165] opened 2022-08-31 04:29 UTC
Right after upgrading from SDL 2.0.20 and into 2.24.0 it would seem that every application built on it with debugging symbols on results in a "Not a valid Win32 application" errors. 

Even with the simplest line of code 

```
#include <stdio.h>
#include <SDL2\SDL.h>

int main(int argc, char* argv[]) {
    SDL_Init(SDL_INIT_VIDEO);
    SDL_Quit();

    printf("If you are reading this then nothing went wrong.\n");
    return 0;
}
```

This is probably the same issue with #6139.

This was all done on a Windows 7-64 bit machine using MinGW via CodeBlocks.

**Comment by slouken** [comment] 2022-09-01 13:45
Duplicate of https://github.com/libsdl-org/SDL/issues/6139

**Closed by slouken** 2022-09-01 13:45 UTC
