### ISSUE TITLE
Using SDL_DYNAMIC_API on macOS triggers warnings about undefined behaviour

### ISSUE THREAD

**Issue by hikari-no-yume** [libsdl-org/SDL#7484] opened 2023-03-16 22:06 UTC
Here's a (slightly fictionalised) example of the warnings you get when running an app that has statically linked SDL2 and using `SDL_DYNAMIC_API` to replace the SDL version:

```
$ SDL_DYNAMIC_API=~/Downloads/SDL2/SDL2.framework/SDL2 ./myApp
hello from myApp, let's initialize SDL2

objc[24875]: Class METAL_RenderData is implemented in both ./myApp (0x10d2c1670) and /Users/me/Downloads/SDL2/SDL2.framework/Versions/A/SDL2 (0x10de25a80). One of the two will be used. Which one is undefined.
objc[24875]: Class METAL_TextureData is implemented in both ./myApp (0x10d2c16c0) and /Users/me/Downloads/SDL2/SDL2.framework/Versions/A/SDL2 (0x10de25ad0). One of the two will be used. Which one is undefined.
objc[24875]: Class SDLApplication is implemented in both ./myApp (0x10d2c1238) and /Users/me/Downloads/SDL2/SDL2.framework/Versions/A/SDL2 (0x10de25af8). One of the two will be used. Which one is undefined.
objc[24875]: Class SDLAppDelegate is implemented in both ./myApp (0x10d2c1288) and /Users/me/Downloads/SDL2/SDL2.framework/Versions/A/SDL2 (0x10de25b48). One of the two will be used. Which one is undefined.
objc[24875]: Class SDLOpenGLContext is implemented in both ./myApp (0x10d2c13c8) and /Users/me/Downloads/SDL2/SDL2.framework/Versions/A/SDL2 (0x10de25b98). One of the two will be used. Which one is undefined.
objc[24875]: Class SDL_cocoametalview is implemented in both ./myApp (0x10d2c1378) and /Users/me/Downloads/SDL2/SDL2.framework/Versions/A/SDL2 (0x10de25be8). One of the two will be used. Which one is undefined.
objc[24875]: Class SDLTranslatorResponder is implemented in both ./myApp (0x10d2c1300) and /Users/me/Downloads/SDL2/SDL2.framework/Versions/A/SDL2 (0x10de25c60). One of the two will be used. Which one is undefined.
objc[24875]: Class SDLMessageBoxPresenter is implemented in both ./myApp (0x10d2c1328) and /Users/me/Downloads/SDL2/SDL2.framework/Versions/A/SDL2 (0x10de25c88). One of the two will be used. Which one is undefined.
objc[24875]: Class SDL_ShapeData is implemented in both ./myApp (0x10d2c1440) and /Users/me/Downloads/SDL2/SDL2.framework/Versions/A/SDL2 (0x10de25d00). One of the two will be used. Which one is undefined.
objc[24875]: Class SDL_CocoaClosure is implemented in both ./myApp (0x10d2c1490) and /Users/me/Downloads/SDL2/SDL2.framework/Versions/A/SDL2 (0x10de25d50). One of the two will be used. Which one is undefined.
objc[24875]: Class SDL_RumbleMotor is implemented in both ./myApp (0x10d2c1198) and /Users/me/Downloads/SDL2/SDL2.framework/Versions/A/SDL2 (0x10de25d78). One of the two will be used. Which one is undefined.
objc[24875]: Class SDL_RumbleContext is implemented in both ./myApp (0x10d2c11e8) and /Users/me/Downloads/SDL2/SDL2.framework/Versions/A/SDL2 (0x10de25dc8). One of the two will be used. Which one is undefined.
objc[24875]: Class SDL_WindowData is implemented in both ./myApp (0x10d2c1530) and /Users/me/Downloads/SDL2/SDL2.framework/Versions/A/SDL2 (0x10de25e40). One of the two will be used. Which one is undefined.
objc[24875]: Class SDLWindow is implemented in both ./myApp (0x10d2c1558) and /Users/me/Downloads/SDL2/SDL2.framework/Versions/A/SDL2 (0x10de25e68). One of the two will be used. Which one is undefined.
objc[24875]: Class Cocoa_WindowListener is implemented in both ./myApp (0x10d2c1580) and /Users/me/Downloads/SDL2/SDL2.framework/Versions/A/SDL2 (0x10de25e90). One of the two will be used. Which one is undefined.
objc[24875]: Class SDLView is implemented in both ./myApp (0x10d2c15f8) and /Users/me/Downloads/SDL2/SDL2.framework/Versions/A/SDL2 (0x10de25f08). One of the two will be used. Which one is undefined.
objc[24875]: Class SDL_VideoData is implemented in both ./myApp (0x10d2c14e0) and /Users/me/Downloads/SDL2/SDL2.framework/Versions/A/SDL2 (0x10de25f80). One of the two will be used. Which one is undefined.

hello again from myApp, I have initialized SDL2
```

Presumably the problem is that Objective-C requires class names to be globally unique, and if you link SDL2 into a process twice like we're doing here, you'll end up with duplicates.

Is this a known issue? For what it's worth, the app seems to work fine regardless, but I've no idea whether this is causing some problems behind the scenes. For example, it might be using the old (statically-linked) versions of the classes, undermining the whole dynamic concept.

One potential workaround for this that I can see is to not actually use `@interface` and `@implementation` to create SDL2's classes. Instead you could use the Objective-C runtime's dynamic features to construct the classes at runtime. You'd then have the freedom to dynamically select non-conflicting names, or simply not construct the statically-linked classes if they'll be dynamically replaced. (I'd be happy to elaborate if you're interested.)

**Comment by icculus** [comment] 2023-03-17 04:02
I have seen this too.

Since these classes are only ever internal to SDL, I wonder if instead of getting super fancy with the runtime, we could just use the preprocessor to name them something that has the current git revision's hash appended to it? That might be a bad idea, idk.

**Comment by hikari-no-yume** [comment] 2023-03-17 07:18
I'm not sure if you can do that with the preprocessor, but if you can, that sounds like a good solution to me.

**Comment by icculus** [comment] 2023-03-17 14:37
Okay, #7488 does the preprocessor magic, which was surprisingly small, so it's probably a reasonable change to make to SDL2 if nothing else.

Let's hear more about using the dynamic runtime, though, @hikari-no-yume, if you want to talk about it or point me towards some documentation, since that might be a better solution for SDL3.

**Comment by hikari-no-yume** [comment] 2023-03-17 15:54
You could make empty classes with the expected names, and then fill them up with methods at runtime. But you'd still have the clashing names issue. I wonder if “One of the two will be used. Which one is undefined.” implies that one of the two classes will be picked everywhere? If so then this should be no problem. But if some accesses get one version, and some get the other, this would be a non-starter.

**Comment by hikari-no-yume** [comment] 2023-03-17 16:03
> Let's hear more about using the dynamic runtime, though, @hikari-no-yume, if you want to talk about it or point me towards some documentation, since that might be a better solution for SDL3.

Here's the documentation: https://developer.apple.com/documentation/objectivec/objective-c_runtime?language=objc.

Various things that are possible:

* Create a new class at runtime (`objc_allocateClassPair` + `objc_registerClassPair`)
* Add methods to a new or existing class at runtime (`sel_registerName` + `class_addMethod`)
* Copy a method from one class to another (use `method_getImplementation` + `method_getTypeEncoding`, then it's the same as adding a new method)

Alas you can't rename classes at runtime, but I don't think that would solve the problem anyway.

**Comment by icculus** [comment] 2023-03-17 16:49
> People override and customize SDL classes from their applications

Ugh, I didn't know that.

The runtime options, then, will probably solve the problem without generating random names, because right now the problem is that these get set up in some sort of automated dylib loader code, so loading the library at all adds them to the namespace, but if we have control of this at runtime, we simply won't be running any code in the overridden copy of SDL to have this problem.

(This won't help with overriding older copies of SDL from before whatever fix we make, but oh well.)

**Comment by slouken** [comment] 2023-03-17 17:55
Yeah, we'd need to test with an application that overrides the SDL classes, because I'm not sure when that linking happens relative to the SDL initialization process.

**Comment by hikari-no-yume** [comment] 2023-03-17 18:51
Hmm, if you have an upcoming opportunity for breaking changes (SDL 3?), you could make a rule that apps can't statically inherit from SDL classes, but are allowed to dynamically (i.e. create a class inheriting from an SDL one at runtime). Then you'd be able to rename the SDL classes freely.

But I've no idea what to do for SDL 2.

**Comment by slouken** [comment] 2023-11-08 03:10
Duplicate of https://github.com/libsdl-org/SDL/issues/6709

**Closed by slouken** 2023-11-08 03:10 UTC
