### ISSUE TITLE
MACOS clang-fat/gcc-fat fails

### ISSUE THREAD

**Issue by ambitslix** [libsdl-org/SDL#4809] opened 2021-10-04 10:18 UTC
macos Catalina
10.15.7
Intel x86_64
Xcode 12.4 + CLT
macports gcc also installed

```
./configure CC="sh build-scrips/clang-fat.sh"
checking build system type... i386-apple-darwin19.6.0
checking host system type... i386-apple-darwin19.6.0
checking how to print strings... printf
checking for gcc... sh build-scrips/clang-fat.sh
checking whether the C compiler works... no
configure: error: in `/Volumes/Etavirp/Projects/External/build/Darwin_x86_64_Release_Native/SDL':
configure: error: C compiler cannot create executables
See `config.log' for more details

... CONFIG.LOG ...

This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by configure, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure --prefix=/Volumes/Etavirp/Projects/External/local/Darwin_x86_64_Release_Native

## --------- ##
## Platform. ##
## --------- ##

hostname = localhost
uname -m = x86_64
uname -r = 19.6.0
uname -s = Darwin
uname -v = Darwin Kernel Version 19.6.0: Thu Sep 16 20:58:47 PDT 2021; root:xnu-6153.141.40.1~1/RELEASE_X86_64

/usr/bin/uname -p = i386
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = Mach kernel version:
	 Darwin Kernel Version 19.6.0: Thu Sep 16 20:58:47 PDT 2021; root:xnu-6153.141.40.1~1/RELEASE_X86_64
Kernel configured for up to 16 processors.
8 processors are physically available.
16 processors are logically available.
Processor type: x86_64h (Intel x86-64h Haswell)
Processors active: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
Primary memory available: 16.00 gigabytes
Default processor set: 472 tasks, 2261 threads, 16 processors
Load average: 1.60, Mach factor: 14.39
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /opt/local/bin
PATH: /opt/local/sbin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/sbin
PATH: /sbin
PATH: /Library/Apple/usr/bin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2883: checking build system type
configure:2897: result: x86_64-apple-darwin19.6.0
configure:2917: checking host system type
configure:2930: result: x86_64-apple-darwin19.6.0
configure:2971: checking how to print strings
configure:2998: result: printf
configure:3067: checking for gcc
configure:3094: result: build-scripts/clang-fat.sh
configure:3323: checking for C compiler version
configure:3332: build-scripts/clang-fat.sh --version >&5
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
configure:3343: $? = 0
configure:3332: build-scripts/clang-fat.sh -v >&5
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
configure:3343: $? = 0
configure:3332: build-scripts/clang-fat.sh -V >&5
clang: error: argument to '-V' is missing (expected 1 value)
clang: error: no input files
configure:3343: $? = 1
configure:3332: build-scripts/clang-fat.sh -qversion >&5 
clang: error: unknown argument '-qversion'; did you mean '--version'?
clang: error: no input files
configure:3343: $? = 1
configure:3363: checking whether the C compiler works
configure:3385: build-scripts/clang-fat.sh    conftest.c  >&5
XXX 
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libSystem.tbd, missing required architecture arm64 in file /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libSystem.tbd
ld: dynamic main executables must link with libSystem.dylib for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:3389: $? = 1
configure:3427: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3432: error: in `/Volumes/Etavirp/Projects/External/build/Darwin_x86_64_Release_Native/SDL':
configure:3434: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=x86_64-apple-darwin19.6.0
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_set=set
ac_cv_env_CC_value=build-scripts/clang-fat.sh
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXCPP_set=
ac_cv_env_CXXCPP_value=
ac_cv_env_CXXFLAGS_set=
ac_cv_env_CXXFLAGS_value=
ac_cv_env_CXX_set=set
ac_cv_env_CXX_value=g++
ac_cv_env_DBUS_CFLAGS_set=
ac_cv_env_DBUS_CFLAGS_value=
ac_cv_env_DBUS_LIBS_set=
ac_cv_env_DBUS_LIBS_value=
ac_cv_env_DIRECTFB_CFLAGS_set=
ac_cv_env_DIRECTFB_CFLAGS_value=
ac_cv_env_DIRECTFB_LIBS_set=
ac_cv_env_DIRECTFB_LIBS_value=
ac_cv_env_FUSIONSOUND_CFLAGS_set=
ac_cv_env_FUSIONSOUND_CFLAGS_value=
ac_cv_env_FUSIONSOUND_LIBS_set=
ac_cv_env_FUSIONSOUND_LIBS_value=
ac_cv_env_IBUS_CFLAGS_set=
ac_cv_env_IBUS_CFLAGS_value=
ac_cv_env_IBUS_LIBS_set=
ac_cv_env_IBUS_LIBS_value=
ac_cv_env_JACK_CFLAGS_set=
ac_cv_env_JACK_CFLAGS_value=
ac_cv_env_JACK_LIBS_set=
ac_cv_env_JACK_LIBS_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBDRM_CFLAGS_set=
ac_cv_env_LIBDRM_CFLAGS_value=
ac_cv_env_LIBDRM_LIBS_set=
ac_cv_env_LIBDRM_LIBS_value=
ac_cv_env_LIBGBM_CFLAGS_set=
ac_cv_env_LIBGBM_CFLAGS_value=
ac_cv_env_LIBGBM_LIBS_set=
ac_cv_env_LIBGBM_LIBS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_LIBUSB_CFLAGS_set=
ac_cv_env_LIBUSB_CFLAGS_value=
ac_cv_env_LIBUSB_LIBS_set=
ac_cv_env_LIBUSB_LIBS_value=
ac_cv_env_PIPEWIRE_CFLAGS_set=
ac_cv_env_PIPEWIRE_CFLAGS_value=
ac_cv_env_PIPEWIRE_LIBS_set=
ac_cv_env_PIPEWIRE_LIBS_value=
ac_cv_env_PKG_CONFIG_LIBDIR_set=
ac_cv_env_PKG_CONFIG_LIBDIR_value=
ac_cv_env_PKG_CONFIG_PATH_set=
ac_cv_env_PKG_CONFIG_PATH_value=
ac_cv_env_PKG_CONFIG_set=
ac_cv_env_PKG_CONFIG_value=
ac_cv_env_PULSEAUDIO_CFLAGS_set=
ac_cv_env_PULSEAUDIO_CFLAGS_value=
ac_cv_env_PULSEAUDIO_LIBS_set=
ac_cv_env_PULSEAUDIO_LIBS_value=
ac_cv_env_RPI_CFLAGS_set=
ac_cv_env_RPI_CFLAGS_value=
ac_cv_env_RPI_LIBS_set=
ac_cv_env_RPI_LIBS_value=
ac_cv_env_XMKMF_set=
ac_cv_env_XMKMF_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=x86_64-apple-darwin19.6.0
ac_cv_prog_ac_ct_CC=build-scripts/clang-fat.sh

## ----------------- ##
## Output variables. ##
## ----------------- ##

ALLOCA=''
ALSA_CFLAGS=''
ALSA_LIBS=''
AR=''
ARTSCONFIG=''
AS=''
AWK=''
BUILD_CFLAGS=''
BUILD_LDFLAGS=''
CC='build-scripts/clang-fat.sh'
CFLAGS=''
CPP=''
CPPFLAGS=''
CXX='g++'
CXXCPP=''
CXXFLAGS=''
DBUS_CFLAGS=''
DBUS_LIBS=''
DEFS=''
DIRECTFB_CFLAGS=''
DIRECTFB_LIBS=''
DLLTOOL=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C='\c'
ECHO_N=''
ECHO_T=''
EGREP=''
ENABLE_SHARED_FALSE=''
ENABLE_SHARED_TRUE=''
ENABLE_STATIC_FALSE=''
ENABLE_STATIC_TRUE=''
ESD_CFLAGS=''
ESD_CONFIG=''
ESD_LIBS=''
EXEEXT=''
EXTRA_CFLAGS=''
EXTRA_LDFLAGS=''
FGREP=''
FUSIONSOUND_CFLAGS=''
FUSIONSOUND_LIBS=''
GEN_HEADERS=''
GEN_OBJECTS=''
GREP=''
IBUS_CFLAGS=''
IBUS_LIBS=''
INCLUDE=''
INSTALL_DATA=''
INSTALL_PROGRAM=''
INSTALL_SCRIPT=''
INSTALL_SDL2_CONFIG=''
JACK_CFLAGS=''
JACK_LIBS=''
LD=''
LDFLAGS=''
LIBDRM_CFLAGS=''
LIBDRM_LIBS=''
LIBGBM_CFLAGS=''
LIBGBM_LIBS=''
LIBOBJS=''
LIBS=''
LIBTOOL=''
LIBTOOLLINKERTAG=''
LIBUSB_CFLAGS=''
LIBUSB_LIBS=''
LINKER=''
LIPO=''
LN_S=''
LTLIBOBJS=''
LT_AGE=''
LT_CURRENT=''
LT_RELEASE=''
LT_REVISION=''
MANIFEST_TOOL=''
NM=''
NMEDIT=''
OBJDUMP=''
OBJECTS=''
OBJEXT=''
OTOOL64=''
OTOOL=''
PACKAGE_BUGREPORT=''
PACKAGE_NAME=''
PACKAGE_STRING=''
PACKAGE_TARNAME=''
PACKAGE_URL=''
PACKAGE_VERSION=''
PATH_SEPARATOR=':'
PIPEWIRE_CFLAGS=''
PIPEWIRE_LIBS=''
PKGCONFIG_LIBS_PRIV=''
PKG_CONFIG=''
PKG_CONFIG_LIBDIR=''
PKG_CONFIG_PATH=''
POW_LIB=''
PULSEAUDIO_CFLAGS=''
PULSEAUDIO_LIBS=''
RANLIB=''
RC=''
RPI_CFLAGS=''
RPI_LIBS=''
SDLMAIN_OBJECTS=''
SDLTEST_OBJECTS=''
SDL_BINARY_AGE='17'
SDL_CFLAGS=''
SDL_INTERFACE_AGE='0'
SDL_LIBS=''
SDL_MAJOR_VERSION='2'
SDL_MICRO_VERSION='17'
SDL_MINOR_VERSION='0'
SDL_RLD_FLAGS=''
SDL_STATIC_LIBS=''
SDL_VERSION='2.0.17'
SED=''
SET_MAKE=''
SHELL='/bin/sh'
STRIP=''
VERSION_OBJECTS=''
WAYLAND_SCANNER=''
WAYLAND_SCANNER_CODE_MODE=''
XMKMF=''
X_CFLAGS=''
X_EXTRA_LIBS=''
X_LIBS=''
X_PRE_LIBS=''
ac_aux_dir='build-scripts'
ac_ct_AR=''
ac_ct_CC='build-scripts/clang-fat.sh'
ac_ct_CXX=''
ac_ct_DUMPBIN=''
bindir='${exec_prefix}/bin'
build='x86_64-apple-darwin19.6.0'
build_alias=''
build_cpu='x86_64'
build_os='darwin19.6.0'
build_vendor='apple'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE}'
dvidir='${docdir}'
exec_prefix='NONE'
host='x86_64-apple-darwin19.6.0'
host_alias=''
host_cpu='x86_64'
host_os='darwin19.6.0'
host_vendor='apple'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/Volumes/Etavirp/Projects/External/local/Darwin_x86_64_Release_Native'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""

configure: exit 77

```

I can build SDL2 with configure default and clang. I'd like to build universal. Is this the right path at this point?

I also tried via cmake and "-DCMAKE_OSX_ARCHITECTURES:STRING=arm64;x86_64" and it builds a proper fat library. 

gcc-fat fails also:
```
configure:3385: SDL/build-scripts/gcc-fat.sh    conftest.c  >&5
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/crt1.10.6.o, building for macOS-i386 but attempting to link with file built for unknown-x86_64
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libSystem.tbd
Undefined symbols for architecture i386:
  "start", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:3389: $? = 1
```

Any suggestions?

**Comment by icculus** [comment] 2021-11-18 04:45
gcc-fat is probably going to be removed (Apple has moved on to Clang), but I'll look at the clang-fat errors.

**Comment by icculus** [comment] 2021-11-19 14:39
Okay, I removed gcc-fat.sh (the primary problem there is it wants to build universal binaries with i386, which Apple's tools won't do anymore, and doesn't build arm64 at all, even discounting that it wants to use gcc instead of clang).

As for the other problem: it looks like it's finding the wrong macOS SDK (it found 10.15, presumably arm64 requires 11.0). I'm not sure why yet; moving to Xcode 13 might magically fix this, but I'll poke this today on Xcode 12 and see what happens.

**Comment by icculus** [comment] 2021-11-20 18:06
Okay, I've tried this on a Mac with Xcode 12.5 and it works here. I would recommend you run `sudo xcode-select -r` to reset the default toolchain to Xcode instead of /Library/Developer/CommandLineTools, and that will _probably_ solve the issue for you.

Alternately: upgrade CommandLineTools...? The issue is you need a newer SDK to build ARM64 binaries, even though we can target older macOS releases with the thing that gets built with the newer SDK.

**Closed by icculus** 2021-11-20 18:06 UTC

**Comment by ambitslix** [comment] 2021-11-21 05:16
Thanks for looking into it. I got around the problem by building under macos via cmake and clang without those scripts.
