### ISSUE TITLE
Viewport clipping issue in SDL 2.0.22

### ISSUE THREAD

**Issue by Marin-MK** [libsdl-org/SDL#5786] opened 2022-06-12 12:39 UTC
I don't know precisely what the issue is, so I'll do my best to demonstrate it visually and describe it.

I have a viewport (the cursor in the videos below) that moves around a lot, but in my upgrade from SDL 2.0.20 to 2.0.22, it seems to create a clipping issue with another viewport (the vignette fade around the central part of the window), where that fade viewport gets cut off wherever the cursor viewport ends.

The fade viewport has a Z index of 9 (i.e. it gets rendered and the viewport gets clipped first), and then the cursor viewport has a Z index of 8, meaning I render and clip its viewport later. I use `SDL_RenderSetViewport` to clip my viewports.

For quick reference, the solid black lines represent viewport boundaries, and here's what the window looks like when the cursor viewport does not go beyond the fade viewport's boundaries:
![image](https://user-images.githubusercontent.com/25814892/173233216-b3c20aaa-5fa7-475b-9161-62519cf5a87d.png)

Then when the cursor is moved to go below the fade viewport's boundaries on both the x and y axes (it does not happen when it only goes over its boundaries on one axis!):
![image](https://user-images.githubusercontent.com/25814892/173233286-9b4dbbd9-4314-4e1d-bd5d-284734a58f99.png)

Another important thing to note is that it also only happens when the viewport goes beneath the other viewport boundaries, and therefore NOT when it exceeds the width and/or height.

Here is a video of me doing the exact same thing in both SDL 2.0.20 and SDL 2.0.22: [https://streamable.com/soddur](https://streamable.com/soddur)

What is also curious is that it only happens with this cursor viewport. I have plenty of other viewports clipping in other parts of the program, but none have any issue. Furthermore, this issue also does not happen with the map itself, despite that also being its own viewport.

I hope I've described the issue in-depth enough to make clear what the issue is. The issue can't be in my code, because my SDL2 wrapper has worked flawlessly since version 2.0.6 and this bug was only introduced in version 2.0.22. I find it unlikely that this would have been an intended change in functionality.

**Comment by 1bsyl** [comment] 2022-06-13 18:25
@Marin-MK 
which platform are you on ?
can you try to switch to another SDL_Renderer (eg opengl / software).
Can you try with latest git version ?

and best, would be to do a git bisect to find which commit is the culprit .
and/or reduce to a small testcase..

**Comment by icculus** [comment] 2022-06-13 20:01
Does this just need a build of https://github.com/Marin-MK/RPG-Studio-MK with the latest SDL to trigger it? Let me know if you want me to try and reproduce it over here.

**Comment by Marin-MK** [comment] 2022-06-14 14:21
> Does this just need a build of https://github.com/Marin-MK/RPG-Studio-MK with the latest SDL to trigger it? Let me know if you want me to try and reproduce it over here.

It's a bit more involved than that, so I won't bother you with all the steps to running the program.

I have found some valuable information though. Until now I've left which driver was being selected up to chance, that is to say, I created my renderers with `SDL_CreateRenderer(..., -1, ...)`, but now that I've started looking into this bug more and having tried different drivers, it's become clear that this bug only happens whenever I pass `-1` as the driver index when creating a renderer. My default driver that's being used is Direct3D, but this bug only happens if I pass `-1`, and not if I pass `0`, which is Direct3D. So same driver but different methods of creating the renderer.

**Comment by icculus** [comment] 2022-06-14 16:49
It's not clear to me what in 1ede941f5c1fce3c9091c6999b732f8150bbf400 causes this bug, but if the bug only happens when creating a renderer with -1 instead of 0, it means it's probably related to batching.
 
Can you verify that it's definitely commit 1ede941f5c1fce3c9091c6999b732f8150bbf400, and it definitely works with renderer 0 and does _not_ work with renderer -1? Just in case those values were changing as you tried different commits.

Sorry to make you do all this legwork, but I think we're pretty close to the culprit now.

**Comment by icculus** [comment] 2022-06-14 18:10
I'm marking this as fixed in a moment of overconfidence, but I think this _should_ fix your problem!

**Closed** 2022-06-14 18:10 UTC

**Comment by icculus** [comment] 2022-06-16 03:40
I don't feel strongly about it, but since there's so few in the source, it might be worth changing them all to `sizeof (varname)`, as long as we don't accidentally do it to a pointer instead of the thing it points to.

Which is to say, I don't mind if _someone else_ does it.  :)

**Comment by sezero** [comment] 2022-06-16 18:11
Isn't there is the issue of src and dest being of same type though? If it were only gcc, type checking would be easy.

**Comment by slouken** [comment] 2022-06-16 18:53
I think the size check is sufficient.

**Comment by 1bsyl** [comment] 2022-06-16 22:22
see PR, it now builds !
