### ISSUE TITLE
WASAPI: Audio distortion 22kHz

### ISSUE THREAD

**Issue by glebm** [libsdl-org/SDL#5538] opened 2022-04-15 16:27 UTC
The WASAPI audio backend introduces distortion when resampling from 22 kHZ.

https://github.com/libsdl-org/SDL/blob/01b14e14e63ac85d295755880bcf7d441c4ff0ce/src/audio/wasapi/SDL_wasapi.c#L562-L566

Spectrogram recorded by @ikonomov:

![Spectrogram](https://user-images.githubusercontent.com/5624187/163593754-ff8af29f-0742-46a0-8264-77d0b14b3706.jpg)

Original report and more details: https://github.com/diasurgical/devilutionX/issues/1390

**Comment by glebm** [comment] 2022-04-15 17:04
Reading the docs over at https://docs.microsoft.com/en-us/windows/win32/coreaudio/audclnt-streamflags-xxx-constants, it seems that we're supposed to use `IAudioClockAdjustment` with `AUDCLNT_STREAMFLAGS_RATEADJUST`.

Something like this:

```c
    if (flags & AUDCLNT_STREAMFLAGS_RATEADJUST) {
        IAudioClockAdjustment *adjustment;
        IAudioClient_GetService(client, &IID_IAudioClockAdjustment, (void **)&adjustment);
        IAudioClockAdjustment_SetSampleRate(adjustment, rate);
        IAudioClockAdjustment_Release(adjustment);
    }
```

**Comment by glebm** [comment] 2022-04-15 20:52
Looks like the issue only occurs with certain audio drivers.

One user reported this happening with the RME "Pro" Audio driver but not the default Windows one.

**Comment by sezero** [comment] 2022-05-18 18:57
vkQuake received a report about popping / crackling audio present in 2.0.22 but not before:
https://github.com/Novum/vkQuake/issues/469 - _possibly_ because of commit https://github.com/libsdl-org/SDL/commit/9e264b921b2f81e2c3d55693f76e06d143c2fbb7?

**Comment by icculus** [comment] 2022-05-18 22:31
I couldn't hear it in the example video.   😬

I'll listen again with headphones tonight, but can someone else make sure I'm not missing the obvious crackle?

**Comment by sezero** [comment] 2022-05-24 20:05
@icculus: is there any progress on this?

**Comment by zenxero** [comment] 2022-05-25 03:09
@slouken 
Hello, I was the one who opened the issue with vkQuake. Yes, replacing the `SDL2.dll` file with an older one like this fixes the audio distortion.

http://libsdl.org/release/SDL2-2.0.20-win32-x64.zip

**Comment by zenxero** [comment] 2022-05-25 03:15
@icculus 
The popping distortion sound should be the most noticeable from the axe "tings" at timestamp 2:43 in the video.

https://www.youtube.com/watch?v=oGWM9bWph2A


I'm not sure if it helps, but I've tried this on both of my Windows 10 machines (laptop and desktop), and it happens on both. They are AMD systems with Realtek audio chips. The distortion happens regardless of if I'm using the 3.5mm jack or a USB audio interface.

**Comment by icculus** [comment] 2022-05-25 18:51
> IIRC, did that not happen in git master? The issue is reported for 2.0.22.

Oh, hmm, yes.

**Comment by icculus** [comment] 2022-05-25 19:31
I went back and checked again...I have to be honest, I can't hear it in the youtube video even with headphones on, I can't hear it in a Linux build using the latest git of vkQuake and SDL. It sounds the same to me in both versions in the video.

My hearing is not great, but I don't hear any crackle in it at all.

Here, this is the audio output of the youtube video during the axe strikes. Can you tell me which one is from 2.0.20 and which is from 2.0.22?

https://www.dropbox.com/s/gvkbrepl3vmydd8/axes.wav?dl=0

**Comment by icculus** [comment] 2022-05-25 19:33
(I don't see anything that looks significantly different between the waveforms in that .wav file, when loaded in Audacity, either, but looks _can_ be deceiving in this regard.)

**Comment by vladkosi** [comment] 2022-05-25 19:56
They look slightly different (right side is 2.0.22), but I can't hear the crackling.

![1](https://user-images.githubusercontent.com/6567423/170355779-dd7977aa-4df4-4469-812e-f00544b0c5dc.png)

**Comment by zenxero** [comment] 2022-05-25 20:49
The one on the right has the crackling. I can hear it in the audio file played through audacity.

**Comment by zenxero** [comment] 2022-05-25 20:59
These large spikes here are the popping/crackling sound
![Screenshot 2022-05-25 135747123](https://user-images.githubusercontent.com/87404368/170366148-4befe66a-9a03-4056-bfd9-6a35bc5b2997.png)

**Comment by sezero** [comment] 2022-05-25 21:13
Is this purely personal experience or is the hardware in use really have a play?

**Comment by zenxero** [comment] 2022-05-25 21:26
@sezero 
I'm not sure I understand the question

**Comment by vladkosi** [comment] 2022-05-25 21:39
I've tried with headphones and I could hear popping in the sample file, but I couldn't reproduce the bug. All my WASAPI loopback recordings look and sound like the one on the left. Tested with vkQuake 1.13.1, SDL 2.0.20 and 2.0.22.

**Comment by sezero** [comment] 2022-05-25 21:45
> @sezero I'm not sure I understand the question

You hear clicks/pops, @icculus can not, and I could not either (but I'm
not audiophile.) Some hear, some don't: That was the question, i.e.: is
the issue really an issue or does the hardware (the sound card, speakers,
drivers, etc) has an effect?

I initially thought that commit 9e264b9 might be at fault, however that
commit was meant to workaround distortions cause by WASAPI's resampler.

It have a feeling that this _might_ be a non-bug, but I really don't know.

**Comment by zenxero** [comment] 2022-05-25 21:48
I'm not sure if my particular audio drivers or DAC are the problem or not. There is definitely extra popping/crackling there where there shouldn't be. But that's what I'm trying to figure out.

At least one other person in the original vkQuake issue reported that they had the same problem.
https://github.com/Novum/vkQuake/issues/469#issuecomment-1130560702

@vladkosi said that they could hear it, but couldn't reproduce it on their system.

**Comment by zenxero** [comment] 2022-05-25 22:13
Ok, so I tested vkQuake 1.13.1 on the Steam Deck (Linux) and it does NOT have the audio crackling or popping issue that my Windows machines have.

**Comment by vladkosi** [comment] 2022-05-25 22:22
@zenxero What is your audio device's sample rate setting in Windows?

At 44100 Hz there should be no resampling done by SDL: https://github.com/Novum/vkQuake/blob/master/Quake/snd_sdl.c#L89 (snd_mixspeed is 44100).

**Comment by zenxero** [comment] 2022-05-25 22:25
Looks like it's 48000 Hz

I'm using one of these desktop USB DAC + AMP devices:
https://jdslabs.com/product/element-ii/

![Screenshot 2022-05-25 152415](https://user-images.githubusercontent.com/87404368/170379086-e3abf5f0-6ba2-42b2-ac22-19a74b9463f2.png)

**Comment by zenxero** [comment] 2022-05-25 22:34
Ah, well now I feel stupid. Turns out if I force my audio device to use 44100 Hz instead of 48000 Hz, the popping/crackling goes away. I'm sorry for the trouble, this seems to have solved the issue.

![facepalm](https://user-images.githubusercontent.com/87404368/170380384-45d33dd8-ef82-484c-8d06-72dc7ea05fb4.png)

**Comment by slouken** [comment] 2022-05-25 22:38
SDL should be resampling without popping and crackling from 44100 Hz to 48000 Hz. @icculus, can you reproduce this if you force 48Khz output?

**Comment by slouken** [comment] 2022-05-25 22:40
Or maybe it's the Windows resampler that introduced the crackling, and it's now fixed because we're using SDL's resampler in the latest code?

**Comment by vladkosi** [comment] 2022-05-25 22:51
I can reproduce it at 48000 Hz. Left side is 2.0.20, right side 2.0.22:

![1](https://user-images.githubusercontent.com/6567423/170381809-9fc956fa-8228-4203-8494-678f31b4b916.png)

**Comment by icculus** [comment] 2022-05-25 22:52
What do you do to make Audacity show that view? I just get a simple waveform in mine.

**Comment by vladkosi** [comment] 2022-05-25 22:53
https://manual.audacityteam.org/man/spectrogram_view.html

**Comment by vladkosi** [comment] 2022-05-25 22:55
Here is the recording: [1.zip](https://github.com/libsdl-org/SDL/files/8775022/1.zip)

**Comment by vladkosi** [comment] 2022-05-26 12:42
Seems like the 48 kHz output is the most broken. 96 kHz and 192 kHz don't look as bad:

![1](https://user-images.githubusercontent.com/6567423/170488608-e16ae770-53b2-47a9-97c5-d7a848eb20dc.png)

**Comment by icculus** [comment] 2022-05-26 13:14
I dunno, I can see it in all resamples. Here it is, pushed through SDL_sound's playsound app, which lets you resample before feeding to SDL, then I used SDL's disk audio driver to write PCM to disk instead of to an audio device...

![image](https://user-images.githubusercontent.com/673562/170494720-9005ab5b-c9a5-42ba-81f5-addb68918c88.png)

(Original wav at 44100, playback with no resampling, then 48000, 96000, 192000)

**Comment by icculus** [comment] 2022-05-26 13:16
...although it definitely elongates in lower sampling rates if you zoom in to look at it...

![image](https://user-images.githubusercontent.com/673562/170495120-8156e9bc-1a13-4030-894d-97cdd5b9c510.png)

**Comment by icculus** [comment] 2022-05-26 13:18
I really can't believe this small change in the waveform is making _this_ much of a difference.

![image](https://user-images.githubusercontent.com/673562/170495529-5881647c-c7cf-40e2-b01c-de7c2d798387.png)

**Comment by vladkosi** [comment] 2022-05-26 13:21
You can switch to dB view to see the change more clearly: https://manual.audacityteam.org/man/audacity_waveform.html#db

**Comment by icculus** [comment] 2022-05-27 02:53
I still haven't figured this one out; I'm fried, I'll try again in the morning.

**Comment by icculus** [comment] 2022-05-29 14:21
I've been looking at this forever and can't see what's wrong; I'm spending too much time on this, so I'm going to come back to this later in the milestone.

**Comment by icculus** [comment] 2022-06-14 03:29
Wondering if these old bug reports are related: #2715 #2716

**Comment by ericoporto** [comment] 2023-08-06 17:28
Sorry to ping, I can't reproduce this but am curious if there's any updates on this.

**Comment by icculus** [comment] 2023-10-04 14:46
Went back and tested this with SDL3, and we have fixed this.

I don't have the original data from the first time I generated these graphs, but here's a resampling from the first half of the axes.wav I posted up above:

![image](https://github.com/libsdl-org/SDL/assets/673562/77c45b59-dd4f-407a-9d5c-d3bd37302c5d)

This is what it looks like with SDL2's resampler...the garbage is less severe, either because we made fixes or this is working from data we already resampled once, I don't know, but you can see there's still garbage in the spectrogram in any case, especially at 48000Hz...
 
![image](https://github.com/libsdl-org/SDL/assets/673562/2dbe5762-5378-4e3f-9f96-efd20b1dd93c)

So I _think_ we're good to go in SDL3.

There's no chance we're backporting this to SDL2, though, as all this code was completely rewritten. Even discounting the idea of migrating bugfixes to SDL2 here, I don't think I could even drop the new resampler code into SDL2 as a complete replacement, in any reasonable way. But for games not migrating to SDL3, sdl2-compat will take advantage of the new resampler.

**Closed by icculus** 2023-10-04 14:46 UTC
