### ISSUE TITLE
Display hotplugging events for Linux

### ISSUE THREAD

**Issue by paleajed** [libsdl-org/SDL#4977] opened 2021-11-18 04:07 UTC
There has just been added a system for hotplugging screen displays for Windows (with an event system).  Now we need this for Linux too.

**Comment by flibitijibibo** [comment] 2021-11-18 05:02
For Wayland this means adding connect/disconnect events via this listener and wl_output:

https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandvideo.c#L598

We of course have the add event done, remove not so much. My budget for new features in 2.0.18 is spent so if someone else wants to tackle this it's all yours.

**Comment by flibitijibibo** [comment] 2021-11-18 05:45
Woops turns out I didn't read the VideoDisplay helpers well enough, this is effectively already done, just had to wire up DelVideoDisplay (which was effectively fixing a memory leak): https://github.com/libsdl-org/SDL/commit/a7a54e64520cff54133f189a3cf4dd1f26395b2c

Keeping this open for X11 but Wayland should be fine now.

**Comment by icculus** [comment] 2022-06-06 06:17
Okay, I took a first shot at this for X11.

Now at startup, with `SDL_EVENT_LOGGING=1`, I get:

```
INFO: SDL EVENT: SDL_DISPLAYEVENT (timestamp=4 display=0 event=SDL_DISPLAYEVENT_CONNECTED data1=0)
```

Plugging a TV into the HDMI port of my laptop at runtime reports:

```
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=21991 windowid=1 event=SDL_WINDOWEVENT_EXPOSED data1=0 data2=0)
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=22084 windowid=1 event=SDL_WINDOWEVENT_EXPOSED data1=0 data2=0)
INFO: SDL EVENT: SDL_DISPLAYEVENT (timestamp=22226 display=1 event=SDL_DISPLAYEVENT_CONNECTED data1=0)
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=23209 windowid=1 event=SDL_WINDOWEVENT_ICCPROF_CHANGED data1=0 data2=0)
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=23209 windowid=1 event=SDL_WINDOWEVENT_ICCPROF_CHANGED data1=0 data2=0)
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=23209 windowid=1 event=SDL_WINDOWEVENT_ICCPROF_CHANGED data1=0 data2=0)
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=23209 windowid=1 event=SDL_WINDOWEVENT_ICCPROF_CHANGED data1=0 data2=0)
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=23209 windowid=1 event=SDL_WINDOWEVENT_ICCPROF_CHANGED data1=0 data2=0)
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=23209 windowid=1 event=SDL_WINDOWEVENT_ICCPROF_CHANGED data1=0 data2=0)
```

And then unplugging it gets me:

```
INFO: SDL EVENT: SDL_DISPLAYEVENT (timestamp=45653 display=1 event=SDL_DISPLAYEVENT_DISCONNECTED data1=0)
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=45881 windowid=1 event=SDL_WINDOWEVENT_EXPOSED data1=0 data2=0)
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=45881 windowid=1 event=SDL_WINDOWEVENT_EXPOSED data1=0 data2=0)
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=45896 windowid=1 event=SDL_WINDOWEVENT_EXPOSED data1=0 data2=0)
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=45896 windowid=1 event=SDL_WINDOWEVENT_EXPOSED data1=0 data2=0)
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=45958 windowid=1 event=SDL_WINDOWEVENT_EXPOSED data1=0 data2=0)
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=45959 windowid=1 event=SDL_WINDOWEVENT_EXPOSED data1=0 data2=0)
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=46265 windowid=1 event=SDL_WINDOWEVENT_ICCPROF_CHANGED data1=0 data2=0)
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=46276 windowid=1 event=SDL_WINDOWEVENT_ICCPROF_CHANGED data1=0 data2=0)
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=46477 windowid=1 event=SDL_WINDOWEVENT_ICCPROF_CHANGED data1=0 data2=0)
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=46477 windowid=1 event=SDL_WINDOWEVENT_ICCPROF_CHANGED data1=0 data2=0)
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=46477 windowid=1 event=SDL_WINDOWEVENT_ICCPROF_CHANGED data1=0 data2=0)
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=46478 windowid=1 event=SDL_WINDOWEVENT_ICCPROF_CHANGED data1=0 data2=0)
```

It will need some testing still, of course.

**Comment by flibitijibibo** [comment] 2022-06-21 00:56
There seems to be a super _super_ tiny regression, which is that the X11 backend sends connect events on startup when technically it should only do it _after_ the video subsystem initializes. Wayland implementation, for reference:

https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandvideo.c#L670

This bug can be seen in Axiom Verge 1, if you toggle fullscreen it tries to set a backbuffer to 0,0 because of a bug in FNA where we get a displayevent that breaks our display enumeration. The bug in FNA has been fixed, but it did help identify the difference here!

**Comment by icculus** [comment] 2022-06-21 18:50
Okay, @flibitijibibo, retest Axiom Verge when you have a moment, but 12b371ee0ffefcd27f3cc38679d7fe58ac8a8459 should resolve the issue.

**Comment by flibitijibibo** [comment] 2022-06-22 13:44
Fixed by https://github.com/libsdl-org/SDL/commit/12b371ee0ffefcd27f3cc38679d7fe58ac8a8459

**Closed by flibitijibibo** 2022-06-22 13:44 UTC
Labels: enhancement
