### ISSUE TITLE
X11: SDL stops receiving keyboard input while window is being moved or resized

### ISSUE THREAD

**Issue by weirddan455** [libsdl-org/SDL#7385] opened 2023-03-01 18:59 UTC
Tested on Arch Linux on both SDL2 and SDL3.

This effects both the event loop as well as the array returned by `SDL_GetKeyboardState`.  Keyboard events stop coming in all together and the array stops being updated.  If you hold down a key, start moving the window, and then release the key, that key will continue to show as pressed in the array until you let go of the mouse (even if the window stays in one place, just holding the mouse over the title bar is enough to stop the events).

I dug into this a bit and found that Xlib simply stops sending events in this case (I have a game coded in raw Xlib that I tested with).  However, calling `XQueryKeymap` gives the correct current state of the keyboard.

As far as SDL is concerned, I saw this is already a half-way workaround.  Xlib never actually sends a key release event when you finish moving the window.  However, it does send a `KeymapNotify` which SDL handles by calling this function that calls `XQueryKeymap` and updates the keyboard state.

https://github.com/libsdl-org/SDL/blob/2f14b367096fa5313dd8ffdd07be1142c83918e5/src/video/x11/SDL_x11events.c#L400-L411

I'm not sure what the best solution to this is.  I would prefer to have an API that simply queries the keyboard state when I call it.  I assumed that's what `SDL_GetKeyboardState` would do but I was incorrect.  It instead tries to stay synchronized with the events API which, for my use case, I don't care about.

Perhaps for SDL3, we can have such an API that would just call `XQueryKeymap` under the hood?  Another alterantive I thought of was to simply call that work-around function `X11_ReconcileKeyboardState` every frame (or at least while the window is being moved), though I suspect that might have its own problems.

**Comment by icculus** [comment] 2023-11-17 00:59
To be clear: this corrects itself when the window is done moving, because we get a KeymapNotify then, so the problem is how to get the correct keystate _during_ the mouse drag?

(And, I don't _think_ this would be a window manager issue, but we're sure this is the X server causing this and not the window manager, right...?)

**Comment by icculus** [comment] 2023-11-28 19:38
I'm closing this as not planned, assuming that this is a request to track the key state during a drag operation and it otherwise works.

(But if I'm misunderstanding, we can reopen the issue, and if you might at some point have a patch that can handle this cleanly and without a lot of overhead, we can talk about applying it.)

**Closed by icculus** 2023-11-28 19:38 UTC
Labels: waiting
