### ISSUE TITLE
Random termination with X errors when resizing by dragging followed by SDL_SetWindowSize

### ISSUE THREAD

**Issue by TimothyEBaldwin** [libsdl-org/SDL#4078] opened 2021-02-13 20:01 UTC
When running on X11 on Ubuntu 20.10 x86-64 with the following test case randomly terminates when the window is resize by dragging or by a scripted simulation with an X error like:

```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  3 (X_ShmPutImage)
  Value in failed request:  0x355
  Serial number of failed request:  22989
  Current serial number in output stream:  22990
```

This usually happens within 1000 resize operations.

* With Wayland support disabled a git bisect run finds commit ed10d9473f62131890166c3b6bcf71db5e53b444 is the first bad commit. Valgrind memcheck finds no memory errors in SDL.
* With Wayland support enabled: 272ebb8efb786a06091357a673b1b274cf4cb6e2 is the first bad commit.
* On Ubuntu 20.04 ARM64 without (and maybe with) Wayland support 1b82606e1dbb2a1b0c581efcd46a257c752826dd is the first bad commit.
* On Ubuntu 20.04 x86-64 without (and maybe with) Wayland support  it works without error.

The test case requires the `gcc make xvfb bubblewrap kwin wmctrl libsdl2-dev ccache wayland-protocols` Ubuntu packages. I have not tried it with a different window manger.

```
#!/bin/bash

run() {
  mkdir -p /var/lib/dbus/ /run
  export PATH="/usr/lib/ccache:$PATH"
  dbus-uuidgen --ensure
  cp -a /s /b
  cd /b
  ./configure CFLAGS="-g -O0" --prefix /i --enable-video-wayland
  make install -j$(getconf _NPROCESSORS_ONLN) -k
  cd /
  gcc /test.c $(/i/bin/sdl2-config --cflags --libs)  || exit 125

  touch flag
  kwin &
  kwin=$!
  sleep 1
  (./a.out; rm flag) &
  testcase=$!
  sleep 1

  i=1
  while [[ -e flag && $i -lt 10000 ]]; do
    wmctrl -r :ACTIVE: -e 0,$(( $RANDOM / 32 )),$(( $RANDOM / 32 )),$(( $RANDOM / 32 )),$(( $RANDOM / 32 ))
    i=$(( $i + 1 ))
    sleep 0.01
    echo $i
  done

  rm flag
  kill $testcase
  kill $kwin
  echo $i resizes
  [[ $i -eq 10000 ]]
}

export -f run
mkdir -p ccache

bwrap --unsetenv TMPDIR --unshare-all                \
--ro-bind /bin /bin                                  \
--ro-bind /lib /lib                                  \
--ro-bind /usr /usr                                  \
--ro-bind-try /lib64 /lib64                          \
--ro-bind-try /etc/alternatives /etc/alternatives    \
--bind ccache /c --setenv CCACHE_DIR /c              \
--ro-bind . /s                                       \
--tmpfs /s/ccache                                    \
--tmpfs /s/.git                                      \
--proc /proc                                         \
--dev /dev                                           \
--dir /tmp                                           \
--file 9 /test.c 9<<END                              \
bash xvfb-run bash -c run

#include <SDL.h>
#include <SDL_video.h>
#include <SDL_surface.h>

static char *pixels[1024*1024];

int main(int argc, char **argv) {

  SDL_Init(SDL_INIT_VIDEO);
  SDL_Window *window = SDL_CreateWindow("TEST", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 640, 480, SDL_WINDOW_SHOWN | SDL_WINDOW_RESIZABLE);
  SDL_Surface *screen = SDL_CreateRGBSurfaceFrom((void*)pixels, 640, 480, 8, 480, 0, 0, 0, 0);

  while(1) {
    SDL_Event e;
    SDL_WaitEvent(&e);
    switch(e.type) {
      case SDL_WINDOWEVENT:
        if (e.window.event == SDL_WINDOWEVENT_RESIZED) {
          for(int i = 1; i != 10; ++i) {
            SDL_Delay(1);
            SDL_PumpEvents();
          }
          SDL_SetWindowSize(window, e.window.data1, e.window.data2);
        }
        break;
      case SDL_QUIT:
        return 0;
    }
    SDL_BlitSurface(screen, 0, SDL_GetWindowSurface(window), 0);
    SDL_UpdateWindowSurface(window);
  }
}
END
```
This test case is based upon a frontend to a virtual machine. The test case is sandboxed to rule out user and machine configuration as the cause.

**Comment by icculus** [comment] 2021-02-14 02:56
This seems like an unreliable result from bisecting, fwiw. I'll try to reproduce here, though.

**Comment by TimothyEBaldwin** [comment] 2021-02-21 12:15
As the Debian package of 2.0.9 is good, I tried running git bisect on gcc, testing with SDL 2.0.9. This lead me to discover adding `-fcommon` gcc option causes SDL 2.0.9 to work. 

On Ubuntu 20.10 x86-64 a git bisect on SDL with `-fcommon` and `--enable-video-wayland` finds 1b82606e1dbb2a1b0c581efcd46a257c752826dd is the first bad commit.

**Comment by icculus** [comment] 2021-04-24 21:29
Okay, I've been fighting with this for way too long, and still don't have a reasonable fix, but here's what's happening:

- the test program gets a resize event
- the test program tries to set the window to the size it is already, but the window manager is simultaneously trying to resize it.
- both of these resize events (window manager and app itself) are racing through the X server, and...
- the UpdateWindowSurface call tries to run with a bogus window size eventually, because it's still changing, and everything explodes.

The short answer here is "don't resize the window in response to a resize event" ... which I suspect is a leftover from 1.2, where you had to call SDL_SetVideoMode() in response to window resize events, and some tutorial probably recommended this.

I think fixing this is going to be a corner case (it's already a corner case for using SDL_UpdateWindowFramebuffer!), and we should probably leave this as WONTFIX instead of trying to coerce this to synchronize.

**Closed** 2021-05-08 16:23 UTC
Labels: bug, wontfix
