### ISSUE TITLE
wayland window decorations occluded by GNOME top bar after exiting fullscreen

### ISSUE THREAD

**Issue by cgutman** [libsdl-org/SDL#4571] opened 2021-08-01 23:59 UTC
It looks like the SDL window doesn't get repositioned after exiting fullscreen on GNOME 40. As a result, the  libdecor window decorations are drawn underneath the GNOME top bar, making them inaccessible.

Reproduced on: cfcdfb7be9f5c97a51ddef9ad3677a604856266b

Steps to reproduce:
1. Run `SDL_VIDEODRIVER=wayland ./testgl2 --fullscreen --resizable`
2. Press Ctrl+Enter to toggle fullscreen

![Screenshot from 2021-08-01 18-55-24](https://user-images.githubusercontent.com/2695644/127789151-3ec81a5b-ca96-4815-ba7b-6aefcbab9391.png)

**Comment by dos1** [comment] 2021-08-02 00:05
This seems like a GNOME Shell bug, SDL has no way to influence window position. Possibly related to negative values in `set_window_geometry` as used by libdecor. It may be best to report it on GNOME bugtracker and provide `WAYLAND_DEBUG=client` logs there.

**Comment by flibitijibibo** [comment] 2021-08-02 01:33
At one point there was interest in exposing an API that UsableBounds would work with, but yeah the position is completely out of our hands.

https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/41

**Comment by christianrauch** [comment] 2021-08-02 21:21
When I run `testgl2` without libdecor, I get a similar result in that the window will be restored in the top-left corner. This is comparable to your libdecor case, since the toplevel surface is restore in the top left, just the decoration surface which extend the toplevel surface will be below the "shell surfaces".

So, this problem is not libdecor specific but related to how SDL restores the window state. Also, you are restoring to floating-mode via the client (by using the clients key inputs). If you would restore via the compositor / server-side, you would end up with a different issue. If you want to test, you have to assign a shortcut to the "toggling fullscreen" function in the keyboard settings of GNOME Shell. Then you can let the compositor send set_fullscreen/unset_fullscreen events to the client. Both issues should be fixed first for the xdg code path (without libdecor) before we try to fix them for libdecor.

**Comment by flibitijibibo** [comment] 2021-08-02 21:29
Isn't the xdg path just to call `unset_fullscreen`? What else is a client supposed to do after that? In our configure callback the only thing we do in the non-fullscreen case is set the surface size and acknowledge it.

**Comment by slouken** [comment] 2021-08-02 21:33
I'm not familiar with wayland, but internally SDL has the concept of fullscreen and windowed position, so if you're toggling between them and need to set window position, you can read from the appropriate variable to find out where the window is supposed to be.

**Comment by christianrauch** [comment] 2021-08-02 21:57
> Isn't the xdg path just to call `unset_fullscreen`? What else is a client supposed to do after that? In our configure callback the only thing we do in the non-fullscreen case is set the surface size and acknowledge it.

The client currently has (by design) no way to define where its window is positioned. The compositor is in charge to make best guesses where to place a client when it starts initially in floating mode or when restoring to floating mode. If I just try this with `gedit` and toggle the fullscreen mode (F11) then it restores it to the last floating position, which is the most sensible thing to do IMHO.

I've seen these issues (surfaces place in the top left) before, but I cannot pin-point the cause. Since there is not API in Wayland to allow setting or reading the window position, only the order setting and committing surface states can have an effect on this.

I see the same issue on Weston, btw.

**Comment by dos1** [comment] 2021-08-02 23:41
> When I run testgl2 without libdecor, I get a similar result in that the window will be restored in the top-left corner.

You mean, part of it is also occluded below the GNOME top bar when not using libdecor?

**Comment by christianrauch** [comment] 2021-08-02 23:45
> You mean, part of it is also occluded below the GNOME top bar when not using libdecor?

No. The toplevel surface (i.e. that is the entire window since there are no decorations) will just be placed to the top-left most area.

**Comment by dos1** [comment] 2021-08-02 23:59
One thing that SDL does that potentially could confuse the compositor is commiting old-sized buffers after already acking the post-unfullscreen configure, so when the compositor does post-unfullscreen surface placement it takes the old size into account. That would make it pretty much a duplicate of #4563 though.

**Comment by flibitijibibo** [comment] 2021-08-03 15:48
Messing around with this a bit I'm pretty sure we're looking at a duplicate of #4563 - basically the behavior seems to consistently be to only ever change a surface's w/h and not its x/y, except under extreme circumstances. For windows that _start_ windowed this ends up being okay since desktops preserve the windowed x/y, so when leaving fullscreen it knows where it used to be and tries to revert to the old position even if the buffer is still the full desktop size. However, in the case where it starts fullscreen, the only real position it has to work with is (0, 0) and the last buffer it has is the full-size buffer, so no matter what you do you end up having your window pinned at the very top left.

This affects both Wayland paths, but manifests primarily in GNOME because the menu is at the top - Plasma also behaves this way, but the menu bar there is at the bottom so it doesn't end up softlocking us.

I'm pretty confident that fixing #4563 will fix this at the same time.

**Comment by christianrauch** [comment] 2021-08-04 00:40
This transition from fullscreen to floating is also broken on X11:
1. `./testgl2 --fullscreen-desktop --resizable`
2. leave fullscreen (via client or server)
3. the window will be restored maximised instead of floating

Does SDL expect all windowing systems to behave the same? If so, SDL needs a proper definition of how clients are supposed to behave when transitioning between states and under some constraints.

**Comment by flibitijibibo** [comment] 2021-11-05 23:42
Bumping this to 2.0.20, since we're starting to get close to 2.0.18 and I'm still like 50/50 on this being `NOTOURBUG`.

**Comment by flibitijibibo** [comment] 2022-01-20 20:46
At this point it seems like this is something that should be fixed at the desktop level... so I'd like to get issues filed elsewhere so we can close this one. Only question is, where should we file it? Is this at the gnome-shell/plasma-desktop level or does it fall under mutter/kwin?

At minimum if we can get issues filed for GNOME and KDE that'd be enough to cover this, I think.

**Comment by christianrauch** [comment] 2022-01-20 22:02
It's often hard to say (at least for me) if this behaviour is caused by the client or by the server. If in doubt, I would always also report that issue to the compositor / wayland server. For GNOME this is [mutter](https://gitlab.gnome.org/GNOME/mutter) and for KDE this is [kwin](https://invent.kde.org/plasma/kwin). They will also have a better overview of what is going on.

**Comment by flibitijibibo** [comment] 2022-01-20 22:35
Right, bugs filed:

- mutter: https://gitlab.gnome.org/GNOME/mutter/-/issues/2112
- kwin: https://bugs.kde.org/show_bug.cgi?id=448856

If either vendor comes up with a way for us to control the window position better this can be reopened.

**Closed by flibitijibibo** 2022-01-20 22:35 UTC
Labels: help wanted, notourbug

**Comment by christianrauch** [comment] 2022-01-20 22:40
> If either vendor comes up with a way for us to control the window position better this can be reopened.

This is not possible by design with the current set of Wayland protocols. If someone proposes a protocol for having the client position its windows and it is implemented by servers, then this would be possible. But I guess this will never happen and is also not really necessary. The way in which windows are placed is a server policy. In GNOME Shell they are centred.

The behaviour that is observed here is a bug that is either caused by the client or server.

**Comment by flibitijibibo** [comment] 2022-01-20 22:44
> > If either vendor comes up with a way for us to control the window position better this can be reopened.
> 
> This is not possible by design with the current set of Wayland protocols. If someone proposes a protocol for having the client position its windows and it is implemented by servers, then this would be possible. But I guess this will never happen and is also not really necessary. The way in which windows are placed is a server policy. In GNOME Shell they are centred.
> 
> The behaviour that is observed here is a bug that is either caused by the client or server.

Makes sense to me (and similar to cursor position I honestly do like that window position isn't hackable, as long as it doesn't do the whole 0,0 thing). I think this is just an edge case where compositors have to validate a window position to make sure nobody's being weird and putting a window behind unusable desktop space, and resetting its position when that happens. In trying to find another example I found that basically _nothing_ starts in fullscreen mode, including media players, so games are just an outliar in this situation.
