### ISSUE TITLE
SDL doesn't pick up all eight axes

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3696] opened 2021-02-11 01:58 UTC
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2020-05-20 18:39:57 +0000,  wrote:

> Hi,
> I connect a joystick board (Leo Bodnar BU0836A) with 8 axis connected but with PYGame in Python I'm able to see only six of them (obviously Windows see all eight axis)
> This is the device info :
> HID\VID_16C0&PID_05BA&REV_0125
> HID\VID_16C0&PID_05BA
> HID\VID_16C0&UP:0001_U:0004
> HID_DEVICE_SYSTEM_GAME
> HID_DEVICE_UP:0001_U:0004
> HID_DEVICE
> 
> This is the vendor website link:
> http://www.leobodnar.com/shop/index.php?main_page=product_info&cPath=94&products_id=204&zenid=4ccdff85db8af0c9a14f39af631a5086

**Comment by FrodeSolheim** [comment] 2021-11-17 08:23
This might be related to https://github.com/libsdl-org/SDL/issues/3561

**Comment by slouken** [comment] 2022-03-17 18:23
I think this is a duplicate of https://github.com/libsdl-org/SDL/issues/3561

**Closed by slouken** 2022-03-17 18:23 UTC
Labels: bug
