### ISSUE TITLE
feature request: push notifications

### ISSUE THREAD

**Issue by dos350** [libsdl-org/SDL#6782] opened 2022-12-07 21:26 UTC
could we please can we get some push notification support in sdl3

i think that a simple send notification function kind of thing would really add alot of convenience to users

**Comment by slime73** [comment] 2022-12-07 21:27
Is this the same as #1932?

**Comment by dos350** [comment] 2022-12-07 21:28
yea it is sorry didnt see that one :)

**Comment by slouken** [comment] 2022-12-08 00:54
Duplicate of #1932

**Closed by slouken** 2022-12-08 00:54 UTC
