### ISSUE TITLE
SDL 2.28.0+ causes texture misalignment in Mesen2

### ISSUE THREAD

**Issue by TakuikaNinja** [libsdl-org/SDL#7954] opened 2023-07-09 05:23 UTC
Since SDL 2.28.0, the texture(s) in [Mesen2](https://github.com/SourMesen/Mesen2) become misaligned: 
![image](https://github.com/libsdl-org/SDL/assets/43363447/36e3fb1f-df33-439a-9baf-08530becfa7c)

Sometimes the texture can be realigned by changing the video settings but it is very inconsistent.
Downgrading SDL to 2.26.5 restores the proper behaviour.
Note: Please use the development builds of Mesen2 for testing.

OS: EndeavourOS (basically Arch)
Display server: X11

**Comment by TakuikaNinja** [comment] 2023-07-09 10:43
After a few `git bisect` attempts, aa536217b3e1a9ea4a5de9944cadbd79b134a41a was named as the first bad commit.

**Comment by zeta0134** [comment] 2023-07-09 11:40
I can confirm this bug on Arch proper, just updated to sdl2 `2.28.1-1` and was greeted with mostly transparent game windows. Mesen2-specific workarounds include resizing the window, but it's temporary and quite glitchy.

**Comment by sezero** [comment] 2023-07-09 14:11
CC: @icculus

**Comment by icculus** [comment] 2023-07-09 20:51
Ugh, sorry about that! I'll look at that cherry-pick today.

**Comment by icculus** [comment] 2023-07-10 17:46
Ok, what the heck, this _shouldn't_ be in HideWindow in the original commit.

I wonder if I made a fix for #4216, then did a `git pull --rebase` before pushing, and it ended up moving elsewhere?

This is wild, I'm digging further.

**Comment by icculus** [comment] 2023-07-10 20:08
> This is wild, I'm digging further.

My current thinking is the SDL2 patch is correct (discounting whatever interaction is causing Mesen2 trouble), and I probably did the work in that branch and tested i3 against it, and then either applied a patch to a separate working copy for SDL3, where it landed incorrectly, or just pasted it into the wrong place, which is at least as likely, if not more.

But since our policy is to commit to SDL3 and cherry-pick back to SDL2, that got committed first and then cherry-picked over (and maybe I even thought "weird, it missed the function" and manually fixed it up in SDL2).

Anyhow, the plan now is to run mesen2 under a debugger and reproduce this issue, see what should be done, and fix up the SDL3 commit in any case.

**Comment by icculus** [comment] 2023-07-26 16:25
Let's close this and track this over in #8029.

**Closed by icculus** 2023-07-26 16:25 UTC
