### ISSUE TITLE
CMake MinSizeRel fails for MSVC

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2955] opened 2021-02-11 01:11 UTC
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Repro log (log (3).txt, text/plain, 2018-10-10 22:33:16 +0000, 49023 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3362)

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Windows (All), x86_64

# Comments on the original bug report:

On 2018-08-18 21:08:26 +0000, Drew Pirrone-Brusse wrote:

> Building SDL.lib from CMake with `-DCMAKE_BUILD_TYPE=MinSizeRel` fails to link with the below error.
> 
> SDL_bmp.c.obj : error LNK2019: unresolved external symbol memset referenced in function SDL_SaveBMP_RW_REAL
> 
> I typically use Ninja to build -- and use it as the generator for the below repro steps -- but this error manifests when building with Visual Studio as well.
> 
> An interesting note; I managed to track this error down to the application of the `\O1` (Optimize for Minimum Size) compiler flag. Adding `set(CMAKE_C_FLAGS_MINSIZEREL "${CMAKE_C_FLAGS_MINSIZEREL} /O2")` as the last line in CMakeLists.txt (to override Minimum Size with Maximum Speed) "fixes" the problem. I'm... not sure what to do with that information, but thought it might be useful.
> 
> 
> ## Steps to Reproduce (from a clean SDL clone)
> 
> mkdir build
> cd build
> cmake .. -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel
> cmake --build .
> 
> ## System Information
> 
> Windows 10 Pro 1803
> Microsoft (R) C/C++ Optimizing Compiler Version 19.14.26433 for x64
> Microsoft (R) Incremental Linker Version 14.14.26433.0

On 2018-10-10 22:09:12 +0000, Joel Winarske wrote:

> I have a repro with amd64 build, as well as a different failure with amd64_x86.
> 
> *** amd64 build ***
> 
> EXTRA_LIBS:    user32;gdi32;winmm;imm32;ole32;oleaut32;version;uuid;dinput8
> 
> [100%] Linking C shared library SDL2.dll
> LINK: command "C:\PROGRA~2\MI0E91~1.0\VC\bin\amd64\link.exe /nologo @CMakeFiles\SDL2.dir\objects1.rsp /out:SDL2.dll /implib:SDL2.lib /pdb:C:\projects\pdcurses\build\sdl2_ext-prefix\src\sdl2_ext-build\SDL2.pdb /dll /version:2.0 /machine:x64 /INCREMENTAL:NO user32.lib gdi32.lib winmm.lib imm32.lib ole32.lib oleaut32.lib version.lib uuid.lib dinput8.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:SDL2.dll.manifest" failed (exit code 1120) with the following output:
> uuid.lib(unknwn_i.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
>    Creating library SDL2.lib and object SDL2.exp
> SDL_bmp.c.obj : error LNK2001: unresolved external symbol memset
> SDL2.dll : fatal error LNK1120: 1 unresolved externals
> NMAKE : fatal error U1077: '"C:\Program Files (x86)\CMake\bin\cmake.exe"' : return code '0xffffffff'
> Stop.
> 
> *** amd64_x86 build ***
> 
> EXTRA_LIBS:    user32;gdi32;winmm;imm32;ole32;oleaut32;version;uuid;dinput8
> 
> [100%] Linking C shared library SDL2.dll
> LINK: command "C:\PROGRA~2\MI0E91~1.0\VC\bin\AMD64_~2\link.exe /nologo @CMakeFiles\SDL2.dir\objects1.rsp /out:SDL2.dll /implib:SDL2.lib /pdb:C:\projects\pdcurses\build\sdl2_ext-prefix\src\sdl2_ext-build\SDL2.pdb /dll /version:2.0 /machine:X86 /INCREMENTAL:NO user32.lib gdi32.lib winmm.lib imm32.lib ole32.lib oleaut32.lib version.lib uuid.lib dinput8.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:SDL2.dll.manifest" failed (exit code 1169) with the following output:
> uuid.lib(unknwn_i.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
> MSVCRT.lib(_ftol2_.obj) : error LNK2005: __ftol2_sse already defined in SDL_stdlib.c.obj
>    Creating library SDL2.lib and object SDL2.exp
> SDL2.dll : fatal error LNK1169: one or more multiply defined symbols found
> NMAKE : fatal error U1077: '"C:\Program Files (x86)\CMake\bin\cmake.exe"' : return code '0xffffffff'
> Stop.
> 
> 
> Build logs:
> https://ci.appveyor.com/project/jwinarske/pdcurses/builds/19415795

On 2018-10-10 22:33:16 +0000, Joel Winarske wrote:

> Created attachment 3362
> Repro log

**Comment by slouken** [comment] 2022-03-18 00:52
I am not able to reproduce the memset undefined error, and I believe that was fixed in SDL_bmp.c at some point. Please reopen this bug if you're still seeing the issue with the latest code. One difference in my test is that I'm not building with ninja, but in theory cmake will generate a solution with the same command line parameters for cl.exe.

**Closed by slouken** 2022-03-18 00:52 UTC
