### ISSUE TITLE
SDL_VIDEODRIVER=wayland window resizing is broken while X11 works

### ISSUE THREAD

**Issue by ell1e** [libsdl-org/SDL#5899] opened 2022-07-09 06:28 UTC
SDL_VIDEODRIVER=wayland window resizing is broken while X11 works, resulting in problems like this:

![Screenshot from 2022-07-09 08-19-24](https://user-images.githubusercontent.com/64124388/178094474-f435de21-ee16-4ee5-8764-c3ffb288bd28.png)

As you can see, it seems like `SDL_RenderClear()` is aware of the new size, some other parts of the SDL2 renderer code clearly not, resulting in lots of things being cut off.

This bug is a forward from https://bugzilla.redhat.com/show_bug.cgi?id=2089848 because it's pretty severe, and there hasn't been much happening on the Fedora end so far.

**SDL 2 version affected:** SDL2-2.0.22-2.fc36

**Comment by sulix** [comment] 2022-07-09 08:56
Sounds similar to #5593, which was similar, but on X11. Equally, if this is on nVidia, it could be related to one of the [resize](https://github.com/NVIDIA/egl-wayland/issues/57) [issues](https://github.com/NVIDIA/egl-wayland/issues/59) there — some of which are my fault.

I can't reproduce this out-of-the-box on an Intel/KDE/Wayland setup, but there is definitely still an issue that looks very similar with ``SDL_GetWindowSurface()``. That's not the SDL renderer API, but might show up if you're using the software backend. Otherwise, wayland definitely doesn't update some things until after a whole frame is rendererd, so if the application isn't constantly rendering frames (but is only rendering them in response to ``SDL_WINDOWEVENT_EXPOSED``, there might be a place where we don't send those.

A few questions and/or things to try:
- Does this occur with all applications, or just one?
- Does this occur on non-Gnome wayland compositors as well?
- (And, specifically, does this also occur in compositors which prefer server-side decorations,i.e., without libdecor.)
- Does this also occur with the latest git version of SDL?
- Does setting ``SDL_RENDER_DRIVER=software`` make it better (or worse)?
- What graphics card (and driver version) are you running. If you're running nVidia, what's the version of libnvidia-egl-wayland?
- Is VSync enabled? Try enabling or disabling it with the ``SDL_RENDER_VSYNC`` environment variable.

**Comment by ell1e** [comment] 2022-07-16 12:20
This produces the bug with `SDL_VIDEODRIVER=wayland ./sdldpibug.c` on the PinePhone with the Phosh wayland compositor and it basically renders the app seemingly useless:

1. Save this into `sdldpibug.c`:

   ```

#include <assert.h>
#include <SDL2/SDL.h>
#include <stdio.h>


double get_dpi(SDL_Window *window, SDL_Renderer *renderer) {
    int ww, wh, rw, rh;
    SDL_GetWindowSize(window, &ww, &wh);
    int result = SDL_GetRendererOutputSize(renderer, &rw, &rh);
    assert(result == 0);
    double dpiscaler = ((double)rw)/((double)ww);
    printf("window size: %dx%d, renderer size: %dx%d, dpi scale: %f\n",
        ww, wh, rw, rh, dpiscaler);
    return dpiscaler;
}

int main(int argc, const char **argv) {
    printf("SDL_Init(...)\n");
    int result = SDL_Init(SDL_INIT_EVENTS|SDL_INIT_TIMER|
        SDL_INIT_VIDEO|SDL_INIT_HAPTIC|SDL_INIT_GAMECONTROLLER);
    assert(result == 0);
    printf("SDL_CreateWindow(...)\n");
    SDL_Window *window = SDL_CreateWindow("sdl dpi bug", 0, 0, 200, 200,
        SDL_WINDOW_RESIZABLE|SDL_WINDOW_OPENGL|SDL_WINDOW_ALLOW_HIGHDPI);
    assert(window != NULL);
    printf("SDL_CreateRenderer(...)\n");
    SDL_Renderer *renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_PRESENTVSYNC|
        SDL_RENDERER_ACCELERATED);

    double dpi = get_dpi(window, renderer);
    int squarex = 100 * 0.5 * dpi;
    int squarey = 100 * 0.5 * dpi;
    int notquit = 1;
    while (notquit) {
        SDL_Event e = {0};
        while (SDL_PollEvent(&e)) {
            if (e.type == SDL_QUIT) {
                notquit = 0;
                break;
            } else if (e.type == SDL_WINDOWEVENT) {
                if (e.window.event == SDL_WINDOWEVENT_CLOSE) {
                    notquit = 0;
                    break;
                } else if (e.window.event == SDL_WINDOWEVENT_SIZE_CHANGED) {
                    dpi = get_dpi(window, renderer);
                }
            } else if (e.type == SDL_MOUSEBUTTONDOWN) {
                squarex = e.button.x * dpi;
                squarey = e.button.y * dpi;
            }
        }
        SDL_SetRenderDrawColor(renderer, 50, 0, 40, 255);
        SDL_RenderClear(renderer);
        SDL_SetRenderDrawColor(renderer, 240, 30, 230, 255);
        SDL_Rect r = {0};
        r.w = dpi * 20;
        r.h = dpi * 20;
        r.x = -0.5 * r.w + squarex;
        r.y = -0.5 * r.h + squarey;
        SDL_RenderFillRect(renderer, &r);
        SDL_RenderPresent(renderer);
    }
    return 0;
}
```

2. Compile `gcc -o sdldpibug ./dpibug.c -lSDL2`
3. Run `./sdldpibug`
4. Tap the window. It should show a violet square where you tapped. Now switch between portrait and landscape, or toggle on screen keyboard, try more taps and see. You'll notice the bottom right of the window will often be entirely broken and not show the square, it seems like `SDL_RenderFillRect` clips at completely wrong and likely outdated renderer & window dimensions before the latest resize which can be wildly too small.

You  might be able to reproduce with above code on a different machine by resizing the window to be fairly small, then press maximize, then do above rectangle click and hopefully see it is cut off. I don't have my laptop around right now so I can't test where I originally ran into this.

Needless to say, unless a bug in my test code above causes this (which wouldn't be the first time haha) this seems to be a possibly fairly major issue. Rendering shouldn't just break from resizing, and it seems to happen both with mali GPU drivers and AMD ones.

**Comment by ell1e** [comment] 2022-07-16 13:32
Maybe relevant notes: 1. this reproduces for me in DPI 1.25x/1.5x (forgot which) and DPI 2x environments with no changing DPI, so whether I set/update the `double dpi` float in enough places shouldn't matter. Especially since I don't even tell SDL2 to clip anything, so it must be something with its own internal size tracking. 2. I actually never tested this on no-High-DPI machines since I don't own any, so this may or may not be required to reproduce this.

**Comment by sulix** [comment] 2022-07-16 14:22
Thanks for the repro code: I was able to reproduce the issue under KDE/Intel fine with it.

It looks like the problem is that the desired buffer width/height isn't being updated until _after_ the SDL_WINDOWEVENT_RESIZED event is sent out (and handled by SDL_Renderer's event filter). This means that SDL_GL_GetDrawableSize() is still returning the old values, so the viewport gets "updated" to the same old size.

I've written a hacky fix here: https://github.com/sulix/SDL/commit/wayland_resize_fix

I haven't tested it with anything other than your reproducer program, so it's possible it breaks several other things. I'll test with some other, nastier cases (hopefully tomorrow) before making a PR out of it.

**Comment by ell1e** [comment] 2022-07-17 15:04
Fix works for me. Was wondering if new compute geometry call should get its own guard to check for actual real size change tho, unless that's guaranteed a cheap & no-alloc operation. (disclaimer: i know the codebase very badly so if in doubt ignore me)

**Comment by sulix** [comment] 2022-07-18 13:45
I tested this on a bunch of things, and sent out #5932 

I'm not putting an extra if() guard around the ``ConfiugueWindowGeometry()`` call — at least in this change — as I'm not 100% sure it'd be correct. It makes some calls into Wayland which might be required in some interesting corner cases: things like fullscreen transitions and the like. Given I'm only moving the call, this won't be any more expensive than the previous version. If it turns out there's some sense in avoiding this in cases where {width, height, scale} are unchanged, we can do so in a separate commit, as to not confuse anyone bisecting if it causes an issue.

**Comment by Kontrabant** [comment] 2022-08-05 01:59
The extra `if` guard won't work , as `ConfigureWindowGeometry()` needs to be always be called from this function to set some initial window properties (making it conditional was tried and caused problems).  To change this would require some changes in `CreateWindow()`.  Nothing complicated, but it's better left for a separate pull as it's not directly related to this issue.

**Comment by icculus** [comment] 2022-08-05 14:00
I opened a separate issue for the if statement thing, so it isn't lost in the noise, and resolving this issue.

**Closed** 2022-08-05 14:00 UTC
Labels: wayland

**Comment by sulix** [comment] 2022-08-05 14:07
Yup — this is definitely fixed. There had been some related issues specific to the software renderer, and those seem to be fixed too.
