### ISSUE TITLE
[request] Surface flip API

### ISSUE THREAD

**Issue by baidwwy** [libsdl-org/SDL#5697] opened 2022-05-19 23:42 UTC
https://github.com/libsdl-org/SDL/blob/83ae1b4987227e9580e32c8c87e92732e8d7edb3/src/render/software/SDL_render_sw.c#L443-L445

use software?

**Comment by Starbuck5** [comment] 2022-05-21 21:41
Do you mean a function like pygame.transform.flip? https://www.pygame.org/docs/ref/transform.html#pygame.transform.flip

**Comment by baidwwy** [comment] 2022-05-21 22:29
> 

right！right！right！

**Comment by baidwwy** [comment] 2022-05-21 22:30
> Do you mean a function like pygame.transform.flip? https://www.pygame.org/docs/ref/transform.html#pygame.transform.flip

right！right！right！

**Comment by baidwwy** [comment] 2022-05-21 22:37
https://github.com/pygame/pygame/blob/365f094d66e688b7582e41fb8aaf9d150b150774/src_c/transform.c#L781-L932
@slouken

**Comment by slouken** [comment] 2024-01-20 13:30
This is a duplicate of https://github.com/libsdl-org/SDL/issues/8857

**Closed by slouken** 2024-01-20 13:30 UTC
Labels: enhancement
