### ISSUE TITLE
[PSP] sdl3/cmake psp port no longer builds/installs libSDL3main.a

### ISSUE THREAD

**Issue by rofl0r** [libsdl-org/SDL#9378] opened 2024-03-26 22:18 UTC
since PSP needs some quite elaborate startup code, it'd be nice having libSDL*main back. this may also affect the autoconf build (untested)

**Comment by icculus** [comment] 2024-03-27 21:59
SDLmain isn't a static library in SDL3, it's header-based now:

https://github.com/libsdl-org/SDL/blob/d00ccc1546c0943481f5d65459496a47fe9721df/docs/README-migration.md#sdl_mainh

(Which is not to say it isn't broken on PSP; if that's the case, we would like to fix it!)

Adding to 3.2.0 milestone in case this isn't working on PSP; if this just needs the app's build system adjusted, though, we can close this.

**Comment by rofl0r** [comment] 2024-03-27 23:57
thanks, that's very helpful. it seems though that for some reason the macro SDL_PLATFORM_PSP isn't defined, so the whole module info stuff isn't included (installation was done via cmake and official psp toolchain file).

**Comment by icculus** [comment] 2024-03-28 03:53
This built for me (but I haven't actually tested the compiled test programs). I downloaded the latest from [pspdev](https://github.com/pspdev/pspdev/releases/tag/latest), unpacked it, put it in my $PATH, and used "psp-cmake" to build SDL3. It definitely defined `__PSP__` on the compiler command line automatically, so SDL_platforms.h picked it up.

**Comment by rofl0r** [comment] 2024-03-28 11:31
ah, than that's it. the older toolchains versions define `__psp__`, `__PSP__` must be a new addition

**Comment by rofl0r** [comment] 2024-03-28 11:32
````
Leaving main
~/tmp/pspsdlvramexample $ psp-gcc -dM -E - < /dev/null | grep -i psp
#define _PSP 1
#define PSP 1
#define __psp__ 1
~/tmp/pspsdlvramexample $
```

**Comment by rofl0r** [comment] 2024-03-28 11:40
actually  it's the cmake toolchain file that adds `__PSP__`:
```
add_definitions("-D__PSP__")
```
that means the detection inside SDL only works if it was invoked in CMake context.

**Comment by icculus** [comment] 2024-03-28 12:31
I'll add a check for the other symbols.

**Comment by icculus** [comment] 2024-03-28 13:28
Try it with the latest in revision control and it _should_ work.

**Closed** 2024-03-28 13:28 UTC

**Comment by sezero** [comment] 2024-03-28 13:36
I think https://github.com/libsdl-org/SDL/commit/0d007bbb014311542f28dd83704a649ce4eaed75 should be cherry picked to SDL2 and 2.30.x

**Comment by icculus** [comment] 2024-03-28 13:49
Done.

**Comment by rofl0r** [comment] 2024-03-29 16:35
@icculus
seems that file is missing the prototypes for the function pointer typedefs, so they default to "int". i got the first compile error fixed by adding `typedef int (SDLCALL *SDL_AppEvent_func)(void *appstate, const SDL_Event *event);`

so i guess the typedefs should be moved from SDL_main.h to ...internal.h

**Comment by madebr** [comment] 2024-03-29 16:48
How come our ci is building the psp binaries successfully, and you don't?
What is different in your build configuration?
Perhaps our tests are not enough?
https://github.com/libsdl-org/SDL/actions/workflows/psp.yml

**Comment by rofl0r** [comment] 2024-03-29 16:48
the command line used by cmake is:
```
/home/rofl/toolchains/mipsallegrexel-psp-elf/bin/psp-gcc -DPSP -DSDL_BUILD_MAJOR_VERSION=3 -DSDL_BUILD_MICRO_VERSION=0 -DSDL_BUILD_MINOR_VERSION=1 -DSDL_STATIC_LIB -DUSING_GENERATED_CONFIG_H -D__PSP__ -I/home/rofl/tmp/SDL/build_sdl3_2/include-config- -I/home/rofl/tmp/SDL/build_sdl3_2/include -I/home/rofl/tmp/SDL/include -I/home/rofl/tmp/SDL/src -I/home/rofl/tmp/SDL/include/SDL3 -I/home/rofl/toolchains/mipsallegrexel-psp-elf/psp/include -I/home/rofl/toolchains/mipsallegrexel-psp-elf/psp/sdk/include -DPSP -Wall -Wundef -fno-strict-aliasing -Wshadow -idirafter/home/rofl/tmp/SDL/src/video/khronos -std=gnu99 -Winvalid-pch -include /home/rofl/tmp/SDL/build_sdl3_2/CMakeFiles/SDL3-static.dir/cmake_pch.h -MD -MT CMakeFiles/SDL3-static.dir/src/main/SDL_main_callbacks.c.obj -MF CMakeFiles/SDL3-static.dir/src/main/SDL_main_callbacks.c.obj.d -o CMakeFiles/SDL3-static.dir/src/main/SDL_main_callbacks.c.obj -c /home/rofl/tmp/SDL/src/main/SDL_main_callbacks.c
```
i wonder how this is not caught by CI

**Comment by rofl0r** [comment] 2024-03-29 17:06
the build includes the SDL3 header that's already installed, version from 3 days ago
```
/home/rofl/tmp/SDL/src/main/SDL_main_callbacks.c:25:23: error: conflicting types for 'SDL_AppEvent_func'
/home/rofl/toolchains/mipsallegrexel-psp-elf/bin/../psp/include/SDL3/SDL_main.h:163:23: note: previous declaration of 'SDL_AppEvent_func' was here
```

**Comment by rofl0r** [comment] 2024-03-29 17:11
so probably the issue here is that stuff is included via <SDL3/...> and depending on the -I order if system headers come first you get that those instead of the one in tree

probably all headers used by C files in-tree should use relative paths like "../foo.h" or "./bar.h"

**Comment by rofl0r** [comment] 2024-03-29 17:18
@madebr looks like to catch this in CI you first gotta install a set of fake SDL3 headers that have all conflicting typedefs into the toolchain's include directory

**Comment by madebr** [comment] 2024-03-29 18:47
I can't reproduce the error during SDL build.

I can reproduce your error in a user application when using CMake and including SDL using `#include "SDL3/SDL.h"` instead of `#include <SDL3/SDL.h>`.
This is a consequence of CMake using `-isystem` for imported targets.
[Fixing that](https://cmake.org/cmake/help/latest/prop_tgt/EXPORT_NO_SYSTEM.html#prop_tgt:EXPORT_NO_SYSTEM), I cannot reproduce your errors anymore.
https://github.com/madebr/SDL/tree/ci-don-t-use-system-headers
https://github.com/madebr/SDL/actions/runs/8484381874/job/23247219310

**Comment by rofl0r** [comment] 2024-03-29 20:28
@madebr i added the fix you apply in CI using sed (replace -I with -isystem) to pspdev's cmake toolchain file, and that makes it work. i guess we should upstream that to pspsdk - otherwise there will always be a mismatch in behaviour between pspsdk user's toolchain and the one you use in CI.

**Comment by madebr** [comment] 2024-03-29 20:32
I undid it in https://github.com/libsdl-org/SDL/pull/9398

Can you try it by building and installing it in a non-system prefix?

**Comment by rofl0r** [comment] 2024-03-29 20:33
i have only cmake 3.20.3, but my cmake is patched anyway to not add -isystem everywhere

**Comment by rofl0r** [comment] 2024-03-29 20:35
https://github.com/sabotage-linux/sabotage/blob/master/KEEP/cmake-isystem.patch

**Comment by rofl0r** [comment] 2024-03-29 20:40
@madebr did you see https://github.com/libsdl-org/SDL/issues/9378#issuecomment-2027706352 ? we really gotta upstream that isystem patch to pspsdk, it's the only way to have `#include <>` behave correctly

**Comment by madebr** [comment] 2024-03-29 21:04
In https://github.com/libsdl-org/SDL/issues/9378#issuecomment-2027476268,
`-I/home/rofl/toolchains/mipsallegrexel-psp-elf/psp/include -I/home/rofl/toolchains/mipsallegrexel-psp-elf/psp/sdk/include` are added as last argument. Isn't that ok?

About https://github.com/pspdev/pspsdk/issues/123, I suggest you add a comment there and/or create a pr to change the cmake toolchain file (I don't now where it lives)

**Comment by rofl0r** [comment] 2024-03-29 21:14
@madebr i added -v to the above compiler command line and this is the include search order spit out by gcc:

```
ignoring duplicate directory "/home/rofl/toolchains/mipsallegrexel-psp-elf/psp/include"
ignoring duplicate directory "/home/rofl/toolchains/mipsallegrexel-psp-elf/psp/sdk/include"
#include "..." search starts here:
#include <...> search starts here:
 /home/rofl/toolchains/mipsallegrexel-psp-elf/bin/../psp/include
 /home/rofl/toolchains/mipsallegrexel-psp-elf/bin/../psp/sdk/include
 /home/rofl/tmp/SDL/build_sdl3_2/include-config-
 /home/rofl/tmp/SDL/build_sdl3_2/include
 /home/rofl/tmp/SDL/include
 /home/rofl/tmp/SDL/src
 /home/rofl/tmp/SDL/include/SDL3
 /home/rofl/toolchains/mipsallegrexel-psp-elf/lib/gcc/mipsallegrexel-psp-elf/4.6.4/include
 /home/rofl/toolchains/mipsallegrexel-psp-elf/lib/gcc/mipsallegrexel-psp-elf/4.6.4/include-fixed
 /home/rofl/toolchains/mipsallegrexel-psp-elf/lib/gcc/mipsallegrexel-psp-elf/4.6.4/../../../../mipsallegrexel-psp-elf/include
 /home/rofl/tmp/SDL/src/video/khronos
End of search list.
```

i **think** the bug came to be because *not* marking the psp sys include dir as -isystem causes it to be considered for `#include "foo"` style lookups, and having it as -isystem only for `<bar>` style includes.

i filed the PR to pspsdk, see above

**Comment by madebr** [comment] 2024-03-29 21:30
Shouldn't your patch also prepend `-isystem` to `psp/sdk/include`?

**Comment by rofl0r** [comment] 2024-03-29 21:31
> Shouldn't your patch also prepend -isystem to psp/sdk/include?

no, those are only sony specific APIs, unlikely to ever clash with anything else - they all have `"sce*"` prefix

**Comment by rofl0r** [comment] 2024-04-01 11:30
small update:
1) confirm that icculus' patch fixes the psp detection outside of cmake,
2) the PR on pspsdk has been merged, so the isystem hack in CI is no longer needed.

@madebr can we go forward merging your PR ? i think it's a good idea to poison the system headers at least on one platform, to catch similar issues immediately.
