### ISSUE TITLE
The shift modifier is released when some keypad keys are pressed while the num lock is on.

### ISSUE THREAD

**Issue by HexDecimal** [libsdl-org/SDL#4407] opened 2021-06-01 07:00 UTC
Using SDL 2.0.14 on Windows 10.  I haven't checked any other platforms.

I expect the shift key modifier to stay active while the keypad is used, regardless of the num lock state.

If a shift key is held and a keypad key is pressed then the shift key is released for the duration that the numpad key is held.  This includes `SDL_KEYUP` and `SDL_KEYDOWN` events for the shift key around the keypad events, so there's no obvious workaround.

This affects `SDL_SCANCODE_KP_0` to `SDL_SCANCODE_KP_9` and `SDL_SCANCODE_KP_PERIOD`.  The other keypad keys seem to work fine.

If you hold one shift key then tap the other shift key, then the held shift key stays held when pressing the keypad keys.

If the numeric lock is off then the keypad works normally, but disabling the numeric lock with `SDL_SetModState` has no effect.

I've primary tested this through an FFI library.  I think I can write a C++ example if that's needed.

**Comment by slouken** [comment] 2023-11-07 02:36
Duplicate of https://github.com/libsdl-org/SDL/issues/1917

**Closed by slouken** 2023-11-07 02:36 UTC
