### ISSUE TITLE
Feature request: Window with fixed aspect ratio

### ISSUE THREAD

**Issue by andreasgrabher** [libsdl-org/SDL#9732] opened 2024-05-09 16:37 UTC
Feature request: 

I think it is quite common for applications to have content that fits to a specific aspect ratio. Therefore I believe there should be a way to preserve the aspect ratio of a window during resize operations. There could be a window flag for this. From my point of view this would be a useful addition to SDL3.

**Comment by slouken** [comment] 2024-05-09 17:16
Yes, this seems like a good idea.

**Comment by slouken** [comment] 2024-05-20 20:42
This is a duplicate of https://github.com/libsdl-org/SDL/issues/1573

**Closed by slouken** 2024-05-20 20:42 UTC
