### ISSUE TITLE
input doesn't work with kmsdrm

### ISSUE THREAD

**Issue by stsp** [libsdl-org/SDL#8219] opened 2023-09-08 13:16 UTC
Running an sdl app under kms console,
I am getting no input.
This used to work fine in the past.

2.28.2+dfsg-1 under ubuntu.

**Comment by slouken** [comment] 2023-11-08 08:56
Can you debug it and see what's happening?

**Comment by stsp** [comment] 2023-11-08 09:53
It appears to be already debugged in
#4812 
So the bug is very obvious: sdl doesn't
report the input failure to the user,
allowing an app to start and hang
entire system.
That solution was discussed in the
aforementioned ticket, but is still
not implemented!

**Comment by slouken** [comment] 2023-11-08 09:57
You say this worked in the past, can you find out which version works for you, so we can see where it broke?

**Comment by stsp** [comment] 2023-11-08 10:00
I suspect that the regression part
came from sdl-unrelated lands, like
udev/systemd. My user wasn't in an
"input" group, although "that used
to work somehow".

sdl should start from propagating an
error, and that will likely be enough.

**Comment by slouken** [comment] 2023-11-08 10:21
Okay, I'm going to mark this as a duplicate of https://github.com/libsdl-org/SDL/issues/4812, since that has more information, and follow up there.

**Closed by slouken** 2023-11-08 10:21 UTC
Labels: waiting
