### ISSUE TITLE
SDL_WINDOW_INPUT_FOCUS always on after initialisation

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3076] opened 2021-02-11 01:19 UTC
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2018-11-21 13:09:23 +0000, Michel Rouzic wrote:

> Let's say I launch my SDL program, but because I click on my web browser as the SDL program is about to launch my SDL program's window gets created in the background, without focus. This is normal, but what's not normal is that SDL_GetWindowFlags(window) & SDL_WINDOW_INPUT_FOCUS would always return 1 after creation even when it doesn't have the focus, and there's no event that indicates a loss of focus, so no matter what I do there's nothing I can do to check whether or not my window is actually in focus or not, which is a big problem when like me you poll the mouse globally to handle clicking and movement.
> 
> Just to be clear, SDL_WINDOW_INPUT_FOCUS is accurate if the window is created while in the foreground, and it gets updated correctly and produces the correct events when the focus changes, just not in case the window is created in the background, as it seems to assume this shouldn't happen.
> 
> To reproduce just log the value of SDL_GetWindowFlags(window) & SDL_WINDOW_INPUT_FOCUS or window events and then launch the app but click repeatedly on another window before it gets created (might help to put a little SDL_Delay(2000); before the window creation, also don't launch it from Visual Studio as VS will bring the window to the foreground), and you'll see that it believes to be in focus from the start even when it isn't.

**Comment by slouken** [comment] 2021-10-05 22:43
Duplicate of #4450

**Closed by slouken** 2021-10-05 22:43 UTC
Labels: bug
