### ISSUE TITLE
`ioctl (GFEATURE): *` message shows when Logitech Lightspeed Receiver plug in

### ISSUE THREAD

**Issue by detiam** [libsdl-org/SDL#8109] opened 2023-08-11 01:34 UTC
Similar to #6799, My USB device
```
$ lsusb
Bus 004 Device 002: ID 17ef:109b Lenovo USB3.0 Hub             
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 004: ID 2109:8883 VIA Labs, Inc. USB Billboard Device   
Bus 003 Device 003: ID 045e:02fe Microsoft Corp. XBOX ACC
Bus 003 Device 002: ID 17ef:109a Lenovo USB2.0 Hub             
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 8087:0aa7 Intel Corp. Wireless-AC 3168 Bluetooth
Bus 001 Device 004: ID 26ce:01a2 ASRock LED Controller
Bus 001 Device 006: ID 046d:c539 Logitech, Inc. Lightspeed Receiver
Bus 001 Device 002: ID 056a:037a Wacom Co., Ltd CTL-472 [One by Wacom (S)]
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
with set env var `SDL_HIDAPI_IGNORE_DEVICES=0x046d/0x0000`, the message are gone 
```bash
$ sdl2-jstest --list
ioctl (GFEATURE): Broken pipe
ioctl (GFEATURE): Broken pipe
ioctl (GFEATURE): Broken pipe
ioctl (GFEATURE): Broken pipe
ioctl (GFEATURE): Broken pipe
ioctl (GFEATURE): Broken pipe
ioctl (GFEATURE): Invalid argument
ioctl (GFEATURE): Invalid argument
ioctl (GFEATURE): Invalid argument
ioctl (GFEATURE): Broken pipe
ioctl (GFEATURE): Broken pipe
ioctl (GFEATURE): Broken pipe
No joysticks were found

$ env SDL_HIDAPI_IGNORE_DEVICES=0x046d/0x0000 sdl2-jstest --list
No joysticks were found
```
but when I added the product ID 
```
$ env SDL_HIDAPI_IGNORE_DEVICES=0x046d/0xc539 sdl2-jstest --list
ioctl (GFEATURE): Invalid argument
ioctl (GFEATURE): Invalid argument
ioctl (GFEATURE): Invalid argument
No joysticks were found
```
there are still three `Invalid argument` messages

Related issues: https://github.com/raspberrypi/linux/issues/5524

**Comment by slouken** [comment] 2023-08-13 20:55
This a duplicate of https://github.com/libsdl-org/SDL/issues/8112, which is now fixed.

**Closed by slouken** 2023-08-13 20:55 UTC
