### ISSUE TITLE
AltGr generates LCtrl + RAlt on Windows with Spanish layout

### ISSUE THREAD

**Issue by rom1v** [libsdl-org/SDL#9201] opened 2024-03-05 16:36 UTC
> when pressing <kbd>AltGr</kbd>, my Windows generates two key events, <kbd>LCtrl</kbd> and <kbd>RAlt</kbd>

I think SDL should generate only <kbd>RAlt</kbd>. What do you think?

More information about the issue: https://github.com/Genymobile/scrcpy/issues/4725#issuecomment-1979147925

**Comment by ikjordan** [comment] 2024-03-06 11:17
I hit this issue recently when adding Spanish keyboard support to a Sinclair QL emulator. The code worked well on Linux, but then failed on Windows as the emulator detected a control button press when AltGr was pressed. I was able to perform a partial workaround by ignoring Control when AltGr was pressed, but a mechanism to specify that Linux and Windows keyboards handle AltGr in the same way would have been beneficial. I expect many programs rely on the current Windows behaviour, but perhaps a hint could be added to optionally modify the behaviour under Windows?

**Comment by slouken** [comment] 2024-05-23 16:50
Duplicate of https://github.com/libsdl-org/SDL/issues/5685

**Closed by slouken** 2024-05-23 16:50 UTC
