### ISSUE TITLE
ManyMouse - Bluetooth, Touchpad, Touchscreen, virtual bindings

### ISSUE THREAD

**Issue by Torinde** [libsdl-org/SDL#6724] opened 2022-12-01 16:19 UTC
Dosbox Staging dual mouse functionality that uses ManyMouse (icculus/manymouse/issues/3) doesn't support:
- Bluetooth mouse 
- laptop touchpad

It would be nice as well to have support for:
- touchscreen
- use as "mouse" the physical keyboard keys
- use as "mouse" the physical gamepad/joystick

Related to dosbox-staging/dosbox-staging/issues/2066

Related request is (user customizable) any-to-any mapping between all physical/virtual input devices (mouse-as-joystick, touchscreen-as-joystick, keyboard-as-joystick, touchscreen-as-keyboard, etc.)

**Comment by slouken** [comment] 2023-11-07 05:34
Duplicate of https://github.com/libsdl-org/SDL/issues/7498

**Closed by slouken** 2023-11-07 05:34 UTC
