### ISSUE TITLE
Unable to link statically with cmake

### ISSUE THREAD

**Issue by yatadev** [libsdl-org/SDL#5324] opened 2022-02-06 15:21 UTC
If i have sdl as git submodule and do the following in CMakeLists.txt:

`
add_subdirectories(vendor/sdl EXCLUDE_FROM_ALL)
target_link_libraries(MyName
        SDL2::SDL2-static
)
`

I get: `MSVCRTD.lib(ftol2.obj) : error LNK2005: __ftol2_sse already defined in SDL2-staticd.lib(SDL_stdlib.c.obj)`

---

If i do the following in CMakeLists.txt:
`
set(SDL2_DIR "vendor/sdl")
find_package(SDL2 REQUIRED)
`

I get multiple lines like that: 
`
CMake Error at MyName/vendor/sdl/SDL2Config.cmake:66 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  MyName/CMakeLists.txt:106 (find_package)

FATAL_ERROR,SDL2::SDL2 and/or SDL2::SDL2main don't seem to contain any kind of IMPORTED_IMPLIB* or IMPORTED_LOCATION*
CMake Error at MyName/vendor/sdl/SDL2Config.cmake:102 (get_filename_component):
  get_filename_component called with incorrect number of arguments
Call Stack (most recent call first):
  MyName/CMakeLists.txt:106 (find_package)
`

**Comment by feliwir** [comment] 2022-05-31 11:26
I can reproduce a similar error with SDL 2.0.20:
When we compile for `WindowsStore` the SDL2main target is not generated (see https://github.com/libsdl-org/SDL/blob/main/CMakeLists.txt#L2884). However inside the SDL2Config.cmake it triesgetting a property from exactly that (non-existant) target. See https://github.com/libsdl-org/SDL/blob/main/SDL2Config.cmake#L50

**Comment by madebr** [comment] 2022-06-01 10:28
I'm doing some significant work on the cmake config files in https://github.com/libsdl-org/SDL/pull/5727 which should fix these errors.

The UWP test is failing because I don't understand what should be different between an ordinary windows application and an uwp one. So feedback on that would be welcome.

**Comment by madebr** [comment] 2022-06-01 22:50
Can any of you test https://github.com/libsdl-org/SDL/pull/5727?
And if possible, tell me how to fix the cmake project in `cmake/test` (created in the pr above), when targeting UWP?

**Comment by madebr** [comment] 2022-06-15 01:37
Closing this as we dont' do anything fancy with the `SDL2::SDL2main` target anymore in `SDL2Config.cmake`.

**Closed by madebr** 2022-06-15 01:37 UTC
