### ISSUE TITLE
update vendor check for accelerated OpenGL

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2510] opened 2021-02-11 00:43 UTC
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Linux, All

# Comments on the original bug report:

On 2017-07-25 04:03:28 +0000,  wrote:

> I noticed that the vendor check in ShouldUseTextureFramebuffer in SDL_video.c is way out of date.
> It needs to have Intel, AMD, and several Mesa drivers added.
> My vendor string for AMDGPU-PRO is "Advanced Micro Devices, Inc."

On 2017-08-09 05:25:34 +0000, Ryan C. Gordon wrote:

> (Sorry if you get a lot of copies of this email, we're touching dozens of bug reports right now.)
> 
> Tagging a bunch of bugs as target-2.0.6.
> 
> This means we're in the final stretch for an official SDL 2.0.6 release! These are the bugs we really want to fix before shipping if humanly possible.
> 
> That being said, we don't promise to fix them because of this tag, we just want to make sure we don't forget to deal with them before we bless a final 2.0.6 release, and generally be organized about what we're aiming to ship. After some debate, we might just remove this tag again and deal with it for a later release.
> 
> Hopefully you'll hear more about this bug soon. If you have more information (including "this got fixed at some point, nevermind"), we would love to have you come add more information to the bug report when you have a moment.
> 
> Thanks!
> --ryan.

On 2017-08-11 17:11:53 +0000, Sam Lantinga wrote:

> Updated to look at post 2.0.6.
> 
> At this point can we just assume that this path is fast enough on all drivers?

**Comment by icculus** [comment] 2021-11-30 05:37
Let's consider this a duplicate of #4624.

**Closed by icculus** 2021-11-30 05:37 UTC
Labels: enhancement
