### ISSUE TITLE
SDL2 and SDL example from action not detecting controller in Android 14

### ISSUE THREAD

**Issue by ikhoeyZX** [libsdl-org/SDL#9831] opened 2024-05-18 14:15 UTC
Hello

it seems like Android 14 broken any USB controller in SDL
i did tried in amdroid 13 or lower and my controller working
only in Android 14 are not detecting
![Screenshot_20240518_221118_testcontroller](https://github.com/libsdl-org/SDL/assets/79812109/3ba5a8d5-6775-4ad5-a7ff-2320aed9f6b1)

**Comment by slouken** [comment] 2024-05-18 14:57
@AntTheAlchemist, are you seeing this as well?

**Comment by AntTheAlchemist** [comment] 2024-05-18 15:25
I don't have a physical Android 14 device (and emulators don't have USB), but if there was an issue with SDL on a specific version of Android, it would reflect on the feedback on my Game Controller Tester app which is live on Google Play. No one has reported any issues and the ratings don't show a specific version problem (4.8 stars on Android 14, 4.3 Android 13, 4.8 Android 12...). It may be a problem with the test app? Rendering issue?

**Comment by ikhoeyZX** [comment] 2024-05-19 09:12
btw other emulator like vita3k have same problem (and it using SDL2)
Only in Android 14 usb not detected

i did tried merge from example SDL android HIDManager, but still same result

**Comment by ikhoeyZX** [comment] 2024-05-19 09:14
> I don't have a physical Android 14 device (and emulators don't have USB), but if there was an issue with SDL on a specific version of Android, it would reflect on the feedback on my Game Controller Tester app which is live on Google Play. No one has reported any issues and the ratings don't show a specific version problem (4.8 stars on Android 14, 4.3 Android 13, 4.8 Android 12...). It may be a problem with the test app? Rendering issue?

intent issue maybe, because i did test your app and it firing USB intent
example in SDL didnt popup that menu

![Screenshot_20240519_171354](https://github.com/libsdl-org/SDL/assets/79812109/53df0f59-0169-4da2-b6b7-0494dfb845da)

**Comment by madebr** [comment] 2024-05-19 12:21
This is the manifest used for the tests built on actions: https://github.com/libsdl-org/SDL/blob/main/test/android/cmake/AndroidManifest.xml.cmake
Can you please give it a sanity test?

**Comment by AntTheAlchemist** [comment] 2024-05-20 02:32
@ikhoeyZX, the pop-up that asks "Allow ... to access Wireless Controller" is caused by the `BLUETOOTH` & `BLUETOOTH_CONNECT` manifest entries. They are only needed for Steam Controllers and are not required. I added them to my app very recently, and it was working before I added them.

I think it might be a setting in the project.

**Comment by ikhoeyZX** [comment] 2024-05-20 10:29
> @ikhoeyZX, the pop-up that asks "Allow ... to access Wireless Controller" is caused by the `BLUETOOTH` & `BLUETOOTH_CONNECT` manifest entries. They are only needed for Steam Controllers and are not required. I added them to my app very recently, and it was working before I added them.
> 
> I think it might be a setting in the project.

still same result

**Comment by AntTheAlchemist** [comment] 2024-05-20 10:36
> still same result

@ikhoeyZX Yes, them manifest entries won't be the problem. 

I don't understand how you're using USB on an emulator though? Nothing I plug into my PC is transferred over to the emulator...

**Comment by ikhoeyZX** [comment] 2024-05-20 10:58
> > still same result
> 
> @ikhoeyZX Yes, them manifest entries won't be the problem.
> 
> I don't understand how you're using USB on an emulator though? Nothing I plug into my PC is transferred over to the emulator...

not in android emulator (because my pc cant run android studio)
but real hardware (samsung m33)
sdl app are vita3k emulator
this is bug what i encounter : https://github.com/Vita3K/Vita3K-Android/issues/625
i did ask dev and they still dont know how to fix it since he doesnt have android 14

**Comment by AntTheAlchemist** [comment] 2024-05-20 11:58
Please note that prompt isn't the reason why my app is working on Android 14. That prompt is only needed for Steam controllers. 

So, my SDL3 app can see game controllers on Android 14, but other apps can't, but they can on other Android versions? Including SDL3's test app?

Which version of SDL are you using to test?

I don't think I'm doing anything special to get this working. The test app's manifest looks fine. It looks like it's something else in the project setting, but there are too many options to guess. If you have the time, you can try to get your project to match my settings as closely as possible (I'll just cut-paste some relevant settings from my project):

```
- gradle-8.7-bin
-     compileSdk 34
-         minSdkVersion 16
-         targetSdkVersion 34
- com.android.tools.build:gradle:8.2.2
-     <uses-feature android:name="android.hardware.bluetooth" android:required="false" />
-     <uses-feature android:name="android.hardware.gamepad" android:required="false" />
-     <uses-feature android:name="android.hardware.type.pc" android:required="false" />
-     <uses-feature android:name="android.hardware.usb.host" android:required="false" />
-                 <action android:name="android.hardware.usb.action.USB_DEVICE_ATTACHED" />
```

**Comment by madebr** [comment] 2024-05-20 14:04
The manifest of the action apks contains the same items, so that shouldn't be it.

However, they have a target sdk version of 31, but don't set a minimum sdk version.
https://github.com/libsdl-org/SDL/blob/c6cc719067af0f1be6671eb258b79b708945210d/test/CMakeLists.txt#L703

@ikhoeyZX 
Replace `TARGET_SDK_VERSION 31` with `TARGET_SDK_VERSION 34 MIN_SDK_VERSION 16` to reproduce ant's configuration (ignoring gradle).

**Comment by AntTheAlchemist** [comment] 2024-05-20 14:10
In case hints might affect it, here are the relevant hints I'm using:

```
	SDL_SetHint(SDL_HINT_TV_REMOTE_AS_JOYSTICK, "0");
	SDL_SetHint(SDL_HINT_GAMECONTROLLER_SENSOR_FUSION, "0");
	SDL_SetHint(SDL_HINT_JOYSTICK_HIDAPI_COMBINE_JOY_CONS, "0");
	SDL_SetHint(SDL_HINT_JOYSTICK_ROG_CHAKRAM, "1");
	SDL_SetHint(SDL_HINT_JOYSTICK_HIDAPI, "1");
	SDL_SetHint(SDL_HINT_JOYSTICK_HIDAPI_PS3_SIXAXIS_DRIVER, "1");
	SDL_SetHint(SDL_HINT_JOYSTICK_HIDAPI_STEAM, "1");
	SDL_SetHint(SDL_HINT_JOYSTICK_HIDAPI_PS4_RUMBLE, "1"); // change to "auto" once SDL fixes power level bug?
	SDL_SetHint(SDL_HINT_JOYSTICK_HIDAPI_PS5_RUMBLE, "1");
	SDL_SetHint(SDL_HINT_JOYSTICK_HIDAPI_WII, "1");
	SDL_SetEventEnabled(SDL_EVENT_JOYSTICK_UPDATE_COMPLETE, SDL_FALSE);
	SDL_SetEventEnabled(SDL_EVENT_GAMEPAD_UPDATE_COMPLETE, SDL_FALSE);
```

**Comment by AntTheAlchemist** [comment] 2024-05-20 14:11
@ikhoeyZX, this is my build.gradle, but yours may look different:

```
android {
    compileSdk 34
    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 34
```

**Comment by ikhoeyZX** [comment] 2024-05-20 14:14
> @ikhoeyZX, this is my build.gradle, but yours may look different:
> 
> ```
> android {
>     compileSdk 34
>     defaultConfig {
>         minSdkVersion 16
>         targetSdkVersion 34
> ```

okay, i'm gonna test compile with minsdk 16 (before was 28)

**Comment by AntTheAlchemist** [comment] 2024-05-20 14:16
> okay, i'm gonna test compile with minsdk 16 (before was 28)

You may struggle to get it to compile with min 16 if there are dependencies that have a higher minimum. I've had to limit myself to older versions of some, to retain min 16:

```
    implementation 'com.android.billingclient:billing:6.0.1' // do not update beyond 6.0.1
    implementation 'com.google.android.gms:play-services-ads-lite:20.6.0' // do not update beyond 20.6.0
```

The minimumSdkVersion is not important - it shouldn't affect the problem, I should think.

**Comment by ikhoeyZX** [comment] 2024-05-22 13:14
nothing works with all suggestion
seems like SDL2 problem
I will wait until vita3k dev upgrade to SDL3

**Comment by AntTheAlchemist** [comment] 2024-05-22 13:21
It's still a problem if it's SDL2, because shares a lot of code with SDL3. It's likely the problem will still persist when they upgrade to SDL3.

**Comment by ikhoeyZX** [comment] 2024-06-14 11:08
Found solution to fix USB not detecting in Android 14
by adding this thing
```
                    intent.setPackage(mContext.getPackageName());
 ```
 in android-project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
 ```
 if (Build.VERSION.SDK_INT >= 33 /* Android 14.0 (U) */) {
                    Intent intent = new Intent(HIDDeviceManager.ACTION_USB_PERMISSION);
                    intent.setPackage(mContext.getPackageName());
                    mUsbManager.requestPermission(usbDevice, PendingIntent.getBroadcast(mContext, 0, intent, flags));
                } else {
                    mUsbManager.requestPermission(usbDevice, PendingIntent.getBroadcast(mContext, 0, new Intent(HIDDeviceManager.ACTION_USB_PERMISSION), flags));
                }
 ```

**Comment by ikhoeyZX** [comment] 2024-06-14 11:10
![Screenshot_20240614_190251_Settings](https://github.com/libsdl-org/SDL/assets/79812109/ee03a033-65ef-4417-935b-5059e2ad473d)

**Comment by slouken** [comment] 2024-06-14 16:08
> Found solution to fix USB not detecting in Android 14 by adding this thing
> 
> ```
>                     intent.setPackage(mContext.getPackageName());
> ```

Can you submit a PR or copy and paste more context so we can see where this would go?

**Comment by ikhoeyZX** [comment] 2024-06-14 16:14
> > Found solution to fix USB not detecting in Android 14 by adding this thing
> > ```
> >                     intent.setPackage(mContext.getPackageName());
> > ```
> 
> Can you submit a PR or copy and paste more context so we can see where this would go?

at in android-project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
in line 601

replace
```
mUsbManager.requestPermission(usbDevice, PendingIntent.getBroadcast(mContext, 0, new Intent(HIDDeviceManager.ACTION_USB_PERMISSION), flags));
```
with

```
if (Build.VERSION.SDK_INT >= 33 /* Android 14.0 (U) */) {
                   Intent intent = new Intent(HIDDeviceManager.ACTION_USB_PERMISSION);
                   intent.setPackage(mContext.getPackageName());
                   mUsbManager.requestPermission(usbDevice, PendingIntent.getBroadcast(mContext, 0, intent, flags));
               } else {
                   mUsbManager.requestPermission(usbDevice, PendingIntent.getBroadcast(mContext, 0, new Intent(HIDDeviceManager.ACTION_USB_PERMISSION), flags));
               }
```

**Comment by slouken** [comment] 2024-06-17 22:12
Fixed, thanks!

**Closed** 2024-06-17 22:11 UTC
