### ISSUE TITLE
Rendering sporadically silently fails on macOS

### ISSUE THREAD

**Issue by andreasgrabher** [libsdl-org/SDL#8495] opened 2023-11-07 19:09 UTC
I am experiencing an issue, where rendering sporadically fails on macOS. All involved functions do not return an error. The problem is described in detail here: https://discourse.libsdl.org/t/inexplainable-race-condition-in-sdl-renderer/39454

Please note that this also happens if running everything in a single thread. So it is NOT a multi-threading issue.

I'm on a Mac mini M1 running macOS Sonoma v14.1 but the problem also occured on an older machine running an older version of macOS. I use the latest version of SDL2 v2.28.5.

This issue might be related to https://github.com/libsdl-org/SDL/issues/5588.

**Comment by slouken** [comment] 2023-11-07 19:58
Duplicate of https://github.com/libsdl-org/SDL/issues/6542

**Closed by slouken** 2023-11-07 19:58 UTC
