### ISSUE TITLE
SDL apps blackscreen and hang on entering fullscreen mode on Ubuntu 22.04

### ISSUE THREAD

**Issue by donmor** [libsdl-org/SDL#5788] opened 2022-06-13 06:23 UTC
These days I'm trying to get [easyrpg-player](https://github.com/EasyRPG/Player) and [thextech-smbx](https://github.com/Wohlstand/TheXTech) on my PC with Ubuntu 22.04 installed. Both are based off SDL2, and when I try entering fullscreen mode, I get black screen and the app hangs. No error message, it just hangs. I tried nomodeset and snap build, but nothing helps.

**Comment by donmor** [comment] 2022-06-13 08:30
And sometimes I can't terminate tge app with ^C and have to kill -9.

**Comment by donmor** [comment] 2022-06-13 08:39
Here's the gdb trace of easyrpg-player, as a referrence.
[gdb.log](https://github.com/libsdl-org/SDL/files/8889440/gdb.log)

**Comment by icculus** [comment] 2022-06-13 19:21
This looks like it fell over waiting to grab the mouse...?

Also this looks like it statically linked SDL. Going to see if I can download this and reproduce the bug here.

**Comment by icculus** [comment] 2022-06-13 19:54
Tried the snap build (`sudo snap install easyrpg-player`) and it launched into fullscreen fine. I'm on 22.04.

I suspect this is a driver/X server issue.

I noticed that the gdb log says you have vmwgfx_dri.so loaded...are you running Ubuntu under vmware?

**Comment by donmor** [comment] 2022-06-13 22:54
It seems to be video-driver-independent. It's amdgpu on my pc, and I had tried nomodeset. It hangs every time I try.

**Comment by donmor** [comment] 2022-06-13 22:58
BTW I'm using mwm (motif window manager). I also use bare Xorg there. I'm trying to make a X session with only the game loaded.

**Comment by donmor** [comment] 2022-06-14 00:37
Tried LXDE but is not helpful... So it is de-independent.

**Comment by donmor** [comment] 2022-06-14 00:51
Hmm... I installed Ubuntu with live server image and choosed minimal, and later unminimized then installed xorg and other... Did this make the system different?

**Comment by icculus** [comment] 2022-06-14 00:57
I don't know, but it definitely seems to be broken in some way, and I'm not really sure how to debug it. From the gdb.log file, it looks like we call XGrabPointer(), which is waiting for a reply from the X server that just never comes.

**Comment by donmor** [comment] 2022-06-14 01:03
So there's no timeout? Not all games need a mouse... why not just suppress it if is no longer accessible?

**Comment by donmor** [comment] 2022-06-14 01:37
Latest: I found that once a SDL app is fullscreen and black screen, it can no longer be set focus by xdotool.

**Comment by donmor** [comment] 2022-06-14 01:47
Maybe I could try using xdotool to make a fake fullscreen, since I'm using bare xorg.

**Comment by icculus** [comment] 2022-06-14 02:32
> So there's no timeout?

XGrabPointer is hanging, assuming the gdb.log is showing where the process is hanging.

[It doesn't have a timeout as part of its API.](https://tronche.com/gui/x/xlib/input/XGrabPointer.html)

When trying to grab the pointer, SDL will retry for 5 seconds on the first attempt, to work around flakey systems, and then give up and never try to grab the pointer again if it still fails, but these should not be blocking inside XGrabPointer for most of those 5 seconds.

We could probably add a hint to say "never try to grab the pointer, even if it will break things" but I'm 80% confident this is something broken in your system installation, to be honest, and I suspect other things are going to not work even if we get past this issue.

If you can build your own SDL from source, this would be the fastest way to test if bypassing XGrabPointer works:

Go find this line in src/video/x11/SDL_x11video.c:

https://github.com/libsdl-org/SDL/blob/714502d3737d64d857460e38f4d5aee31d77b9fe/src/video/x11/SDL_x11video.c#L189

Add this right below it:

```c
data->broken_pointer_grab = SDL_TRUE;
```

And rebuild/install SDL. This won't help with easyrpg, because it looks like they statically linked SDL.

**Comment by icculus** [comment] 2022-06-14 02:56
(Actually, I don't know if this works in snaps, but you can export SDL_DYNAMIC_API=/where/i/installed/my/new/copy/of/libSDL2-2.0.so.0 and the statically-linked version will be bypassed for the new shared library.)

**Comment by carstene1ns** [comment] 2022-06-14 15:27
Just chiming in to say we only link the debug build statically (which is not really meant for distribution, just testing). The snap build and the OBS packages are using shared libraries of the system (or the snap environment).

That being said, I do not think we can do much on that issue, since we use a mostly "standard" event loop.

Maybe @donmor can try with a minimal SDL example to verify if the issue is related to their system setup.

**Comment by icculus** [comment] 2022-06-14 21:03
Here's a minimal example! Creates a 640x480 fullscreen window and just keeps clearing it to red various shades.

Copy/paste into a file named test.c, and compile/run it with:

```bash
gcc -o test test.c `sdl2-config --cflags --libs` && ./test
```

```c
#include "SDL.h"

int main(int argc, char **argv)
{
    SDL_Window *window;
    SDL_Renderer *renderer;
    SDL_bool done = SDL_FALSE;
    Uint8 r = 128;

    SDL_Init(SDL_INIT_VIDEO);
    window = SDL_CreateWindow("Hello SDL", SDL_WINDOWPOS_UNDEFINED,
                              SDL_WINDOWPOS_UNDEFINED, 640, 480, SDL_WINDOW_FULLSCREEN);

    renderer = SDL_CreateRenderer(window, -1, 0);

    while (!done) {
        SDL_Event e;
        while (SDL_PollEvent(&e)) {
            if (e.type == SDL_QUIT) {
                done = SDL_TRUE;
            } else if ((e.type == SDL_KEYDOWN) && (e.key.keysym.sym == SDLK_ESCAPE)) {
                done = SDL_TRUE;
            }
        }

        SDL_SetRenderDrawColor(renderer, r, 0, 0, 255);
        SDL_RenderClear(renderer);
        SDL_RenderPresent(renderer);
        SDL_Delay(10);
        r++;
    }

    SDL_Quit();
    return 0;
}
```

**Comment by icculus** [comment] 2022-07-27 17:58
@donmor We're trying to wrap up the next SDL release, so if you get a chance, it would be _very_ helpful if you could tell us if the little test program up there is also broken on your system. Thanks!

**Comment by icculus** [comment] 2022-08-02 14:44
Assuming this is a system bug and not SDL's, and closing. If there's more information, feel free to add it here and we'll reopen the issue!

**Closed by icculus** 2022-08-02 14:44 UTC
Labels: waiting
