### ISSUE TITLE
SDL_MOUSEMOTION not generated when app run without window manager under Linux

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3978] opened 2021-02-11 02:16 UTC
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.14
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2021-01-10 17:06:45 +0000, Jarosław Siebert wrote:

> Hello,
> I don't know if it is a libsdl bug or may be my setup problem.
> I use libsdl in my app on panel pc with touchscreen and mouse connected to usb port.
> If I run my app in fluxbox, then both input devices (mouse and touchscreen) works without problems. I need only 3 input events: SDL_MOUSEMOTION, SDL_MOUSEBUTTONUP and SDL_MOUSEBUTTONDOWN. When I move finger on touchscreen then I get SDL_MOUSEMOTION event and the same event when I use mouse. Coordinates (x and y) are correct in button.x, motion.x, button.y and motion.y.
> There are updated with correct posistions.
> 
> The problem begin when I run the same app from twm window manager or without any window manager (from .xinitrc directly).
> At the begining I got always the same 3 events:
> SDL_MOUSEMOTION: x = 640, y = 512
> SDL_MOUSEMOTION: x = 0, y = 0
> SDL_MOUSEMOTION: x = 640, y = 512
> and then, when I use touchscreen and move finger over it, I get only SDL_MOUSEBUTTONDOWN and SDL_MOUSEBUTTONUP events. There is no SDL_MOUSEMOTION event any more. Other problem is, that these events doesn't have right coordinates (x and y). When I move finger on screen I always get the same coordinates from SDL_MOUSEBUTTONDOWN and SDL_MOUSEBUTTONUP events: x= 640, y = 512.
> When I use mouse connected to usb, then I get all 3 events: SDL_MOUSEBUTTONUP, SDL_MOUSEBUTTONDOWN and SDL_MOUSEMOTION with right coordinates (x and y).
> When I use touch screen again (after I move cursor with usb mouse) then I read SDL_MOUSEBUTTONDOWN and SDL_MOUSEBUTTONUP with last coordynates read from last SDL_MOUSEMOTION event.
> Do I need to make some input events setup to work correctly without window manager or with simple window manager like twm?
> When I move finger on touchscreen - then I can see that cursor pointer moves with my finger, but there is no SDL_MOUSEMOTION event.
> When I run the app with fluxbox or other wm, then SDL_MOUSEMOTION is present on touchscreen and mouse actions.
> Can you check it?
> I initialize SDL with functions:
> SDL_Init(SDL_INIT_VIDEO|SDL_INIT_EVENTS|SDL_INIT_AUDIO);
> TTF_Init();
> (...)
> for(e = SDL_FIRSTEVENT+1; e < SDL_LASTEVENT; ++e) {
>                 SDL_EventState(e, SDL_IGNORE);
> }
> SDL_EventState(SDL_QUIT, SDL_ENABLE);
> SDL_EventState(SDL_KEYDOWN, SDL_ENABLE);
> SDL_EventState(SDL_KEYUP, SDL_ENABLE);
> SDL_EventState(SDL_MOUSEBUTTONDOWN, SDL_ENABLE);
> SDL_EventState(SDL_MOUSEBUTTONUP, SDL_ENABLE);
> SDL_EventState(SDL_MOUSEMOTION, SDL_ENABLE);
> (...)
> 
> I use slackware64-current with Xorg.
> I hope you can help me to find fix for app with touch input and without window manager.
> Thanks for any help.

On 2021-01-10 17:09:40 +0000, Jarosław Siebert wrote:

> I would like to add some more informations. When I run similar app but with sdl-1.2.15 (no sdl2) then touch events works correct with right x and y coordinates with and without window manager.
> I would like to get similar efect using SDL2.

**Comment by iu1j4** [comment] 2021-03-09 07:15
Hello,
I checked it again on Slackware64-current with SDL2-2.0.14 and the problem is worst.
I don't get any SDL_MOUSEMOTION under fluxbox with touch screen.
I downgraded SDL2 to SDL2-2.0.9 and now it works.
Since SDL2-2.0.10 there is problem with using touchscreen under Linux with SDL2 app and simple window managers.

**Comment by iu1j4** [comment] 2021-03-10 06:45
I have got new observations. The reason why touch movement doesn't work even under fluxbox is that I add to my app function:
SDL_SetHintWithPriority(SDL_HINT_GRAB_KEYBOARD, "1", SDL_HINT_OVERRIDE);
and
SDL_SetWindowGrab(gui.window, SDL_TRUE);
With it, touching screen doesn't update x and y coordinates.
If I touch screen with one finger somewhere and then move another finger on the screen, then the coordinates x and y are updated correctly.
Without SDL_SetWindowGrab(gui.window, SDL_TRUE); and SDL_SetHintWithPriority(SDL_HINT_GRAB_KEYBOARD, "1", SDL_HINT_OVERRIDE); touch movement works correctly under fluxbox.
This is related to SDL2 library version. Problems started with versio 2.0.10 (2.0.9 doesn't has the problems).
But another problem is when I run sdl2 app without any window manager (as standalone app). There are problems even on SDL2-2.0.9 with getting correct x and y coordinates when moving finger over the screen.

**Comment by icculus** [comment] 2021-05-10 14:25
I'm bumping this out of the 2.0.16 milestone; I don't have a touchscreen to reproduce this.

**Comment by 1bsyl** [comment] 2021-05-12 21:18
@iu1j4 
I have a touchscreen, and indeed, on X11:
when the pointer is grabbed, the touchscreen isn't responsive.
The previous commit fix somehow this.
(The pointer remains grabbed, but you can use the touchscreen).
Can you try on your side ?

**Comment by iu1j4** [comment] 2021-05-16 19:45
I tested it with SDL2 from github.
The fix is working. I can use my touch screen with or without pointer grabbed and there is no problems with SDL_MOUSEMOTION. Thanks for the fix.

Some compilation warnings:
  CC     build/SDL_test_memory.lo
/root/SLACKBUILDS/SDL2/SDL/src/test/SDL_test_memory.c: In function 'SDL_TrackAllocation':
/root/SLACKBUILDS/SDL2/SDL/src/test/SDL_test_memory.c:112:103: warning: '+0x' directive output may be truncated writing 3 bytes into a region of size between 1 and 256 [-Wformat-truncation=]
  112 |                 snprintf(entry->stack_names[stack_index], sizeof(entry->stack_names[stack_index]), "%s+0x%llx", sym, (unsigned long long)offset);
      |                                                                                                       ^~~
/root/SLACKBUILDS/SDL2/SDL/src/test/SDL_test_memory.c:112:17: note: 'snprintf' output between 5 and 275 bytes into a destination of size 256
  112 |                 snprintf(entry->stack_names[stack_index], sizeof(entry->stack_names[stack_index]), "%s+0x%llx", sym, (unsigned long long)offset);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC     build/SDL_test_random.lo
  LTLINK build/libSDL2_test.la

**Comment by 1bsyl** [comment] 2021-05-17 08:32
@iu1j4 
Ok, thanks for the feedback ! is that ok to close the issue ?
(+re-open one for the 'snprintf' warning)

**Comment by iu1j4** [comment] 2021-05-17 15:19
> @iu1j4
> Ok, thanks for the feedback ! is that ok to close the issue ?
> (+re-open one for the 'snprintf' warning)

yes, it is ok to close the issue.

**Comment by 1bsyl** [comment] 2021-05-17 17:57
@iu1j4 ok closing !

**Comment by icculus** [comment] 2021-05-17 17:59
@1bsyl Thanks for looking into this!

**Comment by rofl0r** [comment] 2021-09-02 21:55
fyi the commit fixing this issue causes SDL2 to hang after update to 2.0.16 for everybody not using bleeding edge libxi. it took me about an hour to bisect the hang to this issue, and it seem i'm not alone - see references above. additionally the SDL_VIDEO_DRIVER_X11_XINPUT2_SUPPORTS_MULTITOUCH define can't be toggled on or off via a ./configure flag.

**Comment by 1bsyl** [comment] 2021-09-03 20:13
@rofl0r thanks for the info!
There is a function  "query_xinput2_version()" in "src/video/x11/SDL_x11xinput2.c"
Maybe we can add a variable "xinput2_grabtouch_supported" (similar to "xinput2_multitouch_supported")
And activate the feature or not, based on the xinput2 version ?

**Comment by rofl0r** [comment] 2021-09-04 00:50
> And activate the feature or not, based on the xinput2 version ?

i'm generally not a fan of version checks, though in this case which causes a pretty hard to debug complete failure scenario, this could be a workable solution - given that using multitouch with X11 sounds like a rather niche usecase.

**Comment by slouken** [comment] 2021-11-09 18:46
I added a new bug to cover the libXi hang issue.

**Closed by slouken** 2021-11-09 18:46 UTC
Labels: bug, help wanted
