### ISSUE TITLE
SDL3, macOS: Main thread warnings with latest revision of SDL3

### ISSUE THREAD

**Issue by andreasgrabher** [libsdl-org/SDL#10977] opened 2024-09-28 09:01 UTC
Since recently I am getting these warnings when calling `SDL_RenderPresent()` on macOS Sonoma:

[NSView bounds] must be used from main thread only
[NSView convertRectToBacking:] must be used from main thread only

This did not happen before.

**Comment by Akaricchi** [comment] 2024-09-28 14:09
Pretty sure it's because of #10958, since `SDL_RenderPresent()` calls `SDL_GetWindowSizeInPixels()` now, which calls those functions.

cc @thatcosmonaut

**Comment by flibitijibibo** [comment] 2024-09-28 15:09
Marking as ABI since this may be an ABI regression in terms of having no way to get swapchain size safely.

**Comment by flibitijibibo** [comment] 2024-09-28 19:57
@andreasgrabher, can you see if #10984 fixes this problem?

**Closed** 2024-09-29 01:01 UTC
Labels: waiting
