### ISSUE TITLE
In Wayland, Endless Sky game's window drawn in the wrong place when alt-tabbing away and back again

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2360] opened 2021-02-11 00:33 UTC
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [test case (fullscreen_testcase.cpp, text/x-c++src, 2017-02-05 19:26:20 +0000, 1263 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2696)

**Reported in version:** don't know
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2017-01-07 20:07:40 +0000, Nate Graham wrote:

> Software: Fedora 25 + GNOME 3.22 + Wayland
> 
> Hardware: Kaby Lake (late 2016) HP Spectre x360 laptop, Intel HD 620 integrated graphics card, 13.3" display, Kernel 4.10-rc2 (though this has happened since 4.8).
> 
> A graphical anomaly is seen with the SDL-based video game Endless Sky on Fedora 25 with Wayland. When the game is being played full-screen, alt-tabbing away and back again results in the game's window being drawn in the wrong location: offset down and to the right. Here is a screen recording indicating the problem:
> 
> http://hommelscitadel.com/wp-content/uploads/2016/12/not_quite_right.webm
> 
> The issue is 100% reproducible with Wayland every way I try, but not seen if I log into an X session and try the same things.
> 
> I originally filed this against Endless Sky: https://github.com/endless-sky/endless-sky/issues/1902. The developer said it was SDL or Wayland (https://bugs.freedesktop.org/show_bug.cgi?id=99088). The Wayland folks say it's not them, so... here I am :)

On 2017-02-05 19:26:20 +0000, Kārlis Seņko wrote:

> Created attachment 2696
> test case
> 
> Was able to repeat with 2.0.5 and attached test case.

**Comment by flibitijibibo** [comment] 2021-04-08 20:02
I think this may have been fixed when SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS was changed to 0 by default. With my own fullscreen tests I'm unable to reproduce this.

**Comment by icculus** [comment] 2021-04-09 02:24
So we have some unhappy people about the minimize-on-loss change, so we need to revisit that before we celebrate here.

(revisiting it might include deciding to leave it as-is, to be clear.)

**Comment by flibitijibibo** [comment] 2021-04-09 18:46
Double checked with `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=1` and fullscreen still behaves on my test environments. I don't have Endless Sky to check, but our fullscreen behavior in FNA isn't any different than what the test case is doing.

**Comment by flibitijibibo** [comment] 2021-04-09 21:01
Oh, I probably should have checked the original issue too... they also confirmed it as fixed, citing "early Wayland days" https://github.com/endless-sky/endless-sky/issues/1902

**Comment by icculus** [comment] 2021-04-17 04:43
Closing as apparently-fixed.

**Closed by icculus** 2021-04-17 04:43 UTC
Labels: bug
