### ISSUE TITLE
MacOS pinch/spread events lost

### ISSUE THREAD

**Issue by RobertFlatt** [libsdl-org/SDL#6137] opened 2022-08-26 01:24 UTC
For non-MacOS touchpad gestures, SDL2 correctly propagates mousewheel events for scroll, horizontal scroll, and zoom.

For MacOS trackpad gestures, SDL2 propagates mousewheel events but only for the scroll gestures, and not for zoom. And in addition the equivalent zoom equivalent pinch-spread finger gestures are not propagated.

Thus pinch-spread is inconsistent across platforms, so I create an issue.

I can use MultitouchSupport.framework to see that the trackpad is generating the individual events that make up pinch-spread (aka ctrl-mousewheel). But for SDL2 on MacOS neither the individual touches, nor the ctrl-scroll are propagated.

How to enable the detection of zoom?

**Comment by slouken** [comment] 2024-05-21 17:34
This is a duplicate of https://github.com/libsdl-org/SDL/issues/7706

**Closed by slouken** 2024-05-21 17:34 UTC
