### ISSUE TITLE
Hint for a 'out of bounds index' condition in the GLES2 render algorithm

### ISSUE THREAD

**Issue by 312937** [libsdl-org/SDL#5235] opened 2022-01-17 20:07 UTC
Related SDL2 versions:
- 2.0.18, 2.0.20

Reproducible on:
- Android emulator API 24..28 (though never tried below 24)
- Surely (and obviously) not an application or system memory allocation problem.

Severity hard to estimate, as currently only reproducible under the emulator.

How to reproduce:
- Assumable drawing rectangles after images.
- The difficulty disappears while disabling the function SDL_RenderDrawRect() usage.

Observed behaviour:
- Malfunction in the application: missing elements (interrupted rendering), apparent memory overwrites.
- ADB log:
```
E/emuglGLESv2_enc: a vertex attribute index out of boundary is detected. Skipping corresponding vertex attribute. buf=0x91bc5ab0
E/emuglGLESv2_enc: Out of bounds vertex attribute info: clientArray? 0 attribute 2 vbo 7 allocedBufferSize 648 bufferDataSpecified? 1 wantedStart 0 wantedEnd 1068
```

Hints:
- The same code works fine under Linux (portable).
- Emulator API >= 29 does not report the problem.
- Available ('real') Android devices does not show the symptoms.
- It might still be an internal emulator problem, though hardly to believe upon conditions.

Suspected code:
- SDL_render_gles2.c
  - Especially 'join counters' and SDL_Vertex/SDL_VertexSolid usage.
- Interface compatibility.
- Comparing the HEAD, I still suspect the GLES2 implementation.

Unfortunately I cannot provide a remedy or any further evidence at the moment.

**Comment by 1bsyl** [comment] 2022-01-17 20:22
Can you try with latest HEAD version ?

( also re-enable VBO here: 
https://github.com/libsdl-org/SDL/blob/main/src/render/opengles2/SDL_render_gles2.c#L38
)

can you provide a test-case ?

**Comment by 312937** [comment] 2022-01-17 21:08
**HEAD**: I'll surely try the option and let you know. Though, I apologize as I may verify it first tomorrow.

**Test case**: That's unfortuantelly really difficult. I wish I could...

More hints:
- It looks like changing the screens and presentation options in the application 'expands' the (library allocated) background vertex buffer:
```
...
... E/emuglGLESv2_enc: a vertex attribute index out of boundary is detected. Skipping corresponding vertex attribute. buf=0x918bb050
... E/emuglGLESv2_enc: Out of bounds vertex attribute info: clientArray? 0 attribute 2 vbo 5 allocedBufferSize 528 bufferDataSpecified? 1 wantedStart 0 wantedEnd 948
... E/emuglGLESv2_enc: a vertex attribute index out of boundary is detected. Skipping corresponding vertex attribute. buf=0x918bafc0
... E/emuglGLESv2_enc: Out of bounds vertex attribute info: clientArray? 0 attribute 2 vbo 3 allocedBufferSize 528 bufferDataSpecified? 1 wantedStart 0 wantedEnd 948
??? size: 528 --> 696... (after screen change)
... E/emuglGLESv2_enc: a vertex attribute index out of boundary is detected. Skipping corresponding vertex attribute. buf=0x920793f0
... E/emuglGLESv2_enc: Out of bounds vertex attribute info: clientArray? 0 attribute 2 vbo 1 allocedBufferSize 696 bufferDataSpecified? 1 wantedStart 0 wantedEnd 948
... E/emuglGLESv2_enc: a vertex attribute index out of boundary is detected. Skipping corresponding vertex attribute. buf=0x918bb0b0
...
```
- The screen elements are statically assigned 'controls' (each screen), no dynamic contents.
- I reviewed the code for own mistakes first.
- I reverted to 2.0.16, no troubles...

**Comment by 312937** [comment] 2022-01-18 18:55
Environment:

- Emulator
- Android 7.0 (Nougat)	API	24
- Intel x86 Atom System Image	24 Rev. 8
- Details: render-env.txt

[render-env.txt](https://github.com/libsdl-org/SDL/files/7891555/render-env.txt)

Verifcation:

- HEAD: NO VBO (GIT-SHA 381520ad921944284226b4ebf96299cb7fd0a69c 2022-01-18 12:32:24)
  - nothing to report, working correctly

- HEAD VBO (GIT reference as above)
  - SDL render sequence (call) dump attached as TXT below (all parameters in range).
    - ... hoping the sequence may help to produce a test case...
  - malfunction --> render-HEAD-VBO-err.txt
  - semi-acceptable --> render-HEAD-VBO-semi-ok-more-img-less-rect.txt
[render-HEAD-VBO-err.txt](https://github.com/libsdl-org/SDL/files/7891564/render-HEAD-VBO-err.txt)
[render-HEAD-VBO-semi-ok-more-img-less-rect.txt](https://github.com/libsdl-org/SDL/files/7891568/render-HEAD-VBO-semi-ok-more-img-less-rect.txt)

- SDL2 2.0.20
  - confirmed malfunction as GIT HEAD VBO (qed).
  - the same sequence (code), visually slightly worse than HEAD VBO.

**Comment by 1bsyl** [comment] 2022-01-18 20:31
Ok ! Thanks, I'll look at it later!
I already tried with an app and it didn't report any out of bounds like this. But maybe I didn't use a correct broken sequence.
(My emulator can report them if I fake the 'count' in the gles2 driver).

Can you dump the sequence using the 'debug' variable in the file SDL_render.c
So that we can see how it s batched
https://github.com/libsdl-org/SDL/blob/main/src/render/SDL_render.c#L132




Maybe you could

**Comment by 312937** [comment] 2022-01-18 21:39
Trace from SDL2 2.0.20 (the same sequence as reported before)
[render-2.0.20-debug.txt](https://github.com/libsdl-org/SDL/files/7892511/render-2.0.20-debug.txt)

I hope it may help to reproduce the trouble...

**Comment by 1bsyl** [comment] 2022-01-22 18:56
@312937 
I haven't been able to reproduce it so far,

Just wondering, if possible
- can you reduce to isolate a test-case ?
- can you enable the thread id / process id in the logcat so that we are sure this comes from the SDL thread ? 
   (or if there several thread in your app)
-what is strange is the adb log compared to the debug: 
  "wantedEnd 1068" isn't egual to "first=768, count=6, " (eg 768 + 6 * 20 = 908)
  so the error doesn't follow the previous commands


can you add also some log: 
line after 1127 of SDL_render_gles2.c
```diff
vertices = NULL;  /* attrib pointers will be offsets into the VBO. */
+ SDL_Log("vertsize: %ld", vertsize);
+ GL_CheckError("", renderer);
```
and log the calls to glBufferData and glBufferSubData maybe ...

**Comment by 312937** [comment] 2022-01-23 07:15
I'll do

**Comment by 312937** [comment] 2022-01-26 19:46
Provided:
https://github.com/312937/verify_issue/blob/main/src/mainTest.cpp

The whole related project might be provided but I suppose the difficulty analysis may be reduced to the function:
`drawSimpleText()`
... and further especially removing the texture:
`::SDL_DestroyTexture(pSdlTexture);`

Questions:
1) Is it allowed in the context? (thus it might be my own mistake as the partial texture is released before the final draw)
2) It is allowed but resulting in the misbehaviour when VBO is allowed?

**Comment by 1bsyl** [comment] 2022-01-27 09:09
@312937 Thanks, I've reproduced the issue with a smaller test-case. Calling delete texture seems indeed to trigger the warning ! But the test-case seems ok.

```c
#include "SDL.h"

int main(int, char * *)
{
    if (SDL_Init(SDL_INIT_VIDEO) != 0) {
        SDL_Log("init");
        return 2;
    }

    SDL_SetHint(SDL_HINT_RENDER_DRIVER, "opengles2");
    SDL_SetHint(SDL_HINT_RENDER_BATCHING, "1");

    SDL_Window *window = SDL_CreateWindow("GW", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 1000, 1000, SDL_WINDOW_SHOWN | SDL_WINDOW_INPUT_FOCUS);
    if (window == NULL) {
        SDL_Log("SDL_CreateWindow");
        return 2;
    }
    SDL_Renderer *renderer  = SDL_CreateRenderer(window, -1, SDL_RENDERER_PRESENTVSYNC | SDL_RENDERER_ACCELERATED);
    if(renderer == NULL) {
        SDL_Log("SDL_CreateRenderer");
        return 2;
    }

    SDL_Surface *surface = SDL_CreateRGBSurfaceWithFormat(0, 100, 100, 0, SDL_PIXELFORMAT_ARGB8888);
    if(surface == NULL) {
        SDL_Log("error create surface");
    }
    SDL_FillRect(surface, NULL, SDL_MapRGBA(surface->format, 200, 200, 200, 255));

    int done  = 0;
    while (!done) {
        SDL_Event evt;
        while (SDL_PollEvent(&evt)) {
            switch (evt.type)
            {
                case SDL_QUIT:
                    done = 1;
                    break;

                case SDL_KEYDOWN:
                    {
                        const int sym = evt.key.keysym.sym;
                        if (sym == SDLK_SPACE) {
                            SDL_Log("Key : Space!");
                        }
                        if (sym == SDLK_ESCAPE || sym == SDLK_AC_BACK) {
                            done = 1;
                            SDL_Log("Key : Escape!");
                        }
                    }
                    break;
            }
        }

        { 
            SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
            SDL_RenderClear(renderer);

            SDL_Rect  rcPos = { 200, 500, 300, 300 };

            SDL_Texture *texture = SDL_CreateTextureFromSurface(renderer, surface);
            if (texture == NULL) {
                SDL_Log("error create texture");
            }

            SDL_RenderCopy(renderer, texture, NULL, &rcPos);

            SDL_DestroyTexture(texture); // .... move after SDL_RenderPresent() to prevent the warning
            
            SDL_SetRenderDrawColor(renderer, 10, 50, 100, 255);
#if 1
            int x = 10;
            SDL_Rect  rcPos2 = { 600, 500, 100, 30 };
            while (x--) { 
                SDL_RenderFillRect(renderer, &rcPos2);
                rcPos2.y += rcPos2.h * 1.1;
            }
#else
            /* It also fails */
            int x = 1000;
            while (x--) SDL_RenderDrawPoint(renderer, 500, 500);
#endif
            SDL_RenderPresent(renderer);
        }
        SDL_Delay(10);
    }
            
    SDL_FreeSurface(surface);
    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    SDL_Quit();
    return 0;
}
```

**Comment by 1bsyl** [comment] 2022-01-27 09:35
@312937 

Seems that GLES2_DestroyTexture() clears the state "data->drawstate.texture = NULL;"
and so glDisableVertexAttribArray() won't be called to disable textcoord.

Can you try with this GLES2_DestroyTexture modification:

```c
static void
GLES2_DestroyTexture(SDL_Renderer *renderer, SDL_Texture *texture)
{
    GLES2_RenderData *data = (GLES2_RenderData *)renderer->driverdata;
    GLES2_TextureData *tdata = (GLES2_TextureData *)texture->driverdata;
    int update_state = 0;

    GLES2_ActivateRenderer(renderer);
    if (data->drawstate.texture == texture) {
        data->drawstate.texture = NULL;
        update_state = 1;
    }
    if (data->drawstate.target == texture) {
        data->drawstate.target = NULL;
        update_state = 1;
    }

    /* Destroy the texture */
    if (tdata) {
        data->glDeleteTextures(1, &tdata->texture);
#if SDL_HAVE_YUV
        if (tdata->texture_v) {
            data->glDeleteTextures(1, &tdata->texture_v);
        }
        if (tdata->texture_u) {
            data->glDeleteTextures(1, &tdata->texture_u);
        }
#endif
        SDL_free(tdata->pixel_data);
        SDL_free(tdata);
        texture->driverdata = NULL;
    }
    
    /* Turn Vertex Attribute off */
    if (update_state){
        if (data->drawstate.texturing) {
            data->glDisableVertexAttribArray((GLenum) GLES2_ATTRIBUTE_TEXCOORD);
            data->drawstate.texturing = SDL_FALSE;
        }
    }
}

**Comment by 1bsyl** [comment] 2022-01-27 13:30
I think in many place we discard the texture state, but we don't update with "data->glDisableVertexAttribArray((GLenum) GLES2_ATTRIBUTE_TEXCOORD);"

@312937 Can you test the PR #5266 to see if this solves the issue with the real app ?
( you still need to force the VBO inside )

**Comment by 312937** [comment] 2022-01-27 18:44
I've just verified your #5266 with VBO enabled (as an 'add-on' to the current `master`).
As it contains `GLES2_DestroyTexture` modification I've skipped this part.
Both the application and my lengthy test performed fine. It seems really quite comfortable.
I could not register any "damage" in the layout or warnings.

Thanks!

PS. Sorry for my pretty complicated example. I did not want to provide a flaw, so I tried to reproduce all the calls including some timing. Finally (after some failed trials), I had noticed the 'destroy texture' issue from 'dynamic' TTF textures.

**Comment by 1bsyl** [comment] 2022-01-28 09:17
@312937 
Thanks for the testing !  No problem for the test-case, it was not straight forward to reduce.
@icculus has merged it ! but I have also looked at the opengl to see it has the same behavior, and it didn't because the code path is a little different, so I'll try later another approach so we keep more similar code between opengl and gles2.

**Comment by 1bsyl** [comment] 2022-01-28 14:40
@312937 Please try this PR #5272 instead
(just need to update the gles2 file + enable VBO inside)
I think it's more clean than the previous one

**Comment by 312937** [comment] 2022-01-28 18:15
It looks fine as well.

**Comment by 1bsyl** [comment] 2022-01-28 18:26
Thanks, 
merged and let's close this issue

**Closed by 1bsyl** 2022-01-28 18:26 UTC
