### ISSUE TITLE
[Android] audio output breaks when removing / inserting earphones on S9 android 10

### ISSUE THREAD

**Issue by ITotalJustice** [libsdl-org/SDL#4985] opened 2021-11-20 22:19 UTC
This was tested on a Samsung Galaxy S9, running android 10.

However, this does not happen on nvidia shield running android 5.1 and mi9 running lineageos 11.0.

starting my app without or without earphones works normally. However, if i insert / remove them, then audio playback stops. Also, the sdl_audio_callback is called more frequently (haven't measured but it seems to be like max speed my phone can handle).

log from plugging in earphones
```
D/InputTransport: Input channel destroyed: '5af41f5', fd=69
W/AudioTrack: restoreTrack_l(988): dead IAudioTrack, PCM, creating a new one from obtainBuffer()
W/AudioSystem: ioConfigChanged() modifying unknown output! 13
D/AAudio: AAudioStream_requestPause(s#1) called
D/AudioStreamLegacy: onAudioDeviceUpdate() devId 3 => 990
    onAudioDeviceUpdate() DISCONNECT the stream now
D/: PlayerBase::pause() from IPlayer
D/AAudio: AAudioStream_requestStart(s#1) called --------------
E/AAudioStream: setState(1) tried to set to 3 but already DISCONNECTED
D/: PlayerBase::start() from IPlayer
D/AAudio: AAudioStream_requestStart(s#1) returned 0 ---------
```

log pulling out earphones (after restarting the app with headphones already plugged in
```
D/InputTransport: Input channel destroyed: '32fe96 ', fd=69
W/AudioTrack: restoreTrack_l(1007): dead IAudioTrack, PCM, creating a new one from obtainBuffer()
W/AudioSystem: ioConfigChanged() modifying unknown output! 13
D/AAudio: AAudioStream_requestPause(s#1) called
D/: PlayerBase::pause() from IPlayer
D/AAudio: AAudioStream_requestStart(s#1) called --------------
D/: PlayerBase::start() from IPlayer
D/AAudio: AAudioStream_requestStart(s#1) returned 0 ---------
D/AudioStreamLegacy: onAudioDeviceUpdate() devId 1000 => 3
```

as it seems to only happen on my s9, and theres not a way to simulate plugging in headphones using AS emulators, this it probably going to be a pain to debug haha. Let me know if theres anything you want me to test. I can fork sdl and try the changes locally.

**Comment by ITotalJustice** [comment] 2021-11-22 07:59
i had a look at the aaudio docs, and this stood out to me <https://developer.android.com/ndk/guides/audio/aaudio/aaudio#disconnected-streams>

i enabled aaudio logging in sdl, and sure enough, it was spamming AAUDIO_ERROR_DISCONNECTED here https://github.com/libsdl-org/SDL/blob/6d5edfa733cca54671207e2d02b732b231971c76/src/audio/aaudio/SDL_aaudio.c#L219.

the docs say that once the stream is disconnected, then the stream should be closed and then reopened. unless i'm missing it, im not seeing that happen, which causes the error.
source: <https://developer.android.com/ndk/reference/group/audio#group___audio_1ga99fb83031ce9923c84392b4e92f956b5>
```
This could occur, for example, when headphones are plugged in or unplugged. The stream cannot be used after the device is disconnected. Applications should stop and close the stream. If this error is received in an error callback then another thread should be used to stop and close the stream. 
```

as you set the error callback, it's likely the error will be passed to there first, so its worth check in the write fail and error callback. maybe has a function `aaudio_handle_error` which will check the error and see if anything needs to be handled. https://github.com/libsdl-org/SDL/blob/6d5edfa733cca54671207e2d02b732b231971c76/src/audio/aaudio/SDL_aaudio.c#L66

too make sure this was the cause of the issue, i added this to `aaudio_PlayDevice` (im not closing the current audio stream as that crashed for me, so, ignore the mem leak) and this worked
```c
static void
aaudio_PlayDevice(_THIS)
{
    struct SDL_PrivateAudioData *private = this->hidden;
    aaudio_result_t res;
    int64_t timeoutNanoseconds = 1 * 1000 * 1000; /* 8 ms */
    res = ctx.AAudioStream_write(private->stream,  private->mixbuf, private->mixlen / private->frame_size, timeoutNanoseconds);
    if (res < 0) {
        if (res == AAUDIO_ERROR_DISCONNECTED) {
            ctx.AAudioStreamBuilder_openStream(ctx.builder, &private->stream); // reopen stream (mem leak probably)
            ctx.AAudioStream_requestStart(private->stream); // start new stream
        }
        LOGI("%s : %s", __func__, ctx.AAudio_convertResultToText(res));
    } else {
        LOGI("SDL AAudio play: %d frames, wanted:%d frames", (int)res, private->mixlen / private->frame_size);
    }
```

**Comment by 1bsyl** [comment] 2021-11-22 09:09
Hey, I could reproduce the issue: I got the audio disconnected.
Indeed your fix seem to work. I've re-added the "write".
And when I add a call to closeStream(), it crashes.

Seem a concurrency issue with aaudio_DetectBrokenPlayState() /  getTimestamp, which is called from main() thread.
whereas audio playDevice() is run from RunAudio thread.  (that was added in https://github.com/libsdl-org/SDL/commit/2423c514716f0202b098e20cb682f401b3c141fe )
Even without fixing the current issue. It could probably crash the same way when doing closeDevice ?
@slouken ?
maybe the aaudio_DetectBrokenPlayState() could be moved to the RunAudio thread ...  but not sure since write would be blocking


```
static void
aaudio_PlayDevice(_THIS)
{
    struct SDL_PrivateAudioData *private = this->hidden;
    aaudio_result_t res;
    int64_t timeoutNanoseconds = 1 * 1000 * 1000; /* 8 ms */
    res = ctx.AAudioStream_write(private->stream,  private->mixbuf, private->mixlen / private->frame_size, timeoutNanoseconds);
    if (res < 0) {
        if (res == AAUDIO_ERROR_DISCONNECTED) {
            ctx.AAudioStream_close(private->stream);
            ctx.AAudioStreamBuilder_openStream(ctx.builder, &private->stream); // reopen stream (mem leak probably)
            ctx.AAudioStream_requestStart(private->stream); // start new stream
            res = ctx.AAudioStream_write(private->stream,  private->mixbuf, private->mixlen / private->frame_size, timeoutNanoseconds);
            SDL_Log("SDL AAudio play: DISCONNECTED / RECONNECTED");
        }
    }
        
    if (res < 0) {
        LOGI("%s : %s", __func__, ctx.AAudio_convertResultToText(res));
    } else {
        LOGI("SDL AAudio play: %d frames, wanted:%d frames", (int)res, private->mixlen / private->frame_size);
    }

```

**Comment by ITotalJustice** [comment] 2021-11-22 09:12
Ah I’m glad you were able to reproduce it! I was trying to see where best to call close (on main thread) but I’m not really familiar with sdl internally unfortunately

**Comment by AJenbo** [comment] 2022-06-24 11:11
This appears to also be triggered when receiving a phone call. And can lead to 100% CPU load as well.

**Comment by slouken** [comment] 2023-11-07 03:25
Can you see if this is fixed in the latest SDL3 code? We've completely revamped how audio hotplug works.

**Comment by dingogames** [comment] 2024-01-26 07:56
I just disconnected my bluetooth headphones while testing and noticed this issue in my build. I proceeded to test my whole pile of Android devices.
I'm testing on 2.28.x - not on SDL3.

The issue occurs on every device that I tested that uses AAudio. Here is the list: Moto G5 Plus, Moto G7, Fire HD 10 (13th Generation), Fire 7 (12th Generation), Huawei P40 lite, Xiaomi Mi 9 SE, Pixel 6.
Not only does the sound stop working, the game becomes mostly unplayable - every sound that is played causes a half second or more delay.

The only devices that I have that it worked on are the Fire HD 8 (7th gen) - API Level 22 and BLU Advance 5.0 HD - API Level 23. The API level on these are so old that AAudio would not be available and they are falling back to OpenSL ES. The original poster @ITotalJustice had two devices that they said worked - I believe these were also old enough to be falling back to OpenSL ES.

Based on my testing, I believe this is actually a pretty severe bug that affects almost every Android device newer than 6 years old. 

My current solution is to use OpenSL ES on all Android devices. I don't know if there are downsides to this. I did a quick test on all my devices and it worked on all them.

Sorry I didn't test 3.2.0 - but it appears to me that you at least don't need to test on any particular Android device to see if it is fixed. Anything using AAudio should suffice.

**Comment by ITotalJustice** [comment] 2024-01-26 17:40
> I just disconnected my bluetooth headphones while testing and noticed this issue in my build. I proceeded to test my whole pile of Android devices. I'm testing on 2.28.x - not on SDL3.
> 
> The issue occurs on every device that I tested that uses AAudio. Here is the list: Moto G5 Plus, Moto G7, Fire HD 10 (13th Generation), Fire 7 (12th Generation), Huawei P40 lite, Xiaomi Mi 9 SE, Pixel 6. Not only does the sound stop working, the game becomes mostly unplayable - every sound that is played causes a half second or more delay.
> 
> The only devices that I have that it worked on are the Fire HD 8 (7th gen) - API Level 22 and BLU Advance 5.0 HD - API Level 23. The API level on these are so old that AAudio would not be available and they are falling back to OpenSL ES. The original poster @ITotalJustice had two devices that they said worked - I believe these were also old enough to be falling back to OpenSL ES.
> 
> Based on my testing, I believe this is actually a pretty severe bug that affects almost every Android device newer than 6 years old.
> 
> My current solution is to use OpenSL ES on all Android devices. I don't know if there are downsides to this. I did a quick test on all my devices and it worked on all them.
> 
> Sorry I didn't test 3.2.0 - but it appears to me that you at least don't need to test on any particular Android device to see if it is fixed. Anything using AAudio should suffice.

yeah the issue comes from the call to `AAudioStream_write` as it will fail if the device changes, ie, headphones are plugged in, speaker is connected etc. This will return `AAUDIO_ERROR_DISCONNECTED`. The correct way to handle this is to call `AAudioStream_close` and then call `AAudioStreamBuilder_openStream` (you can keep the old build struct alive). 

I made a hacky fix for this when i opened this issue. For some reason, i don't close the audio stream, i can't remember why, maybe it causes issues? Anyway, this works, but the correct fix is to call `AAudioStream_close` *then* re-open, otherwise it's a memleak. https://github.com/libsdl-org/SDL/compare/main...ITotalJustice:SDL:android_headphone_hack#diff-c1eefd450145e966ae859c512d9faea8e6069757634f62b37a97c7cfd89fa99d. I do this correctly in my aaudio wrapper that i currently use for my emulator :)

**Comment by ITotalJustice** [comment] 2024-01-26 17:49
this looks like it's fixed in https://github.com/libsdl-org/SDL/commit/482c2389535a8366187e5b859624bb66b3565f71
2.28 (the version that was tested) still had the bug https://github.com/libsdl-org/SDL/blob/05eb08053d48fea9052ad02b3d619244aeb868d3/src/audio/aaudio/SDL_aaudio.c#L219 and so does the latest sdl2 commit

**Comment by icculus** [comment] 2024-01-26 18:35
Okay, I'll see how hard that is to backport to SDL2.

**Comment by icculus** [comment] 2024-01-27 23:25
I've taken a shot at this in #8937, but I need someone to test it on real hardware. Can anyone do this really quickly, so we can maybe tuck this into the 2.30.0 release that is about to ship? I'd _really_ appreciate it.

**Comment by icculus** [comment] 2024-01-27 23:26
(I'm looking around my office for my test android phone and will charge it, but if anyone is faster on the draw, please try it first!)

**Comment by dingogames** [comment] 2024-01-28 00:46
I did the quickest test I could do, which was simply putting all the new AAudio code into 2.28.x I'm running on - so not sure if this test is valid but.....

Unfortunately got a segfault at line 509 in SDL_audio.c when unplugging/plugging in headphones. Same result thing on two test devices.

**Comment by icculus** [comment] 2024-01-28 01:13
Okay, I'll be trying this on hardware shortly, thanks for taking a look at it!

**Comment by icculus** [comment] 2024-01-28 03:47
So your crash is probably because there's a time when the audio thread might set the stream to NULL, while the main thread is pumping the event loop and assumes it isn't NULL. I've added a fix for this.

I've tested on a real phone now; the headphone hotplugging appears to work.

If anyone wants to take one more run at it, that's cool, otherwise I'm going to close this bug under the assumption we're good.

**Comment by AJenbo** [comment] 2024-01-28 03:52
I'll give it a try sometime this weekend and add a comment here once I have done so.

**Comment by icculus** [comment] 2024-01-28 05:21
(This is in revision control now, but please do speak up if this is still busted for you and I'll reopen!)

**Closed by icculus** 2024-01-28 05:21 UTC

**Comment by dingogames** [comment] 2024-01-28 08:56
I did a quick test on a handful of devices and it seems to work well now. Thank you!

**Comment by AJenbo** [comment] 2024-02-01 21:32
Tested it with DevilutionX, on previous versions the game would lock up when i disconnected the headphones. With 2.29.3 the game correctly switches to the build in speakers and the game continues to run without issues. Nice work!
