### ISSUE TITLE
Window doesn't open when I run the project, even with event loop

### ISSUE THREAD

**Issue by gojzdar** [libsdl-org/SDL#8291] opened 2023-09-23 12:17 UTC
I am writing a program with C++/SDL2, but I can't get a window to show up.
Before switching to SDL2, I used SDL2pp (switched due to vcpkg issues, where I couldn't use vcpkg and imgui renderer + normal binding. Decided to put everything inside a docker container to ensure that if I get it to work once I can get it to work anytime). 
I had similar issues, but it magically fixed itself (not really sure why).
I compiled it on my PC without a docker image. I tried compiling it again but it didn't work.

I know there is a somewhat related issue on MacOS where you have to pump events to get the window to show up and I did that, with no results. This project has over 4000 lines of code and I think I handled everything properly, including event handling, yet a window still doesn't show up.

OS: Kubuntu 23.04, x64
DE: KDE X11 / KDE Wayland / XFCE (tried on all of them)
DM: SDDM

Compilation process:
- CMAKE + VCPKG
- Everything inside a docker container, but I have the same issue if outside
- The project base directory is mounted inside docker.

CMakeListst.txt
```cmake
cmake_minimum_required(VERSION 3.16.0)

set(CMAKE_CXX_STANDARD 20)

project(myProject)


SET(ADDITIONAL_COMPILER_FLAGS "-g")
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${ADDITIONAL_COMPILER_FLAGS}")

add_executable(${PROJECT_NAME} main.cpp )

find_package(SDL2 REQUIRED)
find_package(SDL2_image REQUIRED)
find_package(SDL2_ttf REQUIRED)
find_package(SDL2_mixer REQUIRED)

target_include_directories(${PROJECT_NAME} 
PRIVATE 
	PRIVATE ../inc
	PRIVATE /app/vcpkg/installed/x64-linux/include/	
)

target_link_libraries(${PROJECT_NAME} PRIVATE
	SDL2::SDL2main
	SDL2::SDL2-static
	SDL2_image::SDL2_image-static
	SDL2_ttf::SDL2_ttf-static
	SDL2_mixer::SDL2_mixer-static
)
```

CMake command
`cmake -B build -S latest/src -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCPPFILENAME=$(f) -DCMAKE_TOOLCHAIN_FILE=/app/vcpkg/scripts/buildsystems/vcpkg.cmake

Docker images:
vcpkg base image: (I haven't used them outside this project)
```
FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    curl \
    zip unzip tar \
    && rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/microsoft/vcpkg.git /app/vcpkg
WORKDIR /app/vcpkg
ENV VCPKG_DISABLE_METRICS=true
RUN ./bootstrap-vcpkg.sh
ENV PATH="/app/vcpkg:$PATH"

RUN apt-get update
WORKDIR /app/workspace
CMD ["bash"]
```

Project specific image:
```
FROM vcpkg-base:1.0
RUN apt-get update && apt-get install pkg-config libasound2-dev zlib1g-dev libpng-dev libfreetype6-dev -y
RUN vcpkg install freetype zlib libpng sdl2pp imgui[sdl2-binding] imgui[sdl2-renderer-binding] dbg-macro
WORKDIR /app/workdir
CMD ["bash"]
```

Vcpkg version: (inside docker)
2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416

Library versions:
```
sdl2-image:x64-linux                              2.6.3               SDL_image is an image file loading library. It l...
sdl2-mixer:x64-linux                              2.6.3#1             Multi-channel audio mixer library for SDL.
sdl2-ttf:x64-linux                                2.20.2              A library for rendering TrueType fonts with SDL
sdl2:x64-linux                                    2.28.3              Simple DirectMedia Layer is a cross-platform dev...
sdl2[base]:x64-linux                                                  Base functionality for SDL
sdl2[ibus]:x64-linux                                                  Build with ibus IME support
sdl2[wayland]:x64-linux                                               Build with Wayland support
sdl2[x11]:x64-linux                                                   Build with X11 support
```

Program: (the last one I tried, among literally a dozen others, most from tutorials and solutions for other's issues
```c++
#include <SDL_events.h>
#include <stdio.h>
#include <SDL2/SDL.h>

int main(int argc, char** argv)
{

	puts("Started program!\n");
    if (SDL_Init(SDL_INIT_VIDEO) != 0 )
    {
        fprintf(stdout,"Failed to initialize the SDL (%s)\n",SDL_GetError());
        return -1;
    }

    {
        SDL_Window* pWindow = NULL;
		auto fgs = SDL_WINDOW_OPENGL | SDL_WINDOW_INPUT_GRABBED | SDL_WINDOW_ALWAYS_ON_TOP;
        pWindow = SDL_CreateWindow("My first SDL2 application",SDL_WINDOWPOS_UNDEFINED,
                                                                  SDL_WINDOWPOS_UNDEFINED,
                                                                  643,
                                                                  487,
                                                                  fgs);

        if( pWindow )
        {
			for(int i = 0; i < 100; i++) {


				SDL_Event event;
				while(SDL_PollEvent(&event)) {
					// do nothing
					switch(event.type) {
						case SDL_QUIT:
						i = 1000;
						break;
					}
				}
				SDL_Delay(100);

			}

            SDL_DestroyWindow(pWindow);
        }
        else
        {
            fprintf(stderr,"Error creating the window: %s\n",SDL_GetError());
        }
    }

    SDL_Quit();

    return 0;
}
```
Most of my setup was improvised and I haven't followed any tutorials.

Any help would be appreciated.

**Comment by gojzdar** [comment] 2023-09-23 12:19
I have tried many hacks, like adding a delay between SDL_CreateWindow and every possible combination I could think of and set up environmental variables to toggle composition but still nothing.

**Comment by madebr** [comment] 2023-09-23 13:44
SDL uses libdecor to draw the window decorations on Wayland.
At SDL build time, you need the libdecor-dev package. At runtime, you need libdecor.
(Verify `SDL_WAYLAND_LIBDECOR` is enabled at the end of CMake configuration)

Wayland needs you to draw something before it creates a window.
Add the following code after the call to `SDL_CreateWindow`
```c
SDL_Renderer *pRenderer = SDL_CreateRenderer(pWindow, -1, 0);
```
and do the following just before the `SDL_Delay`.
```c
SDL_RenderPresent(pRenderer);
```

**Comment by madebr** [comment] 2023-09-23 14:11
@woxels
About https://github.com/libsdl-org/SDL/issues/8185#issuecomment-1732209403. You might have the same problem.

**Comment by gojzdar** [comment] 2023-09-23 14:19
Still nothing. And I doubt this has much to do with Wayland since the same issue occurs on KDE X11 and XFCE.
Another thing. When l logged out I saw a message "amd topaz is not supported" or something similar. Still, I doubt this has anything to do with this, since I successfully compiled and ran SDL programs before on the exact same OS, exact same PC and zero updates in between except a few program installations (namely docker)


What I did:
Added  `SET(SDL_WAYLAND_LIBDECOR 1)` to the end of CMakeLists.txt
Modified the code to be:
```c++
#include <SDL_events.h>
#include <stdio.h>
#include <SDL2/SDL.h>

int main(int argc, char** argv)
{

	puts("Started program!\n");
    if (SDL_Init(SDL_INIT_VIDEO) != 0 )
    {
        fprintf(stdout,"Failed to initialize the SDL (%s)\n",SDL_GetError());
        return -1;
    }

    {
        SDL_Window* pWindow = NULL;
		auto fgs = SDL_WINDOW_OPENGL | SDL_WINDOW_INPUT_GRABBED | SDL_WINDOW_ALWAYS_ON_TOP;
        pWindow = SDL_CreateWindow("My first SDL2 application",SDL_WINDOWPOS_UNDEFINED,
                                                                  SDL_WINDOWPOS_UNDEFINED,
                                                                  643,
                                                                  487,
                                                                  fgs);

		SDL_Renderer *pRenderer = SDL_CreateRenderer(pWindow, -1, 0);

        if( pWindow )
        {
			for(int i = 0; i < 100; i++) {


				SDL_Event event;
				while(SDL_PollEvent(&event)) {
					// do nothing
					switch(event.type) {
						case SDL_QUIT:
						i = 1000;
						break;
					} 
				}
				SDL_RenderPresent(pRenderer);
				SDL_Delay(100);
			} 

            SDL_DestroyWindow(pWindow);
        }
        else
        {
            fprintf(stderr,"Error creating the window: %s\n",SDL_GetError());
        }
    }

    SDL_Quit();

    return 0;
}
```

**Comment by madebr** [comment] 2023-09-23 14:26
`SET(SDL_WAYLAND_LIBDECOR 1)` won't do anything.
`SDL_WAYLAND_LIBDECOR` is merely a hint for the cmake script to look for it.
Please manually verify the output of the cmake configuration.

**Comment by gojzdar** [comment] 2023-09-23 14:33
Since you didn't correct me, I guess it is a variable. 
The output of this block did not contain anything about wayland.
Granted, I compiled it whilst on X11, but that shouldn't really make a difference since CMake instide the docker container can't see the difference. And again, not sure what Wayland has to do with the window not showing up since it doesn't work even outside of wayland.

```Cmake
get_cmake_property(_variableNames VARIABLES)
list (SORT _variableNames)
foreach (_variableName ${_variableNames})
    message(STATUS "${_variableName}=${${_variableName}}")
endforeach()
```

**Comment by gojzdar** [comment] 2023-09-25 08:38
Any other ideas? Still not working...

**Comment by woxels** [comment] 2023-09-25 08:58
> 

I don't think this problem is related my problem is specific to libdecor not working on Wayland with SDL2 when using an OpenGL ES context. Also, WarpMouse is not functional on Wayland but Google search both present that these are not unknown issues.

If the problem is that SDL2 requires two specific builds, one for Wayland and one for Gnome then I am simply not interested in SDL as a solution to being a portability layer.

If the problem is that SDL2 requires specific build flags to create a binary that will run on both Gnome and Wayland I would like it to be more obvious and apparent why; preferably with a link to an official statement on the matter.

I don't see why it is so hard for me to get answers on such a glaringly obvious and seemingly common problem many people seem to experience, I expect portability layers like SDL2 to "just work" failing to do so or requiring significant work around to "just work" is not acceptable.

**Comment by madebr** [comment] 2023-09-25 10:51
@woxels please create a new issue from scratch. One SDL binary is able to support both x11 and wayland.

**Comment by Kontrabant** [comment] 2023-09-25 15:07
> Any other ideas? Still not working...

The above sample code works as expected when I build it on Fedora 38, although I had to drop the `#include <SDL_events.h>` line, so the only thing I can think of is that there is some misconfiguration on your specific system.

Does it build cleanly and work if you build it with no docker or CMake, just `g++ main.cpp -lSDL2 -o sdl_test`?

**Comment by gojzdar** [comment] 2023-09-25 16:29
> > Any other ideas? Still not working...
> 
> The above sample code works as expected when I build it on Fedora 38, although I had to drop the `#include <SDL_events.h>` line, so the only thing I can think of is that there is some misconfiguration on your specific system.
> 
> Does it build cleanly and work if you build it with no docker or CMake, just `g++ main.cpp -lSDL2 -o sdl_test`?

```
#include <stdio.h>
#include <SDL2/SDL.h>

int main(int argc, char** argv)
{

        puts("Started program!\n");
    if (SDL_Init(SDL_INIT_VIDEO) != 0 )
    {
        fprintf(stdout,"Failed to initialize the SDL (%s)\n",SDL_GetError());
        return -1;
    }

    {
        SDL_Window* pWindow = NULL;
                auto fgs = SDL_WINDOW_OPENGL | SDL_WINDOW_INPUT_GRABBED | SDL_WINDOW_ALWAYS_ON_TOP;
        pWindow = SDL_CreateWindow("My first SDL2 application",SDL_WINDOWPOS_UNDEFINED,
                                                                  SDL_WINDOWPOS_UNDEFINED,
                                                                  643,
                                                                  900,
                                                                  fgs);

                SDL_Renderer *pRenderer = SDL_CreateRenderer(pWindow, -1, 0);

        if( pWindow )
        {
                        for(int i = 0; i < 100; i++) {


                                SDL_Event event;
                                while(SDL_PollEvent(&event)) {
                                        // do nothing
                                        switch(event.type) {
                                                case SDL_QUIT:
                                                i = 1000;
                                                break;
                                        }
                                }
                                SDL_RenderPresent(pRenderer);
                                SDL_Delay(100);
                        }

            SDL_DestroyWindow(pWindow);
        }
        else
        {
            fprintf(stderr,"Error creating the window: %s\n",SDL_GetError());
        }
    }

    SDL_Quit();

    return 0;
}
```

Compiled with
`g++ main.cpp -lSDL2 -o sdl_test`

Resulted in no window appearing.

I can try using some library other than SDL, but not really sure which one I should try.

**Comment by gojzdar** [comment] 2023-10-03 11:34
If I can't fix this issue, I'll be forced to switch to an alternative. Any suggestions?
Requirements:
- Drawing to screen + event handling
- Render text
- Allows use of custom shaders (including "compute" shaders)

**Comment by madebr** [comment] 2023-10-03 12:43
Using [x11docker](https://github.com/mviereck/x11docker), I get the following error:
```
INFO: SDL_CreateWindowAndRenderer failed (failed to create an EGL window surface)
```
@Kontrabant Do you know what I'm doing wrong?

Steps to reproduce:
1. Build the app: `gcc app.c -lSDL2 -I/usr/include/SDL2`
2. Build the docker image: `docker build -t vm_wayland .` (do this again whenever you rebuild the app)
3. Start the docker with [x11docker](https://github.com/mviereck/x11docker): `x11docker/x11docker --wayland vm_wayland /app/app`

<details>

<summary>Dockerfile</summary>

```
FROM ubuntu:latest
WORKDIR /app

# A real dockerfile should do this in one step, and clean itself up afterwards
RUN apt-get update -y
# Install both x11 and wayland
RUN apt-get install -y libwayland-client0 libdecor-0-0 libsdl2-2.0-0 libx11-6 libegl1

COPY app .
CMD ["/app/app"]
```

</details>

<details>

<summary>app.c</summary>

```c
#include "SDL.h"

int main(int argc, char *argv[]) {
 const char *hint_video = "wayland";
 if (argc > 1) {
  hint_video = argv[1];
 }
 const char *hint_renderer = "software";
 if (argc > 2) {
  hint_renderer = argv[2];
 }
 
 SDL_Log("SDL_SetHint(\"%s\", \"%s\")", SDL_HINT_VIDEODRIVER, hint_video);
 SDL_SetHint(SDL_HINT_VIDEODRIVER, hint_video);
 
 SDL_Log("SDL_SetHint(\"%s\", \"%s\")", SDL_HINT_RENDER_DRIVER, hint_renderer);
 SDL_SetHint(SDL_HINT_RENDER_DRIVER, hint_renderer);

 if (SDL_Init(SDL_INIT_VIDEO) < 0) {
  SDL_Log("SDL_Init failed (%s)", SDL_GetError());
  return 1;
 }

 SDL_Window *window;
 SDL_Renderer *renderer;
 if (SDL_CreateWindowAndRenderer(640, 480, 0, &window, &renderer) < 0) {
  SDL_Log("SDL_CreateWindowAndRenderer failed (%s)", SDL_GetError());
  return 1;
 }
 
 SDL_Log("video driver: %s", SDL_GetCurrentVideoDriver());

 for (;;) {
  SDL_Event event;
  int quit = 0;
  while (1) {
   SDL_Event event;
   if (!SDL_PollEvent(&event)) {
    break;
   }
   if (event.type == SDL_QUIT) {
    quit = 1;
    break;
   }
  }
  if (quit) {
   break;
  }
  SDL_RenderClear(renderer);
  SDL_RenderPresent(renderer);
 }
 SDL_DestroyRenderer(renderer);
 SDL_DestroyWindow(window);
 SDL_Quit();
}
```

</details>


<details>

<summary>Full log</summary>

```
$ x11docker --wayland vm_wayland /app/app
x11docker WARNING: User maarten is member of group docker.
  That allows unprivileged processes on host to gain root privileges.

x11docker note: Using X server option --hostwayland

x11docker note: You are running a pure Wayland environment.
  X applications without Wayland support will fail.

x11docker note: Option --network=none is set to disable network access.
  If you need network and internet access, set option -I, --network [=NET].

INFO: SDL_SetHint("SDL_VIDEODRIVER", "wayland")
INFO: SDL_SetHint("SDL_RENDER_DRIVER", "software")
INFO: SDL_CreateWindowAndRenderer failed (failed to create an EGL window surface)
```

</details>

**Comment by Kontrabant** [comment] 2023-10-03 15:34
Wayland still uses a hardware texture to scan out, even with software rendering. I think Docker needs to be started with `--gpu` (Nvidia might require more configuration).

The only other suggestion I have for the original issue is to try and verify or reinstall all the relevant packages and maybe try building SDL from source to see if that helps. I can't replicate the issue, and if the sample code doesn't work for the OP even in the simplest case with no build systems or containers in the way, that would seem to suggest a bad package or misconfiguration on their specific system.

**Comment by madebr** [comment] 2023-10-03 16:02
I got it working by also installing `libgl1`. (`--gpu` was not needed for my example)
So these are the minimal packages required to run sdl2 in a docker container:
`libwayland-client0 libdecor-0-0 libsdl2-2.0-0 libegl1 libgl1`

**Comment by gojzdar** [comment] 2023-10-04 12:34
> try building SDL from source to see if that helps

I just built it from source and ran the tests. Both main and SDL2 branch are working, at least for testdrawchessboard and testdraw2 files. I don't have any time right now so I'll try more tomorrow.

**Comment by gojzdar** [comment] 2023-10-04 12:40
Is it worth trying to build SDL from source inside a docker container? Would it should still work right?
So the issue is that both the SDL apt package and SDL vcpkg package are not configured correctly for me?
Is there a way to troubleshoot the issue now that I have a working copy, or is that too hard to do?
I should probably try to build the same source code with my toolchain, SDL-dev packages and from source.

**Comment by madebr** [comment] 2023-10-04 14:06
> The only issue is that when I start the program, the whole screen turns black for half a second and the same happens when I stop it.

Some SDL3 tests have a `--fullscreen` argument. Does it also happen with these?
Does the black screen delay happen when running the test outside the docker container?

> Is it worth trying to build SDL from source inside a docker container? Would it should still work right?

If you install [the same packages we install on ci](https://github.com/libsdl-org/SDL/blob/ff57867516d4f8044283ec4a8554c27782e525a6/.github/workflows/main.yml#L50-L64), it should result in a working SDL3
FYI, you can [download binaries](https://github.com/libsdl-org/SDL/actions/runs/6397260439) from the actions page so you can compare with a "known good" (SDL2 does not provide binaries).

> So the issue is that both the SDL apt package and SDL vcpkg package are not configured correctly for me? Is there a way to troubleshoot the issue now that I have a working copy, or is that too hard to do?

It would surprise me Ubuntu's package to be non-functional. In my use of docker above, I built the app with Fedora's SDL2 and ran it with Ubuntu's SDL2 inside a container. But you can always build the SDL2 tests and run them against various SDL2 libraries (using `LD_LIBRARY_PATH`). vcpkg should allow you to compare the cmake configure arguments easily.

**Comment by gojzdar** [comment] 2023-10-05 19:28
Progress update:
since I used `cmake --install` on both SDL2 and SDL3 build directories. Now compiling with -lSDL2 and -lSDL3 works.
However SDL3 stopped working after installing SDL2. Not sure when exactly, if right after the installation or when I renamed the parent folder of the build dir from SDL to SDL3 to avoid confusion. And is it safe to alter/remove the build directories after I used cmake install?

So right now, compiling with the recommended CMake file works (the one provided in README-cmake.md)  and also using the system libraries.

Just to makes things clear, I use docker only as a compilation tool chain. I run the compiled programs outside of it.
---
>>The only issue is that when I start the program, the whole screen turns black for half a second and the same happens when I stop it.

The issue seems to have fixed itself. 

>Some SDL3 tests have a --fullscreen argument. Does it also happen with these?

When I try to use the --fullscreen flag on SDL3 tests, the screen flickers a few times before the display resolution matches the app's. 

> If you install [the same packages we install on ci](https://github.com/libsdl-org/SDL/blob/ff57867516d4f8044283ec4a8554c27782e525a6/.github/workflows/main.yml#L50-L64), it should result in a working SDL3
FYI, you can [download binaries](https://github.com/libsdl-org/SDL/actions/runs/6397260439) from the actions page so you can compare with a "known good" (SDL2 does not provide binaries).

So I should install these (two?) inside the docker container?
If yes -> why, the compilation works perfectly fine and I would think that if anything went wrong I would be notified
If no -> how could that help with the window showing up outside the container?

> But you can always build the SDL2 tests and run them against various SDL2 libraries (using LD_LIBRARY_PATH).

I tried using `export LD_LIBRARY_PATH=/usr/local/lib` (the place where cmake --install places the files) and then running the result of my docker compilation toolchain (in the same shell session, outside of the docker container), but nothing changed.

I never specified that my project is to be statically linked, so I assume it isn't, however the file is still 6mb large (with debugging symbols) so I am not 100% sure. I also ran the command
``` 
file myProject                       
myProject: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=58a9930606a7b5cd258b55b6f9950d47008959ab, for GNU/Linux 3.2.0, with debug_info, not stripped
```

> vcpkg should allow you to compare the cmake configure arguments easily.

How can I do that? And what exactly do you mean by that?

If I can't get vcpkg to play nicely, how can I port my compiled binaries inside of cmake so it uses the working ones instead of the faulty ones it is using right now? Directly copying them into /usr/local/lib and modifying the CMake file?

Thank you for the response, thanks to you all I've come closer to SDL working and avoided a lot more potential hassle.

**Comment by gojzdar** [comment] 2023-10-06 16:19
I mistyped. I meant how to do so within a Docker image/container instead of CMake.
A possible option would be to build SDL from source inside a container, or maybe just copying the `.so` files.
But I don't know much about these things so I am really not sure.

**Comment by madebr** [comment] 2023-10-06 18:06
You can mount a volume using [the `-v` option](https://docs.docker.com/storage/volumes/#choose-the--v-or---mount-flag).

Since it looks like you're no longer have SDL-specific issues, is it ok to close this  issue?

**Comment by gojzdar** [comment] 2023-10-06 18:11
Not really sure how the whole system works here on github, but I would like to find the reason why both vcpkg and apt SDL packages don't work on my machine, which I think is an SDL problem. The docker workaround is just a quick and dirty solution, but I would prefer something permanent and less awkward. I do realize that this may be a fault with my machine or (less likely) with apt and docker packages, so you make the call on that.

Thank you everyone for help.

**Closed** 2023-11-08 09:38 UTC
