### ISSUE TITLE
Fullscreen has issues on Windows when statically linking sdl2

### ISSUE THREAD

**Issue by ericoporto** [libsdl-org/SDL#8418] opened 2023-10-22 11:02 UTC
Just to report something, our project has a CMake file that can statically link everything, including SDL2, and when I do this, on Windows, the fullscreen has black bars on bottom and top in a 2560x1440p monitor when the content is supposed to have the same resolution - it gets squished instead. I previously thought this was an issue because we use MSVC, and MSVC isn't really looked into here, but I recently managed to build our project in MinGW, and turns out the issue persists on it.

Dynamically linking to SDL2 fixes it. We have no need to actually ship static linked SDL2, much less on Windows, so this is not a particular issue for us, just felt it was weird enough to report.

This doesn't happen on macOS or Linux. Has someone ever experienced something like this?

**Comment by slouken** [comment] 2023-11-08 20:12
This is very weird. Please let us know if you figure this out! I'll go ahead and close this for now.

BTW, we highly recommend dynamically linking with SDL so users can upgrade it in the future with bug fixes and additional driver support.

**Closed by slouken** 2023-11-08 20:12 UTC

**Comment by madebr** [comment] 2023-11-08 20:19
Is your project available anywhere? If not, perhaps you can reduce it until you have a minimal reproducer (or you find an issue in the project).

**Comment by ericoporto** [comment] 2023-11-09 00:43
It's the ags engine, so it's fairly complex, and I haven't managed a minimal reproducible build yet. It's ok to close the issue and we do ship SDL as a dll in our Windows build, I just wanted to ask so if somehow someone reproduces this they find it on their search and comment here. :)

**Comment by madebr** [comment] 2023-11-09 01:06
I have succesfully built ags , but can't start it because of a missing `acsetup.cfg`.
What data/files am I missing?

**Comment by madebr** [comment] 2023-11-11 19:09
Extracting the non-exe/non-dll files to the same directory as ags.exe, it fails in the [following location](https://github.com/adventuregamestudio/ags/blob/a753e251aed7f98ee434c96f148ce7a437884868/Engine/main/engine.cpp#L224-L228).
The `acsetup.cfg` of tea-for-two does not have a `misc.datafile` entry.

**Comment by ericoporto** [comment] 2023-11-11 19:57
The main game data is attached to the exe file, the ags runtime can find it to run. You can try other games I have there ([manamatch is a single file](https://eri0o.itch.io/mana-match), might be easier) or create one yourself on the AGS Editor - the templates already contain a simple game.

**Comment by madebr** [comment] 2023-11-12 18:57
I don't see a difference between executables built with a shared/static SDL2: [ags-fd491b6.zip](https://github.com/libsdl-org/SDL/files/13328874/ags-fd491b6.zip).
This executable is built with Visual Studio 2019 Community Edition.

The intro "tea for two" banner is shown with the full height of my monitor (but not in full width due to the game designed for smartphone screens).
The game itself has black bars, but I can still move the mouse cursor in there. So I assume it is designed so.

**Comment by ericoporto** [comment] 2025-08-30 00:58
Hey, got someone else that can reproduce this, see https://github.com/adventuregamestudio/ags/issues/2822

**Comment by ericoporto** [comment] 2026-07-29 13:41
I think it may be something from our CMake that is leaking into the CMake from you guys, so some setting on our side somehow affects some setting in SDL that somehow causes this issue.

**Comment by madebr** [comment] 2026-07-29 16:40
What's the behavior when you use a non-vendored SDL3?
Try a SDL3 build from ci (SDL-VC-x64): https://github.com/libsdl-org/SDL/actions/runs/30393425321
You can also easily switch shared/static.
Then you know it has something to do with cmake or some unwanted symbol sharing.
