### ISSUE TITLE
stick drift with increasing velocity until move stick

### ISSUE THREAD

**Issue by bluenote73** [libsdl-org/SDL#8133] opened 2023-08-19 17:31 UTC
I'm using antimicrox on windows and the issue is only present on newer SDL and not older. When I (sometimes) press the right trigger, it will trigger an upward motion on the stick. As I press and release the trigger, the amount of drift increases.  Then actually moving the stick will "reset" the behaviour until it happens again. 
This is the antimicrox issue which sent me here: https://github.com/AntiMicroX/antimicrox/issues/808

**Comment by slouken** [comment] 2023-11-08 06:29
Can you debug SDL and find out what's going on?

**Comment by bluenote73** [comment] 2023-11-09 19:00
Sorry, that's beyond me :/

**Comment by slouken** [comment] 2023-11-22 17:31
Duplicate of https://github.com/libsdl-org/SDL/issues/8168

**Closed by slouken** 2023-11-22 17:31 UTC
