### ISSUE TITLE
multiple keyboard and mice

### ISSUE THREAD

**Issue by netpipe** [libsdl-org/SDL#5117] opened 2021-12-18 17:13 UTC
multiple keyboard and mice support for X11

https://github.com/netpipe/libInput/

**Comment by orbea** [comment] 2022-09-04 03:17
This is a duplicate issue, the newer one has more replies.

https://github.com/libsdl-org/SDL/issues/5663

**Comment by slouken** [comment] 2022-09-04 12:19
Duplicate of #https://github.com/libsdl-org/SDL/issues/5663

**Closed by slouken** 2022-09-04 12:19 UTC
