### ISSUE TITLE
Can't cross-compile from linux with MinGW-w64

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3770] opened 2021-02-11 02:03 UTC
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-07-13 11:39:04 +0000, Unarelith wrote:

> When trying to cross-compile latest SDL2 commit on Arch with mingw-w64-cmake (CMake 3.17.3), it gives the following errors:
> 
> CMake Error at external/gamekit/external/SDL2/CMakeLists.txt:2186 (add_library):
>   Target "SDL2-static" links to item "-Wl,-O1,--sort-common,--as-needed
>   -fstack-protector " which has leading or trailing whitespace.  This is now
>   an error according to policy CMP0004.
> 
> 
> CMake Error at external/gamekit/external/SDL2/CMakeLists.txt:2186 (add_library):
>   Target "SDL2-static" links to item "-Wl,-O1,--sort-common,--as-needed
>   -fstack-protector " which has leading or trailing whitespace.  This is now
>   an error according to policy CMP0004.
> 
> 
> CMake Error at external/gamekit/external/SDL2/CMakeLists.txt:2186 (add_library):
>   Target "SDL2-static" links to item "-Wl,-O1,--sort-common,--as-needed
>   -fstack-protector " which has leading or trailing whitespace.  This is now
>   an error according to policy CMP0004.
> 
> 
> CMake Error at external/gamekit/external/SDL2/CMakeLists.txt:2186 (add_library):
>   Target "SDL2-static" links to item "-Wl,-O1,--sort-common,--as-needed
>   -fstack-protector " which has leading or trailing whitespace.  This is now
>   an error according to policy CMP0004.
> 
> 
> -- Generating done
> CMake Generate step failed. Build files cannot be regenerated correctly.

**Comment by madebr** [comment] 2022-06-15 02:14
I am able to cross build from Linux to Windows using the following command:
```
CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++ cmake .. -DCMAKE_SYSTEM_NAME=Windows
```
(using Fedora Linux)

Grep'ing for `sort-common` and `fstack-protector` does not return any hits in cmake scripts, so I am going to close this as "cannot reproduce".
If you know a way to reproduce (eventually using docker images), please re-open with a reproducer.

**Closed by madebr** 2022-06-15 02:14 UTC
