### ISSUE TITLE
SDL3 Linux Wayland - SDL_SetWindowFullscreen incorrect size

### ISSUE THREAD

**Issue by BurkeyCode** [libsdl-org/SDL#9999] opened 2024-06-10 04:54 UTC
Bit of a long title!

Ubuntu 24.04
Wayland

What I am seeing is if I create the window without setting SDL_WINDOW_RESIZABLE then toggling fullscreen via SDL_SetWindowFullscreen often does not generate the correct values in SDL_EVENT_WINDOW_RESIZED and possibly the GL surface is not resizing (or glViewport is not filling it).

The thing of note is it is intermittent, so maybe due to the async nature of the change and Ubuntu 'animating' the fullscreen, will try to detail:

**Switch to fullscreen and it is NOT adjusting correctly:**
```
SDL_EVENT_WINDOW_ENTER_FULLSCREEN
SDL_GetWindowFlags does report it is indeed fullscreen
SDL_GetWindowSizeInPixels - 1280x744
SDL_EVENT_WINDOW_RESIZED - data1+data2 are 1280x744 (window was 1280x720 so maybe due to window manager animation?)
```

**Switch to fullscreen and it IS adjusting correctly:**
```
SDL_EVENT_WINDOW_ENTER_FULLSCREEN (SDL_GetWindowFlags does report it is indeed fullscreen)
SDL_GetWindowFlags does report it is indeed fullscreen
SDL_GetWindowSizeInPixels - 1920x1080
SDL_EVENT_WINDOW_RESIZED - data1+data2 are 1920x1080
```

Oh every time I call `SDL_SetWindowFullscreen ` I then call `SDL_SyncWindow` to block and wait.

Even if I detect fullscreen and use the screen size for all calls to glViewport every frame, it does not update so I suspect the GL render surface is not scaling, maybe because of that SDL_EVENT_WINDOW_RESIZED being incorrect?

I tried enabling SDL_WINDOW_RESIZABLE and the events then post with correct dimensions but ideally I do not want to allow resizing the window since I am trying to keep full pixel multiples as best I can.

**Comment by Kontrabant** [comment] 2024-06-10 08:18
Can you run it with the envvar `WAYLAND_DEBUG=1` and attach the output in a case where it is broken?  The size constraints are forcibly removed when entering fullscreen, so something is strange here.

**Comment by BurkeyCode** [comment] 2024-06-10 09:14
Hi!  Thanks for the reply.. I did have a peek into the wayland code and saw it removes that constraint so yeah could be barking up the wrong tree there..

I have attached a log here, cleaned out some of my games log data so hopefully is ok but I also left in the output when I toggle screen size changes so you can search to `INFO: Entering fullscreen` to see were I toggle fullscreen since there is a lot dumped from wayland there.

[error.txt](https://github.com/user-attachments/files/15759717/error.txt)

**Comment by Kontrabant** [comment] 2024-06-10 14:37
Thanks! So, the relative bits are here:
```
[1653593.718]  -> xdg_toplevel@54.set_min_size(0, 0)
[1653593.720]  -> xdg_toplevel@54.set_max_size(0, 0)
[1653593.723]  -> xdg_surface@58.set_window_geometry(0, -24, 1280, 744)
[1653593.726]  -> wl_surface@51.commit()
[1653593.729]  -> xdg_toplevel@54.set_fullscreen(wl_output@6)
<some irrelevant lines removed>
[1653595.846] xdg_toplevel@54.configure(1280, 744, array[8])
```
SDL is clearing the constraints, committing to apply the new values, and issuing the fullscreen request, but the compositor is replying with the old size of the window as the fullscreen window dimensions (the extra 24 pixels is where the title bar used to be). SDL is obeying the size that it is given, as the spec states that the supplied fullscreen dimensions are a maximum and clients must be that size or smaller.

SDL seems to be doing everything right here and this doesn't happen on upstream GNOME, so I'm inclined to say that this is a bug in Unity's Mutter fork, especially given the sporadic reproduction nature that you mentioned.

**Comment by BurkeyCode** [comment] 2024-06-10 22:52
Nice, thanks for the feedback, of course title bar for the xtra 24px.

Well, probably not really anything to do on SDL3 as whatever would be need ed would be a bit of a workaround.. I just removed the constraint for resizing from my game for now and fixed some of my own calcs which seems to be ok.  I also tried creating the window as sizeable then setting the constraint later - same behaviour.

Cheers for digging into it, much appreciated!

**Comment by Kontrabant** [comment] 2024-06-18 16:23
Upstream bug report on Ubuntu's bug tracker: https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/2069766

**Comment by Kontrabant** [comment] 2024-07-01 18:17
It looks like Ubuntu updated 24.04 with backported fixes last week. Did the update happen to fix your issue?

**Comment by BurkeyCode** [comment] 2024-07-01 21:26
Oh cool, I already worked around it but will see if I can revert my changes and test.

**Comment by Kontrabant** [comment] 2024-08-28 17:20
Closing as I can't replicate this locally, no other reports of this behavior have been submitted, and Ubuntu 24.04 is now shipping a newer version of Mutter that probably fixed whatever the underlying issue was.

**Closed by Kontrabant** 2024-08-28 17:20 UTC
Labels: waiting, notourbug
