### ISSUE TITLE
Windows 11 with WSL2 + SDL2 : keydown event triggered at initialisation

### ISSUE THREAD

**Issue by ToguyC** [libsdl-org/SDL#5084] opened 2021-12-09 07:20 UTC
## Reproduction Steps
- Have a really basic program in C using the library SDL2 openning a blank window. (see: https://gigi.nullneuron.net/gigilabs/showing-an-empty-window-in-sdl2/)
- Make it exiting by pressing the "Escape" key.

## Expected Behaviour
- Quit the window, press the "Escape" key.
- Program exit successfuly.

## Actual Behavior
- Keydown event triggered without any key pressed at start.
- Program exit immediately.

---

I don't know if it is possible to have some extra logs or not, but it is very frustrating to have the program exiting directly 
when the exit condition is a keydown event and that event is triggered at startup.

**Comment by orkaboy** [comment] 2022-03-19 21:47
I am also seeing the same issue. I'm using the (currently) standard Ubuntu 20.04.4 LTS. The installed version of libsdl2-dev shows:

```
$ apt show libsdl2-dev
Package: libsdl2-dev
Version: 2.0.10+dfsg1-3
...
```

**Comment by slouken** [comment] 2022-04-26 17:21
I think this has been fixed in 2.0.22, can you confirm?

**Comment by slouken** [comment] 2022-04-26 17:22
Specifically, this change sounds like it fixed this bug: https://github.com/libsdl-org/SDL/commit/49b9e3470bc9f07cf666e92bbc7405696f2b2ed9

**Comment by orkaboy** [comment] 2022-04-29 19:18
I changed my project to use SDL from git instead of the version installed in Ubuntu 20.04. After fighting with dependencies for an hour or three, I made the minimum code that reproduces the issue, skipping the libraries I had issues with and only linking in SDL.

In my CMake, I use FetchContent to get the current main branch of SDL, and link against that.

```
FetchContent_Declare(SDL2
    GIT_REPOSITORY https://github.com/libsdl-org/SDL.git
    GIT_TAG main
)
FetchContent_MakeAvailable(SDL2)
```

At the top of my code I have:

```
    SDL_version compiled;
    SDL_version linked;
    SDL_VERSION(&compiled);
    SDL_GetVersion(&linked);
    fmt::print("Compiled against SDL version {}.{}.{}.\n",
        compiled.major, compiled.minor, compiled.patch);
    fmt::print("Linking against SDL version {}.{}.{}.\n",
        linked.major, linked.minor, linked.patch);
```

This prints out the following, verifying that the correct library is used (I had to uninstall SDL from apt in order to get this):

```
Compiled against SDL version 2.0.23.
Linking against SDL version 2.0.23.
```

After initializing SDL and creating a window, I start an event loop, with this inside it:

```
            if(event.type == SDL_KEYDOWN) {
                switch (event.key.keysym.scancode) {
                case SDL_SCANCODE_ESCAPE: // TODO Bug in SDL2 2.0.x in WSL2
                    fmt::print("SDL_SCANCODE_ESCAPE\n");
                    quit = true;
                }
            }
```

Unfortunately, this still triggers (without me touching the ESCAPE key) first thing that happens when the application starts. So in short, no, the issue was not fixed by the mentioned bugfix.

Unrelated to the issue at hand, display output no longer works after I changed the SDL version.

**Comment by slouken** [comment] 2022-04-29 20:11
Duplicate of #5550

**Closed by slouken** 2022-04-29 20:11 UTC
