### ISSUE TITLE
Moza R5, force feedback (haptic) works on linux, but is not working on windows 10

### ISSUE THREAD

**Issue by Vladeeg** [libsdl-org/SDL#8422] opened 2023-10-22 17:09 UTC
I have Moza R5 racing wheel, and trying to get force feedback to work in some SDL2 applications.

I've tested it with [PCSX2](https://github.com/PCSX2/pcsx2) and [GIMX](https://github.com/matlo/GIMX) software. Both are using SDL2 for managing racing wheels and haptic effects.

Problem is that haptic effects (even constant left/right) are not working under windows 10, but are working under linux (Pop!OS 22.04).

In PCSX2 logs (under windows) it says that haptic effects are not supported by the device:

```
[    0.5391] (SDLInputSource) Opened joystick 0 (instance id 0, player id 0): MOZA R5 Base
[    0.5417] (SDLInputSource) Failed to create haptic left/right effect: Haptic: Effect not supported by haptic device.
[    0.5548] (SDLInputSource) No haptic rumble supported: Haptic: Effect not supported by haptic device.
[    0.5583] (SDLInputSource) Rumble is not supported on 'MOZA R5 Base'
```

GIMX logs are not so helpful, but seems like it's trying to do something:

```
Warning: skipping unsupported command SET_DEFAULT_SPRING
Warning: skipping unsupported command DEFAULT_SPRING_ON

< CONSTANT, level: -10320
> DOWNLOAD_AND_PLAY - slot 1 - VARIABLE - 0x52 0x80 0x00 0x00 0x00
> push: 10
> peek: 10
> remove 10
< CONSTANT, level: -11610
> DOWNLOAD_AND_PLAY - slot 1 - VARIABLE - 0x51 0x80 0x00 0x00 0x00
> push: 10
> peek: 10
> remove 10
```

**Comment by Vladeeg** [comment] 2023-10-23 09:04
Interesting that if we do this modification to registry, force feedback starts working in GIMX and in PCSX2. (but "effect not supported" message is still present)
Though, it's a bit weird in PCSX2: sometimes it just turns off and restarts after a bit of delay.

Original OEMData value is `hex:03,00,88,11,80,00,00,00`:

```
Windows Registry Editor Version 5.00
[HKEY_CURRENT_USER\System\CurrentControlSet\Control\MediaProperties\PrivateProperties\Joystick\OEM\VID_346e&PID_0004]
"OEMData"=hex:43,00,88,01,fe,00,00,00
"OEMName"="MOZA R5 Base"
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\MediaProperties\PrivateProperties\Joystick\OEM\VID_346e&PID_0004]
"OEMData"=hex:43,00,88,01,fe,00,00,00
"OEMName"="MOZA R5 Base"
```

**Comment by slouken** [comment] 2023-11-08 20:13
This sounds like a hardware or driver support issue. I'll go ahead and close this now. Feel free to reopen if you find it's a bug in SDL.

**Closed by slouken** 2023-11-08 20:13 UTC

**Comment by badfontkeming** [comment] 2024-10-21 23:39
Hi there! This is a bit of a necro, but I'd like to provide some closure here as I recently looked into this while working on this issue for PCSX2 specifically.

Context:

- Racing games, including old ones for the PS2, rely heavily on rapidly updating an ongoing constant force effect for the majority of their effects. For instance, in Gran Turismo 4, constant forces were used almost exclusively.

After digging deep, I can confirm a few things: 

- The wheel (and many other modern wheels) was not fully compliant with the HID standard. In this case, it's ignoring the iteration count, so it wasn't looping the constant force we sent. This is the root cause: We sent a ten second looping force; if the emulated game didn't stop and start the force, the duration would elapse without looping.
- We were able to mitigate the issue for most wheels by making the constant force's duration infinite, which it arguably should've been from the beginning on our end. The majority of wheels respect an infinite duration, but annoyingly we found one brand that doesn't even handle that correctly (grumble grumble...)
- Re-starting the force regularly caused problems on certain wheels, ranging from a loss of detail to stuttering "micro-dropouts" of force with each restart. SDL's DirectInput implementation can send excess reports if only the magnitude of the force has changed; it's unclear whether this affects the issue.

**Comment by Vladeeg** [comment] 2024-11-14 14:10
@badfontkeming Thank you for your investigation and overview!
So, as I understand, the problem with inconsistent feedback is on PCSX2 side and it might (but is very hard to (because of inconsistency between HID implementations in wheels)) be fixed in some future release of it? Is there an issue to follow by any chance?

As for my initial issue (wheel is not recognised as ffb device) I guess it's mostly on a Moza's driver side, though it's interesting that in many games or test programs like Assetto Corsa, MudRunner (both games released wayyy earlier than the wheel) or some ffb testers it works oob without any registry modifications... so in my head it should be possible to change device descriptor reading routine in SDL to support this (but unfortunately I don't have enough knowledge about SDL code nor reading device descriptors)

**Comment by badfontkeming** [comment] 2024-11-14 17:54
@Vladeeg 

The issues you're mentioning are unfortunately irrelevant to the topic of this specific issue, as this issue was only concerned with forces intermittently being interrupted. This was found to be a flaw of the wheels' firmwares thet requires workarounds at a level above SDL.

The issue with the wheel not being recognized is because SDL leverages DirectInput, which Moza wheels hide themselves from by default. If you install the Richard Burns Rally fix for Moza wheels, all that does is expose the wheel to DirectInput, which fixes the issue for PCSX2 and any other software that relies on DirectInput. This isn't SDL's fault. Commercial sims don't have this issue as they send raw HID/PID reports directly to the device, bypassing DirectInput. SDL _could_ start doing this (at least on paper), but it would be a significant development and may not be worth maintaining on their end.

The loss of definition issue isn't currently in SDL's territory as I haven't had time and energy to actually identify where the issue lies due to work and poor health. If I identify a flaw in SDL that is causing the issue (it could also be a flaw in PCSX2, we don't know yet), then I'll open a separate issue concerning that.

For now let's keep SDL's issue tracker and the maintainer's inbox clean, and avoid discussing it here, as there's nothing for SDL to currently address about any of these issues.
