### ISSUE TITLE
WINDOW_FULLSCREEN_DESKTOP leaves one-pixel gap on Windows

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3233] opened 2021-02-11 01:29 UTC
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Screenshot of the issue (onepixelgap.png, image/png, 2019-04-12 02:05:31 +0000, 4693781 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3742)

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2019-04-12 02:05:31 +0000, Caleb Cornett wrote:

> Created attachment 3742
> Screenshot of the issue
> 
> Creating a window with the flag SDL_WINDOW_FULLSCREEN_DESKTOP leaves a one-pixel gap at the very bottom of screen, allowing part of the Windows taskbar to show through. You can see an example in the attached image.
> 
> Reproduced with various SDL games, including Celeste and VVVVVV, as well as my own test project (shown in the image).
> 
> Tested on a Surface Laptop running Windows 10 Pro, Version 1809.

On 2019-04-12 03:03:40 +0000, Caleb Cornett wrote:

> After a little more investigation, it only seems to happen when the Windows Display settings have a scaling factor that's not a multiple of 100%. For instance, 125% scaling adds a pixel-wide gap on the right side of the screen, and 150% yields the bottom gap I mentioned in the original comment.

**Comment by slouken** [comment] 2023-11-06 05:53
Duplicate of https://github.com/libsdl-org/SDL/issues/6900

**Closed** 2023-11-06 05:53 UTC
