### ISSUE TITLE
Render crashes with GPU backend on NVIDIA + Windows

### ISSUE THREAD

**Issue by l-t-m-f** [libsdl-org/SDL#10924] opened 2024-09-23 01:53 UTC
Hello,

I will preface this by saying I still need to learn a lot and hopefully I can get a cue in the right direction (am noob).
I'm making an isometric game using your API. Its a fun project.
It uses Texture Target (a lot). I'm going to list everything and you call me stupid if that deserves it LOL...

- 11 x 2K or 4K texture targets (depending if the monitor supports more than 2K resolution)
- 24 x 1K texture target for pages of a glyph atlas
- 8 x 512x512 texture target for pages of a sprte atlas

So like, is this a problem? Recently, I tested my project on an MSI Titan laptop and it crashes on Vulkan.

`ERROR: vkBindBufferMemory VK_ERROR_OUT_OF_DEVICE_MEMORY`
`ERROR: Unable to bind memory for texture!`
`ERROR: Failed to create texture!`

The line that segfault is 8827 in SDL_gpu_vulkan.c
`Uint32 srcLayer = srcHeader->info.type == SDL_GPU_TEXTURETYPE_3D ? 0 : info->source.layer_or_depth_plane;`

After investigating, I realized 2 of my 3 computers also render an empty texture instead of the game, with D3D12.

However, ever thing works fine on D3D11...

Additionally, I tested the game on a really poor laptop that is 6-7 years old and it ran well on any of the 3 backends. So like, why don't my newer machines work properly with the other backend ?

I have D3D11 working for 3/3.
D3D12 working for 1/3.
Vulkan working for 2/3.

That hardly seems normal...

I was using Texture Target to avoid blitting surfaces with a cpu renderer. But now I am regretting this choice and thinking of using surfaces for all my atlas and stuff... It seems like I am either doing something wrong or something else is going on.

I tried to reduce the texture target count to experiment. I reduced it by A LOT and even stripping them down to the bare minimum:
- 2 x 2K/4K instead of 11x
- 2x sprite_atlas sheet instead of 8x
- 6x glyph sheet instead of 24x

and that didn't change a thing. So I didn't really think I did something wrong, but you tell me. As I said, my experience with this API is limited.

I'm on latest `main`.

Thank for your help in advance,

**Comment by thatcosmonaut** [comment] 2024-09-25 17:01
If you call CreateGPUDevice with debug_mode set to true, does anything come up?

**Comment by l-t-m-f** [comment] 2024-09-25 20:26
Hi, thanks for answering.

I'm unfamiliar with `SDL_CreateGPUDevice`, I used the hint to ask for a different backend with `SDL_SetHint(SDL_HINT_GPU_DRIVER, ` using the various names. `"direct3d11"`, `"direct3d12"`, and `"vulkan"`.

I did try to use `SDL_CreateGPUDevice` as your recommended, to help you with more information, but since I'm unfamiliar with this part of the API, there's a fair chance I didn't do it properly. I then claimed the window.

I'm only copying sprite textures in this game using `SDL_RenderTexture`. Knowing this, do you still advice me to try to setup a `GPUDevice` with debug_mode?

I'm just wondering if the GPUDevice is compatible with my current approach before I delve deeper.

**Comment by thatcosmonaut** [comment] 2024-09-25 20:52
Oh... are you using SDL_Render and not using the GPU API directly?

**Comment by l-t-m-f** [comment] 2024-09-25 21:17
Hi, yes exactly thatcosmonaut. All of my problems is within `SDL_Render`, which is why I find it so weird. And its also not consistent on all my machine, but if its really a memory error in the backend, all bets are up.

The only reason I realized was with the recent commit which forced Win11 backend to be on Vulkan. Then one of my device began crashing on that project and thus I started to investigate... 

This is a pixel art game, so I don't really care about which renderer is used. But if the default is crashing now.

Hope this helps. Let me know if I can be of more assitance. 

If it turns out to be needed, I could potentially go back a certain way in the `main` tree of SDL and try to see when the problem started appearing with a specific commit...

**Comment by l-t-m-f** [comment] 2024-09-25 22:39
I took a new look at my problem(s) after writing this. I was able to identify the 2nd issue (not the one in the title of this thread -- but rather the one with direct3d12 not rendering any textures in 2 of my 3 computers). It is caused by the `for` loop on the codepaste. If it executes, then, my rest of my game doesn't render. The renderer will only the fill colors set with `RenderClear` appear but no texture. This is part of the loop for loading the fonts as glyph atlases, so its odd that it affects other parts of the project like game sprites...

Additionally, I disabled line by line the for loop and identified the fault coming from `SDL_RenderTexture (app->renderer, as_texture, NULL, &next_glyph_rect);` ! 

(If I manage to hunt down the source of the VK_ERROR I shall post a new reply, in the meantime perhaps you can advise me on this secondary fault as well.)

    if (atlas->glyph_sheets[font_face][font_size] == NULL)
    {
      app_error_log (
      true,
      "Critical internal error! Attempting to use a NULL render_target.");
       exit(1);
    }
    render_target_switch (atlas->glyph_sheets[font_face][font_size]);

    /* A temporary surface which holds the next glyph */
    SDL_Surface *next_glyph_surface = NULL;
    SDL_Texture *as_texture = NULL;
    SDL_FRect next_glyph_rect;
    char c[2];

    next_glyph_rect.x = 0;
    next_glyph_rect.y = 0;



    /* Iterate over all the writeable glyphs. */
    for (size_t i = ' '; i <= 'z'; i++)
    {
      as_texture = NULL;
      next_glyph_surface = NULL;
      c[0] = (char)i;
      c[1] = (char)0;

      next_glyph_surface
          = TTF_RenderUTF8_Blended (atlas->fonts[font_face][font_size], c,
                                    (SDL_Color){ 255, 255, 255, 255 });
      if (next_glyph_surface == NULL)
        {
          app_error_log (false,
                         "Error while rendering a glyph surface of font face "
                         "%d of size %d. \n SDL says: '%s'...",
                         font_face, font_size, SDL_GetError ());
          continue;
        }

      SDL_SetSurfaceBlendMode (next_glyph_surface, SDL_BLENDMODE_BLEND);

      as_texture
          = SDL_CreateTextureFromSurface (app->renderer, next_glyph_surface);

      if (as_texture == NULL)
        {
          app_error_log (false,
                         "Error while creating the glyph texture of font face "
                         "%d of size %d.\n SDL says: '%s'...",
                         font_face, font_size, SDL_GetError ());
          continue;
        }

      SDL_SetTextureScaleMode (as_texture, SDL_SCALEMODE_NEAREST);
      SDL_SetTextureBlendMode (as_texture, SDL_BLENDMODE_BLEND);

      /* Calculate the resulting texture size. */
      SDL_GetTextureSize (as_texture, &next_glyph_rect.w, &next_glyph_rect.h);

      /* If we reach the width extent of the sheet, readjust the position to
       * the next line. */
      if (next_glyph_rect.x + next_glyph_rect.w >= FONT_TEXTURE_SIZE_X)
        {
          /* Reset to a new row, column 1. */
          next_glyph_rect.x = 0;
          next_glyph_rect.y += next_glyph_rect.h + 1;

          /* If we reach the height extent of the sheet, there's a problem. */
          if (next_glyph_rect.y + next_glyph_rect.h >= FONT_TEXTURE_SIZE_Y)
            {
              app_error_log (
                  true,
                  "Out of glyph space in %.1f x %.1f font atlas texture map.",
                  FONT_TEXTURE_SIZE_X, FONT_TEXTURE_SIZE_Y);
              exit (1);
            }
        }

      /* Paste the glyph to the render_target. */
      SDL_RenderTexture (app->renderer, as_texture, NULL, &next_glyph_rect);

      app_debug_log (DEBUG_LOG_ALL, false,
                     "Pasting new character '%c' of font %d.%d with size %f, "
                     "%f, at %.1f, %.1f "
                     "into glyph sheet.",
                     (char)i, font_face, font_size, next_glyph_rect.w,
                     next_glyph_rect.h, next_glyph_rect.x, next_glyph_rect.y);

      /* Cache the rect. */
      atlas->glyphs[font_face][font_size][i] = next_glyph_rect;

      /* Adjust the position of the next glyph based on the size the current
       * glyph will add to the taken space on the glyph sheet. */
      next_glyph_rect.x += next_glyph_rect.w;

      /* Cleanup the surface and texture. */
      SDL_DestroyTexture (as_texture);
      SDL_DestroySurface (next_glyph_surface);
    }
    render_target_switch (NULL);

**Comment by Akaricchi** [comment] 2024-09-26 00:43
You can set the `SDL_PROP_GPU_DEVICE_CREATE_DEBUGMODE_BOOL` hint to `true` to enable debugging in the GPU render driver.

However, I think you might be actually just running out of memory here. You are creating a ton of temporary GPU resources in a loop. `SDL_DestroyTexture` won't save you here because texture deletion is deferred; it won't actually happen until the frame is fully rendered at least.

Instead of creating a temporary texture for every glyph, you should update the atlas texture directly instead. See the `SDL_LockTexture()` and `SDL_UnlockTexture()` functions; they allow you to upload pixels to a specific region of a texture.

**Comment by l-t-m-f** [comment] 2024-09-26 01:08
Thank you for pointing out what I was doing it wrong. I'll looking into it. I knew this loop was bad, I didn't think it was this bad ahah. Truth is, I would have done this with surface and I couldn' t figure out how to access the pixels of the texture directly so I put this hack in the meantime. Appreciate the help and I think you can put this to snooze for now. I'll implement your suggestions.

**Comment by Akaricchi** [comment] 2024-09-26 02:32
I guess I forgot to mention that you need to create the texture with `SDL_TEXTUREACCESS_STREAMING` for this to work.

> figure out how to access the pixels of the texture directly

Just to be pedantic, you are not accessing the texture pixels directly with this method either. The texture pixels live in GPU memory. `SDL_Texture`s with `SDL_TEXTUREACCESS_STREAMING` maintain a pixel buffer on the CPU. When you "lock" a texture, you get a pointer to that buffer (with an offset based on the region you specified) that you can write into. "Unlocking" the texture then uploads the affected part of the buffer to the GPU.

**Comment by l-t-m-f** [comment] 2024-09-26 02:41
Thanks. I'm pretty interested in how SDL works so I appreciate the details. Hopefully one day I know enough to help!

**Comment by l-t-m-f** [comment] 2024-09-26 05:02
Hi, so two things ... 
First, I have succeeded with Akaricchi's suggestion  and all my issues with d3d12 are resolved.

I was disappointed to see that it was still crashing with Vulkan `VK_ERROR_OUT_OF_DEVICE_MEMORY` on my MSI Laptop Titan HX 18. This crash happens somewhere totally different, on the SDL_RenderPresent call at the end of the `AppIterate`.
After much tinkering, I discovered that my crash is gone if I disable VSync...

Isn't that odd? Since I've resolved it on my end, I just wondered why that might be and I post this info since maybe someone else will get the same jam.

That's all!

**Comment by l-t-m-f** [comment] 2024-09-26 16:44
Hi,

So thanks, the hint makes a new assertions proc.

    WARNING: 
    Assertion failure at SDL_BlitGPUTexture_REAL (../../../../repos/SANDBOX/deps/SDL/src/gpu/SDL_gpu.c:2470), 
    triggered 1 time: 
    '!"Blit source/destination regions must have non-zero width, height, and depth"'`


and 
    `'!"For any texture: width, height, and layer_count_or_depth must be >= 1"'`

and
    `'!"Blit source texture must be non-NULL"'`

Another fact I feel I should mention, is I have 10 "maps" on my game and each of them is pretty big (2048x2048 pixels), so that's 10 textures of fair size.
Should I keep these as surfaces? If the player moves fast to an adjacent map, I wanted to load it fast without having to generate the map texture, which is why I precreated these textures and was keeping them active. Because they are also texture tagrets... I don't have a good concept of the overhead this creates, so this is hard for me to know if this is an issue. Maybe?

Regarding the part of my program you already helped me with, the glyph atlas. I use the `SLD_LockTextureToSurface` now (hopefully this is the same performance as the one which puts a `void *` pixels buffer?) The way I used it, is I locked the texture whole before the for loop and then used small rects to fill it gradually with `BlitSurface`. I also do the same for my sprite atlas sheets.

After the for loop, I unlock the texture. See for example how I did it for the glyph atlas:

    SDL_Surface *glyph_sheet_stream = NULL;
    if (SDL_LockTextureToSurface (atlas->glyph_sheets[font_face][font_size],
                                NULL, &glyph_sheet_stream)
      == false)
    {
      app_error_log (true, "Error! Couldn't lock texture! \n SDL says: '%s'",
                     SDL_GetError ());
      exit (1);
    }

    /* Iterate over all the writeable glyphs. */
    for (size_t i = ' '; i <= 'z'; i++)
    {
        next_glyph_surface = NULL;
        c[0] = (char)i;
        c[1] = (char)0;

      next_glyph_surface
          = TTF_RenderUTF8_Blended (atlas->fonts[font_face][font_size], c,
                                    (SDL_Color){ 255, 255, 255, 255 });
      SDL_SetSurfaceBlendMode (next_glyph_surface, SDL_BLENDMODE_BLEND);

      if (TTF_SizeText (atlas->fonts[font_face][font_size], c,
                        &next_glyph_rect.w, &next_glyph_rect.h)
          == false)
        {
          app_error_log (false,
                         "Error while acquiring TTF font size for string "
                         "'%s'. \n SDL says: '%s'...",
                         c, SDL_GetError ());
          continue;
        }

      if (next_glyph_surface == NULL)
        {
          app_error_log (false,
                         "Error while rendering a glyph surface of font face "
                         "%d of size %d. \n SDL says: '%s'...",
                         font_face, font_size, SDL_GetError ());
          continue;
        }

      /* If we reach the width extent of the sheet, readjust the position to
       * the next line. */
      if (next_glyph_rect.x + next_glyph_rect.w >= FONT_TEXTURE_SIZE_X)
        {
          /* Reset to a new row, column 1. */
          next_glyph_rect.x = 0;
          next_glyph_rect.y += next_glyph_rect.h + 1;

          /* If we reach the height extent of the sheet, there's a problem. */
          if (next_glyph_rect.y + next_glyph_rect.h >= FONT_TEXTURE_SIZE_Y)
            {
              app_error_log (
                  true,
                  "Out of glyph space in %.1f x %.1f font atlas texture map.",
                  FONT_TEXTURE_SIZE_X, FONT_TEXTURE_SIZE_Y);
              exit (1);
            }
        }

      SDL_BlitSurface (next_glyph_surface, NULL, glyph_sheet_stream,
                       &next_glyph_rect);

      app_debug_log (DEBUG_LOG_ALL, false,
                     "Pasting new character '%c' of font %d.%d with size %d, "
                     "%d, at %d, %d "
                     "into glyph sheet.",
                     (char)i, font_face, font_size, next_glyph_rect.w,
                     next_glyph_rect.h, next_glyph_rect.x, next_glyph_rect.y);

      /* Cache the rect. */
      atlas->glyphs[font_face][font_size][i] = next_glyph_rect;

      /* Adjust the position of the next glyph based on the size the current
       * glyph will add to the taken space on the glyph sheet. */
      next_glyph_rect.x += next_glyph_rect.w;

      /* Cleanup the surface. */
      SDL_DestroySurface (next_glyph_surface);
    }

    SDL_UnlockTexture (atlas->glyph_sheets[font_face][font_size]);

**Comment by Akaricchi** [comment] 2024-09-26 17:22
I can't reproduce these assertion failures on Vulkan/Linux. What backend(s) are you getting them on? Does it happen on first present only, or maybe after a resize or fullscreen toggle? If this happened every time I don't think you'd see anything displayed at all.

Besides the assertions, can you see any Vulkan validation errors in the console output?

> Another fact I feel I should mention, is I have 10 "maps" on my game and each of them is pretty big (2048x2048 pixels), so that's 10 textures of fair size.

It shouldn't be a problem to keep them in VRAM. Assuming those are RGBA 8bpp textures, `2048 * 2048 * 4 * 10` is just 160MBs.

> After the for loop, I unlock the texture. See for example how I did it for the glyph atlas:

This code looks ok now.

**Comment by l-t-m-f** [comment] 2024-09-26 18:10
Its on the Vulkan backend. It happens on all `RenderPresent()` and crashes the app. I can't reproduce it either except on one Windows 11 laptop device. I'm going to try to create a minimal example which creates the same bug on that device, and if I can, share it with you.

**Comment by l-t-m-f** [comment] 2024-09-27 17:25
The following minimal code is sufficient to recreate the issue, again only on my laptop MSI Titan HX 18 - GTX 4080, with VSync 1, but why?


    #define SDL_MAIN_USE_CALLBACKS 1

    #include "SDL3/SDL.h"
    #include "SDL3/SDL_main.h"

    SDL_Window *window = NULL;
    SDL_Renderer *renderer = NULL;

    SDL_AppResult
    SDL_AppInit (void **state, int argc, char *argv[])
    {
      SDL_InitFlags sdl_flags = SDL_INIT_VIDEO;
    
      if (SDL_Init (sdl_flags) == false)
        {
          SDL_Log ("Couldn't initialized SDL! SDL says: '%s'", SDL_GetError ());
          return SDL_APP_FAILURE;
        }

      const char *drive_name = "vulkan";
      if (SDL_SetHint (SDL_HINT_GPU_DRIVER, drive_name) == false)
        {
          SDL_Log ("Something went wrong when setting the hint '%s'! "
                   "\n SDL says: '%s'!",
                   SDL_HINT_GPU_DRIVER, SDL_GetError ());
          return SDL_APP_FAILURE;
        }
      else
        {
          if (SDL_SetHint (SDL_HINT_RENDER_GPU_DEBUG, "1") == false)
            {

              SDL_Log ("Something went wrong when setting the hint '%s'! "
                       "\n SDL says: '%s'!",
                       SDL_HINT_RENDER_GPU_DEBUG, SDL_GetError ());
            }
        }

      /*
       * Window/Renderer creation
       */
      SDL_WindowFlags window_flags = SDL_WINDOW_RESIZABLE;
      if (SDL_CreateWindowAndRenderer ("Test", 640, 480, window_flags, &(window),
                                       &(renderer))
          == false)
        {
          SDL_Log ("Couldn't create window and/or renderer.\n SDL says: %s",
                   SDL_GetError ());
          return SDL_APP_FAILURE;
        }
      SDL_SetWindowTitle (window, "Test");
      if (SDL_SetRenderVSync (renderer, 1) == false)
        {
          SDL_Log ("Error while setting VSync! SDL says '%s'!", SDL_GetError ());
        }
      SDL_SetRenderDrawBlendMode (renderer, SDL_BLENDMODE_BLEND);

      return SDL_APP_CONTINUE;
    }

    SDL_AppResult
    SDL_AppEvent (void *state, SDL_Event *event)
    {
      switch (event->type)
        {
        case SDL_EVENT_QUIT:
          {
            return SDL_APP_SUCCESS;
          }
        }
      return SDL_APP_CONTINUE;
    }

    /*
     * MAIN LOOP
     */
    SDL_AppResult
    SDL_AppIterate (void *state)
    {

      SDL_SetRenderDrawColor (renderer, 0, 0, 0, 255);
      SDL_RenderClear (renderer);

      if (SDL_RenderPresent (renderer) == false)
        {
          SDL_Log (
              "Error while trying to present the final render!\nSDL says: '%s'",
              SDL_GetError ());
          return SDL_APP_FAILURE;
        }

      return SDL_APP_CONTINUE;
    }

    void
    SDL_AppQuit (void *state)
    {
    }

**Comment by thatcosmonaut** [comment] 2024-09-27 17:33
I committed a change last night that may affect this issue, can you test with latest `main`?

**Comment by l-t-m-f** [comment] 2024-09-27 17:39
It seems fixed. Amazing!

**Comment by thatcosmonaut** [comment] 2024-09-27 17:54
Excellent. Just to be specific, the issue was that AcquireGPUSwapchainTexture could return a width and height of 0 under certain conditions which aren't necessarily failures, so the Render backend was creating a 0-size texture as the backbuffer. After the revision we no longer return width and height from that function, and the client is just expected to use the window size, so this is no longer a problem.

**Comment by slouken** [comment] 2024-09-27 18:00
> Excellent. Just to be specific, the issue was that AcquireGPUSwapchainTexture could return a width and height of 0 under certain conditions which aren't necessarily failures, so the Render backend was creating a 0-size texture as the backbuffer. After the revision we no longer return width and height from that function, and the client is just expected to use the window size, so this is no longer a problem.

On macOS high density displays (2x, etc.) the backbuffer size is larger than the window size. Are we handling that correctly? Or is the application intended to use `SDL_GetWindowSizeInPixels()`?

**Comment by thatcosmonaut** [comment] 2024-09-27 18:12
> On macOS high density displays (2x, etc.) the backbuffer size is larger than the window size. Are we handling that correctly? Or is the application intended to use `SDL_GetWindowSizeInPixels()`?

It's intended to use `SDL_GetWindowSizeInPixels`, this is what SDL_render_gpu.c does now. I'll specify this in the header docs.

**Comment by Akaricchi** [comment] 2024-09-27 18:29
Not sure I love this change, just because somebody will definitely screw up and use `SDL_GetWindowSize()` on accident.

**Comment by l-t-m-f** [comment] 2024-09-29 07:32
Hi, thatcosmonaut!

I noticed that the assertion is back on all devices now. But, instead of crashing with `VK_ERROR_OUT_OF_DEVICE_MEMORY`, on this new device it just makes a black screen.

Thought I'd notify you !

**Comment by l-t-m-f** [comment] 2024-09-29 17:22
Hi thatcosmonaut, I have the assertion triggering again on a new device (not the same device!). This time, **it doesn't crash.** A window opens of the right size, but its all black. 

Thought I'd let you know. I pulled the very last main 15 minutes ago and made sure.

**Comment by l-t-m-f** [comment] 2024-09-29 18:36
Its on my old crappy laptop.

11th Gen Intel Core i7-1165G7
Windows 10 Pro 22H2
NVIDIA GeForce mx330

Vulkan backend only, direct3d11 and 12 work. Vsync has no effect now. On or off, the assertions trigger. (previously, it was only when Vsync was ON)

Best of luck, if I can run any test on my end let me know :)

**Comment by thatcosmonaut** [comment] 2024-09-29 19:03
This seems to be literally an out of memory issue then, there might be an issue with the host memory fallback in Vulkan.

**Comment by Akaricchi** [comment] 2024-09-29 19:06
Which assertion exactly is triggering?

**Comment by thatcosmonaut** [comment] 2024-09-29 19:31
Could you try setting the log level to warn or debug and see if you get any messages near the bind failure?

**Comment by l-t-m-f** [comment] 2024-09-29 19:40
With Priority DEBUG:

    . In Accept Drag and Drop, window 2, enabled Full OLE IDropTarget 
    WARNING: Validation layers not found, continuing without validation 
    SDL_GPU Driver: Vulkan 
    Vulkan Device: NVIDIA GeForce MX330 
    Vulkan Driver: NVIDIA 556.12 
    Vulkan Conformance: 1.3.0 
    Created renderer: gpu 
    WARNING:

Then assertions trigger.

I'll try to run some system updates. I don't use this computer too much.

**Comment by thatcosmonaut** [comment] 2024-09-29 19:50
... the warning is just empty?

**Comment by l-t-m-f** [comment] 2024-09-29 19:58
No! Sorry for the confusion, that's just the first line of the assertion I shared earlier, which begin after. But you saw this warning also, is it relevant? `WARNING: Validation layers not found, continuing without validation `

**Comment by Akaricchi** [comment] 2024-09-29 19:59
Yeah, it is. I believe you have to install the Vulkan SDK to get validation layers on windows?

**Comment by l-t-m-f** [comment] 2024-09-29 20:01
Should SDL default to direct3D then? I definitively did not install the Vulkan SDK on that machine. Its just lying around and I just wanted to see how the project would run on it ahah. I can try to install the Vulkan SDK to see if it goes away.

**Comment by thatcosmonaut** [comment] 2024-09-29 20:02
You don't need the Vulkan SDK to run the applications correctly, the validation layers are just for debugging.

**Comment by thatcosmonaut** [comment] 2024-09-29 20:04
I was expecting to see this line get hit: https://github.com/libsdl-org/SDL/blob/c84d825241447a466cc3df24a04d85b83148834d/src/gpu/vulkan/SDL_gpu_vulkan.c#L2138

But since it isn't, it seems like texture binds aren't falling back to non-device-local memory for some reason.

**Comment by l-t-m-f** [comment] 2024-09-29 20:05
> You don't need the Vulkan SDK to run the applications correctly, the validation layers are just for debugging.

Oh that makes sense! My bad, I did not understand correctly what Akaricchi meant!
Should I install the Vulkan SDK, maybe it will give more insight?

**Comment by thatcosmonaut** [comment] 2024-09-29 20:06
It's probably not necessary right now - I need to do some investigation.

**Comment by l-t-m-f** [comment] 2024-09-29 20:06
No worries, I'll just run with direct3d12 for now. Happy bug-hunting!

**Comment by thatcosmonaut** [comment] 2024-09-29 20:35
@l-t-m-f Question: are you creating lots of textures with SDL_TEXTUREACCESS_TARGET?

**Comment by thatcosmonaut** [comment] 2024-09-29 20:43
Actually I might be confused... is the minimal example failing with out of memory errors or just blit asserts?

**Comment by l-t-m-f** [comment] 2024-09-29 21:59
Unfortunately its all with the minimal reproduction, so not even a single `SDL_Texture` is created on my end.

- **Before (when I opened the thread):** I was getting `VK_ERROR_OUT_OF_DEVICE_MEMORY` + the Assertions + Crash on my GTX 4080. Then you fixed that.

- **Now (after your fix 2 days ago)**: I get the Assertions, no crash, and black screen. Only card affected is my MX 330 (low-end device).

I also have to report something new that might help. On my GTX 4080, thanks to the new Debug priority you had me set, I noticed a warning (even though the example launches now without assertions since you fixed it). It reads: `WARNING: Out of BAR memory, allocating uniform buffers on host-local memory, expect degraded performance!`

Perhaps this has something to do with the issue.

**Comment by thatcosmonaut** [comment] 2024-09-29 22:05
The BAR memory is unrelated to whatever this is, although it _is_ surprising that it would run out, so I'll look into that separately.

**Comment by thatcosmonaut** [comment] 2024-09-29 23:02
@l-t-m-f I have a test branch here, could you try your example on this: https://github.com/thatcosmonaut/SDL/tree/more_render_gpu_fixes

**Comment by l-t-m-f** [comment] 2024-09-30 00:03
It seems good now, I tested it on my 3 computers and it works without issue. Good work man.

**Comment by thatcosmonaut** [comment] 2024-09-30 07:27
@l-t-m-f Could you test this PR: https://github.com/libsdl-org/SDL/pull/11003? I'm trying to handle this in a more robust way.

**Comment by l-t-m-f** [comment] 2024-09-30 17:13
Done! It works correctly.

**Comment by thatcosmonaut** [comment] 2024-09-30 17:23
Fixed by #11003

**Closed by thatcosmonaut** 2024-09-30 17:23 UTC
