### ISSUE TITLE
[WAYLAND] OpenTyrian only shows a part of the screen in fullscreen mode.

### ISSUE THREAD

**Issue by vanfanel** [libsdl-org/SDL#6354] opened 2022-10-07 18:13 UTC
Hi there,

In the latest stable version of SDL2 (2.24.1) only a part of the screen in OpenTyrian  (https://github.com/opentyrian/opentyrian)  is visible in fullscreen mode.

With current GIT code (commit 31991ab85185309a46b7a62e11ade196e1c86ad5) things have improved and, after some seconds into the game logos, full game screen is visible.

I believe this commit improved things: https://github.com/libsdl-org/SDL/commit/914a65e0982f9049b517a181f5956338e2bf1ed1

Anyway, it's *almost* fixed on current GIT code, but there's that small defect that only a part of the screen is visible in fullscreen mode during the first seconds of the game.

@flibitijibibo Maybe you could take a look? Seems that you are the master of Wayland improvement  :)

**Comment by slouken** [comment] 2022-10-07 18:17
@Kontrabant, can you take a look?

**Comment by flibitijibibo** [comment] 2022-10-07 19:02
Throwing out a couple generic ideas, may not be wholly relevant:

- `WAYLAND_DEBUG=1` output is always nice (probably want this in [Gist](https://gist.github.com/) form)
- When it's partially visible is it actively rendering frames, or does it render one frame and stop to do something like load assets?

The second one might just be that it hasn't done the whole roundtrip yet, which would explain why it self-corrects shortly after. (Would still be nice if it's something we can fix though.)

**Comment by Kontrabant** [comment] 2022-10-07 19:09
The main problem this game seems to have is that it doesn't run process messages or flip the buffers when there's no animation occurring onscreen unless input events occur, so any window messages such as resizes or going in/out of fullscreen won't be processed until something occurs that causes the game to process it's message loop or flip the buffers and subsequently process the Wayland message loop.

Running it with Wayland debug output shows everything coming to a halt when the game logos or menu are static unless some input occurs. Everything just stops, which is why the game seems to fix itself when some animation occurs and the menus crossfade.

Not something that can be fixed on SDL's end. This game has to flip the buffers and run it's message loop more often.

**Comment by vanfanel** [comment] 2022-10-07 19:13
@Kontrabant Maybe it should be reported to the engine's authors then?
On KMS/DRM, the engine runs flawlessly in this regard.

**Comment by vanfanel** [comment] 2022-10-07 19:29
@Kontrabant I use the Sway compositor.

**Comment by Kontrabant** [comment] 2022-10-07 22:01
The only thing I can think of offhand is that WLRoots compositors might be doing some late window configuration that isn't being processed because the game isn't running the message loop at that time. I'm not familiar with the inner workings of WLRoots, so you would have to ask the developers there.

Ultimately though, the game needs to run the message loop at regular intervals.  As flibit mentioned, not doing so on Wayland can have some bad side effects ranging from what you are seeing, to the compositor thinking the application has hung, to outright crashes because a message buffer fills up and libwayland breaks the connection.

I don't think there is anything SDL can really do about this (barring some radical redesign of the event system), so I'm inclined to categorize this as `NOTOURBUG`.

**Comment by slouken** [comment] 2022-10-07 23:08
Speaking of radical redesign of the event system, we're running into this pretty regularly on Wayland. Maybe we do need to create a separate event thread to handle Wayland server communication?

**Comment by flibitijibibo** [comment] 2022-10-07 23:35
Wayland might need a thread for events, yeah... note that this doesn't solve _everything_ though; it will still adamantly refuse to present until the application presents (which when you say it out loud, _duh_, but we seem to get lots of test apps that don't do this).

**Comment by Kontrabant** [comment] 2022-10-08 18:58
> Wayland might need a thread for events, yeah... note that this doesn't solve _everything_ though; it will still adamantly refuse to present until the application presents (which when you say it out loud, _duh_, but we seem to get lots of test apps that don't do this).

To note, I hacked things up so that the Wayland event loop runs in it's own thread and it didn't help in the case of this game. As was mentioned, even if the Wayland message loop is run, the game still has to respond to changes and display a new frame, which this isn't doing.

Window behavior with events in their own thread also seems somewhat buggy, so I would be weary of going down the path of shoving the entire Wayland event system in it's own thread as that road likely leads to world of pain.

Given that most of the issues related to application inactivity and Wayland event processing are from a buildup of input events (devices like high-res mice filling the buffer until it disconnects), it might be a good idea to just give the `wl_seat` instance it's own event queue separate from the main Wayland queue.  You could then have a watchdog thread that wakes up occasionally and pumps input events if the main application hasn't done so for a while, or even put the input event handler entirely on it's own thread if desired (probably overkill though). I wired up the former as an experiment, and it seems to work with no immediate side-effects.

**Comment by Kontrabant** [comment] 2022-10-09 17:36
There's already a discussion for the larger Wayland issue at #5536, so this can continue there. As for this specific bug, the root of the problem is that the game isn't responding to messages or flipping buffers when the screen is static, which isn't something that SDL can fix, so I still have to go with `NOTOURBUG` on that.

**Comment by Cacodemon345** [comment] 2022-10-19 16:30
This is fixed on OpenTyrian's side as of now.

**Comment by flibitijibibo** [comment] 2022-10-19 16:38
Going to mark this closed as `NOTOURBUG` then - #5536 should be used for further discussion as previously mentioned.

**Closed by flibitijibibo** 2022-10-19 16:38 UTC
Labels: notourbug, wayland
