### ISSUE TITLE
BUG: in SDL_SetRenderTarget(SDL_TEXTUREACCESS_TARGET)

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3481] opened 2021-02-11 01:45 UTC
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [test-case to dump value (main_bug_4901_logical_and_target.c, text/x-csrc, 2019-12-19 10:49:27 +0000, 3067 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4118)

**Reported in version:** 2.0.10
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2019-12-17 14:33:15 +0000, Marcel Bakker wrote:

> logical_w/h not being set to it's default value
> 
>     if (texture) {
>         ...
> -        renderer->logical_w = texture->w;
> -        renderer->logical_h = texture->h;
> +        renderer->logical_w = 0;
> +        renderer->logical_h = 0;
>     } else {
>         ...
>     }

On 2019-12-18 06:24:04 +0000, Sylvain wrote:

> https://hg.libsdl.org/SDL/rev/2d2fd56db9b7

On 2019-12-18 06:31:57 +0000, Sylvain wrote:

> and before that, this was added here:
> https://hg.libsdl.org/SDL/rev/008057dcc079

On 2019-12-18 13:10:30 +0000, Marcel Bakker wrote:

> patch: https://hg.libsdl.org/SDL/rev/2d2fd56db9b7
> says: The SDL_RenderGetLogicalSize function should always return the amount of pixels that are currently available for rendering to.
> 
> This is wrong imo, we have SDL_GetRendererOutputSize to return the amount of pixels that are currently available.
> 
> SDL_RenderGetLogicalSize should only return some value, if a logical size has been set by the user.
> Also, the default-target renderer does set its logical_w/h to 0 by default.

On 2019-12-18 15:03:13 +0000, Sylvain wrote:

> I agree, it also seems to me logical_w/h could be set to 0.
> 
> In fact, logical_w/h seems has no purpose with texture target.
> logical_w/h is used for scaling events, with the real target.

On 2019-12-18 20:22:09 +0000, Marcel Bakker wrote:

> I also see that mouse and finger events are only being corrected by SDL when a logical size has been set on the default target.
> But draw and copy functions will still use the logical size set on a texture target. [combination of viewport + scale]
> 
> I am looking at this from a 3rd party library POV
> that wants to preserve user made settings for a texture target [logical,viewport,scale,clip]
> before using SDL on a different texture target internally
> 
> you make it sound like there is no use-case for having set a logical-size on a texture-target.
> As a 3rd party, i must assume there is, because SDL has the option to set it on either the default or texture target.
> But if this is not suppose to happen in SDL, then maybe remove the option from the texture and force it on the default target?

On 2019-12-19 10:49:27 +0000, Sylvain wrote:

> Created attachment 4118
> test-case to dump value
> 
> Just adding a test-case to help dumping the values.
> 
> I think the first version was ok. (eg setting logical_w/h to 0,0).
> because as you said, normal renderer also has logical_w/h set to 0,0 at creation.
> It shouldn't have been reverted back in 2013.
> 
> But by dumping the value: it seems setting the texture w/h is also coherent with the scale of (1,1) and with the viewport values. It's also no affected by using overscan/letterbox. So this seems also fine to me: when using a target texture, the logical size is set to the texture w/h. 
> Changing it would can also break existing users ?
> 
> 
> Moreover, maybe we should update the renderer to have a valid logical w/h ?
> (but that would make the renderer also do a dummy re-scaling for events)
> 
> Maybe other maintainers has an idea about it ?

**Comment by 1bsyl** [comment] 2022-03-21 10:27
closing are duplicate of 2419

**Closed by 1bsyl** 2022-03-21 10:27 UTC
Labels: bug
