### ISSUE TITLE
run in arm wayland  Broken pipe

### ISSUE THREAD

**Issue by tienham** [libsdl-org/SDL#4389] opened 2021-05-18 02:11 UTC
I run SDL2 demo in arm wayland environment. onlyuse follow api
 renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED);

SDL_SetRenderDrawColor(renderer, 0xff, 0, 0, 0xff);
SDL_Rect Rect1 = {100, 120, 50, 50};
SDL_RenderDrawRect(renderer, &Rect1);
SDL_RenderPresent( renderer );
SDL_Delay( 10);

after about 5~10 seconds. it will abort with error
libwayland: error in client communication (pid 1200)
Error sending request: Broken pipe

this issue occurs every time.does anyone have some suggestion ? thanks

**Comment by icculus** [comment] 2021-06-14 03:59
Does this program pump the event queue or just delay? It's possible wayland gets upset if there isn't an occasional call to SDL_PollEvent.

If that isn't the issue, and the latest in revision control is still causing problems (there has been a _lot_ of Wayland improvements in SDL recently!), then it would be useful to know where the abort signal is happening, by running the program under a debugger and getting a backtrace when this crash happens. This is sort of generic advice, which I apologize for offering, but more information would be extremely helpful here.

**Comment by icculus** [comment] 2021-07-24 15:40
Paging @flibitijibibo ... is this a Wayland thing, that it freaks out if the app doesn't respond fast enough? This seems like this would be a problem if there's a game that stops pumping the event loop for a few seconds to load the next map, or whatever.

If this doesn't sound familiar, I'll try to reproduce here.

**Comment by flibitijibibo** [comment] 2021-07-24 15:51
I've not seen this before - I have a few test programs that stall on loading for a long time and it seemed okay. `WAYLAND_DEBUG=1` should tell the whole story if it's reproducible.

**Comment by icculus** [comment] 2021-07-24 16:34
Thanks!

@tienham If you can set the `WAYLAND_DEBUG=1` environment variable and try again, we can see if this is an SDL issue.

**Comment by icculus** [comment] 2021-07-29 21:45
I'm going to bump this to the 2.0.18 milestone, but I can readjust to 2.0.16 if we hear back soon with more info (and will eventually close the issue completely if we don't hear back at all).

**Comment by flibitijibibo** [comment] 2021-09-24 11:29
Closing as a dupe of #4769... I know this one came first but the other thread has a crazy amount of useful info for the same bug (which may not actually be us).

**Closed by flibitijibibo** 2021-09-24 11:29 UTC
Labels: waiting
