### ISSUE TITLE
SDL_RenderDrawLine draws extra pixels at start and end of line

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3604] opened 2021-02-11 01:53 UTC
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [A simple demo of the issue. (drawlines.cpp, text/x-c++src, 2020-03-21 21:36:57 +0000, 3097 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4274)

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-03-21 21:36:57 +0000, William Cleveland wrote:

> Created attachment 4274
> A simple demo of the issue.
> 
> SDL_RenderDrawLine draws extra pixels at the end points when the line is drawn from the 2nd to 4th quadrants. A quadrant reference is as:
> 
>                 |
>            3    |   2
>                 |
>        -------------------
>                 |
>            4    |   1
>                 |
> 
> I think my issue is related to:
> 
> https://bugzilla.libsdl.org/show_bug.cgi?id=2796
> https://bugzilla.libsdl.org/show_bug.cgi?id=2711
> 
> The pixels always appear towards the 3rd quadrant side of the line.
> 
> I have attached a simple program that shows the issue in real time. Just click and draw and you will see two white pixels appear whenever the line is being drawn from quadrants 2 to 4.
> 
> The program will show a yellow line that has the issue, and it is reproducible--live.
> 
> My system is:
> Intel® Core™ i5-9600K CPU @ 3.70GHz × 6
> Radeon 550 Series (POLARIS12, DRM 3.33.0, 5.3.0-7642-generic, LLVM 9.0.0)
> GNOME 3.34.2

**Comment by icculus** [comment] 2021-09-08 16:37
This bug is reproducible with 2.0.10, but not with the latest in revision control; leaving this open until _all_ the line rendering issues are sorted, since regressions are common in this code, but this otherwise appears to be already fixed.

**Comment by icculus** [comment] 2021-11-27 01:00
Okay, closing this with several other bugs.

**Closed by icculus** 2021-11-27 01:00 UTC
