### ISSUE TITLE
CMake config needs too much time

### ISSUE THREAD

**Issue by fknfilewalker** [libsdl-org/SDL#9951] opened 2024-06-03 07:47 UTC
When using SDL through cmake it takes very long to config. Is there some way to speed that up. I think most of the time is spend on the CLIB part. I tried SDL2 and SDL3 and both take very long...

**Comment by olekolek1000** [comment] 2024-06-07 11:43
Are you using windows?

**Comment by fknfilewalker** [comment] 2024-06-23 14:41
Yes. Interestingly when generating vs solutions it takes very long to check all libc functions, but withing visual studio code it is much faster. With msvc you can turn of libc and you safe some time but on macos, turning off libc results in compile errors.

**Comment by icculus** [comment] 2024-12-04 18:19
Duplicate of #9949.

**Closed by icculus** 2024-12-04 18:19 UTC
