### ISSUE TITLE
SDL_DestroyWindow doesn't free memory

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3453] opened 2021-02-11 01:43 UTC
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Heap allocation before and after test code (logcompare.txt, text/plain, 2019-12-02 10:30:22 +0000, 1031017 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4082)
* [Heap before test (log1.txt, text/plain, 2019-12-02 10:40:16 +0000, 863848 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4083)
* [Heap after test (log2.txt, text/plain, 2019-12-02 10:40:39 +0000, 3440154 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4084)

**Reported in version:** 2.0.8
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2019-11-17 09:03:14 +0000, Francesco wrote:

> Basically, in my program I have sometimes to create and destroy a window. I always use the same window pointer creating and destroying the contents (texture and render).
> 
> I notice a memory leak in this process (checking memory usage by the application process) so I wrote a simple program to verify this.
> 
> At the end the process occupied 243.4 MB of RAM, at the beginning 7.3 MB.
> 
> Here the code in order to reproduce the problem:
> 
> ```c
> #include <iostream>
> #include "SDL.h"
> 
> 
> int main(int argc, char *argv[])
> {
> 	SDL_Init(SDL_INIT_VIDEO);
> 
> 	SDL_Window* mainWindow;
> 	SDL_Renderer* mainRenderer;
> 	SDL_Texture* mainTexture;
> 
> 	for (int i = 0; i < 200; i++)
> 	{
> 		mainWindow = SDL_CreateWindow("Memory Leak Test v1.0", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 320, 240, SDL_WINDOW_SHOWN);
> 		mainRenderer = SDL_CreateRenderer(mainWindow, -1, SDL_RENDERER_ACCELERATED);
> 		mainTexture = SDL_CreateTexture(mainRenderer, SDL_PIXELFORMAT_ABGR8888, SDL_TEXTUREACCESS_STREAMING, 320, 240);
> 
> 		if (i == 0)
> 		{
> 			std::cout << "SDL Memory Leak Tester, please check the amount of memory\noccupied by the process, then press Enter\n";
> 			getchar();
> 		}
> 
> 		SDL_Delay(50);
> 
> 		if (i == 199)
> 		{
> 			std::cout << "SDL Memory Leak Tester, please check the amount of memory\noccupied by the process, then press Enter\n";
> 			getchar();
> 		}
> 
> 		SDL_DestroyTexture(mainTexture);
> 		SDL_DestroyRenderer(mainRenderer);
> 		SDL_DestroyWindow(mainWindow);
> 	}
> 
> 	std::cout << "Test finished, press Enter to close\n";
> 	getchar();
> 
> 	return 0;
> }
> ```

On 2019-11-17 13:53:46 +0000, Francesco wrote:

> The problem has the higher impact on Windows, on Ubuntu at the end of the test the memory is increased only around 3MB (around 236MB on Windows).

On 2019-11-18 14:04:14 +0000, Francesco wrote:

> It doesn't happen with SDL_RENDERER_SOFTWARE

On 2019-11-19 13:43:27 +0000, Francesco wrote:

> The behaviour is the same with version 2.0.10 and different rendering drivers

On 2019-11-22 04:53:23 +0000, Cameron Gutman wrote:

> I was not able to reproduce this issue here using the latest HG code on Win10 1909 x64. It may have already been fixed or it could be caused by a driver or other software on your machine.
> 
> I would suggest using UMDH to get heap allocation stack traces from your affected machine. That will be able to pinpoint the source of the leak.
> 
> https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/using-umdh-to-find-a-user-mode-memory-leak

On 2019-12-02 08:49:55 +0000, Francesco wrote:

> Thanks, I will give you all the informations. I have the problem also on a different machine, both ones with Intel UHD Graphics card

On 2019-12-02 10:30:22 +0000, Francesco wrote:

> Created attachment 4082
> Heap allocation before and after test code
> 
> Here the compare file between 2 log files taken at different time

On 2019-12-02 10:40:16 +0000, Francesco wrote:

> Created attachment 4083
> Heap before test

On 2019-12-02 10:40:39 +0000, Francesco wrote:

> Created attachment 4084
> Heap after test

On 2020-03-24 20:07:01 +0000, Ryan C. Gordon wrote:

> 
> The logs weren't insightful for me, but I'm betting this is something we didn't release correctly in the Direct3D renderer. We made some fixes to this for SDL 2.0.12, but I'd have to look at it more closely to see if this is still leaking.
> 
> I assume this _also_ doesn't leak if you force the OpenGL renderer instead of the software one.
> 
> --ryan.

**Comment by honglong1987** [comment] 2022-09-07 02:19
I had the same problem.
I created an simple MFC dialog program and set a timer to create and destroy SDL_Windowand&SDL_Renderer.  when i run the program in vs2017, the process memory and handle keeps growing，and  crashed finally.   

system version: win10 1809
SDL version: 2.24.0

![image](https://user-images.githubusercontent.com/61338601/188773805-43ec8fbc-85d1-4ae1-974a-4db4e6475326.png)

![image](https://user-images.githubusercontent.com/61338601/188773173-b2c6ad84-66ff-47f4-9af7-d067b91c42a2.png)


Here the code in order to reproduce the problem:

// SDLDlgDlg.cpp : implementation file
//

#include "pch.h"
#include "framework.h"
#include "SDLDlg.h"
#include "SDLDlgDlg.h"
#include "afxdialogex.h"
#include "SDL.h"
#ifdef _DEBUG
#define new DEBUG_NEW
#endif

#pragma comment(lib, "SDL2.lib")
// CAboutDlg dialog used for App About

class CAboutDlg : public CDialogEx
{
public:
	CAboutDlg();

// Dialog Data
#ifdef AFX_DESIGN_TIME
	enum { IDD = IDD_ABOUTBOX };
#endif

	protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support

// Implementation
protected:
	DECLARE_MESSAGE_MAP()
};

CAboutDlg::CAboutDlg() : CDialogEx(IDD_ABOUTBOX)
{
}

void CAboutDlg::DoDataExchange(CDataExchange* pDX)
{
	CDialogEx::DoDataExchange(pDX);
}

BEGIN_MESSAGE_MAP(CAboutDlg, CDialogEx)
END_MESSAGE_MAP()


// CSDLDlgDlg dialog



CSDLDlgDlg::CSDLDlgDlg(CWnd* pParent /*=nullptr*/)
	: CDialogEx(IDD_SDLDLG_DIALOG, pParent)
{
	m_hIcon = AfxGetApp()->LoadIcon(IDR_MAINFRAME);
}

void CSDLDlgDlg::DoDataExchange(CDataExchange* pDX)
{
	CDialogEx::DoDataExchange(pDX);
}

BEGIN_MESSAGE_MAP(CSDLDlgDlg, CDialogEx)
	ON_WM_SYSCOMMAND()
	ON_WM_PAINT()
	ON_WM_QUERYDRAGICON()
	ON_WM_TIMER()
END_MESSAGE_MAP()


// CSDLDlgDlg message handlers

BOOL CSDLDlgDlg::OnInitDialog()
{
	CDialogEx::OnInitDialog();

	// Add "About..." menu item to system menu.

	// IDM_ABOUTBOX must be in the system command range.
	ASSERT((IDM_ABOUTBOX & 0xFFF0) == IDM_ABOUTBOX);
	ASSERT(IDM_ABOUTBOX < 0xF000);

	CMenu* pSysMenu = GetSystemMenu(FALSE);
	if (pSysMenu != nullptr)
	{
		BOOL bNameValid;
		CString strAboutMenu;
		bNameValid = strAboutMenu.LoadString(IDS_ABOUTBOX);
		ASSERT(bNameValid);
		if (!strAboutMenu.IsEmpty())
		{
			pSysMenu->AppendMenu(MF_SEPARATOR);
			pSysMenu->AppendMenu(MF_STRING, IDM_ABOUTBOX, strAboutMenu);
		}
	}

	// Set the icon for this dialog.  The framework does this automatically
	//  when the application's main window is not a dialog
	SetIcon(m_hIcon, TRUE);			// Set big icon
	SetIcon(m_hIcon, FALSE);		// Set small icon

	// TODO: Add extra initialization here
	SDL_Init(SDL_INIT_VIDEO);
	SetTimer(1, 10, nullptr);

	return TRUE;  // return TRUE  unless you set the focus to a control
}

void CSDLDlgDlg::OnSysCommand(UINT nID, LPARAM lParam)
{
	if ((nID & 0xFFF0) == IDM_ABOUTBOX)
	{
		CAboutDlg dlgAbout;
		dlgAbout.DoModal();
	}
	else
	{
		CDialogEx::OnSysCommand(nID, lParam);
	}
}

// If you add a minimize button to your dialog, you will need the code below
//  to draw the icon.  For MFC applications using the document/view model,
//  this is automatically done for you by the framework.

void CSDLDlgDlg::OnPaint()
{
	if (IsIconic())
	{
		CPaintDC dc(this); // device context for painting

		SendMessage(WM_ICONERASEBKGND, reinterpret_cast<WPARAM>(dc.GetSafeHdc()), 0);

		// Center icon in client rectangle
		int cxIcon = GetSystemMetrics(SM_CXICON);
		int cyIcon = GetSystemMetrics(SM_CYICON);
		CRect rect;
		GetClientRect(&rect);
		int x = (rect.Width() - cxIcon + 1) / 2;
		int y = (rect.Height() - cyIcon + 1) / 2;

		// Draw the icon
		dc.DrawIcon(x, y, m_hIcon);
	}
	else
	{
		CDialogEx::OnPaint();
	}
}

// The system calls this function to obtain the cursor to display while the user drags
//  the minimized window.
HCURSOR CSDLDlgDlg::OnQueryDragIcon()
{
	return static_cast<HCURSOR>(m_hIcon);
}

void CSDLDlgDlg::OnTimer(UINT_PTR nIDEvent) {
	SDL_Window* sdl_window = nullptr;
	SDL_Renderer* sdl_renderer = nullptr;
	do {
		CWnd* pWnd = GetDlgItem(IDC_STATIC_HD);
		if (pWnd == nullptr) {
			break;
		}

		sdl_window = SDL_CreateWindowFrom(pWnd->m_hWnd);
		if (sdl_window == nullptr) {
			break;
		}

		sdl_renderer = SDL_CreateRenderer(sdl_window, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);

	} while (false);

	if (sdl_renderer != nullptr) {
		SDL_DestroyRenderer(sdl_renderer);
		sdl_renderer = nullptr;
	}

	if (sdl_window != nullptr) {
		SDL_DestroyWindow(sdl_window);
		sdl_window = nullptr;
	}
}

**Comment by icculus** [comment] 2022-09-07 02:32
I wonder if the problem here is something in SDL_CreateWindowFrom not getting cleaned up...it's a significantly less-used codepath with a lot of weird and subtle differences.

**Comment by slouken** [comment] 2022-09-07 16:54
Can you post a link to a whole test project? I'm not sure how to get the source file you posted to compile.

Thanks!

**Comment by honglong1987** [comment] 2022-09-08 00:56
here the test project

[SDLDlg.zip](https://github.com/libsdl-org/SDL/files/9522583/SDLDlg.zip)

**Comment by slouken** [comment] 2022-09-08 02:26
So I'm running this using the debug x86 configuration, and I'm seeing memory fluctuate between 14 and 15 MB, after running for an hour. I'm not seeing a memory leak, although I am seeing a bunch of DLLs load and unload as the renderer is created and destroyed.

Maybe you're seeing a driver bug?

**Comment by honglong1987** [comment] 2022-09-08 02:58
> So I'm running this using the debug x86 configuration, and I'm seeing memory fluctuate between 14 and 15 MB, after running for an hour. I'm not seeing a memory leak, although I am seeing a bunch of DLLs load and unload as the renderer is created and destroyed.
> 
> Maybe you're seeing a driver bug?

Yes，After I upadte the driver，the program's memory fluctuate between 10 and 20 MB. but program's handle shown in system task manager still keeps growing.

![image](https://user-images.githubusercontent.com/61338601/189023986-36570a58-5868-4d8d-af73-0e2fc299159d.png)

**Comment by slouken** [comment] 2022-09-08 19:31
It seems like there's more to be fixed in that driver. On my system the number of handles fluctuates around 370.

Since this doesn't appear to be an SDL bug, I'll go ahead and close this.

**Closed by slouken** 2022-09-08 19:31 UTC
