### ISSUE TITLE
MacOS: Input monitoring permissions requested when joystick/game controller subsystem enabled

### ISSUE THREAD

**Issue by 17cupsofcoffee** [libsdl-org/SDL#4887] opened 2021-10-28 09:24 UTC
After upgrading to Big Sur, one of the Mac users of my library (which uses SDL2 for windowing/input) is getting a keyboard permissions dialog when their game starts up:

* https://github.com/17cupsofcoffee/tetra/discussions/289

This only seems to happen when the joystick/controller subsystems are enabled - when they're commented out, the dialog does not show.

The user in question is using 2.0.16, but did not have this issue when they were using that version on Catalina. They switched it out for 2.0.14 (built from source), and that did not seem to be affected - so it sounds like this may be an interaction between some new code in 2.0.16 and something that's changed in the OS update.

Is this the expected behaviour, or have Apple pulled the rug out from under us? The latter would not surprise me 😄 

A few bits of context/background info:

* This seems to be a seperate issue from the [Caps Lock one](https://discourse.libsdl.org/t/macos-catalina-keyboard-monitoring-permission/27529) that was fixed last year.
* There seems to be [another user on the forums seeing the same behaviour](https://discourse.libsdl.org/t/my-sdl-app-is-asking-for-permission-to-read-all-keystrokes-from-any-application-on-macos/32893), and they also came to the conclusion that it was the joystick subsystem triggering the dialog.

**Comment by icculus** [comment] 2021-10-30 19:25
Pinging @slime73 in case this has been heard of before. If not, I'll see if I can reproduce here.

**Comment by cgutman** [comment] 2021-10-31 23:06
I wonder if we're touching a HID device that we think is a joystick but macOS classifies as a keyboard. Prime candidates are probably the IOKit and HIDAPI joystick backends.

Can you try setting the environment variable `SDL_JOYSTICK_HIDAPI` to `0` and running your test program again?

**Comment by sumibi-yakitori** [comment] 2021-11-01 00:27
@cgutman @17cupsofcoffee
Thanks a lot. I was able to get around this problem by setting that environment variable and running it.

**Comment by icculus** [comment] 2021-11-01 14:22
@sumibi-yakitori Can you tell us what sort of USB devices you have plugged in? It appears we're accessing something we think is a joystick but macOS thinks is a keyboard, and I'd like to see if there's some way to prevent that from happening in the future.

**Comment by slouken** [comment] 2021-11-01 18:12
Can you edit src/joystick/hidapi/SDL_hidapijoystick.c and add this line to the top and send the output?
`#define DEBUG_HIDAPI`

**Comment by sumibi-yakitori** [comment] 2021-11-01 18:45
```sh
INFO: Added HIDAPI device 'Logitech Gaming Mouse G600' VID 0x046d, PID 0xc24a, version 30464, serial NONE, interface -1, interface_class 0, interface_subclass 0, interface_protocol 0, usage page 0x0001, usage 0x0002, path = USB_046d_c24a_0x7f9c68573ce0, driver = NONE (DISABLED)
INFO: Added HIDAPI device 'Massdrop Inc. ALT Keyboard' VID 0x04d8, PID 0xeed3, version 257, serial NONE, interface -1, interface_class 0, interface_subclass 0, interface_protocol 0, usage page 0x0001, usage 0x0080, path = USB_04d8_eed3_0x7f9c68574140, driver = NONE (DISABLED)
INFO: Added HIDAPI device '0x05f3/0x0007' VID 0x05f3, PID 0x0007, version 800, serial NONE, interface -1, interface_class 0, interface_subclass 0, interface_protocol 0, usage page 0x0001, usage 0x0006, path = USB_05f3_0007_0x7f9c685746b0, driver = NONE (DISABLED)
INFO: Added HIDAPI device 'pqrs.org Karabiner DriverKit VirtualHIDKeyboard 1.3.0' VID 0x16c0, PID 0x27db, version 0, serial NONE, interface -1, interface_class 0, interface_subclass 0, interface_protocol 0, usage page 0x0001, usage 0x0006, path = , driver = NONE (DISABLED)
INFO: Added HIDAPI device 'Massdrop Inc. ALT Keyboard' VID 0x04d8, PID 0xeed3, version 257, serial NONE, interface -1, interface_class 0, interface_subclass 0, interface_protocol 0, usage page 0x0001, usage 0x0006, path = USB_04d8_eed3_0x7f9c68574e50, driver = NONE (DISABLED)
INFO: Added HIDAPI device 'Logitech Gaming Mouse G600' VID 0x046d, PID 0xc24a, version 30464, serial NONE, interface -1, interface_class 0, interface_subclass 0, interface_protocol 0, usage page 0x0001, usage 0x0006, path = USB_046d_c24a_0x7f9c68573a90, driver = NONE (DISABLED)
INFO: Added HIDAPI device 'Massdrop Inc. ALT Keyboard' VID 0x04d8, PID 0xeed3, version 257, serial NONE, interface -1, interface_class 0, interface_subclass 0, interface_protocol 0, usage page 0xffbc, usage 0x0234, path = USB_04d8_eed3_0x7f9c68574fa0, driver = NONE (DISABLED)
INFO: Added HIDAPI device 'Massdrop Inc. ALT Keyboard' VID 0x04d8, PID 0xeed3, version 257, serial NONE, interface -1, interface_class 0, interface_subclass 0, interface_protocol 0, usage page 0x0001, usage 0x0006, path = USB_04d8_eed3_0x7f9c685744a0, driver = NONE (DISABLED)
INFO: Added HIDAPI device '0x05f3/0x0007' VID 0x05f3, PID 0x0007, version 800, serial NONE, interface -1, interface_class 0, interface_subclass 0, interface_protocol 0, usage page 0x0001, usage 0x0080, path = USB_05f3_0007_0x7f9c68574980, driver = NONE (DISABLED)
```

**Comment by slouken** [comment] 2021-11-01 22:55
@sumibi-yakitori Thanks!

There's nothing there that seems like it would trigger the permissions dialog. Apple has a bug open internally to investigate:
rdar://84890707

**Comment by slouken** [comment] 2021-11-01 22:57
In the meantime, if you would like to disable HIDAPI in your application to work around this, you can add this line before SDL_Init():
SDL_SetHint(SDL_HINT_JOYSTICK_HIDAPI, "0");

**Comment by icculus** [comment] 2021-11-06 16:41
Also, if you're bored in the meantime, it could be helpful to unplug devices one at a time until we figure out which one is triggering the issue.

**Comment by dqh-github** [comment] 2021-11-14 08:49
We (VICE Team) are seeing the same issue in macOS 11. We were also seeing it in our own joystick code for non-SDL builds of VICE, which I fixed by filtering the device enumeration to joystick and gamepad devices: https://sourceforge.net/p/vice-emu/code/40439

I just tested the same code in SDL, which fixes the 'scary permission dialog for keystroke monitoring' problem for me, here is a patch against SDL main: [macos-game-controller-enumeration.patch.zip](https://github.com/libsdl-org/SDL/files/7533412/macos-game-controller-enumeration.patch.zip)

By the way, with or without this patch, I found that I had to configure with --disable-joystick-mfi to get my USB connected PS4 controller to work. As I was testing with Homebrew supplied deps, I essentially used their configure line plus  --disable-joystick-mfi:

`/configure --without-x --prefix /opt/homebrew --enable-hidapi --disable-joystick-mfi`

Should I create a separate issue to discuss this?

**Comment by dqh-github** [comment] 2021-11-14 09:40
In fact with --disable-joystick-mfi there's no need for the patch. This is the code that triggers the keystroke monitoring warning, depending on which device is passed to it:

`if ([GCController supportsHIDDevice:device]) {`

**Comment by dqh-github** [comment] 2021-11-14 10:21
More info. In my case, the device that triggers the permission dialog on my M1 Mac mini is "Magic Keyboard with Touch ID". **However** , it appears multiple times in the list iteration in `hid_enumerate()`, with varying values for `cur_dev->usage_page` and `cur_dev->usage`. It seems that when `cur_dev->usage_page == 1` and `cur_dev->usage == 6`, calling `[GCController supportsHIDDevice:device]` triggers the permission dialog.

FYI - I have also seen this permission dialog on a Mac with an older Apple bluetooth keyboard (no touch ID) although I have not debugged the issue to this extent.

It seems that configuring with `--disable-hidapi` and NOT `--disable-joystick-mfi` results in no permission dialog, but it also doesn't detect the controller. When configuring with `--disable-joystick-mfi' and NOT `--disable-hidapi` then everything works as expected without a permission dialog.

Hope this helps ...

**Comment by FrodeSolheim** [comment] 2021-11-17 08:59
If you need more testers, I also get this error on my MacBook Pro without any USB or Bluetooth devices attached. The patch from @dqh-github fixed the warning at least.

**Comment by cgutman** [comment] 2021-11-20 19:16
I was able to reproduce this locally (building with CMake didn't enable `SDL_JOYSTICK_MFI`). I pushed a fix to this that looks very similar to what the IOKit backend does and what our Windows HIDAPI code does too (due to hangs touching some devices, rather than permission issues).

Try with the latest commit and see if that fixes it for you too.

**Comment by dqh-github** [comment] 2021-11-24 04:04
The permission warnings are gone! But there are still some unexpected results:

`./configure --without-x`
- no joysticks found

`./configure --without-x --enable-hidapi`
- no joysticks found

`./configure --without-x --enable-hidapi --disable-joystick-mfi`
- joysticks are found

`./configure --without-x --disable-joystick-mfi`
- joysticks are found

In this aspect, it behaves the same as release-2.0.16, at least on macOS 11.16.1. The only difference I see is that the permission dialog problem exists in 2.0.16 unless you build with --disable-joystick-mfi.

The macports install of libsdl2 is built with `./configure --without-x`, and also fails to detect any joysticks. I am wondering, should I request that they build with --disable-joystick-mfi ? Or is this better fixed in a future release of libsdl2 ?

**Comment by cgutman** [comment] 2021-11-24 07:51
@dqh-github  are you still testing with a PS4 controller connected via USB?

If so, can you try it via Bluetooth? Is it an official Sony PS4 controller or a third party controller?

**Comment by dqh-github** [comment] 2021-11-24 09:08
Official Sony, connected using both USB and Bluetooth at same time most of the time, but sometimes one or the other. Have never observed a changed result.

**Comment by dqh-github** [comment] 2021-11-24 11:55
Just in case I repeated the test using bluetooth only, using main HEAD.

`./configure --prefix=/opt/local --without-x --enable-hidapi`

And no joysticks found

**Comment by cgutman** [comment] 2021-11-24 17:52
Are you handling hot-plugged controllers or just counting `SDL_NumJoysticks()` at startup?

Some joystick backends don't report controllers at startup and only enumerate them once you start calling `SDL_PumpEvents()` (or one of `SDL_PollEvent()`, `SDL_WaitEvent()`, etc. that call it under the hood). This is the case for MFI on macOS and WGI on Windows.

Are you able to reproduce this with the `testgamecontroller` utility in the tests folder?

**Comment by dqh-github** [comment] 2021-11-24 20:14
oh - wow - the test program works great. Our codebase is ancient and doesn't support hot-plugged joysticks. Time to change that, many thanks for your help!

In the meantime, do see any disadvantages to our releasing a VICE binary distribution containing SDL2 compiled with --disable-joystick-mfi ?

**Comment by dqh-github** [comment] 2021-11-24 20:34
As a dirty, DIRTY, hack, I chucked a cheeky SDL_PumpEvents() between calls to SDL_InitSubSystem(SDL_INIT_JOYSTICK) and SDL_NumJoysticks() but no good. However, Adding a second call SDL_PumpEvents() as an even dirtier hack seems to reliably work.

But, i'm guessing this depends entirely on the host machine - I assuming the OS needs an unpredictable and hardware dependent amount of time to generate the necessary events. All good - we need to migrate to hot-plug support which will be far better for users anyway. Unless you think there's a big problem with the approach, i'll bundle 3.6 with SDL2 that's been compiled with --disable-joystick-mfi.

**Comment by cgutman** [comment] 2021-11-25 08:29
> In the meantime, do see any disadvantages to our releasing a VICE binary distribution containing SDL2 compiled with --disable-joystick-mfi ?

Nope, I don't think there are any at the moment. It looks like it is used on macOS just in case Apple requires it someday (based on the comment [here](https://github.com/libsdl-org/SDL/blob/343fa612158e4365bc4ea96e8a939767e806bd4c/src/hidapi/mac/hid.c#L560-L567)). As of now (macOS Monterey), macOS still supports the IOKit HID APIs and I'm not aware of any documention that indicates Apple's intention to deprecate them.

Given the compatibility issues in games that don't support hot-plugging joysticks and questionable value with macOS as of today, I wonder if we should default MFI off for macOS. It's currently on by default for Autotools and Xcode builds, and off (unsupported) on CMake (see #5004). What do you think @slouken @slime73 ?

**Comment by slouken** [comment] 2021-11-25 18:24
Yes, I think it's reasonable to default it off for now. Let's do that for 2.0.18 and revisit it as Apple progresses their recommendations.

**Comment by slouken** [comment] 2021-11-26 16:39
Actually, you need to use controller kit and the sfsymbols for controller elements for Apple Arcade titles, so let's leave it enabled by default for now.

Since the original issue with permission prompts seems to be fixed, I'll go ahead and close this for now.

**Closed by slouken** 2021-11-26 16:40 UTC
