### ISSUE TITLE
SDL_PumpEvents requires significant processing power with high polling rate mice, causing low frame rate

### ISSUE THREAD

**Issue by curvedinf** [libsdl-org/SDL#4376] opened 2021-05-11 22:16 UTC
I have been stress testing SDL on Windows with a Razer Viper 8Khz, which is the first 8,000 hz polling rate mouse (most mice are 1,000 hz), and SDL_PumpEvents has poor performance. When the mouse is moved quickly and consistently, SDL's event handling in SDL_PumpEvents slows my test OpenGL app to 30 fps from approximately 3,000 fps when the mouse is not moved.

It appears that SDL is architected to go through the entire event queue multiple times per frame, which is not desirable when there are hundreds of events in the queue from high performance mice.

It would be desirable to index or subdivide the events as they are added to the queue so different event handlers can more efficiently access their subset of applicable events.

**Comment by meyraud705** [comment] 2021-05-15 12:50
You could try to change your event loop from:
```c
while (1) { // main game loop
    SDL_Event e;
    while (SDL_PollEvent(&e)) {
        switch (e.type) {
             /* handle event */
        }
    }
}
```
to:
```c
#define SIZE_EV 64
SDL_Event* es = malloc(SIZE_EV * sizeof(*es));
while (1) { // main game loop
    SDL_PumpEvents();
    int n_ev = 0;
    while ((n_ev = SDL_PeepEvents(es, SIZE_EV, SDL_GETEVENT, SDL_FIRSTEVENT, SDL_LASTEVENT))) {
        for (int i = 0; i < n_ev; ++i) {
            switch (es[i].type) {
                 /* handle event */
             }
        }
    }
}
```
This way, `SDL_PumpEvents` is only called once per frame. `SDL_PeepEvents` is also called once per frame if you have less than `SIZE_EV` event waiting in queue.

**Comment by curvedinf** [comment] 2021-05-15 13:04
Thank you, but your suggestion is how i already have my loop setup. Pump
events is only called once per frame and i have isolated the lag to it. I
do not use PollEvents and instead use the stateful keyboard and mouse
interfaces.

**Comment by meyraud705** [comment] 2021-05-15 15:02
I do not have a mouse that fast to test, so I modified SDL to put `SDL_SendMouseMotion` in a for loop to simulate high frequency mouse. My test app could maintain 60fps even at an equivalent of 32000Hz.

It would help if you could provide a performance profile.

**Comment by curvedinf** [comment] 2021-05-15 17:28
In my test, the performance impact becomes significant at 4-6k mouse events
per second.

My performance testing is for a low latency shooter, where users have high
performance monitors and framerate consistency is critical. For this
reason, while 360 fps theoretically synchronizes with the refresh of the
best monitors, the event queue consuming a highly variable amount of cpu
time creates framerate inconsistency that effects input latency in a
noticable/variable way even when framerates are relatively high.

Unfortunately I can't share my code, but I can assure you that the only
input-related call in the thread which is impacted by this lag is
PumpEvents. I went as far as to isolate my input code into another thread
and benchmark both threads separately.

I am sure it is input-related as the framerate only shifts when the mouse
is moved. Im sure it is related to the volume of mouse events as i can do
the same movements at lower mouse polling rates with no framerate penalties.

**Comment by curvedinf** [comment] 2021-05-15 17:30
Its worth saying ... i did not isolate whether the slow down is in windows
or sdl, just that it is within PumpEvents.

**Comment by curvedinf** [comment] 2021-05-15 17:36
Another note: im using an unlimited framerate. Maybe there is additional
performance impact in SDL initiated by flipping the buffers?

**Comment by icculus** [comment] 2021-05-15 23:48
Are you using relative mouse mode? I bet a lot of that mouse input gets dropped in the standard Windows event queue but when we use RAWINPUT for relative mode we get the whole firehose of input.

**Comment by curvedinf** [comment] 2021-05-16 05:44
Yes i am

**Comment by DomGries** [comment] 2021-05-16 06:41
Just a guess but in the past there was a performance regression related to clip cursor inside PumpEvents introduced by https://github.com/libsdl-org/SDL/commit/a1ca84411e695103f4da1a32d0ac5f02d4898c02 which looks similar. See #3353 for more info.

Try commenting out WIN_UpdateClipCursorForWindows or reverting to SDL 2.0.8 to see if thats it

**Comment by curvedinf** [comment] 2021-05-16 18:05
Ok i have to compile for MSYS2 so it may take a while but I'll report back.
Thank you foe your help.

**Comment by icculus** [comment] 2021-05-16 21:54
So Raymond Chen explained how this works in the standard win32 event queue:

https://devblogs.microsoft.com/oldnewthing/20031001-00/?p=42343

The gist is even if you have a mouse that reports motion one billion times a second, you'll only get one motion event each time you process the event queue, so a game locked to vsync might only be getting 60 mouse motion events a second out of the 8000 that fancy mouse is producing. That's all SDL will see, so that's the most the app will see.

When we use win32's RAWINPUT interface, though, I think you get all 8,000 whether you can keep up or not, so SDL is generating SDL events for all of these, probably about 500 of them per frame at 60Hz.

We'll probably need to combine all of the available RAWINPUT mouse motion data available per PumpEvents into a single SDL event to fix this, but that's a guess.

**Comment by icculus** [comment] 2021-05-16 21:56
(Which is to say, we don't care about the raw input data for the sake of precision, we care about it because it lets us avoid the mouse cursor leaving the window.)

**Comment by cgutman** [comment] 2021-05-22 19:12
This might be fixed by 157c3f8097403c08cc9747082de37276fb2ab28c

**Comment by icculus** [comment] 2021-06-08 20:57
> This might be fixed by [157c3f8](https://github.com/libsdl-org/SDL/commit/157c3f8097403c08cc9747082de37276fb2ab28c)

Seems unlikely; we're probably going to need to squash all the mouse events into one (or at least decide when we're getting a legit flood of mouse events and do so then).

**Comment by cgutman** [comment] 2021-06-09 02:20
It depends on where the CPU time is going. If it's spent mostly in the Win32 subsystem or in SDL's WindowProc, then 157c3f8 is likely to help. If it's primarily spent in `SDL_SendMouseMotion()` then we'll need some batching.

I did some profiling of rapid mouse movement with [UIForETW](https://github.com/google/UIforETW) and found that the majority of processing time in `WIN_WindowProc()` was spent in `GetPropW()` which is exactly what 157c3f8 tries to address. My mouse only polls at 500 Hz, so it's hard to say whether it will scale similarly for @curvedinf. It seems likely though.

![image](https://user-images.githubusercontent.com/2695644/121282452-2a4d5b00-c89f-11eb-9d9a-b8dfc5277933.png)

I don't have access to Valve's bugtracker to see what CSGO-4855 is all about, but it definitely seems to be WM_INPUT processing overhead similar to what we're discussing here.

**Comment by icculus** [comment] 2021-06-09 15:45
Well if that's the case, that would be great news.  :)

@curvedinf, can you retest with the latest in revision control when you get a moment and see if this issue is resolved?

**Comment by curvedinf** [comment] 2021-06-09 21:53
I'm on a trip and don't have the mouse with me. Will test it when i get
back.

**Comment by omahena** [comment] 2021-06-23 10:21
I am targeting lower end platforms as well... Like a Intel Core M-5Y71 CPU @ 1.20GHz and the Intel graphics. 

I see my refresh rate drop significantly as soon as I interact with the system. As soon as I use the touchscreen or a mouse the refresh might be blocked for up to a second or more. For some reason the most severe impact was observable on Windows. It helped when I hijacked the event procedure and handled the events before the winproc of SDL2 was called. I am still using SDL to pump the events and that still appears to slow down the redraws significantly.

I can try and assess the impact with actual numbers to make the report less subjective.

For me the issue is so severe I am considering this a showstopper.

**Comment by slouken** [comment] 2021-07-27 00:45
I just tested with a Viper 8K mouse, generating 100-200 events per frame, and the CPU time is now down to PeekMessage():
Function Name	Total CPU [unit, %]	Self CPU [unit, %]	Module
| - [External Call] PeekMessageW	2473 (8.94%)	2107 (7.62%)	user32.dll
| - [External Call] CBaseDevice::Present	2098 (7.59%)	2098 (7.59%)	d3d9.dll
| - [External Call] CD3DBase::DrawPrimitive	435 (1.57%)	435 (1.57%)	d3d9.dll
| - [External Call] OutputDebugStringW	406 (1.47%)	406 (1.47%)	KernelBase.dll
| - [External Call] CallWindowProcW	330 (1.19%)	330 (1.19%)	user32.dll
| - [External Call] CDriverVertexBuffer::Lock	306 (1.11%)	306 (1.11%)	d3d9.dll
| - [External Call] NtUserGetRawInputData	303 (1.10%)	303 (1.10%)	win32u.dll
| - [External Call] CD3DBase::DrawPrimitive	277 (1.00%)	277 (1.00%)	d3d9.dll

I think the original performance issue is fixed in the latest code.

@omahena, please submit a separate bug for your issue. 1 second delay on touch events is crazy and definitely some other issue that we should investigate. Please let us know in the bug report whether you're also seeing it in the SDL test programs, like testgesture.

**Closed by slouken** 2021-07-27 00:45 UTC
