### ISSUE TITLE
Default OpenGL framebuffer "0" is not valid

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#4021] opened 2021-02-11 02:19 UTC
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Standalone code to reproduce the FBO 0 incomplete issue (sdltest2.c, text/x-csrc, 2021-02-03 03:33:56 +0000, 11285 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4752)

**Reported in version:** 2.0.14
**Reported for operating system, platform:** macOS 10.15, x86_64

# Comments on the original bug report:

On 2021-01-26 02:33:14 +0000,  wrote:

> Hi,
> 
> this is a bug that I ran into after upgrading to 2.0.14. The same code used to work on 2.0.12.
> 
> In my render loop, I have this code:
> 
> ```
> // write to default framebuffer
> glBindFramebuffer(GL_FRAMEBUFFER, 0);
> 
> int status = glCheckFramebufferStatus(GL_FRAMEBUFFER);
> if (status != GL_FRAMEBUFFER_COMPLETE)
> {
>     fprintf(stderr, "unexpected fbo status: 0x%x\n", status);
>     return;
> }
> 
> glClearColor(0.0f, 0.0f, 0.0f, 0.0f);
> glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
> 
> /// render code follows
> ```
> 
> Expected: the default (window) framebuffer is '0' and this code works.
> Results:
> in 2.0.12: this code works as expected
> in 2.0.14: it prints "unexpected fbo status: 0x8219" (0x8219 is the value of 'GL_FRAMEBUFFER_UNDEFINED'), and does not work anymore.
> 
> Since the OpenGL documentation (and pretty much every OpenGL example code out there) stipulates that '0' ought to be the default framebuffer, this regression might surprise a lot of developers.
> 
> Best regards.

On 2021-01-26 02:35:57 +0000,  wrote:

> A workaround exists, namely by querying the value of the default framebuffer at program start with `glGetIntegerv(GL_FRAMEBUFFER_BINDING, &defaultFramebuffer);` to use it later with glBindFramebuffer to bind the default FBO.

On 2021-02-01 06:55:44 +0000, Ryan C. Gordon wrote:

> 
> We talked about this briefly on Twitter, but I wanted to follow up because I'm still confused and have never seen this behavior on macOS.
> 
> This is the OpenGL 4.1 Core spec on the topic:
> 
> "The initial state of DRAW_FRAMEBUFFER and READ_FRAMEBUFFER refers to the default framebuffer.  In order that access to the default framebuffer is not lost, it is treated as a framebuffer object with the name of zero. The default framebuffer is therefore rendered to and read from while zero is bound to the corresponding targets."
> 
> Can you tell me some specifics of the app that's causing this problem? Is it using the Core or Compatibility profiles (and if using compat, does this happen if you call glBindFramebufferEXT instead of glBindFramebuffer)? If this is something you can isolate in a small piece of code, can you show me?
> 
> Also: does the thing let you draw correctly anyhow, if you bind FBO 0 and either don't call or ignore a failed call to glCheckFramebufferStatus? I have to be honest and say I've never checked FBO 0 for completeness, so maybe macOS changed what happens in this scenario? (Generally you only check FBOs you create yourself for completeness).
> 
> --ryan.

On 2021-02-03 03:33:56 +0000,  wrote:

> Created attachment 4752
> Standalone code to reproduce the FBO 0 incomplete issue

On 2021-02-03 03:37:31 +0000,  wrote:

> Hi Ryan,
> 
> I copy-pasted together a standalone sample code that allows to reproduce the issue. (See previous comment).
> 
> Using this, I could reproduce the issue with SDL 2.0.14, and verify that it does not happen with SDL 2.0.12.
> 
> Please let me know if you need more info, or if you find that I'm doing something wrong that could be the actual cause of the issue.
> 
> Best regards.

**Comment by icculus** [comment] 2021-04-04 06:05
I finally tracked this down.

This code is in the example app between creating a context and making it current:

```c
// get window surface
if (!s_screen)
{
    s_screen = SDL_GetWindowSurface(s_window);
}
ASSERT(s_screen);
```

This isn't necessary (or used further), but this causes all sorts of havoc on the window: internally, we create a Metal renderer to try to accommodate what we now thing will be software rendered pixels being pushed to the screen, and replace the existing window out from under the app, probably destroying the GL context, but definitely damaging it in unspecified ways.

Remove those lines and the problem goes away.

Not a bug in SDL, closing.

**Closed by icculus** 2021-04-04 06:05 UTC
Labels: bug, invalid
