### ISSUE TITLE
SDL_RenderDrawRect not rectangular

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#4001] opened 2021-02-11 02:18 UTC
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Display of SDL_RenderDrawRect (sdlbug.png, image/png, 2021-01-19 11:06:36 +0000, 4467 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4679)

**Reported in version:** 2.0.15
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2021-01-19 11:06:36 +0000, David Connolly wrote:

> Created attachment 4679
> Display of SDL_RenderDrawRect
> 
> Using SDL_RenderDrawRect does not produce a perfect rectangle anymore.
> 
> The bottom line seems to be out by one pixel. 
> 
> See attached screenshot.
> 
> --------------------------
>
> ```c
> //Using SDL and standard IO
> #include <SDL2/SDL.h>
> #include <stdio.h>
> 
> //Screen dimension constants
> const int SCREEN_WIDTH = 640;
> const int SCREEN_HEIGHT = 480;
> 
> int main( int argc, char* args[] )
> {
>     //The window we'll be rendering to
>     SDL_Window* window = NULL;
>     
>     SDL_Renderer* renderer = NULL;
> 	
>     //Initialize SDL
>     if( SDL_Init( SDL_INIT_VIDEO ) < 0 )
>     {
>         printf( "SDL could not initialize! SDL_Error: %s\n", SDL_GetError() );
>     }
>     else
>     {
>         //Create window
>         window = SDL_CreateWindow( "SDL Tutorial", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, SCREEN_WIDTH, SCREEN_HEIGHT, SDL_WINDOW_SHOWN );
>         if( window == NULL )
>         {
>             printf( "Window could not be created! SDL_Error: %s\n", SDL_GetError() );
>         }
>         else
>         {
> 	    renderer = SDL_CreateRenderer( window, -1, SDL_RENDERER_ACCELERATED );
> 	    if( renderer == NULL )
> 	    {
> 		printf( "Renderer could not be created! SDL Error: %s\n", SDL_GetError() );
> 	    }
> 
> 	    SDL_Rect outlineRect = { SCREEN_WIDTH / 6, SCREEN_HEIGHT / 6, SCREEN_WIDTH * 2 / 3, SCREEN_HEIGHT * 2 / 3 };
>             SDL_SetRenderDrawColor( renderer, 0x00, 0xFF, 0x00, 0xFF );        
>             SDL_RenderDrawRect( renderer, &outlineRect );
> 	    
> 	    SDL_Rect outlineRect2 = { SCREEN_WIDTH / 4, SCREEN_HEIGHT / 4, SCREEN_WIDTH * 2 / 4, SCREEN_HEIGHT * 2 / 4 };
>             SDL_SetRenderDrawColor( renderer, 0xFF, 0xFF, 0x00, 0xFF );        
>             SDL_RenderDrawRect( renderer, &outlineRect2 );
> 	    
> 	    SDL_Rect outlineRect3 = { SCREEN_WIDTH / 3, SCREEN_HEIGHT / 3, SCREEN_WIDTH / 3, SCREEN_HEIGHT / 3 };
>             SDL_SetRenderDrawColor( renderer, 0xFF, 0xFF, 0xFF, 0xFF );        
>             SDL_RenderDrawRect( renderer, &outlineRect3 );
> 	    	    
> 	    SDL_RenderPresent( renderer );
> 		
>             //Wait two seconds
>             SDL_Delay( 5000 );
>         }
>     }	
>     //Destroy window
>     SDL_DestroyWindow( window );
> 
>     //Quit SDL subsystems
>     SDL_Quit();
> 
>     return 0;
> }
> ```

On 2021-01-19 11:08:10 +0000, David Connolly wrote:

> This is from latest HG 2.0.15

On 2021-01-25 09:47:00 +0000, David Connolly wrote:

> Seems to be caused by http://hg.libsdl.org/SDL/rev/ba7112eeb065

**Comment by mkalte666** [comment] 2021-02-14 10:56
I can also observe this (linux, all gl renderers).

**Comment by JayFoxRox** [comment] 2021-04-12 19:54
What backends are affected?
Could it be related to half-pixels / differences in D3D / OpenGL coordinate systems?

**Comment by Taiko2k** [comment] 2021-08-12 11:38
I have noticed this bug upon upgrading from 2.0.14 to 2.0.16 (Linux). Heres a screenshot in case its helpful:

![Screenshot from 2021-08-12 23-20-39](https://user-images.githubusercontent.com/17271572/129190039-acbd5013-6f63-4b26-8475-f2b68430c4f2.png)

 (Using `SDL_RenderDrawRect`, the resultant rectangle isn't perfectly square)

**Comment by icculus** [comment] 2021-09-19 20:06
OpenGL and GLES renderers should be improved here, in the latest in revision control. Any corner cases that remain (or are caused by this patch), _PLEASE_ report them asap, as we would like this to be solid and never thought about again by the time 2.0.18 ships.

Thanks!

**Comment by AntTheAlchemist** [comment] 2021-11-11 05:24
Ah, the return of Ryan's nemesis. I've just checked this and here's what I see:
Rects are perfect.
Lines are 1 pixel too far on OpenGL* and 2 pixels too far on everything else. <-- this is when plotting a line that's double the width. If plotting a line of equal height / width then lines are perfect on OpenGL* and 1 pixel too far on everything else.

This test code might be more useful for testing. Press any key to cycle through renderers, look at the window title on status bar for the renderer in use.

```
#include <SDL.h>
int main(int argc, char** argv) {
	SDL_Init(SDL_INIT_VIDEO);
	SDL_Window *w = SDL_CreateWindow(nullptr, SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 200, 100, 0);
	SDL_Renderer* r = nullptr;
	int index = 0;
	for (;;) {
		SDL_PumpEvents();
		SDL_Event event;
		while (SDL_PeepEvents(&event, 1, SDL_GETEVENT, 0, SDL_LASTEVENT) == 1) {
			switch (event.type) {
			case SDL_KEYDOWN:
				if (r) {
					SDL_DestroyRenderer(r);
					r = nullptr;
				}
				index++;
				break;
			case SDL_QUIT:
				if (r)
					SDL_DestroyRenderer(r);
				SDL_DestroyWindow(w);
				SDL_Quit();
				return 0;
			}
		}
		if (r) {
			SDL_SetRenderDrawColor(r, 0x00, 0x00, 0x00, 0xFF);
			SDL_RenderClear(r);
			SDL_SetRenderDrawColor(r, 255, 0, 0, 128);
			SDL_SetRenderDrawBlendMode(r, SDL_BLENDMODE_ADD);
			SDL_FRect box = { 20, 20, 160, 60 };
			SDL_RenderDrawRectF(r, &box);
			SDL_RenderDrawLineF(r, 22, 22, 178, 78);
			SDL_RenderPresent(r);
		} else {
			r = SDL_CreateRenderer(w, index, SDL_RENDERER_PRESENTVSYNC);
			if (r) {
				SDL_RendererInfo info;
				SDL_GetRendererInfo(r, &info);
				SDL_SetWindowTitle(w, info.name);
			} else
				index = 0;
		}
	}
}
```

**Comment by icculus** [comment] 2021-11-12 19:57
I can reproduce here, I'll take a look.

**Comment by icculus** [comment] 2021-11-12 20:10
Moved this last one to https://github.com/libsdl-org/SDL/issues/4948 to keep track of it.

**Comment by icculus** [comment] 2021-11-27 01:01
Okay, closing this with several other bugs.

**Closed by icculus** 2021-11-27 01:01 UTC
