### ISSUE TITLE
Mingw static lib supposedly broken in 2.24.0 release

### ISSUE THREAD

**Issue by iyenal** [libsdl-org/SDL#6237] opened 2022-09-15 21:33 UTC
Hi,
Just want to inform that on my setup so far (WSL2, mingw) static librairies supplied in 2.24.0 release for mingw can't produce a working executable, both in 32-bit and 64-bit mode.
No errors from gcc or g++, linking operational, but Windows throws a "This app can't run on your pc" error.
Bad EXE on Wine too.

Swapping the 2.24.0 static lib with an older version (2.0.10) fixed the issue and produced a, well, executable/runnable EXE.
I'm unfortunately not able to try to reproduce the issue on another system or conduct other trials for investigation, hence I create this issue in case someone else find himself in the same situation.

Other than that, thanks a lot for your work.

**Comment by madebr** [comment] 2022-09-15 21:39
In https://github.com/libsdl-org/SDL/issues/6139#issuecomment-1234325699, I have a very similar issue.
Does compiling **with** `-DSDL_MAIN_HANDLED` and linking **without** `-lSDL2main` also produce a broken executable?

**Comment by ahprog** [comment] 2022-09-24 17:39
I had the same issue using MinGW, swapping to the previous release ([2.0.22](https://github.com/libsdl-org/SDL/releases/tag/release-2.0.22)) did fix it.

> In [#6139 (comment)](https://github.com/libsdl-org/SDL/issues/6139#issuecomment-1234325699), I have a very similar issue. Does compiling **with** `-DSDL_MAIN_HANDLED` and linking **without** `-lSDL2main` also produce a broken executable?

Compiling with these options also works on my setup.

**Comment by slouken** [comment] 2022-10-04 23:31
Duplicate of #6139

**Closed** 2022-10-04 23:31 UTC
