### ISSUE TITLE
Unrecognized key (fn)

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3793] opened 2021-02-11 02:05 UTC
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-08-13 00:49:34 +0000, oscar.neln@gmail.com wrote:

> I (very unexpectedly) got the message
> "The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL forums/mailing list <https://discourse.libsdl.org/> X11 KeyCode 151 (143), X11 KeySym
> 0x1008FF2B (XF86WakeUp)."
> When I pressed my FN-key on my Thinkpad T480 laptop. I was told to report it, so I did.
> No crashes or odd behaviour except for the message to stdout happens.
> 
> Feel free to point me in the right direction if this is reported in the wrong place.
> 
> PS. I've switched control and FN in BIOS, but I dont think this should matter.
> 
> kind regards

**Comment by InfoTeddy** [comment] 2022-03-09 19:54
Duplicate of #3113.

**Comment by slouken** [comment] 2023-11-07 01:34
This is fixed in the latest SDL release.

**Closed by slouken** 2023-11-07 01:34 UTC
